### ISSUE TITLE
Add WriterT Monoid

### ISSUE THREAD

**Issue by yilinwei** [typelevel/cats#1012]
I would like to add an implicit `Monoid` for `WriterT`. I've copied the implementation from scalaz [here](https://github.com/yilinwei/cats/commit/542b971f1c442eb8f04389f99ff695c943d463bf).

I would like to add some tests for the commit but am having a little trouble understanding how the tests work and should be structured. My initial attempt is [here](https://github.com/yilinwei/cats/commit/cfc2ccb045bfffda53a371efa5ef21c8b4c08e15) where I've just made sure that the `Monoid` and `Semigroup` can be resolved.

**Comment by adelbertc** [comment]
You'll also have to test the `Monoid` laws for it

**Comment by yilinwei** [comment]
I had some issues finding them at first (which was what I meant to ask) because I didn't realise they were under `GroupLaws` in `kernel`.

I've now added the test [here](https://github.com/yilinwei/cats/commit/d48c051a8c530eeeedcbeb7e387cfe285d0ec70e).
