### ISSUE TITLE
Jump start guide

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1017]
One of my coworkers was looking at the GitHub repo and website and was confused at first because he didn't really understand what constituted "abstractions for functional programming." He said something that would be really helpful is if there was a "jump start guide" of sorts that gives short examples that can get you started.. examples I can think of are `Validated`, `Xor`, `Traverse/Applicative`, `Kleisli`..

Now the question is where should such a thing live?

**Comment by kailuowang** [comment]
could be part of #1031

**Comment by kailuowang** [comment]
Here is a great blog post alone the same line 
https://virtuslab.com/blog/cats-library/

**Comment by Andrea** [comment]
HI there, kind of starting to look at this. Where should this live? Maybe `cats/docs/src/main/tut/JumpStart`  ?

**Comment by kailuowang** [comment]
@Andrea thanks! that location looks good to me.

**Comment by PawelLipski** [comment]
@Andrea @kailuowang I'm the author of the mentioned blog post, please contact me at plipski-at-virtuslab.com about using the examples from the blog in the library docs

**Comment by Andrea** [comment]
hey @PawelLipski  emailed you yesterday :D

**Comment by Andrea** [comment]
Sorry about the delay, I was hoping to work with some other peeps on this but it's taking too long so I started myself

**Comment by pauljamescleary** [comment]
fwiw - I was planning to do a write up on abstractions used in the microsite I am building for https://github.com/pauljamescleary/scala-pet-store

**Comment by PawelLipski** [comment]
Ok great @Andrea, please keep me posted, once you create a PR I can populate the guide file content (in markdown)

**Comment by PawelLipski** [comment]
@Andrea @kailuowang just created a PR https://github.com/typelevel/cats/pull/2178

**Comment by PawelLipski** [comment]
@Andrea @kailuowang @adelbertc pls take a look at the PR #2178
