### ISSUE TITLE
Avoid kind-projector in docs where possible

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1033]
The kind-projector usage in the docs trips up a lot of people (as evident by it frequently coming up in Gitter questions). I think that where possible we should use simple type aliases instead of kind-projector syntax.

If we have any cases where a simple type alias isn't possible, I like using kind-projector instead of a type lambda, but I think that we should preface the first such usage on each page with an explanation that kind-projector is being used.

**Comment by peterneyens** [comment]
In the [`Functor` documentation](https://github.com/typelevel/cats/blob/master/docs/src/main/tut/functor.md#creating-functor-instances) there already is an explanation about the kind projector plugin.

Do you suggest writing something similar on the other pages where we can't replace it by a type alias, or should we create a new page about kind projector where we could link to ?

**Comment by ceedubs** [comment]
@peterneyens I guess it would depend on how many can't be replaced by a simple type alias. If it's only one then inline is probably fine, but otherwise we should probably create a new page. Either way having a new page that we link to probably wouldn't be a bad thing.

**Comment by ceedubs** [comment]
I'm working on this.
