### ISSUE TITLE
import cats.data.State not found

### ISSUE THREAD

**Issue by sscarduzio** [typelevel/cats#1037]
I'm following the Free monad example: when you propose a pure interpreter using the State monad, my code does not compile.

```scala
...
...
 import cats.data.State
  type KVStoreState[A] = State[Map[String, Any], A]
  val pureCompiler: KVStoreA ~> KVStoreState = new (KVStoreA ~> KVStoreState) {
    def apply[A](fa: KVStoreA[A]): KVStoreState[A] =
      fa match {
        case Put(key, value) => State.modify(_.updated(key, value))
        case Get(key) =>
          State.inspect(_.get(key).map(_.asInstanceOf[A]))
        case Delete(key) => State.modify(_ - key)
      }
  }
```

sbt run complains:

````
[error] /me/Free/src/main/scala/free/State.scala:8: object State is not a member of package cats.data
[error]   import cats.data.State
```

**Comment by yilinwei** [comment]
You need to import `cats.data._` since the `State` alias is on the `package` object. The documentation needs to be updated.

**Comment by yilinwei** [comment]
Which version of cats are you using? I'm resolving it fine on the REPL for 0.5.0.

**Comment by sscarduzio** [comment]
https://gist.github.com/sscarduzio/c80da3d89e9c33f2e01c99d0423db3a4

my deps:
```
  "com.twitter" %% "twitter-server" % "1.16.0",
  "com.propensive" %% "rapture-json-circe" % "2.0.0-M5",
  "org.typelevel" %% "cats" % "0.5.0",
  "org.specs2" %% "specs2-core" % "3.7" % "test"
```

sbt clean compile 
```
[info] Compiling 2 Scala sources to /tr/Moscato/convene/Free/target/scala-2.11/classes...
[error] /tr/Moscato/convene/Free/src/main/scala/free/Main.scala:106: not found: type State
[error]   type KVStoreState[A] = State[Map[String, Any], A]
[error]                          ^
[error] /tr/Moscato/convene/Free/src/main/scala/free/Main.scala:110: not found: value State
[error]         case Put(key, value) => State.modify(_.updated(key, value))
[error]                                 ^
[error] /tr/Moscato/convene/Free/src/main/scala/free/Main.scala:112: not found: value State
[error]           State.inspect(_.get(key).map(_.asInstanceOf[A]))
[error]           ^
[error] /tr/Moscato/convene/Free/src/main/scala/free/Main.scala:113: not found: value State
[error]         case Delete(key) => State.modify(_ - key)
```

**Comment by ceedubs** [comment]
It looks like that version of rapture-circe depends on a version of circe (0.2.1) that depends on a very old version of cats (0.2.0): http://mvnrepository.com/artifact/com.propensive/rapture-json-circe_2.11/2.0.0-M5

**Comment by sscarduzio** [comment]
Nice find @ceedubs. 
Damn, that's tricky. Any workarounds beside changing rapture backend to Jackson?

**Comment by ceedubs** [comment]
@sscarduzio I imagine that @propensive would be open to a Rapture PR that updates the circe dependency. In the meantime, I believe you should be able to depend on the older `cats-state` module where `State` should be in the `cats.state` package.

**Comment by sscarduzio** [comment]
Yeah good idea, I'll open an issue on Rapture right away.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out since it's not really an issue with cats.
