### ISSUE TITLE
Why there's no cats.std.Try?

### ISSUE THREAD

**Issue by sscarduzio** [typelevel/cats#1038]
I saw an implementation for Future, Option, Either, etc. But not for Try. 
Is there a reason?

I'm getting 
` could not find implicit value for parameter M: cats.Monad[scala.util.Try]`

even if I have imported:

```scala
  import cats.std.all._
```

**Comment by rossabaker** [comment]
There is an instance in the alleycats project, along with a comment about
why it's an alley cat.

https://github.com/non/alleycats/blob/master/core/src/main/scala/alleycats/std/try.scala

**Comment by sscarduzio** [comment]
OK makes sense. BTW, quite instructive, thanks.
