### ISSUE TITLE
filterM broken?

### ISSUE THREAD

**Issue by 3rdLaw** [typelevel/cats#1054]
I ran the following in sbt console after a git pull:
```scala
scala> import cats.implicits._
import cats.implicits._
scala> import cats._
import cats._
scala> List(1, 2, 3).filterM { x => List(true, false) }
res0: List[Int] = List(1, 2, 3)
```

Compare this to scalaz's results:
```scala
import scalaz._
import scalaz.Scalaz._
List(1, 2, 3).filterM { x => List(true, false) }
res0: List[List[Int]] = List(List(1, 2, 3), List(1, 2), List(1, 3), List(1), List(2, 3), List(2), List(3), List())
```

**Comment by ceedubs** [comment]
@3rdLaw thanks for bringing this up. The `filterM` in cats indeed isn't the `filterM` in Haskell or scalaz. It doesn't even have quite the same type signature: the one in cats is not specialized to `List` and returns an `F[A]` result as opposed to `F[F[A]]`.

We should probably do something to avoid confusion. @non it looks like you originally added `filterM` - what are your thoughts?

**Comment by 3rdLaw** [comment]
Thanks for the clarification @ceedubs; I clearly assumed this was the same as Haskell/Scalaz's, so some documentation would be helpful.

Does cats have an equivalent to `filterM` in Haskell or scalaz?

**Comment by ceedubs** [comment]
@non to avoid confusion, what do you think about renaming our `fliterM` to `flatFilter` to parallel the relationship between `map` and `flatMap`?

**Comment by ceedubs** [comment]
@non on second thought, can you think of any practical example of using the method as it currently exists in cats? `Option` is about the only type that I imagine myself using it with, and in that case it would be pretty easy to use `flatMap` with `filter` instead.
