### ISSUE TITLE
Remove boilerplate for n-ary typeclasses

### ISSUE THREAD

**Issue by yilinwei** [typelevel/cats#1064]
Since simulacrum now supports [n-ary typeclass constructors](https://github.com/mpilquist/simulacrum/pull/59) though not typeclasses of the form `TC[F[_], A]` (yet!) I'd like to start removing the boilerplate and adding some symbolic ops to some of the less used packages.

In particular I'm thinking of the `arrow` package.

**Comment by yilinwei** [comment]
So I've made a start on it [here](https://github.com/yilinwei/cats/tree/arrow).

I've got a few questions about some of where the operations have come from - in particular I'm wondering if the `choice` operation on the `Choice` is named correctly since it seems to be identical to fan in according to [hackage](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Arrow.html).

I'm also a little confused by the hierarchy - I can understand inheriting some stuff from `Profunctor` and splitting out `Compose` and `Category`, but I'm having a hard time understanding why `Choice` doesn't inherit from `Arrow` given they are both in the `arrow` package.

As I'm learning more about arrows I'm thinking that if `free` is it's own module, then arrows should be as well.

@non I think you originally wrote the arrow implementations, so was wondering whether you could provide some insight.

**Comment by ceedubs** [comment]
@yilinwei this is great!

Other than being in the same package, is there anything else that makes you think that `Choice` should inherit from `Arrow`?

The idea of `arrow` being its own package is interesting. To me `FunctionK` seems like something that should be in `core`, but I'm not so sure about the other stuff - it's not stuff that I see people use often. Anyone else have thoughts on this?

@mpilquist do you think that this effort is something that we should move forward with for cats 1.0? It seems like we are probably closing in on a 1.0 milestone within the next few months.

**Comment by yilinwei** [comment]
@ceedubs 

It's not entirely clear to me where the `Choice` comes from - I had suspected it was the `ArrowChoice` in which case, the problem with not inheriting from `Arrow` is that certain operations on the `Choice` can't be derived (if choice is indeed written with the wrong signature currently, then `|||` can't be derived without the `lift` on the arrow) which means that it's of fairly limited use and we'd have an `ArrowChoice` which inherits from both anyway. 

If `Choice` is not from the same abstraction as `Arrow` then I think it ought to be moved to reflect that - mainly to help people understand where the terms come from; in a similar way that `free` and `functor` have their own separate package.

**Comment by mpilquist** [comment]
> The idea of arrow being its own package is interesting. To me FunctionK seems like something that should be in core, but I'm not so sure about the other stuff - it's not stuff that I see people use often. Anyone else have thoughts on this?

I agree with moving `FunctionK` to `cats` package and then possibly moving `cats.arrow` package to its own JAR.

> @mpilquist do you think that this effort is something that we should move forward with for cats 1.0? It seems like we are probably closing in on a 1.0 milestone within the next few months.

I don't see any risk doing this before 1.0. +1 from me.

**Comment by yilinwei** [comment]
Apologies @mpilquist, @ceedubs I've been caught up in the Brexit stuff so haven't been on top of PRs. Will do this, this week.

**Comment by ceedubs** [comment]
@yilinwei no need to apologize. That's certainly a bigger issue than this one. Thanks for volunteering -- let us know if you'd like to tag someone else in.

**Comment by ceedubs** [comment]
@yilinwei are you still pursuing this? I was thinking it would be nice to get going on this, and I'm happy to take over the effort if you can't get to it at the moment.

**Comment by yilinwei** [comment]
@ceedubs 

Feel free to take it up - the `Arrow` syntax should probably be a different issue since I was still mulling over some of the ways we're using it in our code before committing to a particular syntax.
