### ISSUE TITLE
Rename NaturalTransformation to FunctionK?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1065]
Recently @paulp [suggested](https://gitter.im/typelevel/cats?at=573ddd230cb634927f80758c) that `NaturalTransformation` should be renamed to `FunctionK`. This does seem to fit nicely with the convention used by other types such as `SemigroupK` and `MonoidK`. What do people think?

Note: I (and I imagine others) would still want to keep the `~>` alias around.

**Comment by kailuowang** [comment]
👍

**Comment by ceedubs** [comment]
Resolved by #1072.
