### ISSUE TITLE
Mixed use of symbols in Kind projections

### ISSUE THREAD

**Issue by ghost** [typelevel/cats#1069]
Independent to https://github.com/typelevel/cats/issues/993, there is currently a mixed use of `Lambda` and `λ` in kind projections. Eg

`def compose[G[_, _]](implicit ev: Bifoldable[G]): Bifoldable[Lambda[(A, B) => F[G[A, B], G[A, B]]]]`

`def compose[G[_]](implicit GG : Applicative[G]): Applicative[λ[α => F[G[α]]]] =`

Whatever the chosen convention, it should be applied consistently.

**Comment by ceedubs** [comment]
I think this was fixed by #1079 (and even with a scalastyle rule to make sure we are consistent in the future!), so I'm going to close this out. Please feel free to reopen if I'm missing something.
