### ISSUE TITLE
Document cats' stance on currying

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1071]
Cats seems to have settled on a convention to curry when it helps scalac infer types for function arguments but to otherwise generally avoid currying. We should document/explain this convention (and probably also make sure we are being consistent about it).

See also #950.

**Comment by peterneyens** [comment]
This is a more general version of #147.

**Comment by armanbilge** [comment]
There's more discussion in https://github.com/typelevel/cats/issues/147 so let's just generalize that issue.
