### ISSUE TITLE
Moving Eval to cats.data ?

### ISSUE THREAD

**Issue by peterneyens** [typelevel/cats#1077]
`Eval` seems to be the only non type class in `cats._`, should we move it to `cats.data._` to be more consistent ?
Moving `Eval` would add a lot of `cats.data.Eval` imports, but that is currently already the case for `cats.data.Xor`.

Thoughts ?

**Comment by ceedubs** [comment]
The breakdown of the packages has always felt a bit arbitrary to me. For example, I don't really think of `Eval` as a data structure, but then I don't really think of `Kleisli` as a data structure either. Having said that, every line that I try to draw seems arbitrary short of just shoving everything into the `cats` package. I don't have any very strong opinions on this, but I think that when a cats 1.0 milestone is released we should freeze the package structure, so I guess people should weigh in quickly if they have strong opinions on this.

**Comment by ceedubs** [comment]
At this point making the move would needlessly break compatibility, so I'm going to go ahead and close this out.
