### ISSUE TITLE
create cats.data.NonEmptyVector

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1088]
We seem to have arrived on a decision in #537 that NonEmptyVector should have its own data type. Let's go for it!

Since representing a `Vector` as `case class NonEmptyVector[A](head: A, tail: Vector[A])` is not very efficient for quite a few operations, @non has suggested that we create a class that wraps a `Vector` that it knows to be non-empty. We can guarantee this by making the companion object method that creates  an instance of the class from a `Vector` return an `Option`.

**Comment by zainab-ali** [comment]
I'm working on this

**Comment by ceedubs** [comment]
Resolved by #1137
