### ISSUE TITLE
Size or length operation on Foldable

### ISSUE THREAD

**Issue by benhutchison** [typelevel/cats#1091]
Please provide a `size` method, with the ordinary meaning eg:
```
@ Foldable[List].foldLeft(List(1, 2, 3), 0){case (count, elem) => count + 1}
res6: Int = 3
```

Both (a) to provide a convenient default impl for a common operation, and (b) to allow instances to define their own faster size computation.

**Comment by benhutchison** [comment]
background context from haskell: https://www.reddit.com/r/haskell/comments/xo05l/why_isnt_length_part_of_foldable/

**Comment by ceedubs** [comment]
👍. I've also wondered if we should have a similar method that would be safe on infinite streams - something like "size, but stop calculating if it's over N".

**Comment by ceedubs** [comment]
This was introduced in #1114.
