### ISSUE TITLE
Enforce kind projection style

### ISSUE THREAD

**Issue by peterneyens** [typelevel/cats#1092]
Now we have settled on using Greek characters in our kind projections in #1079, we should try to keep it consistent.

I was thinking about a scalastyle rule to check that files don't contain `Lambda[`.

This could look like the following (but I have been unable to test it, since running `scalastyle` gives me `[info] Processed 0 file(s)`) : 
```xml
 <check level="error" class="org.scalastyle.file.RegexChecker" enabled="true">
  <parameters>
   <parameter name="regex">Lambda\[</parameter>
  </parameters>
  <customMessage>Use Greek characters in a kind projection : λ[α => ...].</customMessage>
 </check>
```

**Comment by fthomas** [comment]
@peterneyens I think we need to update our scalastyle configuration, see: https://github.com/scalastyle/scalastyle-sbt-plugin/issues/47
