### ISSUE TITLE
cats.Order: Support for pattern matching on comparison results

### ISSUE THREAD

**Issue by benhutchison** [typelevel/cats#1101]
When doing comparisons with cats.Order, would be desirable to pattern match on the cases, like eg:
```
a comparison b match {
  case GreaterThan => ???
  case Equivalent => ???
  case LessThan => ???
}
```
Order.compare returns an Int for performance and Java 1.7 compat reasons, which is fair enough, when you need that. But that requires an if (c <0) ... else if (c == 0) .. else ... construct to handle a comparison; less readable than the above alternative IMO.

Proposal is a function, implemented on top of `compare: Int`, perhaps named `comparison: Comparison` that returned a case object (GreaterThan etc) for pleasant pattern matching.

Gitter discussion: https://gitter.im/typelevel/cats?at=5758beb8064b9e7266f0c086

**Comment by julienrf** [comment]
Note that you can still get quite the same syntax without changing `Order`:

~~~ scala
object GreaterThan {
  def unapply(i: Int): Boolean = i > 0
}
~~~

~~~ scala
(a comparison b) match {
  case GreaterThan() => ???
}
~~~

**Comment by ceedubs** [comment]
@julienrf I thought the same thing at first. The problem is that while you do get the syntax, you don't get the exhaustive matching. So if you match on the `GT` and `LT` case but forget the `EQ` case, your code will just blow up at runtime.

**Comment by julienrf** [comment]
Fair point :)

**Comment by benhutchison** [comment]
IMO this isnt _quite_ done, since there's no [syntax](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/order.scala) to enable `a comparison b`.

I think (?) Ive seen some syntax in the cats project autogenerated, maybe from `@typeclass`; why doesnt `Order` use that?

**Comment by adelbertc** [comment]
@benhutchison Ah true, oops forgot about that.

I believe kernel doesn't use simulacrum to minimize dependencies
