### ISSUE TITLE
Add Monoid syntax

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1124]
Currently we have [Semigroup syntax](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/semigroup.scala) but lack something similar for `Monoid`. This means that you can do something like `1 |+| 2`, you can't do something like `1.isEmpty` (even though `Monoid[Int].isEmpty(1)` works).

**Comment by ceedubs** [comment]
Note: I think that `isEmpty` is currently the only method that we can really add to this syntax.

**Comment by hamishdickson** [comment]
I'll have a look at this today
