### ISSUE TITLE
Add Kailuo Wang as a Cats maintainer

### ISSUE THREAD

**Issue by non** [typelevel/cats#1126]
I propose that we add @kailuowang as a maintainer. He's helped with several of the past releases and has been great about submitting and helping review PRs.

Kailuo, is this something you'd be interested in? What do the other maintainers think?

**Comment by mpilquist** [comment]
👍

**Comment by kailuowang** [comment]
I am truly honored. It is my goal to contribute to cats as much as I can and as long as I write code in scala. ( a language I love and probably won't change in the foreseeable future)

**Comment by non** [comment]
It seems like this won't be necessary this time, but maintainers should feel free to voice any concerns privately to me and I can share them here.

**Comment by non** [comment]
It looks like we have heard from 8/11 of the current maintainers. I think it's safe to say "welcome!"
