### ISSUE TITLE
std in instance/syntax imports

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1135]
Currently if you want to import the type class _instances_ for `Option`, you `import cats.std.option._`. If you want to import the _syntax_ for `Option`, you `import cats.syntax.option._` (note the lack of `std`). This seems inconsistent and/or backwards to me. Since instances for Cats types are in their companion objects, I don't think I'll ever need to import instances for anything _other_ than `std` and thus the namespacing doesn't really seem to make much sense. However, when it comes to syntax, I may be adding syntax to std lib types (like `Option`) or cats types (like `Functor`).

I see several logical ways that we could do this:

1. Drop the `std` from the instance imports
2. Keep the `std` in the instance imports and add it to the syntax imports
3. Drop the `std` from the instance imports (since they are all std lib anyway) and add it to the syntax imports (since not all of them will actually be related to std lib)

I think that I prefer `2`. The thing that makes me uneasy about `1` is that it continues the current trend of not namespacing syntax for std lib types, so if the std lib were to gain a `Functor` or `Semigroup` in the future it could mess up our naming convention. I'm fine with `3`, but the lack of symmetry between the instance and syntax imports seems like it could make things less intuitive.

**Comment by kailuowang** [comment]
I vote for 2 as well. I like the `std` package convention.

**Comment by philwills** [comment]
I'd vote for 1. The `std` thing has always seemed a bit odd and unintuitive to me.

**Comment by non** [comment]
What if we rename `std` to `instances`? To me `std` is the place where implicit instances go and `syntax` is the place where implicit syntax goes.

**Comment by ceedubs** [comment]
@non I like that. I had thought of that but was thinking that we had some non-instance things in there like the `none[A]` syntax. It looks like that's in `syntax`, so as long as we don't think we'll have non-instance things in there, 👍 from me.

**Comment by kailuowang** [comment]
👍  on renaming `std` to `instances`.

**Comment by ceedubs** [comment]
Fixed in #1140.
