### ISSUE TITLE
MonadState instance for StateT with get as val not serializable (for List)

### ISSUE THREAD

**Issue by peterneyens** [typelevel/cats#1139]
The `MonadState[StateT[List, Int, ?], Int]` instance is not serializable if `get` is implemented as a `val`.

 #1138 changes/changed the `val` to a `lazy val`.

**Comment by ceedubs** [comment]
Good catch @peterneyens!

I'm wondering if it should be a `def` instead of a `lazy val`. The overhead of `lazy` may be worse than the extra allocations, and I'm always a bit skeptical of `val`s in `traits`. WDYT?

**Comment by ceedubs** [comment]
Fixed by #1138.
