### ISSUE TITLE
Add ValidatedIor

### ISSUE THREAD

**Issue by mkotsbak** [typelevel/cats#1152]
From Gitter:

@mkotsbak 00:03
How is sequence/traverse working with Ior? Could I get it to collect all errors (left sides) so that I end up with IoR[Nel[String], R]?

@sellout 04:26
@mkotsbak Interesting. I’ve been wanting the same thing – basically, a Validated on Ior rather than Xor. For collecting warnings in addition to errors.

@mkotsbak 08:59
Japp, I'm not sure if Ior is designed for that case or more for one result and/or one error message?

@yilinwei 09:01
@mkotsbak, traverse on Ior takes in an Applicative[F]
but no Semigroup on A
which means it can't possibly accumulate errors on the left. So it's similar to a Xor rather than a Validated. But I think it's a good idea to have a ValidatedIor case class

**Comment by mkotsbak** [comment]
Hmm, would this be a monad supporting map/flapMap like Ior, or not like Validated?

**Comment by ceedubs** [comment]
@mkotsbak if it collects errors then I think it would need to _not_ be a monad (like `Validated` isn't). If it _did_ have a `flatMap`, it would run into the same issue where `flatMap` and `ap`/`map2` wouldn't be consistent.

@sellout @mkotsbak do you have a handy example of how you might use this? I'm not opposed to it, but I can't think of a time that I've run into a need for this. I've used something like `WriterT[Err Xor ?, Warning, ?]` to represent fatal errors in a disjunction and a log of non-fatal warnings, which sounds kind of similar but definitely not the same.

**Comment by sellout** [comment]
@ceedubs That `WriterT` won’t maintain the warnings after a failure, though. I think `ValidatedT[Writer[List[Warning], ?], Nel[Err], ?]` is more the type I wanted (maintaining the warnings even with fatal errors, and accumulating errors as well). But that doesn’t exist either.

**Comment by yilinwei** [comment]
@sellout Applicatives compose so I think you could use a `Nested` for that behaviour?

**Comment by leandrob13** [comment]
Ior implements the ap function based on flatMap and if you see its implementation, it does not accumulate errors if it is a Ior.Left. It does so if it is a Both, and also accumulates the Ior.RIght.

How I got around that was with the function append, which you can use on a list of Iors and reduce them to accumulate both left and rights.

**Comment by LukaJCB** [comment]
Implemented in https://github.com/typelevel/cats/pull/2059 :)
