### ISSUE TITLE
FreeT

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1158]

**Comment by zainab-ali** [comment]
This sounds interesting.  Presumably something along the lines of 
```
class FreeT[F[_], S, A](fa: F[Free[S, A]]) {
  def map[B](f: A => B): FreeT[F, S, B] = ???
}
```

**Comment by raulraja** [comment]
@adelbertc We have two use cases for `FreeT` at 47 both for `Fetch` and `Github4s`. I recall discussing with you back then that stack safety was a concern for implementing `FreeT` and some other areas needed to change to support that. Do you know out of the top of your head if this limitation is cleared? If so we can take a shot at contributing `FreeT` to cats. thanks!

**Comment by ceedubs** [comment]
@zainab-ali not quite like that. http://functorial.com/stack-safety-for-free/index.pdf contains some more information (though it uses PureScript as opposed to scala), and scalaz also has one.

**Comment by adelbertc** [comment]
@raulraja Hm I don't quite remember the "other areas needed to change" but I suppose yeah, `FreeT` I'm guessing would need to be stack safe for all choice of `F[_]` so we need to be careful with that.

**Comment by raulraja** [comment]
Cool, I'll look into it as soon as we get Scala Exercises out this week. Thanks @adelbertchang

**Comment by beefyhalo** [comment]
This would be great 👍
