### ISSUE TITLE
Documentation - Example for Semigroup won't compile SBT/IntelliJ

### ISSUE THREAD

**Issue by tdrozdowski** [typelevel/cats#1187]
Either via sbt compile on command line or in IntelliJ, the examples that are with the Semigroup documentation just don't work.

I had to change things up a bit (looking at your syntax unit tests) to get something to work...

I seems if I import cats.std.AllInstances & cats.syntax.AllSyntax and then add them to an object, I can get that object to compile in both.

i.e.: 

```scala
object Demo extends App with AllInstances with AllSyntax {
   val a = Semigroup[Int].combine(1,2)
   val b = List(1,2,3) |+| List(4,5,6)
}
```

If you don't extend those traits, then this will not compile with the imports that your documentation provides.

v0.6.0

**Comment by tdrozdowski** [comment]
Just realized...

The documentation asks for:

import cats._
import cats.std.all._
import cats.implicits._

And my compiles fail with those imports.

However I remove import cats.std.all._ line - and they all work.  In SBT, in IntelliJ & even in the IntelliJ worksheets...

**Comment by adelbertc** [comment]
Hm what you're seeing seems right to me - with `cats.std.all._` and `cats.implicits._` you're probably getting conflicting implicits. Which `Semigroup` documentation are you looking at? If it's the tut ones I'm surprised they compile..

**Comment by tdrozdowski** [comment]
http://typelevel.org/cats/tut/semigroup.html

So yeah - the tut ones...

Is there a better set?  Trying to learn/evaluate the framework - and present it to my local Scala UG this week...

**Comment by benhutchison** [comment]
IMO root problem is that the docs source (
https://github.com/typelevel/cats/blob/master/docs/src/main/tut/semigroup.md),
which is *correct*, is de-synced from whats at:
http://typelevel.org/cats/tut/semigroup.html .

Terrence, use the source as workaround.

How does it get published to typelevel.org?

**Comment by ceedubs** [comment]
Thanks for bringing this to attention @tdrozdowski. I'm not quite sure how this came to be.

@benhutchison currently publishing the site is a manual step in the [release process](https://github.com/typelevel/cats/blob/master/PROCESS.md#post-release). We like to keep the site in sync with the latest stable release, so unfortunately it's not as simple as just publishing the site off of the current head of master. This is kind of sketchy, but I think I'm going to just manually edit the gh-pages branch to try to ensure this doesn't trip someone else up.

**Comment by ceedubs** [comment]
I've just created #1190 to fix this.
