### ISSUE TITLE
Scalastyle rule for javadoc-style comments

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1195]
We have settled on javadoc-style indentation for comments such as:

``` scala
/**
 * Does stuff.
 */
```

However, often PRs use the scala-style indentation such as:

``` scala
/**
  * Does stuff.
  */
```

It would be nice if we could force consistency via a scalastyle rule.

**Comment by ceedubs** [comment]
I've created a scalastyle feature request for this: https://github.com/scalastyle/scalastyle/issues/211

**Comment by mpilquist** [comment]
Note scalafmt supports changing this automatically: https://olafurpg.github.io/scalafmt/#Formattingrules

**Comment by ceedubs** [comment]
@mpilquist ah thanks for pointing that out. I had heard of scalafmt, but I never gave it a proper look. I'm always a bit skeptical of code formatters, but I think that for some simple rules like this one and whether there is a space after commas it would be great (better than us nitpicking minor formatting concerns in PRs). That sounds promising to me.

**Comment by FrancescoSerra** [comment]
Can this be mark as closed, considering th work done for #2546 ?
