### ISSUE TITLE
Check syntax for typeclass piecemeal imports

### ISSUE THREAD

**Issue by yilinwei** [typelevel/cats#1209]
As demonstrated by @ShaneDelmore in the gitter channel, `syntax.flatMap._` doesn't have the functor syntax. I suspect that was because `FlatMap` had some new syntax added on and it doesn't extend the ones that simulacrum generates in the `ToOps`.

We should probably catch these in some tests.

**Comment by ceedubs** [comment]
I think that this is probably resolved as we moved more syntax to be simulacrum-generated. Feel free to open new issues for any lingering problems.
