### ISSUE TITLE
Rearrange Typecalsses in tutorial in a easy to follow manner

### ISSUE THREAD

**Issue by kovszilard** [typelevel/cats#1252]
Currently on the bottom of the Typeclasses tutorial page the list of all the Typeclasses are in alphabetical order. It would be easier to follow the tutorial for example in this order:
Semigroup, SemigroupK, Monoid, MonoidK, Functor, Apply, Applicative, Monad, MonadCombine, MonadFilter, Foldable, Traverse, Id, Show, Invariant, Contravariant

I might be wrong but i think it can be done by renaming the files in the docs/src/main/tut folder in a way that it represent the correct order. For example tc-00-semigroup.md, tc-01-semigroupk.md etc.

I can work on this if you find it an useful improvement.

**Comment by adelbertc** [comment]
Hey @kovszilard , we recently did a revamp of the website, let me know your thoughts. I'm also going to go through the current docs and check/revise them to better reflect the new ordering, tracking that here: https://github.com/typelevel/cats/issues/1443

Closing this for now, feel free to re-open if you think it can be improved.
