### ISSUE TITLE
Draft 0.7.0 release notes

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#1253]
We'd like to publish an 0.7.0 release in the next few days, and we need release notes. Since this release includes a number of large breaking changes (I just updated circe and my other Cats-dependent projects to the 0.7.0 snapshot yesterday and it took a couple of hours longer than I expected), I think it'd be a good idea to include something like a migration guide in addition to the summary of pull requests.

**Comment by ceedubs** [comment]
Resolved in #1259.
