### ISSUE TITLE
Make cats-kernel law organization consistent with cats-core

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1272]

**Comment by kailuowang** [comment]
see comment here https://github.com/typelevel/cats/issues/1341#issuecomment-243899002

**Comment by LukaJCB** [comment]
I know, I just wrote the law testing guide that documented this inconsistency, but going forward I'd love to have these be consistent. So we are going to break bin-compat one last time before potentially a year or something, so now seems to be a good time, right?

**Comment by kailuowang** [comment]
On the other hand it's less big a deal to break bin compat in the laws module.

**Comment by LukaJCB** [comment]
If so, I'm going to try to make a PR early next week :)

**Comment by johnynek** [comment]
I think keeping kernel *very* compatible is still important. Laws less so in my opinion. You don't transitively pull testing packages generally.
