### ISSUE TITLE
Add Arbitrary instances for all data types

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1274]

**Comment by kailuowang** [comment]
How important is this for 1.0.0 release?

**Comment by kailuowang** [comment]
@adelbertc feel free to change the scope label to what you think would be more appropriate.

**Comment by adelbertc** [comment]
I'd consider it fairly important - it's reasonable to expect any users of Cats to want Arbitrary instances for Cats defined data types, otherwise we'd end up with people rolling their own arbitrary.

**Comment by kailuowang** [comment]
It seems to me that the only one missing is `StateT`.  I am going to change it to scope:small

**Comment by kailuowang** [comment]
basically move 
https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/StateTTests.scala#L297-L308
and 
https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/StateTTests.scala#L297-L308
to 
https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
