### ISSUE TITLE
Follow-up on tut and/or FAQ about Cats and tailRecM

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1284]
Currently tut docs just implement `tailRecM` when implementing `Monad` which can throw off some beginners who are learning `Monad` - we should clarify somewhere noticeable why we chose to do what we did.

**Comment by kailuowang** [comment]
I think this is addressed https://github.com/typelevel/cats/blob/master/docs/src/main/tut/faq.md#tailrecm
Shall we close this?

**Comment by kailuowang** [comment]
@adelbertc see comment above, shall we close this one?
