### ISSUE TITLE
Maven build for 2.12

### ISSUE THREAD

**Issue by unoexperto** [typelevel/cats#1285]
Guys, could you please publish build for scala  2.12-M5 ?

**Comment by SethTisue** [comment]
how about 2.12.0-RC1? I saw some evidence at #1377 that @BennyHill is working on it?

are there any missing upstream dependencies whose maintainers should be nudged?

**Comment by BennyHill** [comment]
Also see PR https://github.com/typelevel/cats/pull/1382

**Comment by SethTisue** [comment]
new PR https://github.com/typelevel/cats/pull/1415

**Comment by peterneyens** [comment]
As of 0.8.0 (#1415) we have a cats version for 2.12 (RC2).

**Comment by nrinaudo** [comment]
Any plan for a 2.12.0?

**Comment by travisbrown** [comment]
@nrinaudo It's being tracked [here](https://github.com/typelevel/cats/pull/1450#issuecomment-258610199).

**Comment by nrinaudo** [comment]
@travisbrown not sure how I failed to find this, thanks!
