### ISSUE TITLE
Semigroup |+| is 4 times slower than scalaz Semigroup |+|

### ISSUE THREAD

**Issue by rayqiu** [typelevel/cats#1291]
Semigroup |+| is 4 times slower than scalaz Semigroup |+|, when combining two large Maps that have nested Maps inside.  

Map type: Map[Seq[Char], Map[Char, Int]]

**Comment by adelbertc** [comment]
Perhaps related to https://github.com/typelevel/cats/issues/1290

**Comment by ceedubs** [comment]
Thanks for reporting this, @rayqiu. I think this is a duplicate of #1290, so I'm going to close it out. @rayqiu please feel free to reopen it if you have an example of another data type that is also slow with `|+|`.
