### ISSUE TITLE
Add withFilter and filter to XorT

### ISSUE THREAD

**Issue by mkotsbak** [typelevel/cats#1294]
This will allow to use if statements in for-comprehensions. See similar issue for OptionT: https://github.com/typelevel/cats/issues/981

**Comment by ceedubs** [comment]
I think that `OptionT` is a bit different than `XorT` in this context. If you filter out an item from an `Option` then you can naturally return `None`. What do you return in the case of `Xor`/`XorT` for an empty value? `Xor` used to require a `Monoid` instance for the left type and use the `empty` value from that `Monoid`, but it was removed in #276 as it was pretty ad-hoc and arbitrary. For example what should the following return?

```scala
val x: String Xor Int = Right(3)
val y = x.filter(_ % 2 == 0)
```

With a `Monoid` `empty` it would return `Left("")`. To me this seems pretty arbitrary and probably unhelpful. I think it's better to do something like:

```
val x: String Xor Int = Right(3)
val y = x.ensure("oops it was odd!")(_ % 2 == 0)
```

Note that I'm using `Xor` in these examples but I think it all applies equally well to `XorT`.

**Comment by mkotsbak** [comment]
Agree, this is not solvable.
