### ISSUE TITLE
Revert Xor / Either changes for 0.7.0 release

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#1302]
We'd planned to start the switch from `Xor` to `Either` [in Cats 0.8](https://github.com/typelevel/cats/issues/1192#issuecomment-239699123), but several of the `Either` pull requests just got merged, and 0.7.0 isn't out yet:

- https://github.com/typelevel/cats/pull/1289
- https://github.com/typelevel/cats/pull/1301
- https://github.com/47deg/cats/pull/1

(The last one will only need to be reverted if we're trying to get #1266 into 0.7.0, which I think would be a good idea, since it's ready now, and since it's at least part of what we've been waiting for.)

Up until now we've been tagging and publishing 0.x.0 releases from master, and I don't see any reason to make that more complicated now, so I think at least #1289 and #1301 will need to be reverted before the 0.7.0 release.

**Comment by non** [comment]
👍  to this plan

I think I gave @adelbertc the wrong idea when I signed-off on #1289. Apologies!

I propose that I:

 * un-merge #1289 and #1301
 * merge #1259 and #1266
 * release 0.7.0
 * re-merge #1289 and #1301
 * celebrate

What do people think? We don't often revert things, I'd like to get at least 1-2 other +1s on this plan.

**Comment by travisbrown** [comment]
:+1: to @non's plan, with one additional piece:

- https://github.com/47deg/cats/pull/2 to revert https://github.com/47deg/cats/pull/1 before #1266 gets merged

I've also just opened #1303 for the #1301. GitHub isn't letting me open a revert PR for #1289, and the error message is unclear, so I'm not sure whether reverting #1301 will fix the situation. (This is probably an argument for rebasing big PRs before merging.)

**Comment by kailuowang** [comment]
:+1:  i vote for let's wrap asap before more confusion

**Comment by adelbertc** [comment]
I'm so sorry guys! I completely forgot about the 0.7.0 release - I saw the approvals so I clicked merge and moved on. :( :( Of course 👍 from me

**Comment by non** [comment]
Here's a PR where I'm doing it: https://github.com/typelevel/cats/pull/1305

**Comment by non** [comment]
Alright, as-per discussions on Gitter it seems like we've decided to hold off doing a full-scale revert and instead just revert the existing API changes (to minimize 0.6.1 -> 0.7.0 breakage). This will make the future 0.7.x -> 0.8.0 upgrade path less painful.

@adelbertc agreed to take point on this.

**Comment by non** [comment]
This was fixed by #1306.
