### ISSUE TITLE
add scaladoc for Comonad / CoFlatMap

### ISSUE THREAD

**Issue by stew** [typelevel/cats#131]
core/src/main/scala/cats/Comonad.scala
core/src/main/scala/cats/CoFlatMap.scaal

**Comment by lukewyman** [comment]
@stew I'd like to work on this one (and have started already). Question on the scaladocs: do we want to make these comments nice and pretty complete with examples (like the comments in `cats.Arrow`)?

If the answer is yes, then it doesn't look like we have instances (or complete combinators on our instances) for `Comonad` and `CoFlatMap`. Should I go ahead and polish this up?

And if the answer to that is yes, how on earth does one extract `A

**Comment by lukewyman** [comment]
And if the answer to that is yes, how on earth does one extract `A` from None without knowing what `A

**Comment by lukewyman** [comment]
without knowing what `A` is?

**Comment by adelbertc** [comment]
We have a couple instances for `Comonad`, see `Id` and `Eval`. `Id` is defined as `type Id[A] = A` so extraction is identity. `Eval` is a data type that captures evaluation strategy of a value, extracting is equivalent to executing the strategy to compute the value.

re: Scaladoc w/ examples, that would be good. We use [sbt-doctest](https://github.com/tkawachi/sbt-doctest) to make sure the examples are compile-able and correct, so you may want to look into that.

**Comment by lukewyman** [comment]
Do there exist possible implementations for extract on things like 'None` and `List()`, as in is that solvable?

**Comment by adelbertc** [comment]
Nope, for the reason you stated previously

**Comment by ceedubs** [comment]
`NonEmptyList` is probably a good item for a `Comonad` example. Other than the fact that it will show up as `OneAnd` in the `toString` representation, which could be a bit confusing...

**Comment by kailuowang** [comment]
fixed by #898
