### ISSUE TITLE
FS2 information in FAQ is outdated

### ISSUE THREAD

**Issue by durban** [typelevel/cats#1314]
[This page](https://github.com/typelevel/cats/blob/master/docs/src/main/tut/faq.md) in the FAQ mentions that "At the time of this writing, Scala.js support is in progress" (for FS2), and links to functional-streams-for-scala/fs2/issues/500. Since then, that issue have been closed, and FS2 0.9.0-RC1 seems to support Scala.js.

**Comment by non** [comment]
@durban Thanks! We should definitely update the FAQ to say that support is available in an RC, and is expected to be available in 0.9.0.

**Comment by durban** [comment]
This have been already fixed in 43091bf762da1118a178fdc9a98cbe346312fd1c (although it is not on the site yet).
