### ISSUE TITLE
Consider an `EmptyK[F[_]]` type class, or remove `MonadFilter`

### ISSUE THREAD

**Issue by eed3si9n** [typelevel/cats#1336]
This is the type constructor version of #307 (Consider an `Empty[+A]` type class ).

Currently there are two typeclasses that promises in `def emtpy` for `F[_]`: `MonadFilter` and `MonoidK`. (There's also `ApplicativeMonoid`)

Would it make sense to unify them as `EmptyK` and mix them into whatever parent traits that needs empty? For example, we can remove `MonadFilter`.

**Comment by adelbertc** [comment]
What would the laws be?

**Comment by eed3si9n** [comment]
ok. So if you look at the laws:

```scala
  def monoidKLeftIdentity[A](a: F[A]): IsEq[F[A]] =
    F.combineK(F.empty, a) <-> a

  def monoidKRightIdentity[A](a: F[A]): IsEq[F[A]] =
    F.combineK(a, F.empty) <-> a

  def monadFilterLeftEmpty[A, B](f: A => F[B]): IsEq[F[B]] =
    F.empty[A].flatMap(f) <-> F.empty[B]

  def monadFilterRightEmpty[A, B](fa: F[A]): IsEq[F[B]] =
    fa.flatMap(_ => F.empty[B]) <-> F.empty[B]
```

To these `F.empty[A]`s mean different notion for `MonoidK` and `MonadFilter`?
I understand the lawfulness concerns, but two typeclasses introducing a contract that is named the same (and likely means the same) is concerning as well.

**Comment by adelbertc** [comment]
They may be the same between the two (maybe `Option` has the same behavior?) but given they live in different hierarchies it wouldn't surprise/bother me if it meant they had a different notion. For instance, the `Semigroup` instance for `Option` will actually try to add the values whereas the `SemigroupK` instance just takes the first `Some`.

Perhaps we could name them something different to disambiguate, but I prefer this situation over having a lawless type class like `EmptyK`.

**Comment by kailuowang** [comment]
there is one in alleycats https://github.com/non/alleycats/blob/master/core/src/main/scala/alleycats/EmptyK.scala
it's there because of the lawless nature.

**Comment by eed3si9n** [comment]
> They may be the same between the two (maybe Option has the same behavior?) but given they live in different hierarchies it wouldn't surprise/bother me if it meant they had a different notion.

That's my point. They are currently disconnected so the two notions of "emptiness" can diverge between `MonadFilter` and `MonoidK`. Suppose we are not into having multiple typeclass instances per datatype, I see `List` having two different notions of emptiness to be a bug rather than a feature.

Note that this won't happen to `MonadPlus` because it's on top of `Monad`:

```haskell
class Monad m => MonadPlus m where
  mzero :: m a
  mplus :: m a -> m a -> m a
```

In Cats itself `Alternative` brings in `MonoidK`:

```scala
@typeclass trait Alternative[F[_]] extends Applicative[F] with MonoidK[F] { self => ...
```

so the hierarchy gets unified there, and to make the matter more complicated `MonadCombine` extends both `Alternative` and `MonadFilter`.

```scala
@typeclass trait MonadCombine[F[_]] extends MonadFilter[F] with Alternative[F] { self => ...
```

Is there a reason to keep `MonadFilter` around now that filtering is done via `FunctorFilter`?

**Comment by kcsongor** [comment]
In all of these cases, an empty element is the identity of the binary operation.
Say `Int` has a monoid instance with multiplication, where identity (empty) is 1. It also has a monoid instance with addition, where identity is 0. But `Int` itself doesn't have an empty element.
The point is that emptiness is the property of the operation, and not something that could be separated out. (in a lawful way)

What I mean is you can say that `Monoid = Semigroup + Empty`, but `Empty` on its own doesn't make sense.

**Comment by kcsongor** [comment]
does `FunctorFilter` make sense on non-Applicative functors? I can't see how you would be able to do the filtering without at least a lax monoidal structure.

**Comment by eed3si9n** [comment]
@kcsongor I agree that mathematically a monoid is formed under a pair of datatype and a binary operation like `(Int, +)`, but when we deal with `Monoid` with upper case I think we pretend that there is *the* binary operation for **`Int`**. Here's a proof:

```scala
scala> import cats._, cats.instances.all._
import cats._
import cats.instances.all._

scala> Monoid[Int].combine(1, 1)
res0: Int = 2

scala> Monoid[Int].empty
res1: Int = 0
```

I'm ok with "let's make sure all typeclasses have laws." That's fine.

Really what I'm questioning is having two notions of emptiness coming from two class hierarchies that eventually gets merged into one.

```scala
scala> MonadFilter[List].empty[Int]
res2: List[Int] = List()

scala> MonoidK[List].empty[Int]
res3: List[Int] = List()

scala> MonadCombine[List].empty[Int]
res4: List[Int] = List()
```

### deriving empty from FunctorFilter

While we're at it, I am wondering if `empty` can just be derived out of FunctorFilter's `filter` like so:

```scala
scala> FunctorFilter[List].filter(List(1, 2, 3))(_ => false)
res5: List[Int] = List()

scala> FunctorFilter[Option].filter(Some(1))(_ => false)
res6: Option[Int] = None
```

This might also be another case for removing `MonadFilter` as a typeclass.

### consistent emptiness

To me, it would be odd if the emptiness arrived by `xs filter {_ => false }` and the identity on `MonoidK[List]` is different. I think there should a law to check the consistencies between the two. Does that make sense?

### MonadCombine

Looking at `MonadCombine`, I don't think it actually needs `MonadFilter[F]` in the mix.

**Comment by kcsongor** [comment]
re: deriving from `filter`:
It feels odd that you need a concrete instance of a List in order to be able to generate an empty one. This being said, I'm still confused about `FunctorFilter`. It doesn't explicitly necessitate the definition of an `empty` element, but as you've shown, it definitely has to exist - that's what you get if you filter everything out.

`MonadFilter` doesn't seem to add anything here.

Can you show me a proper instance of `FunctorFilter` that doesn't admit a `MonoidK` structure?

**Comment by non** [comment]
@kcsongor I'm not sure that's the best line of reasoning: for any `F[_]` I can give you a `SemigroupK[F]` (e.g. *take-left*), and if you give me a way to test emptiness I can give you a `MonoidK[F]` as well (e.g. *take-left-if-not-empty*). That doesn't necessarily mean that those operations are particularly useful or meaningful.

I do agree that `FunctorFilter[F[_]]` should probably have an `empty` method (but *not* necessarily an `isEmpty` test). In the context of `map` it's possible to write laws about `empty` (which is the usual objection against an `Empty[F[_]]` type class: that it's lawless). I'm a bit agnostic on whether we should remove `MonadFilter` or not.

**Comment by BennyHill** [comment]
ref https://gitter.im/typelevel/cats-dev?at=5a99bffa6f8b4b9946e0c3c6 

Could this now be closed?

**Comment by kailuowang** [comment]
MonadFilter moved to cats-mtl.
