### ISSUE TITLE
Add a trait LeftFoldable[F[_]] such that Foldable[F[_]] <: LeftFoldable[F[_]] 

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/cats#1339]
It seems useful (at least, to me) to encode a notion of objects that support left-associative folding but not right-associative:  `Foldable[F[_]] <: LeftFoldable[F[_]]`

Likely also:  `Foldable[F[_]] <: RightFoldable[F[_]]`

**Comment by edmundnoble** [comment]
Can you give an example of a structure that would satisfy `LeftFoldable` but not `RightFoldable`? What exactly are you trying to capture in the associativity of the fold? You can reverse the associativity of a fold trivially; i.e., `foldLeft` and `foldRight` can be implemented in terms of each other, with the only differences being strictness and performance, and so if no laws differentiate `LeftFoldable` from `RightFoldable` I cannot see them being useful abstractions. I believe offering typeclasses abstracting over folds with different performance and strictness characteristics could be very useful, especially for stack-safety, but associativity not as much.

**Comment by erikerlandson** [comment]
For my purposes, it was more about just being interested in the left-associative fold, and not wanting to have to implement the right-associative method.   If one can be implemented from the other, maybe the better answer is to provide a pair of _sub_-classes, where only one implementation is required and the companion has a default implementation in terms of that, with whatever efficiency impact there may be.

**Comment by edmundnoble** [comment]
Ah, that makes a lot of sense. I believe what you're looking for - default implementations of redundant typeclass methods - is covered by #992, which is currently attached to the 1.0.0 milestone. Scalaz 8 should also have it out of the box when it's released, as of https://github.com/scalaz/scalaz/pull/1226.

Haskell has a similar mechanism for declaring that e.g., Foldable requires at least `foldLeft` or `foldRight` and will use a default implementation for either if not provided.

**Comment by erikerlandson** [comment]
Actually another angle (and not mutually exclusive) would be to provide factory methods that generate concrete instantiations, based on either a left-associative definition or right-.  However, that may be more an algebird style of solution than in cats.
