### ISSUE TITLE
Consider freezing cats-kernel

### ISSUE THREAD

**Issue by non** [typelevel/cats#1341]
Hi folks,

As per the comments on this _algebra_ PR (https://github.com/non/algebra/pull/162) I want to start thinking about freezing _cats-kernel_. By freezing, I mean turning on MiMA compatibility checking, and committing to keeping the API stable for a relatively long timeframe (e.g. a year or more).

Before we do this I want to be be sure that the design of _cats-kernel_ and _algebra_ works for Spire (and Algebird too). We should also be sure that it works for Cats.

Has anyone identified problems in the design of _cats-kernel_ that would break compatibility to fix? Is there anything people think is essential to add or change? I know the design is slightly inconsistent with Cats (necessarily for compatibility reasons). I'm asking more about the names, methods, and type classes than about these kinds of consistency concerns, but if you feel strongly about those feel free to bring them up here.

What do you all think? From a Cats-centric point of view, is _cats-kernel_ ready to be declared done?

**Comment by non** [comment]
I should add that I think freezing *cats-kernel* is a required precursor to *cats-1.0.0* so the process I mention about freezing could happen relatively quickly.

**Comment by adelbertc** [comment]
One thing I've noticed is the style of laws exposed in `kernel-laws` differs from that of `cats-laws`. I have a ticket to track this: https://github.com/typelevel/cats/issues/1272

**Comment by non** [comment]
@adelbertc I'm open to doing this, but I want to get the *algebra* team on board first.

**Comment by kailuowang** [comment]
Should this one be closed now? according to this  https://github.com/typelevel/cats/blob/master/build.sbt#L222 kernel is locked at 0.8.0

**Comment by ceedubs** [comment]
I think that this is resolved. @non feel free to reopen if I'm mistaken.
