### ISSUE TITLE
Add toNestedValidatedand and toNestedValidatedNel to XorT/EitherT

### ISSUE THREAD

**Issue by mkotsbak** [typelevel/cats#1344]
These would be similar to `XorT.toOption(implicit F: Functor[F]): OptionT[F, B]`

**Comment by kailuowang** [comment]
`XorT` is removed since 0.7.0. Do you want this for the replacement `EitherT`?

**Comment by mkotsbak** [comment]
Ah ok, yes please, and to XorT too if there are 0.7 minor releases.

**Comment by conniec** [comment]
Hi @mkotsbak, do you mean something like this? 

```def toNestedValidated(implicit F: Functor[F]): Nested[F, Validated[A, ?], B] ``` ?

**Comment by mkotsbak** [comment]
Yes

**Comment by peterneyens** [comment]
Added in #1408.
