### ISSUE TITLE
The combineAll method of MapMonoid always returns an empty map

### ISSUE THREAD

**Issue by denisftw** [typelevel/cats#1346]
I was updating my tutorial to Cats 0.7.0 and noticed that combining `Map`s doesn't work as expected. 
The `combine` method works:

```scala
import cats.instances.int._, cats.instances.map._

val totals1 = Monoid[Map[String,Int]].combine(Map("a" -> 12, "b" -> 21), Map("a" -> 10))
println(totals1) // Map(a -> 22, b -> 21)
```

However, the `combineAll` method doesn't work:

```scala
val scores = List(Map("a" -> 12, "b" -> 21), Map("a" -> 10))
val totals2 = Monoid[Map[String,Int]].combineAll(scores)
println(totals2) // Map()
```

I looked at the [combineAll implementation](https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/map.scala), and it seems that `acc` is initialized as an empty `Map`, but it isn't changed throughout the function. Maybe that's the cause of the problem.

**Comment by non** [comment]
Ugh! Thanks for catching that. Will fix (and add tests to catch this).
