### ISSUE TITLE
Release 0.7.1?

### ISSUE THREAD

**Issue by non** [typelevel/cats#1349]
I feel like #1346 is serious enough to warrant an urgent 0.7.1 release. The fix is already in *master* and I'm prepared to do a release tonight but realized I should probably get a few other maintainers to sign-off on this plan as well.

My proposal is to do the release now, and then assemble some release notes (such as they are). Since it hasn't been long since 0.7.0 it shouldn't be too hard to put those together -- I'd be happy to do that as well.

What do you all think?

**Comment by rossabaker** [comment]
:+1: to the release and the numbering.

**Comment by kailuowang** [comment]
Let's see if `sbt release` works this time.

**Comment by non** [comment]
Alright, I think two sign-offs is good enough. Releasing!
