### ISSUE TITLE
Add {Xor, XorT}.filter question to FAQ

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1361]
Pretty regularly someone asks about a `filter` method on `Xor` or `XorT` either on Gitter or in [a GitHub issue](https://github.com/typelevel/cats/issues/1294). We've made a conscious decision to not implement `filter` on these types, but we should add the reasoning to the FAQ (and perhaps also to the data structure scaladocs).

**Comment by diesalbla** [comment]
Given that the types `Xor` and `XorT` were removed from `cats`, this issue is no longer relevant.
