### ISSUE TITLE
Tuple Apply syntax fixes

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1363]
Referring to this syntax:

``` scala
import cats.implicits._

(Option(2), Option(3)).map2(_ + _)
```
- [ ] No `Unapply`
- [ ] Should this be under `cats.syntax.tuple` as it currently is or `cats.syntax.apply`?
- [ ] Deprecate/remove CartesianBuilder syntax

**Comment by non** [comment]
For (1), let's add it!
For (2) I think I prefer `cats.syntax.apply`.
For (3), yes.

**Comment by longcao** [comment]
As noted by @non, maybe `mapN` would be a nice name for this: https://gitter.im/typelevel/cats?at=582dd60269eb65323c45819c

**Comment by mpilquist** [comment]
:+1: for `mapN` so that folks don't need to manually count the number of values.

**Comment by julienrf** [comment]
for `Unapply` support I remember having tried without success a few month ago. You can see my code [here](https://gist.github.com/julienrf/26cb86a423dba86c8b2cd3111424cb57).

**Comment by mpilquist** [comment]
@julienrf I think we can drop `Unapply` support now that we have SI-2712 fixed.
