### ISSUE TITLE
Monad instance for tuple 2 causing strange implicit search behavior for non-tuple types

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1368]
Although such behavior isn't very easy to reproduce, I have a minimum example here but it involves shapeless
```scala 
import cats.{Applicative, Unapply}
import cats.instances.all._
import shapeless._

object Test {

  trait Foo[L <: HList]

  object Foo extends MkFoo

  trait MkFoo0 {
    implicit def con[H, T <: HList](implicit st: Foo[T]): Foo[H :: T] = null
  }

  trait MkFoo extends MkFoo0 {
    implicit def nil[F[_] : Applicative]: Foo[HNil] = null
    implicit def single[H]: Foo[H :: HNil] = null
  }

  implicitly[Foo[Either[String, Int] :: Either[String, Int] :: Either[String, Int] :: HNil]]   // <-  attempt1 passes
  implicitly[Foo[Either[String, Int] :: HNil]] //<- attempt 2 fails compilation with  diverging implicit expansion
}
```

As noticed above there is no tuple type involved, but during the compilation, the compiler some how get to this implicit [instance](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/instances/tuple.scala#L47-L50) search in tuple which then try to locate a `Monoid[X]`, then the search begins 
From the log below, it's a rather ridiculous search. This somehow still compiles but won't compile with Si-2712 fix. I suspect that somewhere tuple is used as primitives (could be predef) that complicated the type search.
This issue forbids `kittens.sequence` users from using `cats.implicits._`  .  

> [info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:27: cats.this.Unapply.catsUnapply2left is not a valid implicit value for cats.Unapply[cats.Applicative,Either[String,Int]] because:
[info] hasMatchingSymbol reported error: could not find implicit value for parameter tc: cats.Applicative[[α]Either[α,Int]]
[info]   implicitly[Unapply[Applicative, Either[String, Int]]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsStdInstancesForEither is not a valid implicit value for cats.Applicative[F] because:
[info] incompatible: cats.MonadError[[β]scala.util.Either[Nothing,β],Nothing] with cats.Traverse[[β]scala.util.Either[Nothing,β]] with cats.RecursiveTailRecM[[β]scala.util.Either[Nothing,β]] does not match expected type cats.Applicative[?F]
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsStdInstancesForFuture is not a valid implicit value for cats.Applicative[F] because:
[info] hasMatchingSymbol reported error: Cannot find an implicit ExecutionContext. You might pass
[info] an (implicit ec: ExecutionContext) parameter to your method
[info] or import scala.concurrent.ExecutionContext.Implicits.global.
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsStdMonoidForTry is not a valid implicit value for cats.Monoid[A] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsStdMonoidForTry is not a valid implicit value for cats.Monoid[A] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsStdMonoidForFuture is not a valid implicit value for cats.Monoid[A] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForBigDecimal is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForBigInt is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdMonoidForMap is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdMonoidForTuple22 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForTuple22 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdMonoidForTuple21 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForTuple21 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdMonoidForTuple20 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForTuple20 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdMonoidForTuple19 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:28: catsKernelStdGroupForTuple19 is not a valid implicit value for cats.Monoid[A] because:
[info] diverging implicit expansion for type cats.Monoid[A]
[info] starting with method catsStdMonoidForTry in trait TryInstances1
[info]   implicitly[Foo[Either[String, Int] :: HNil]]
[info]             ^

Log truncated here. 
The search goes on and on, hitting all kinds of instances.

**Comment by johnynek** [comment]
it is not clear to me how the `Monad` instance you linked to is involved. Can you explain it a bit? It seems like you are seeing all kinds of instances searched (including Future and Try and more).

**Comment by kailuowang** [comment]
I don't know how the `Monad` instance of `Tuple2` gets involved either. I can see how `Monad` becomes a target as the code was looking for a `Applicative`. I am almost certain that there is a scalac bug somewhere. Notice that there are two lines that are doing the same the implicit search. 
```Scala
 implicitly[Foo[Either[String, Int] :: Either[String, Int] :: Either[String, Int] :: HNil]]  
 implicitly[Foo[Either[String, Int] :: HNil]] 
```
The two searches should be searching the exactly same thing (actually if you can replace the second line with the first one and get the same error), but from the log, the first search went fine (as you can see from the first couple of lines of the output.) The second search is the one that went wild. It first complains that "`catsStdInstancesForEither` is not a valid implicit value for `cats.Applicative[F]`, but we couldn't see what `F` is. Then it complains that `catsStdInstancesForFuture`  is not a valid implicit value for `cats.Applicative[F]`. That gives me the impression that the `F` is not a very concrete type.  Then it complains that `catsStdMonoidForTry is not a valid implicit value for cats.Monoid[A]` which lead me to tuple2 Monad instance which requires a `Monoid`. And I confirmed that it's the case by removing that instance and the error went away. Again it seems to me that compiler doesn't know what type A is, and it's trying every single instance to fit in. Maybe  this `A` or `F` is `Nothing` or `Any`, I don't know. 

My completely blind guess is that somewhere in the scalac, it creates an intermediate tuple type. It also has something to do with the `Unapply`.

**Comment by kailuowang** [comment]
UPDATE: I simplified the reproducing example to a search for any `F[_] : Applicative` which might demonstrate an issue closer to the root cause in the chain. 
The symptom is that if you try to search instance for any `F[_]` for an typeclass under which `Tuple2` has instances, the search goes crazy (but eventually compiles for this particular example. 
```scala 

import cats.Applicative
import cats.instances.tuple._

object Test {
  trait Foo

  object Foo {
    implicit def mk[F[_] : Applicative] = null
  }

  implicitly[Foo]
}
```

This issue forbids `kittens.sequence` users from using `cats.implicits._`  .  


> [info] Compiling 1 Scala source to /Users/1110604/projects/kittens/core/.jvm/target/scala-2.11/test-classes...
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdMonoidForTuple22 is not a valid implicit value for cats.kernel.Monoid[A0] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.kernel.Monoid[A0]
[info] starting with method catsKernelStdMonoidForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple22 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple22 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple21 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple20 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple19 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple18 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple17 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple16 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple15 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple14 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple13 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple12 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple11 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple10 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple9 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
[info]             ^
[info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdGroupForTuple8 is not a valid implicit value for cats.kernel.Group[A0] because:
[info] diverging implicit expansion for type cats.kernel.Group[A0]
[info] starting with method catsKernelStdGroupForTuple22 in trait TupleInstances
[info]   implicitly[Foo]
             ^

Output truncated here. 
The search goes on and on, hitting all tuple2-22 instances.

**Comment by johnynek** [comment]
I'm confused by this code. I don't see any method to give an implicit `Foo`. Is this working because `Null <: Foo` and you have an implicit `Null`? If so, might this be fixed by putting a type on your `def mk[F[_]: Applicative]: Foo` method?

Also, this is really weird, right?. So, for any `F[_]` at all that there is an applicative, just make a `Foo`. I mean, the compiler has to search all types (including all Tuples) to see if they have applicatives because you can view a `(Int, ?)` as a candidate, or `(Int, Int, ?)` right?

I'm not sure why we expect good behavior from this code.

**Comment by kailuowang** [comment]
I appologize @johnynek , the example in the comment above was mistyped. It should be ` implicit def mk[F[_] : Applicative] : Foo = null`.  
I think now I understand the problem a bit better.  Basically the compiler is just looking for any implicit value of `Applicative[F]` type in which `F` can be **any type**.  
In the above sample code (corrected with the right type `Foo` for `mk`) , if you replace `import cats.instances.tuple._` with `import cats.instances.option._`, the compiler quickly happily finds the `Applicative` instance. If you replace it with `import cats.instances.option._, cats.instances.list._`, the compiler quickly tells you that there is ambiguous implicit `Applicative`s in scope. 
When you `import cats.instances.tuple._` though, the only tuple that has `Applicative` instance is `Tuple2` through `Monad`, but it requires a `Monoid` for the type of the first item . And because the type of first item is not fixed in this case, so, I think, the compiler again just tries to find a `Monoid` for **any type**. This search for `Monoid` isn't that smooth within the scope of tuple instances - it doesn't quickly find one, nor did it quickly get an ambiguous result. It took a lot of search attempt failures as seen in the implicit search logs.
This means that if we have a `Tuple2` with `Nothing` as the type for the first item we might have the same difficulties in search. To verify, I just tried this search: 
`implicitly[Monad[(Nothing, ?)]`
And sees all the implicit search failures again. I know, its tempting to say "well if might just take that many searches to find out there is not `Monoid` for `Nothing`". But it's not true, a search for `implicitly[Monoid[Nothing]] returns pretty quickly. 

I maybe over simplified the original problem (i.e. `kitten.sequence` incompatible with the `Monad` instance of `Tuple2`), but I think this search difficulty for `Monad[(Nothing, ?)]` is probably related. 

From the log, I think the following error might be causing the difficulty of finding a `Monoid` when search within tuple instances.
> [info] /Users/1110604/projects/kittens/core/src/test/scala/cats/sequence/sequence.scala:16: catsKernelStdMonoidForTuple22 is not a valid implicit value for cats.kernel.Monoid[A0] because:
[info] hasMatchingSymbol reported error: diverging implicit expansion for type cats.kernel.Monoid[A0]

But I haven't found out why or how to fix it.

**Comment by johnynek** [comment]
@kailuowang I don't see how this is a bug. Why do you want an `Applicative` for some unknown `F[_]` that the compiler can choose? If you don't care, just use `Id` and not have the giant search.

I mean, I guess I'd like the compiler to be smart about it, but it is not clear it is an easy problem to write this algorithm in a way it will terminate on an easy instance and not spiral out on nested tuples.

**Comment by kailuowang** [comment]
For `kittens.sequence`,  `F[_]` it's not a given, it has to be "figured out" by the compiler. For example, in
`(Option(1) :: Option("A") :: HNil).sequence //results in Some(1::"A"::HNil)
The fact that `F[_]` is `Option`  needs to be figured out by the compiler. 

I don't see it as a bug in cats either, I think it's a subtle scalac bug that materialized with the `Tuple2` `Monad`. In best thing I can come up with to describe this bug is:
implicit search for `Monad[(Nothing, ?)]` causes a lot of search errors for `Monoid[A0]` (through `  implicit def catsStdMonadForTuple2[X](implicit MX: Monoid[X]):Monad[(X, ?)]` , while implicit search for `Monoid[Nothing]` happens pretty quickly. 
Isn't that a bit weird?

**Comment by kailuowang** [comment]
I made a change in sequence so that it's no longer an issue with kittens.sequence. I am closing this for now. Thanks for help investigating, @johnynek

**Comment by johnynek** [comment]
Can you link to the diff just in case anyone gets hit by it again? Glad you
got to the bottom!

**Comment by kailuowang** [comment]
Here is the kitten PR that resolved the issue. 
https://github.com/milessabin/kittens/pull/24/files
The code that caused the problem was exactly like the one in the second example I posted here. 
```Scala
 implicit def nilSequencerAux[F[_] : Applicative]: Aux[HNil, F[HNil]] = ...
```
This line only confuses compiler when the implicit search fails in some route.
