### ISSUE TITLE
More cats.data.Prod instances

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1375]
https://hackage.haskell.org/package/transformers-0.5.1.0/docs/Data-Functor-Product.html

**Comment by pepegar** [comment]
Working on it!

Would it be better to have just all the instances in the same pull request, or is it better to have one pull request for each one?

**Comment by adelbertc** [comment]
@pepegar Awesome, thanks!

I would be fine to just have them all in one PR. Would probably be very annoying for you to have to have N branches for each of the N instances. I'm also guessing you might have to group some of them up if only so you can do things like split out type class implementations into traits so you can re-use them.

**Comment by pepegar** [comment]
Instances I've found I think I'll be able to implement are:

* Monad
* Foldable
* Traverse
* Show

More ideas?

**Comment by pepegar** [comment]
Work is being done [here](https://github.com/pepegar/cats/tree/more-instances-for-prod)

**Comment by adelbertc** [comment]
Looks like you could also do `MonadPlus` and `Ord` I think.

**Comment by pepegar** [comment]
Maybe I am doing it wrong, but cannot find where `MonadPlus` is implemented in Cats... Any hint?

**Comment by adelbertc** [comment]
Sorry, we call it `MonadCombine` https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/MonadCombine.scala
