### ISSUE TITLE
More MTL instances

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#1378]
A lot of MTL instances are defined inductively, see: https://hackage.haskell.org/package/mtl

We seem to only have the obvious instances, but none on the other transformers.

**Comment by kailuowang** [comment]
should this one be closed by #1413?

**Comment by kailuowang** [comment]
@adelbertc should this one be closed by #1413?

**Comment by adelbertc** [comment]
Mm, we're still missing instances. For instance we don't have a `MonadWriter` for `EitherT` if `F[_]: MonadWriter`.

On a related note @edmundnoble is working on a re-encoding of the MTL type classes soo..

**Comment by kailuowang** [comment]
Sort of blocked by #1210

**Comment by kailuowang** [comment]
continued on #1616
