### ISSUE TITLE
Figure out what to do with MonadCombine and left-distributivity

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1381]
This is a follow-up item to address the left-distributivity law from `MonadCombine` being removed in #1345. In the comments on that PR there is some discussion about this law and whether or not it should exist in its previous form on `MonadCombine`.

**Comment by non** [comment]
I support what @johnynek proposed: `MonadOr` and `MonadCombine`, each with the relevant set of laws.

**Comment by adelbertc** [comment]
Concerns surrounding more of these kinds of type classes: https://github.com/typelevel/cats/pull/1379#issuecomment-247878936

**Comment by LukaJCB** [comment]
`MonadCombine` hasn't been around for a while, closing this out :)
