### ISSUE TITLE
Symbols page not on site

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1384]
We have this handy symbols guide: https://github.com/typelevel/cats/blob/master/docs/src/main/tut/symbols.md

But as far as I can tell it's not being published to the docs site. I think that it may be because it's missing the yaml/jekyll front matter at the top of the file. We should also make sure that we link to this page so people can find it.

**Comment by zainab-ali** [comment]
I'd be happy to add this, but I'm unsure which section it would go in.  Definitely not typeclasses or data types - perhaps it should be a subsection under the FAQ?

**Comment by kailuowang** [comment]
fixed by #1573
