### ISSUE TITLE
Consider using Travis-CI Trusty Beta

### ISSUE THREAD

**Issue by BennyHill** [typelevel/cats#1387]
ref https://docs.travis-ci.com/user/ci-environment/

The scala.js continues to randomly fail, I suspect due to the limited memory, 4 GB __Max__, available in Travis-CI container builds and hence little available for SBT.

Their Trusty Beta environments have 7.5 GB, so would allow  an increase to 5 or 6 GB [in the options] (https://github.com/typelevel/cats/blob/master/.jvmopts#L4). The downside of the the slower boot time is a small fraction of the overall build time.

**Comment by kailuowang** [comment]
I am going to give this a try.

**Comment by kailuowang** [comment]
fixed by #1389
