### ISSUE TITLE
Bassem haddara

### ISSUE THREAD

**Issue by bassemhaddara** [typelevel/cats#1406]
removed

**Comment by bassemhaddara** [comment]
Ok then that's  great

**Comment by bassemhaddara** [comment]
How can do it

**Comment by bassemhaddara** [comment]
[samii-master.zip](https://github.com/typelevel/cats/files/524919/samii-master.zip)

**Comment by bassemhaddara** [comment]
Thank you

**Comment by bassemhaddara** [comment]
Thanks

**Comment by non** [comment]
Looks like spam/viruses/whatever.
