### ISSUE TITLE
Start using sbt-microsites for doc

### ISSUE THREAD

**Issue by tpolecat** [typelevel/cats#1409]
This is a really nice plugin that does all the boring parts of maintaining a doc site. Basically builds on top of tut by building up a nice website around the output. Should be straightforward to try out.

- https://47deg.github.io/sbt-microsites/

**Comment by adelbertc** [comment]
👍

**Comment by kailuowang** [comment]
This PR is doing that. https://github.com/typelevel/cats/pull/1369 I already gave my thumb up. @ceedubs mentioned that he would give it a look.

**Comment by tpolecat** [comment]
Aha! Sweet.
