### ISSUE TITLE
Cofree comonad

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/cats#1422]
Should I add it? Would anyone be interested in both lazy and strict versions of Cofree? I find the strict version very useful in creating trees.

**Comment by adelbertc** [comment]
Paging @sellout our Cofree extraordinnaire

**Comment by sellout** [comment]
Well, I think if you’re going to have Free, you should have Cofree! I’m still mostly a Cats spectator at this point, though.

**Comment by adelbertc** [comment]
I think it makes sense to have corresponding `Co-` versions of the `Free` stuff we have. 👍  from me.

**Comment by edmundnoble** [comment]
I'm on it. My current plan is to trampoline the tail with `Eval`, if anyone is interested in a strict `Cofree` (or, perhaps, a tagged "newtype" with strict instances on a `Cofree`) please do speak up.

**Comment by adelbertc** [comment]
Awesome, thanks!

**Comment by tpolecat** [comment]
Yep we definitely need this. Scalaz only has the lazy one and nobody ever complained as far as I know so that's probably sufficient.

**Comment by adelbertc** [comment]
Do you think it would also make sense to add `Fix`-y things, or does that belong in a (hypothetical) `matryoshka-cats` ?

**Comment by sellout** [comment]
@adelbertc I vote the latter – I _really_ want to make Matryoshka FP-lib-agnostic, but don’t really have the bandwidth for it at the moment.

Also, because I think there’s another lib of higher-order stuff (which I am tentatively calling Griffins) that Matryoshka will want, that we probably(?) don’t want to lump into Cats.

**Comment by tpolecat** [comment]
Yeah I think `Free` and `Cofree` are probably good enough for Cats proper.

**Comment by KadekM** [comment]
Yes please, Cofree is useful and I'd feel much better using standardised cats one than reinventing it :)

**Comment by kailuowang** [comment]
closed by https://github.com/typelevel/cats/pull/1446
