### ISSUE TITLE
class diagram not rendered in sites

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1438]
The type class diagram isn’t rendering correctly in microsites
It’s renderred correctly in github:
https://github.com/typelevel/cats/blob/master/docs/src/main/tut/typeclasses/typeclasses.md
But the markdown is simply displayed as plain text here in the site
http://typelevel.org/cats/typeclasses.html
cc @juanpedromoreno I wonder if you happen to have some clue off the top of your head.

**Comment by juanpedromoreno** [comment]
Oops, we could tackle it in one of these ways:

http://pother.ca/StackOverflow/question.13808020.include-an-svg-hosted-on-github-in-markdown/

@kailuowang Would be any of those alternatives valid?

**Comment by kailuowang** [comment]
@juanpedromoreno thanks! I am not sure I understand the cause of this problem. The question you posted, it seems to me, is about github serving text based file with text content type. In our case the svg is served by a 3rd part service gravizo.com, which shouldn't have the content type problem. In our case, I think jekyll didn't render the ![XXX](http://....) into an image tag, rather, it just render it as plain text. Could it be related to the embedded dot language in the url?

**Comment by kailuowang** [comment]
I found out a cause some entries has quotes in name. e.g. `"functor.Invariant"`, without the `"`, the `.` will break the entry name. However this seems broke the jekyll rendering, if I replace all quoted entry with a single word, the diagram works, e.g. change from `"functor.Invariant"` to `Invariant`.  So the solution I think we can take is to use a label `functor` for that sub group instead of using `functor.Invariant` and `functor.Contravariant`

**Comment by juanpedromoreno** [comment]
Oops, sorry for the late answer, good to know that the issues were resolved. 

Thanks @kailuowang

**Comment by kailuowang** [comment]
@juanpedromoreno no problem. Thanks again for your tremendous contribution to cats' site. Everybody loves it.
