### ISSUE TITLE
Don't use PK's natural xform syntax in docs 

### ISSUE THREAD

**Issue by tpolecat** [typelevel/cats#1449]
The intro doc for `FreeApplicative` (at least) uses the new PK syntax for natural transformation literals but doesn't offer an explanation, which was baffling for me and I assume would also be for most beginners. So I suggest we write out the `~>` construction explicitly in the doc, and maybe introduce the shorter form as an aside.

**Comment by adelbertc** [comment]
Will keep this in mind for https://github.com/typelevel/cats/issues/1449

**Comment by ceedubs** [comment]
I believe this was solved by #1472. @tpolecat please let me know and reopen if I've missed something.
