### ISSUE TITLE
`MonadTests[M].stackUnsafeMonad` overflows - `MonadLaws.tailRecMStackSafety` should be a def

### ISSUE THREAD

**Issue by TrustNoOne** [typelevel/cats#1463]
`MonadLaws.tailRecMStackSafety` is currently a `val`; this means `MonadTests[M].stackUnsafeMonad` checks for stack safety anyway as soon as the `MonadLaws[M]` instance is created

**Comment by non** [comment]
Good catch!  I think a `lazy val` might be best but a `def` would work too.

**Comment by edmundnoble** [comment]
We should also look into testing this by changing MonadTestsTests to use a stack-unsafe monad.

**Comment by travisbrown** [comment]
Ugh, I think this must have been my fault. Thanks for catching it, @TrustNoOne.
