### ISSUE TITLE
Decide what to do about Unapply in the short term

### ISSUE THREAD

**Issue by DavidGregory084** [typelevel/cats#1491]
To deprecate our CartesianBuilders (part of #1363) we will be creating tuple apply syntax instances for Tuple1..22.

However, these instances cannot be resolved without `-Ypartial-unification` enabled.

It has been suggested that we extend our Unapply machinery to do this and I have prototyped this for Tuple2 in #1487 based on @julienrf's work.

I also had a quick look at templating Unapply2..N as part of our generated code but this was a bit of a horrible process and I'm not sure whether to continue it.

Should we put #1363 and similar issues on hold until Scala 2.11.9 is available and we can remove Unapply entirely?

**Comment by peterneyens** [comment]
This is related to #1073.

**Comment by peterneyens** [comment]
We removed `Unapply` in #1679.
