### ISSUE TITLE
Kleisli as AnyVal

### ISSUE THREAD

**Issue by 13h3r** [typelevel/cats#1503]
Is it any reason to not make Kleisli extends AnyVal? It should improve performance and have no downsides (from my pov). Am I miss something?

**Comment by 13h3r** [comment]
Here it is the reason -  https://issues.scala-lang.org/browse/SI-7685

**Comment by edmundnoble** [comment]
I believe it will be binary incompatible; however, Kleisli is not the only data type which needs this treatment. Cokleisli, Const, Coproduct, EitherT, IdT, Nested, OptionT, WriterT...

**Comment by ceedubs** [comment]
See also #546.

**Comment by johnynek** [comment]
seems like https://github.com/typelevel/cats/issues/546#issuecomment-143931634 implies we have made a decision here.

I'm closing. Reopen if this is premature.
