### ISSUE TITLE
Put together coding style guide

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#151]
Currently the contributor guide just has a TODO for the [Write code](https://github.com/non/cats/blob/7ace9b39b333a8d6ae3536013993eacfc6fff31f/CONTRIBUTING.md#write-code) section.

This should be expanded into a description of the coding style conventions that Cats is settling on. There are a few items mentioned in the TODO that would make a good start. There are probably others that have been formed but aren't yet listed in the TODO (currying of function parameters is one that comes to mind).

The coding style guide will probably become large enough that it will warrant its own document that can be linked to from the CONTRIBUTING doc. We can either do that now or come back to it later as the doc grows.

**Comment by channingwalton** [comment]
#147 is related.

**Comment by ceedubs** [comment]
This was resolved some time ago. Closing this out.
