### ISSUE TITLE
Document Either's replacement for Xor's `.left` and `.right`

### ISSUE THREAD

**Issue by gavares** [typelevel/cats#1533]
In older versions of cats, it was very nice to use `.left` and `.right` to convert values into Xor instances. With the move to `Either`, there are no examples or documentation that instructs users about the change. It would be nice to add some notes in the FAQ here: http://typelevel.org/cats/faq.html#either and/or add an example usage in to docs here: http://typelevel.org/cats/datatypes/either.html#either-in-the-small-either-in-the-large showing and explaining that `.left` -> `.asLeft` etc.

**Comment by armanbilge** [comment]
I'd say Xor is ancient history. I don't know what it is anyway.
