### ISSUE TITLE
Adding Ior syntax to cats.syntax package object

### ISSUE THREAD

**Issue by leandrob13** [typelevel/cats#1539]
I had a practical use of Ior recently and I had the need of some useful syntax like there is for validated or option. The purpose of this would be to have useful syntax for Ior as well to add into other syntaxes functions `leftIor`, `rightIor` or `both` in validated, option and either syntaxes.

Is this something that would be worth working on? I might have an example to add to the tut docs.

**Comment by peterneyens** [comment]
Added in #1540.
