### ISSUE TITLE
MonadError instance for Kleisli

### ISSUE THREAD

**Issue by durban** [typelevel/cats#1542]
Is there any reason for not having a `MonadError` instance for `Kleisli`? Since `MonadError` seems to be simply `Monad` and `ApplicativeError`, and `Kleisli` has instances of both, it seems like it could work. Although prioritizing the instance could be a little tricky, I guess...

**Comment by kailuowang** [comment]
I think we should have a `MonadError` instance for `Kleisli`. Prioritizing shouldn't be too tricky. We just need a new layer between the current `KleisliInstance` and `KleisliInstance0` and move `ApplicativeError` instance there. This probably means that rename all `KleisliInstanceN` to ``KleisliInstanceN+1` and name the new layer `KleisliInstance0`. Care to give a try? :)
