### ISSUE TITLE
MonadError instance for Ior

### ISSUE THREAD

**Issue by leandrob13** [typelevel/cats#1544]
I noticed there is no MonadError instance for Ior. Is there a reason for this?

**Comment by kailuowang** [comment]
I think it's just that people didn't get the chance to add it yet. PR is more than welcome!

**Comment by leandrob13** [comment]
@kailuowang got it. I am already working on #1540 and since it is also Ior related I don't know if I should work on it in the same PR or open a new one. What do you suggest?

**Comment by kailuowang** [comment]
Without any strong preference, I am leaning slightly towards separate PRs.

**Comment by leandrob13** [comment]
@kailuowang got it, I will work on it.

**Comment by kailuowang** [comment]
Thanks very much @leandrob13
