### ISSUE TITLE
Add Validated.ensure[EE >: E](onFailure: A => EE)(f: A => Boolean): Validated[EE, A]

### ISSUE THREAD

**Issue by ronanM** [typelevel/cats#1550]
Add a `cats.data.Validated.ensure(...)` with this signature: 

`ensure[EE >: E](onFailure: A => EE)(f: A => Boolean): Validated[EE, A]`. 

To be able to extract informations from `A` to construct the `EE` in the failure case with the `onFailure` function.

```scala
val personValidated = ???

personValidated.ensure(p => s"Too young (age: ${p.age} < 18)")(_.age >= 18)
```

**Comment by LukaJCB** [comment]
I can make a PR soon :)

**Comment by pierangeloc** [comment]
Would be nice to have the same feature on `Either`:

```
def ensure[AA >: A](onFailure: B => AA)(f: B => Boolean): Either[AA, B]
```
so that one can write

```
type ErrorWith[A] = Either[String, A]
val n: ErrorWith[Int] = Right(6)
n.map(_*100).ensure(n => s"$n is less than 1000")(_ >= 1000)
```
