### ISSUE TITLE
When implicit imports collide

### ISSUE THREAD

**Issue by paulp** [typelevel/cats#1562]
When you import, at the same scope, two implicits which have the same name, they don't conflict in a way which is reported. They are both silently ignored, as seen here:
```scala
import cats.syntax.all._
import cats.syntax.either._

class A {
  "a".asRight
}
// a.scala:5: error: value asRight is not a member of String
//   "a".asRight
//       ^
// one error found
```
Unfortunately when there are traits which contain implicits and they are mixed into multiple objects, this situation is almost guaranteed to arise. And from a user POV the cause is unbelievably opaque.

I don't know what to do about it but maybe someone else has an idea.

Here's what happens if I rename one of the same-named implicits. I'd say this proves it's a scala bug but I also have the most or second most notabug tickets so don't take my word for it.
```scala
// import cats.syntax.all.{ catsSyntaxEitherId => bob }
// import cats.syntax.either._
// ...
//
// a.scala:5: error: type mismatch;
//  found   : String("a")
//  required: ?{def asRight: ?}
// Note that implicit conversions are not applicable because they are ambiguous:
//  both method catsSyntaxEitherId in trait EitherSyntax of type [A](a: A)cats.syntax.EitherIdOps[A]
//  and method catsSyntaxEitherId in trait EitherSyntax of type [A](a: A)cats.syntax.EitherIdOps[A]
//  are possible conversion functions from String("a") to ?{def asRight: ?}
//   "a".asRight
//   ^
```

**Comment by milessabin** [comment]
It's not a bug because use of a same-named definition (implicit or otherwise) to shadow and hence disable an implicit is a "feature".

**Comment by paulp** [comment]
Using a same named definition to shadow an implicit is a feature. That's not what this is. They're imported at the same scope; neither shadows the other. See the [section on shadowing](http://www.scala-lang.org/files/archive/spec/2.11/02-identifiers-names-and-scopes.html).

**Comment by paulp** [comment]
This can also be verified by explicitly calling the twice-imported name, at which point we get the error we might have expected for the implicit invocation.
```scala
import cats.syntax.all._
import cats.syntax.either._

class A {
  catsSyntaxEitherId("a").asRight
}
// a.scala:5: error: reference to catsSyntaxEitherId is ambiguous;
// it is imported twice in the same scope by
// import cats.syntax.either._
// and import cats.syntax.all._
//   catsSyntaxEitherId("a").asRight
//   ^
```

**Comment by Daenyth** [comment]
This happens in scalaz too - I don't think it's avoidable in the current compiler, though I would dearly love to be proven wrong.

**Comment by armanbilge** [comment]
Doesn't seem like something we can fix. Using only `import cats.syntax.all._` works perfectly fine nowadays.
