### ISSUE TITLE
`Bounded` and `Enum` Type Classes?

### ISSUE THREAD

**Issue by kevinmeredith** [typelevel/cats#1574]
Hi - 

Does this library provide [Bounded](http://hackage.haskell.org/package/base-4.9.1.0/docs/Prelude.html#t:Bounded) and [Enum](http://hackage.haskell.org/package/base-4.9.1.0/docs/Prelude.html#t:Enum) type classes?

I failed to find them:

```bash
$pwd
/Users/kevinmeredith/Workspace/cats
$grep -r 'trait Bounded' . 
./kernel/src/main/scala/cats/kernel/BoundedSemilattice.scala:trait BoundedSemilattice[@sp(Int, Long, Float, Double) A] extends Any with Semilattice[A] with CommutativeMonoid[A]
$grep -r 'trait Enum' . 
$
```

Thanks

**Comment by peterneyens** [comment]
Not for the moment, there also is issue #1536.

**Comment by kevinmeredith** [comment]
I actually no longer have a need for these type classes.

Thanks for pointing me to the existing issue, @peterneyens!
