### ISSUE TITLE
rename Prod / Coproduct to ProductK / CoproductK

### ISSUE THREAD

**Issue by fommil** [typelevel/cats#1582]
The problem is that we already have `scala.Product` and `shapeless.Coproduct` and that means it is easy to get the wrong import.

In addition, it is very unfortunate that `cats` and `shapeless` (the foundations of this FP stack) should have a name conflict on something so simple.

I understand that the `K` postfix is appropriate for a higher kinded thing as a workaround until https://github.com/scala/scala/pull/5538 become ubiquitous. I suppose `M` would also be appropriate?

**Comment by diesalbla** [comment]
¿Could they be called `TupleK` or `PairK`,  and `EitherK`? That would make it a bit more clear the relation to their 0-Kind counterparts.

**Comment by kailuowang** [comment]
I vote for `Tuple2K` and `EitherK`, I think they are more accurate than `ProductK` and `CoproductK` which have no set arity.

**Comment by edmundnoble** [comment]
@kailuowang Makes sense to me; should we add a ProductK and CoproductK (or at least just the CoproductK) to avoid fixing an arity?

**Comment by kailuowang** [comment]
@edmundnoble sure, if there is need for them. Do you think they should go into 1.0.0-RC1 though? if not maybe we should create another issue for them?

**Comment by kailuowang** [comment]
Seems that the opinion we got so far favors renaming to `Tuple2K` and `EitherK`. I am going to go ahead creating a PR.

**Comment by fommil** [comment]
`Produkt` and `Coprodukt` :trollface:
