### ISSUE TITLE
Document how to test typeclass instances with respective laws.

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1585]
From [gitter discussion](https://gitter.im/typelevel/cats?at=58e14e54ad849bcf4244a81e)
We can add a section into the [typeclass page](https://github.com/typelevel/cats/blob/master/docs/src/main/tut/typeclasses/typeclasses.md). 

This would be
> A huge win for cats  - @djspiewak

**Comment by ceedubs** [comment]
I agree that this would be a huge win. One specific thing that I think is a bit confusing is that the law-checking for cats-kernel is significantly different than for the other modules. At a minimum we should document this difference.

See also #529.

**Comment by kailuowang** [comment]
related issue https://github.com/typelevel/cats/issues/1272

**Comment by kailuowang** [comment]
this should be easier now with cats-testkit published.
