### ISSUE TITLE
Union typeclass for abstracting boxed union types

### ISSUE THREAD

**Issue by leandrob13** [typelevel/cats#1593]
Would it make sense to work on a typeclass that can be defined for boxed union types like, but not limited to, Either or Ior? I have this idea in mind:

```scala
trait Union[U[_, _], A, B] extends ApplicativeError[U[A, ?], A] with Monad[U[A, ?]] {
  def isLeft: Boolean

  def isRight: Boolean

  def fold[C](Uab: U[A, B])(fl: A => C, fr: B => C): C

  def leftMap[C](Uab: U[A, B])(fl: A => C): U[C, B]
}
```

If it does make sense, I could work on the PR.

**Comment by peterneyens** [comment]
Also see #974 and #976.

**Comment by leandrob13** [comment]
@peterneyens I see the limitations, specially regarding Validated. Maybe define it only for Either and Ior but I guess it won't be enough to justify its addition to the library. I had a use for it but I guess I might have to rethink my use case.
