### ISSUE TITLE
Let's talk about road map to 1.0.0

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1595]
Timing wise, I think the goal should be set such that cats 1.0.0 is ready for doobie, http4s and Matryoshka to release their own cats-dependent releases mid-to-late 2017 as [announced](https://http4s.github.io/fp-ecosystem/). 

For this to happen, it's obvious to me that we need some managing. 
I think that having a roadmap as a team/community will help us get there,  although I am not, by any measure, an expert in development roadmaps or project management in general.

Please provide your input/feedback/suggestion in the following proposal:

1. **1.0.0-MF**:  MF stands for Final milestone. The main purpose/focus of this release is to give the above three projects (and any other projects targeting cats) a relatively stable API to work with. It can be deemed as a proposal for the final API we are going to lock down at 1.0. The community will then have some time to validate it. Note that unlike other lib, cats commit to maintain binary compatible for a longer time post 1.0, its going to be hard to add new methods to existing typeclasses.
Timing wise, June 3rd the Typelevel summit Copenhagen might be a managable target. 

2. **1.0.0-RC1**: Incorporate all the API changes identified by the community with MF. Polish documentation to be 1.0 ready. 
We use this release to identify bugs that require binary incompatible changes. 
Timing wise, I am thinking 3 months after RC1, so likely Sep 2017

3. **1.0.0**: We fixed all the bugs, cats goes gold! This could be scheduled within 1 month after RC1, So Oct 2017.   

Uodates: revised according to @tpolecat  feedback, changed RC1 to MF and RC2 to RC1. Added some notes to MF.

**Comment by kailuowang** [comment]
paging @tpolecat , @rossabaker, @sellout

**Comment by tpolecat** [comment]
So, to me RC means we think it's done, i.e., in principle 1.0 could arrive a few weeks into June if nobody finds any problems in RC1. If this isn't what we mean then maybe we should have a 1.0.0-Mx or  0.10.x series. I don't have a good feel for the remaining work so I'll try to get caught up over the weekend and may have some concrete thoughts.

In any case there won't be a whole lot of work to do on doobie so don't worry about me.

**Comment by kailuowang** [comment]
M1 is probably more appropriate. I will revise.

**Comment by rossabaker** [comment]
I agree with this plan.  RC2 means something unanticipated happened in RC1.

http4s is already tracking cats, so I have a pretty good idea what we're missing switching to cats.  Right now the only real hangup is the IO story, which is being discussed in a couple other places.

**Comment by kailuowang** [comment]
paging @edmundnoble, I am really looking forward to your new typeclass encoding. Obviously, we would want that for 1.0.0-MF. Does this roadmap (especially the timeline) make sense to you?

**Comment by edmundnoble** [comment]
@kailuowang That makes sense for me. I am a day or so off creating an issue to make a real proposition and promote some discussion on the subject; my PR is a couple of days off as well.

**Comment by kailuowang** [comment]
Implemented into milestones.
