### ISSUE TITLE
Revise Task/IO FAQ to reference cats-effect

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1624]
Originally opened against the wrong repo: https://github.com/typelevel/typelevel.github.com/issues/166

I'm happy to help with this, but I'm not nearly as knowledgable on this subject as @mpilquist and @djspiewak, so I'm hoping that they can lead this effort.

**Comment by djspiewak** [comment]
Happy to lead the effort, just wasn't sure how to word things.  What sort of FAQ entry do we really want?  By which I mean, what exactly do we want to communicate?

**Comment by kailuowang** [comment]
@djspiewak for context here is the current entry http://typelevel.org/cats/faq.html#task. The question is Where is IO/task? I was thinking now the answer to that question would be easier.
