### ISSUE TITLE
a getOrElseM and orElseM?

### ISSUE THREAD

**Issue by fommil** [typelevel/cats#1625]
It'd be nice to be able to write

```scala
for {
  cache <- getFromReddis(key)
  res   <- cache.getOrElseM(getFromSql(key))
} yield res
```

instead of

```scala
for {
  cache <- getFromReddis(key)
  res   <- cache match {
             case Some(cached) => cached.pure
             case None         => getFromSql(key)
           }
} yield res
```

maybe this already exists.

**Comment by peterneyens** [comment]
You could write this as `OptionT(getFromReddis(key)).getOrElseF(getFromSql(key))`.

**Comment by fommil** [comment]
I'm not keen on mixing monad transformers with Algebras, I think I prefer the original to having to introduce an OptionT here.

**Comment by johnynek** [comment]
So what you want is a method like this on Option:

```scala
implicit class OptExt[A](val opt: Option[A]) extends AnyVal {
def getOrElseM[F[_]: Applicative](fa: => F[A]): Option[F[A]] = opt match {
  case Some(a) => Applicative[F].pure(a)
  case None => fa
}
```
Seems nice enough to me but I wouldn't call it M but getOrElseA or something.

**Comment by fommil** [comment]
Yup, something like that: for getOrElse and orElse, why A?

**Comment by johnynek** [comment]
`A` for applicative. Why `M`?

**Comment by fommil** [comment]
hmm, it's even better if it could just be written

```
for {
  res <- getFromReddis(key) orElseM getFromSql(key)
} yield res
```

**Comment by raulraja** [comment]
@fommil there is an `option` effect that will flatten your value so you don't need transformers if this in the context of drone dynamic agents using Freestyle.

**Comment by fommil** [comment]
no this is in the context of explaining how some things are just really tricky to write as a `for` comprehension. Imagine the two methods are in an algebra and we want to implement this business logic.

But flattening the final `option` might still be useful. It'll be a while before I get to effects and by that point maybe freestyle and cats-eff will have merged!

**Comment by raulraja** [comment]
hahahaha not sure that will ever happen but looking forward to more eff releases. It's a great library. 

For what is worth, in my experience you have three options to mix monads in for comprehensions.
1. Create an uber datatype that fits your use case for example `FutureOption`. Not sure anybody will recommend this.
2. Using monad transformers, in this case `OptionT`.
3. If you are in the context of an Algebras based app over Free, Eff or whatever reify those `option` semantics in an algebra or use MTL style constrains such as `MonadFilter` where you need to flatten or provide empty values.

People usually learn for comprehensions before they understand monads and this puzzles everyone. Looking forward to read that section of the book.

**Comment by fommil** [comment]
oh, so this isn't about mixing monads. It's about fall-through behaviour. The business logic is "if this didn't yield anything, do this other thing". That can't be handled by the monad because then it would short circuit.

I'll be doing monad mixing next.
