### ISSUE TITLE
Add ApplicativeError#ensuring (under another name, smelling as sweet)

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#1630]
RFC on the naming.

The semantics and implementation of the function can be found [here](https://github.com/typelevel/cats-effect/blob/5e03a6099414554df741196ac019434c87b5e749/core/shared/src/main/scala/cats/effect/IO.scala#L116-L137).  We're going to remove the concrete implementation from `IO` after pushing it into the typeclass in cats.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out, because I think that in #1662 we decided that this shouldn't exist. @djspiewak feel free to reopen this if I'm mistaken.
