### ISSUE TITLE
Type Class Infographic

### ISSUE THREAD

**Issue by tpolecat** [typelevel/cats#1633]
Hi everyone, while I was in bed with some kind of plague last week I made a sort of infographic-like thing for the type class hierarchy. I'd like to submit as a resource in a PR, but I'd like to iterate on the design a bit first here if that's ok.

So, soliciting feedback. Additions, subtractions, modifications. I'm not heavily invested in any part of this, so go nuts. Instead of trying to explain my thought process I'll just let you see if it works or doesn't. If nobody sees any big issues I'll go ahead and do a PR.

✨  [PDF Link](https://www.dropbox.com/s/ojm6nrcnujgy7ul/cats.pdf?dl=1) ✨

**Comment by kailuowang** [comment]
This looks fantastic! I am curious, does it require a specific software to maintain this graph going forward?

**Comment by tpolecat** [comment]
Yes, it's an OmniGraffle document so someone with a Mac will need to keep it up to date. I'm happy to do this. But if we don't want it as part of the cats doc I can maintain it in my own repo and just put a pointer on the resources page. Either way is fine with me.

**Comment by tpolecat** [comment]
I was thinking we could have an associated tut doc that asserts all the arrows in the diagram, which would give some kind of indication when things change. It wouldn't catch additions but it would catch inaccuracies in what's there.

**Comment by edmundnoble** [comment]
I think you can generate some `implicitly[Monad <:< Functor]` statements from the diagram's source, which won't typecheck if they're incorrect.

**Comment by milessabin** [comment]
It's great, but I think it should be maintained in some format that doesn't require the purchase of special hardware and software. It's a pretty simple diagram ... can't we use an open format like SVG?

**Comment by tpolecat** [comment]
I'll just maintain it on my own website and if someone wants to convert it to SVG or whatever they're welcome to.

**Comment by ceedubs** [comment]
I'm sad to see this closed out. An infographic is something that there have been multiple discussions/issues/PRs for over the course of years, and I think that in every case we have been guilty of letting perfect be the enemy of good. I'd be all for incorporating this infographic and over time if we want to add more automation or switch to a more open format, then we are always free to do so.

**Comment by kailuowang** [comment]
@tpolecat Would you kindly provide the current file? Omnigraffle Pro can export it to a SVG. I don't have one but I'm sure if we ask the community someone with it will be able to help.

**Comment by tpolecat** [comment]
@kailuowang  https://github.com/tpolecat/cats-infographic

**Comment by kailuowang** [comment]
Thanks!

**Comment by tpolecat** [comment]
I will tweet a request for SVG conversion.

**Comment by kailuowang** [comment]
@tpolecat do you mind if I copied the SVG file to this PR https://github.com/typelevel/cats/pull/1565?

**Comment by tpolecat** [comment]
No, fine with me.
