### ISSUE TITLE
Eval does not obey SyncLaws

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#1639]
Partially as an exercise, and partially because it makes a lot of sense, I implemented an instance of `cats.effect.Sync[Eval]`… and lo and behold, it isn't lawful!

```
[info] - Eval.sync.ap consistent with product + map
[info] - Eval.sync.applicative homomorphism
[info] - Eval.sync.applicative identity
[info] - Eval.sync.applicative interchange
[info] - Eval.sync.applicative map
[info] - Eval.sync.applicativeError attempt consistent with attemptT
[info] - Eval.sync.applicativeError handle
[info] - Eval.sync.applicativeError handleError consistent with recover
[info] - Eval.sync.applicativeError handleError pure
[info] - Eval.sync.applicativeError handleErrorWith consistent with recoverWith
[info] - Eval.sync.applicativeError handleErrorWith pure
[info] - Eval.sync.applicativeError handleWith
[info] - Eval.sync.applicativeError pure attempt
[info] - Eval.sync.applicativeError raiseError attempt
[info] - Eval.sync.applicativeError recover consistent with recoverWith
[info] - Eval.sync.apply composition
[info] - Eval.sync.cartesian associativity
[info] - Eval.sync.covariant composition
[info] - Eval.sync.covariant identity
[info] - Eval.sync.delay constant is pure
[info] - Eval.sync.flatMap associativity
[info] - Eval.sync.flatMap consistent apply
[info] - Eval.sync.followedBy consistent flatMap
[info] - Eval.sync.invariant composition
[info] - Eval.sync.invariant identity
[info] - Eval.sync.map flatMap coherence
[info] - Eval.sync.monad left identity
[info] - Eval.sync.monad right identity
[info] - Eval.sync.monadError left zero *** FAILED ***
[info]   Error was thrown during property evaluation.
[info]     Message: "None"
[info]     Occurred when passed generated values (
[info]       arg0 = java.lang.Error,
[info]       arg1 = <function1>
[info]     )
[info] - Eval.sync.monoidal left identity
[info] - Eval.sync.monoidal right identity
[info] - Eval.sync.mproduct consistent flatMap
[info] - Eval.sync.repeated sync evaluation not memoized
[info] - Eval.sync.suspend constant is pure join
[info] - Eval.sync.tailRecM consistent flatMap
[info] - Eval.sync.throw in delay is raiseError *** FAILED ***
[info]   Error was thrown during property evaluation.
[info]     Message: "None"
[info]     Occurred when passed generated values (
[info]       arg0 = java.lang.Error: null
[info]     )
[info] - Eval.sync.throw in suspend is raiseError *** FAILED ***
[info]   Error was thrown during property evaluation.
[info]     Message: "None"
[info]     Occurred when passed generated values (
[info]       arg0 = java.lang.Error: null
[info]     )
[info] - Eval.sync.unsequenced delay is no-op
```

Or rather, the direct implementation is not lawful.  The implementation is here:

```scala
  implicit object evalSync extends Sync[Eval] {
    private val delegate: Monad[Eval] = Eval.catsBimonadForEval

    def pure[A](x: A): Eval[A] = delegate.pure(x)

    // TODO replace the following with delegation when upgrading to cats 1.0
    def handleErrorWith[A](fa: Eval[A])(f: Throwable => Eval[A]): Eval[A] =
      Eval.defer(try Now(fa.value) catch { case internals.NonFatal(t) => f(t) })

    def raiseError[A](e: Throwable): Eval[A] = Eval.defer(throw e)

    def flatMap[A, B](fa: Eval[A])(f: A => Eval[B]): Eval[B] =
      delegate.flatMap(fa)(f)

    def tailRecM[A, B](a: A)(f: A => Eval[Either[A,B]]): Eval[B] =
      delegate.tailRecM(a)(f)

    override def delay[A](thunk: => A): Eval[A] = Eval.always(thunk)

    def suspend[A](thunk: => Eval[A]): Eval[A] = Eval.defer(thunk)
  }
```

Obviously the `MonadError[Eval, Throwable]` instance isn't in the 0.9 release, so I reimplemented that functionality.  But the issue remains even in master.

The problem is either in the implementation of `Always#value` or in the implementation of `Eval.always` (it can be solved in either place).  Exceptions thrown in suspended thunks are not caught, and thus cannot be recovered by the `MonadError` functionality.  This is a very reasonable expectation, and is codified as a law in cats-effect:

```scala
  def delayThrowIsRaiseError[A](e: Throwable) =
    F.delay[A](throw e) <-> F.raiseError(e)

  def suspendThrowIsRaiseError[A](e: Throwable) =
    F.suspend[A](throw e) <-> F.raiseError(e)
```

Even though `Sync` is not actually a part of cats, I would submit that this is a problem that `Eval` should probably address.  It doesn't make any sense for `Eval` to implement `MonadError` and *not* also implement `Sync`, but it cannot lawfully do so, even in master.  Either `Eval` shouldn't purport to have error-handling capabilities (in which case, it just isn't a `Sync`), or it should fix `Always` to resolve this issue.

**Comment by ceedubs** [comment]
Thank you @djspiewak. I didn't notice the `MonadError` instance that was introduced for `Eval`, but it seems to be problematic to me. My gut says that the right solution to this is to remove the `MonadError` instance for `Eval`. Can someone convince me otherwise? :) cc @non

**Comment by djspiewak** [comment]
It's definitely non-trivial to get this sort of error handling right.  Very easy to let stuff slip through the cracks, sacrifice stack safety, etc.

**Comment by johnynek** [comment]
I think it would be nicer if we can find a way to fix it. It's easy to remove capabilities, but we provide much more value if we can do the hard work of getting it right.

**Comment by djspiewak** [comment]
@johnynek See `IO` in cats-effect for an idea of what's involved here.  Notably, [this](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/internals/AndThen.scala#L52-L79) is more or less what is necessary if you want to do it while maintaining stack-safety.

**Comment by alexandru** [comment]
@djspiewak @johnynek you don't necessarily need `AndThen`, I came up with a slightly different approach for the Monix Task.

That said, I don't like the way `Eval` is implemented. And we can't change it easily, because the implementation exposes internal stuff. For example I see no reason to expose `Compute` or `Call`. 

I would seriously consider changing `Eval`'s internals. In `monix.eval.Coeval` I have an implementation that implements `MonadError` and that is lawful with `Sync`. 

Would you be interested in a PR that hides `Compute` and `Call` and that fixes these problems?

(asking because Cats PRs tend to linger on forever, until they get shot down)

**Comment by djspiewak** [comment]
I don't think `Compute` or `Call` need to be exposed.

**Comment by non** [comment]
@djspiewak Did you look at how the tests for `MonadError[Eval]` work right now?

Using this test file, `Sync[Eval]` passed for me: https://gist.github.com/non/c42882f431283ba017abdcea6e0ec249

I'm totally fine with making `Eq[Eval[A]]` use this code by default, to remove the need for custom test instances of `Eq`. Is there a problem beyond that?

**Comment by non** [comment]
I agree with @alexandru and @djspiewak that we should be hiding `Call` and `Compute` (in fact I thought we were?) so I'd definitely support making those private again. As far as larger refactors go, I'd want to see the effects measured with benchmarks before agreeing to anything.

(As an aside, I hear @alexandru's pain re: PRs and definitely want to apologize for past problems.)

**Comment by djspiewak** [comment]
@non I hadn't looked at the underlying test instances for `Eval`.  It's a little difficult for me to visually perform the semantic diff; is the only thing you changed `Eq[Throwable]`?

**Comment by non** [comment]
@djspiewak No, I used a different `Eq[Eval[A]]` -- that's the difference (we consider two `Eval` instances that throw what looks like the "same" exception to be the same).

**Comment by djspiewak** [comment]
Oh I see what you mean.  Hmm.  Well, that particular `Eq[Eval[A]]` looks basically like what I assumed it was already doing.  :-)  And if that passes `SyncLaws`, then I think we're probably in good shape.  I'm relatively certain all of the identities I care about are encoded either in there or in `MonadErrorLaws`.

**Comment by non** [comment]
Great!

**Comment by djspiewak** [comment]
@non So can we PR the revised `Eq[Eval[A]]` to cats?  Meanwhile, I'll just inline it into cats-effect so I can move forward with `Sync[Eval]` (cats-effect currently depends on cats-core 0.9).

**Comment by non** [comment]
Sure!

**Comment by djspiewak** [comment]
Now that we've removed `MonadError[Eval, Throwable]`, I think we can probably just close this.

**Comment by johnynek** [comment]
@djspiewak why does `Sync` extend `MonadError` and not have `SyncError` or something that does that? Certainly we could do a `Sync[Eval]` if it only extended `Monad` right?

**Comment by djspiewak** [comment]
@johnynek What does `Sync.delay(throw t)` mean if it *doesn't* extend `MonadError`?  This is probably a better discussion on cats-effect than on cats, but the tl;dr is that I'm making the claim that `Sync` is meaningless without error handling.

**Comment by johnynek** [comment]
that is not legit. The law is only the first ones that don't include throw (the mutation checking ones).

Same as `F.map(fa)(throw t)` just not defined.

**Comment by djspiewak** [comment]
I reject the usefulness of a `Sync` which does *not* define what it means to have error handling.  Also if you're referencing `SyncLaws`, note that there are several things on `EffectLaws` right now which *should* be on `SyncLaws`.

**Comment by johnynek** [comment]
I think you will often only use `delay` or `suspend` and not do `throw`. So, if that is the case, you could only depend on the `Sync[Eval]` not `SyncError[Task]` for instance.

But it's not a huge issue to me. @alexandru had tried to pitch a typeclass like I am describing before (which I didn't like because I don't really like these laws which are purely about evaluation, but I guess that's a reality for us in a language like scala).

**Comment by djspiewak** [comment]
The problem I keep coming back to with typeclasses like what you're describing is they're *only* useful for either `Eval` specifically or things that are actually effects.  `suspend` captures effects, and it would be really strange if we had to say "it captures effects, but not effects which `throw`".  So, "all effects, except these effects over here".  That's just weird.  And I have yet to see a compelling use-case for it which cannot be satisfied with either using the full error-handling `Sync` *or* specializing on `Eval` itself.

A corollary of my contention is that `Eval` is basically definitive.  It abstracts over evaluation strategy; how many possible ways are there of doing that?  My contention is that there's really only one way, and there's never a point in abstracting over a singleton.

**Comment by johnynek** [comment]
This is an interesting idea. You point is that in scala it does not make sense to talk about effects without throw. I'm not seeing immediately how that is different from other method calls in scala.

```scala
object Evil { 
  private[this] var counter: Int = 0

  def something: Eval[Unit] = Eval.always { counter += 1; () }
}
```
will never throw, but it is certainly an effect. I can imagine lots of cases may be similar to this: best-effort logging/counters for debug, a mutable cache behind the scenes to avoid recomputation (mutable, but referentially transparent), are a couple of effects that come to mind that I don't expect to throw.

For those cases I might want to write code that works with `Eval`, `Task`, `Rerunnable` whatever.

I'm not too attached to it, because you can hack around it. However I'm not immediately seeing that is clear that all effects need to deal with jvm exceptions. That seems to be making the case that every effect can throw, but I think that (as I have said) excludes a broad class of mutation effects.
