### ISSUE TITLE
MonadError[StateT[F, S, ?]] doesn't handle errors in outer effect

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#1640]
It seems like a more correct implementation would be the following:

```scala
    def handleErrorWith[A](st: StateT[F, S, A])(f: Throwable => StateT[F, S, A]): StateT[F, S, A] = {
      val handled = F.handleErrorWith(st.runF) { t =>
        F.map(f(t).runF) { sf => s: S =>
          F.handleErrorWith(sf(s)) { t =>
            f(t).run(s)
          }
        }
      }

      StateT.applyF(handled)
    }
```

Specifically, if the outer `F` in the `StateT` is `raiseError`, it will not be handled.

**Comment by peterneyens** [comment]
Whoops, I think am the one to blame. Do you want to open a PR?

**Comment by djspiewak** [comment]
It's on my stack of things.  If it sits for a few days, I'll probably get to it.  :-)

**Comment by djspiewak** [comment]
As a sidebar, the `Arbitrary` for `StateT` defined [here](https://github.com/typelevel/cats/blob/4e381d27da64bde44f64895be184d6132196d598/laws/src/main/scala/cats/laws/discipline/Arbitrary.scala#L168) ensures that we could never possibly catch this issue in the laws.  I'm relatively certain that fixing this will reveal the bug.

**Comment by kailuowang** [comment]
related #1616

**Comment by ceedubs** [comment]
I'm looking into this.

**Comment by kailuowang** [comment]
removing from the 1.0.0-MF project since it's going to continue on #1714

**Comment by kailuowang** [comment]
Not sure how to repeat this bug. The following test passes on both mater and 0.9.0
```scala
    val s = new StateT(None: Option[Int => Option[(Int, Int)]])
        .handleErrorWith((_: Unit) => StateT.pure(0))
    s.run(3) should === (Some((3, 0)))
```

**Comment by ceedubs** [comment]
I'm pretty sure that this is resolved, so I'm going to close this out. @djspiewak please speak up if I'm mistaken.
