### ISSUE TITLE
Publish cats-tests

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/cats#1656]
cats-tests remains unpublished and undocumented (https://github.com/typelevel/cats/issues/152). This is a stumbling block for new contributors and for people like @djspiewak and myself who find ourselves writing add-on libraries for cats and are unable to write tests in a style consistent with the tests in cats.

cats-tests has never been published according to Git blame, even in the `cats` artifact, contrary to statements in https://github.com/typelevel/cats/issues/1184.

Are there any issues with publishing cats-tests?

**Comment by kailuowang** [comment]
My 2 cents: 
1. we need to consolidate all the packaging related issues. I think @BennyHill summarize the situation (questions to answer) pretty well in this [comment](https://github.com/typelevel/cats/issues/1184#issuecomment-298991494)
2. I totally agree that we need better documentation on how to write law tests in cats style.

**Comment by BennyHill** [comment]
I think this replicates #529.

Note that the scala-bricks project is now the more advanced [catalysts](https://github.com/typelevel/catalysts) project, that would also allow the tests to be written in a an abstract fashion, so end users can choose their preferred framework - scalatest, specs2,etc

**Comment by BennyHill** [comment]
Also related https://github.com/typelevel/cats/issues/1585, that also links #529 and #1272.

As @kailuowang alludes to above, a _lot_ of work in this area has already been, but not yet fully taken on board and implemented.

FYI. much of this also relates to algebra, spire and more recently paiges, from which a lot of the ideas in catalysts were collected.

For example, compare:
https://github.com/typelevel/paiges/blob/master/cats/src/test/scala/org/typelevel/paiges/LawTests.scala#L66-L74 
with 
 https://github.com/typelevel/catalysts/blob/master/lawkit/src/main/scala/catalysts/lawkit/LawChecks.scala#L15-L45

**Comment by ceedubs** [comment]
@kailuowang was this resolved by #1758?

**Comment by kailuowang** [comment]
yes, closing.
