### ISSUE TITLE
Kernel instances are in typeclasses which are subclasses

### ISSUE THREAD

**Issue by yilinwei** [typelevel/cats#1657]
~~Both `Order` and `PartialOrder` need a `Contravariant` instance.~~

Will submit a PR for it shortly.

EDIT: #1659 has proper explanation of the issue.

**Comment by ceedubs** [comment]
@yilinwei I think that those exist here: https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/functor/Contravariant.scala#L42-L58

**Comment by peterneyens** [comment]
Fixed in #1659.
