### ISSUE TITLE
Order to Ordering conversion

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1665]
In #1646 there's a discussion about how there's a conversion from `Order` to `Ordering` but that it won't actually be picked up where an implicit `Ordering` instance is expected.

It sounds like the general consensus is that we should make it so that after you've imported `cats.implicits._` you pick up this functionality.

It may not make a lot of sense to expose this as an implicit in the `Order` companion object, because it won't be found there during an implicit search for an `Ordering` instance, and having it there will probably result in ambiguous implicits if someone imports both `cats.implicits._` and `Order._`. However, we may not want to make this incompatible change to cats-kernel. @johnynek do you have thoughts on this?

**Comment by ceedubs** [comment]
By the way if this is added via `cats.implicits._`, then #1659 is a relevant change.

**Comment by johnynek** [comment]
Yeah, adding it to `cats.implicits._` seems like it would be what most
users want.

**Comment by edmundnoble** [comment]
I'll go ahead tonight and put up the fixed PR.

**Comment by edmundnoble** [comment]
Up as #1670, #1659 will conflict a teeny tiny bit.

**Comment by ceedubs** [comment]
Resolved by #1670.
