### ISSUE TITLE
Use macro for implicit summoning in typeclass companion objects for Cats/Algebra/Spire

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#1667]
I wrote a macro in [this gist](https://gist.github.com/ctongfei/fa15d5e748c764de62be301cc02288bd). This removes the boilerplate every companion object of typeclasses has (the `def apply[A](implicit A: Ev[A]) = A` method), and is faster: the method invocation is replaced by the actual typeclass instance filled by the macro.

**Comment by ctongfei** [comment]
And results in less jar size: the `apply` method does not longer need to be specialized.

**Comment by edmundnoble** [comment]
Have you seen https://github.com/non/imp? It seems to do most of what you propose, except for the `ImplicitSummoner` traits. Paging @non, because the reason why we don't use `imp` in cats is escaping me.

**Comment by johnynek** [comment]
As @non notes in the issues, the JVM can already optimize this and there is
little evidence this helps:

https://github.com/DarkDimius/imp-bench

**Comment by edmundnoble** [comment]
@johnynek I just, *just* ran benchmarks to test if the JIT is doing this. If it is, we have to consider that not every piece of code is JITted and it never is on its first runs. JMH is giving us potentially unrealistic results because of this; my benchmarks have `CompilerControl.Mode.Exclude` which will disallow the JIT. I posted these results at https://github.com/DarkDimius/imp-bench/issues/4:

```
[info] Benchmark                                 Mode  Cnt   Score   Error  Units
[info] addable.ImplVsImplicitlyAddable.baseline  avgt   30  82.945 ± 2.765  ns/op
[info] addable.ImplVsImplicitlyAddable.explicit  avgt   30  73.834 ± 1.009  ns/op
[info] addable.ImplVsImplicitlyAddable.imply     avgt   30  74.103 ± 0.975  ns/op
```

**Comment by ctongfei** [comment]
@edmundnoble I was not aware of the `imp` project before. But still we could use my `ImplicitSummoner` traits to reduce some boilerplates.

**Comment by diesalbla** [comment]
Considering that the use of macros to generate boilerplate, such as done in https://github.com/typelevel/cats/pull/2925, it seems unlikely that this will be taken up.

**Comment by rossabaker** [comment]
I agree, and the complexity only gets worse during the Scala 3 transition.
