### ISSUE TITLE
Piecemeal import guide

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1668]
Currently the [imports guide](http://typelevel.org/cats/typeclasses/imports.html) only really describes the "uber" import (`cats.implicits._`). It may be handy to have a detailed guide of piecemeal imports, such as `cats.instances.string._` and `cats.syntax.functor._` as an additional section for people who prefer this approach.

**Comment by LukaJCB** [comment]
I can start working on this soon. :) Shouldn't really be too difficult.
