### ISSUE TITLE
 unify `lift` between all of the transformers all `liftT` methods

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1681]
e.g .`EitherT.right`, `OptionT.liftF`, `StateT.lift`, `Free.liftF`, `WriterT.valueT`, `Kleisli.lift`.
Per conversation here https://gitter.im/typelevel/cats?at=591c9cb564a70be11ad2eb79
also we can consider provide `FunctionK` version, which is easier to compose. e.g.
```scala
def liftFK[F[_], S]: F ~> StateT[F, S, ?] =
    λ[F ~> State[F, S, ?]](StateT.lift(_))
```

**Comment by wedens** [comment]
with `MonadTrans` such function can be generalized to `def liftTTrans[F[_]: Monad, G[_[_], _]: MonadTrans] =  λ[F ~> G[F, ?]](_.liftT[G])`

**Comment by kailuowang** [comment]
per [conversation here](https://gitter.im/typelevel/cats-contrib?at=591dc40992217cca588cc6dc) we might want to wait for  cats-mtl

**Comment by edmundnoble** [comment]
Also we need `transform`

**Comment by LukaJCB** [comment]
This should be done with https://github.com/typelevel/cats/pull/2033 and https://github.com/typelevel/cats/pull/2000 :)
