### ISSUE TITLE
Cats 1.0.0 packaging 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1682]
This is an issue consolidating all the packaging/publish related issues #1656, #1184, #472 and #592. 
There are three separate decisions that are sort of related. It may make sense to decide on all of them all together. Here is the revised version of @BennyHill's summarization in this [comment](https://github.com/typelevel/cats/issues/1184#issuecomment-298991494) (I added more description for context)

1. Shall we continue publishing the current cats bundle which includes cats-laws and cats-free?
The cats-laws includes a scalacheck dependency which [surprises people.](https://github.com/typelevel/cats/issues/1184#issuecomment-285366498)

Options are:
a) Keep as-is
b) Keep as-is but minus test libs
c) Rename as-is
d) Rename as-is but minus test libs
e) Remove

2. Shall we include alleycats into the cats repo as submodule? detailed discussion in #472

Options are: 
a) Keep as-is, i.e. separate repo
b) move in as cats submodule. It will keep using a separate top `alleycats` namespace and will not be included in the cats bundle shall we decide to keep one. As a submodule, its releases will be part of cats release, but unlike cats-core, it is allowed to have binary breaking changes between patch versions for alley-cats, at least for now, since it's API hasn't reached the stable status yet.

3. Shall we publish cats-testkit? discussion in #1656

a) Create a new module called `cats-testkit` that includes the following utils from `cats-tests`: [Helpers](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/Helpers.scala), 
 [CatsSuite](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/CatsSuite.scala) and [CatsEquality](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/CatsEquality.scala)
Note that these classes are not required for users to write cats style tests - `cats-laws/discipline` is the one that is required. `cats-testkit` will depend on `cats-laws` 
b) keep as-is 
c) simply publish `cats-tests` ( but not included in the cats bundle shall we have one. )

We've done extensive discussion around these for quite a while. So I propose we are ready to collect votes and see if we can reach consensus.

**Comment by kailuowang** [comment]
copying @BennyHill's vote from his [comment](https://github.com/typelevel/cats/issues/1184#issuecomment-298991494) (with minor modification for revised question 3. @BennyHill feel free to vote again and delete this comment)
> 1. e (remove cats bundle and go on holiday just before the release)
> 2. b (move alley cats)
> 3. a

**Comment by kailuowang** [comment]
My vote
1, e
2. b
3. a or b

**Comment by mpilquist** [comment]
1. e
2. a
3. b

**Comment by BennyHill** [comment]
My final vote
1, e
2. b
3. b (if we want common test-kits, move them to catalysts)

**Comment by djspiewak** [comment]
Only strong opinions are on 2 and 3.  On 2, I *strongly* oppose moving alleycats into the cats repo.  Polyrepo is significantly easier to manage here, and it ensures that the versioning is kept independent.  Having things like alleycats, dogs, cats-mtl and cats-effect in repos that are separate from cats-core is a major win relative to the way that scalaz is setup, since scalaz's versioning is fundamentally tied together, meaning that changes which are non-breaking for core still have to increment the core breaking version, which in turn cascades through the entire ecosystem.

Regarding 3, option c seems fine, but I'm ok with any which publishes the test infrastructure.

**Comment by edmundnoble** [comment]
1. e
2. a
3. c please give me cats-tests.

**Comment by milessabin** [comment]
1. e
2. b
3. a or b

**Comment by kailuowang** [comment]
Results (if a vote for (a or b), I count both)
1. e (unanimous)
2. a (4), b(2) 
3. a (3), b(4), c(2)
I think for 1.0.0-MF, we just do 
`e` remove cats bundle,
 `a` leave alleycats out of cats repo and
 `a` release a test-kit,  "b" gets more vote but I think a will make both a and c happy.
