### ISSUE TITLE
Suggestion: renaming Foldable/Reducible to Fold/Reduce in cats 1.0

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#1689]
In common idiomatic Scala usage `-able` is usually a trait (e.g. `Traversable`, `Iterable`) instead of a typeclass. A typeclass that captures some higher-order function is commonly named as the verb itself (as seen in cats: `Compose`, `FlatMap`, `Traverse`, etc.)

**Comment by johnynek** [comment]
I hope we don't change names like this at this late stage. This is a minor
blemish at worst.

**Comment by ceedubs** [comment]
@ctongfei thanks for raising this concern. This wasn't changed before 1.0 and I think that it would be unnecessarily disruptive at this point, so I'm going to go ahead and close this out.
