### ISSUE TITLE
Weird 'unused private method' warning from implementing typeclass

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats#1692]
I'm converting a project from scalaz to cats and I'm getting a compile error I don't understand

```
Error:(24, 20) private method in <$anon: cats.Semigroup[com.github.daenyth.taklib.GameEndResult] with cats.Eq[com.github.daenyth.taklib.GameEndResult]> is never used
      override def combine(f1: GameEndResult, f2: => GameEndResult): GameEndResult = (f1, f2) match {
```

From the code here:
```scala
  implicit val gerInstance: Semigroup[GameEndResult] with Equal[GameEndResult] =
    new Semigroup[GameEndResult] with Equal[GameEndResult] {
      override def combine(f1: GameEndResult, f2: => GameEndResult): GameEndResult = (f1, f2) match {
```

The full code is here: https://github.com/Daenyth/taklib/blob/49fdd59c548436ad149519bc1a835cce91f051b8/taklib/src/main/scala/com/github/daenyth/taklib/Game.scala#L24

Did I do something wrong? Could this be a compiler bug?

**Comment by peterneyens** [comment]
Cats' [`Semigroup#combine`](https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/Semigroup.scala#L14) takes its parameters by value, where Scalaz' `Semigroup#append` takes it second parameter by name.

**Comment by Daenyth** [comment]
Gotcha, that was exactly my problem. Bizarre compiler error, but once I made them by-value it worked.
