### ISSUE TITLE
How do I test laws for my semigroups?

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats#1694]
The laws stuff appears to only contain SemigroupK stuff, but nothing for Semigroup (and also Monoid).

I can obviously write out the scalacheck by hand, but it would be nice if it integrated with the rest of the discipline-based stuff

**Comment by peterneyens** [comment]
The laws for type classes in `cats-kernel` like `Semigroup` and `Monoid` can be found in `cats-kernel-laws`.

Eg
```scala
import cats.kernel.laws.GroupLaws

checkAll("Int", GroupLaws[Int].semigroup)
checkAll("Int", GroupLaws[Int].monoid)
```

Used for example to test `Validated`'s `Semigroup` instance [here](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/ValidatedTests.scala#L35).

That is definitely something which should be mentioned in the documentation about the laws (#1585).

**Comment by Daenyth** [comment]
For anyone watching / future me, `checkAll` comes from the `Discipline` test mixin
