### ISSUE TITLE
Monoid instances for Boolean

### ISSUE THREAD

**Issue by anler** [typelevel/cats#1700]
Hello, I can't find any instance of `Boolean` for `Monoid`, is it something cats explicitly avoid or are you open to a humble PR? 🙂

Thanks!

**Comment by edmundnoble** [comment]
We would need newtypes to disambiguate between the Conjunction and Disjunction (`and` and `or`) monoids. Because we don't have those yet, the Monoid we'd choose for Boolean would be arbitrary.

**Comment by anler** [comment]
Yeah I know, but with my current knowledge of Scala I thought something like this suffice would suffice:
```scala
final case class Any(value: Boolean) extends AnyVal

object Any {
  implicit val anyMonoidInstance = new Monoid[Any] {
    def empty = Any(false)
    def combine(a: Any, b: Any) = Any(a.value || b.value)
  }
}
```
Any argument against it that I'm not aware of?

**Comment by djspiewak** [comment]
Something like that does suffice, but in areas like this, we generally prefer something with a more general mechanism.  Scalaz experimented with type tags (the `@@` notation), and there are some advantages and disadvantages to approaches like that.  Just adding a straight newtype to `Any`/`All` is a bit of a one-off thing targeted solely at `Boolean`, which is less interesting.

**Comment by anler** [comment]
Oh I see, I'm up for interesting solutions too, although the solution of the straight newtype looks like a good tradeoff for me 😇.  Apart from the newtype solution and the tagged solution, all I can think of is to specialise the Monoid typeclass itself 🤔, e.g:

```scala
import cats.Monoid
import cats.implicits._

trait SumMonoid[A] extends Monoid[A]
trait ProductMonoid[A] extends Monoid[A]

object SumMonoid {
  def apply[A](implicit inst: SumMonoid[A]) = inst

  implicit val booleanSumMonoidInstance = new SumMonoid[Boolean] {
    def empty = false
    def combine(a: Boolean, b: Boolean) = a || b
  }

  implicit def sumMonoid2Monoid[A](x: SumMonoid[A]): Monoid[A] = x.asInstanceOf[Monoid[A]]
}

object ProductMonoid {
  def apply[A](implicit inst: ProductMonoid[A]) = inst

  implicit val booleanProductMonoidInstance = new ProductMonoid[Boolean] {
    def empty = true
    def combine(a: Boolean, b: Boolean) = a && b
  }

  implicit def productMonoid2Monoid[A](x: ProductMonoid[A]): Monoid[A] = x.asInstanceOf[Monoid[A]]
}

SumMonoid[Boolean].combine(true, false) // true
ProductMonoid[Boolean].combine(true, false) // false
```

**Comment by edmundnoble** [comment]
I'm a :-1: on that because:
There is no law or method difference between `SumMonoid` and `ProductMonoid`,
this approach doesn't generalize to more instances, or instances that don't make sense as sums and products, and 
for any non-primitive type this introduces extra boxing in a generic context. 

IMO this is just going to have to wait until we have working newtypes; @alexknvl is on it. Sorry about this, I know these are incredibly useful to have.

**Comment by anler** [comment]
Ok ok, I'm closing this issue then, I also prefer the newtype approach but I'm getting confused because I thought my first example was using Scala's newtypes although I read that the extra indirection is not guaranteed to disappear after compilation if you use pattern matching on it. When you say newtypes, are you talking about a solution that does guarantee that?

**Comment by edmundnoble** [comment]
Yes, I am. Unfortunately yes, it's not just *if* you use pattern matching on it. The indirection is kept whenever it's generic *just in case* you use pattern matching on it later.
