### ISSUE TITLE
MonadError instance for Kleisli

### ISSUE THREAD

**Issue by anler** [typelevel/cats#1701]
Hello! I was looking for a `MonadError` instance for `Kleisli` but I saw it doesn't exist, any particular reason for not having it? I had to write one myself because I have a transformer that is `ReaderT[F, Env, A]` and I require an evidence for `MonadError[F, Throwable]` (to handle unexpected exceptions when interfacing with imperative code)

Thanks!

**Comment by kailuowang** [comment]
No particular reasons for its missing other than we didn't get to it yet. If you want, a PR will be more than welcome, but if you don't have time, I think I am going to add it before 1.0.0-MF release, if no one beats me.

**Comment by anler** [comment]
Oh great! I'll grab this _low-hanging-fruit_ and send you a PR ^^

**Comment by anler** [comment]
Nevermind, I found that the instance was already added in #1618 by @peterneyens 🙂
Thanks!

**Comment by kailuowang** [comment]
sorry my badkhttps://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Kleisli.scala#L230

**Comment by kailuowang** [comment]
the next release should be soon 🤞
