### ISSUE TITLE
MonadState instance for ReaderT/Kleisli

### ISSUE THREAD

**Issue by anler** [typelevel/cats#1704]
Hello again 😄 this time I've checked if there is a MonadState instance for ReaderT/Kleisli since the transformer I'm working with is something like `type App[A] = ReaderT[StateT[util.Try, AppState, ?], AppConfig, A]`. I saw you guys merged #1598 a few days ago but I don't see any harm in having the instance I'm asking, right? Here's a what-I-think-is-a-functional instance:

```scala
   implicit def readerMonadState[F[_], I, O, S]
    (implicit M: Monad[ReaderT[F, I, ?]], ST: MonadState[F, S]) =
    new MonadState[ReaderT[F, I, ?], S] {
      def flatMap[A, B](fa: ReaderT[F, I, A])(f : A => ReaderT[F, I, B]) = M.flatMap(fa)(f)

      def tailRecM[A, B](a: A)(f : A => ReaderT[F, I, Either[A, B]]) = M.tailRecM(a)(f)

      def pure[A](a: A) = M.pure(a)

      def get = ReaderT[F, I, S] { env => ST.get }

      def set(s: S) = ReaderT[F, I, Unit] { env => ST.set(s) }
    }
}

```

**Comment by kailuowang** [comment]
FYI #1616, maybe @edmundnoble can have it in cats-mtl?

**Comment by anler** [comment]
Oh I see, then I will address my mtl enquiries to [edmundnoble/cats-mtl](https://github.com/edmundnoble/cats-mtl) Thanks!
