### ISSUE TITLE
Linking error on scala.js

### ISSUE THREAD

**Issue by cquiroz** [typelevel/cats#1708]
I tried to make an `Eq` instance on scala.js but I get a linking error. I tried to reproduce the problem on the cats tests but it worked fine. I checked the code of `Eq` but I can't see anything obvious that could be causing this

```
[error] Referring to non-existent method cats.kernel.Eq.$$init$()scala.Unit
[error]   called from demo.DemoApp$$anon$1.<init>()
[error]   called from demo.DemoApp$.main()scala.Unit
[error]   called from scala.scalajs.js.JSApp.$$js$exported$meth$main()java.lang.Object
[error]   called from demo.DemoApp$.$$js$exported$meth$main()java.lang.Object
[error]   called from demo.DemoApp$.main
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   demo.DemoApp$
```

I made a minimal repo to reproduce the issue:
https://github.com/cquiroz/cats-js-bug

Do `sbt fastOptJS` to observe the problem

**Comment by kailuowang** [comment]
Thanks very much @cquiroz!

**Comment by kailuowang** [comment]
I am not an expert in scalajs but I changed your build file to 
```
libraryDependencies ++= Seq(
  "org.typelevel" %%% "cats-core" % "0.9.1-SNAPSHOT"
)
```
and it worked. so it's probably more a sbt build issue on use site than an issue in cats?

**Comment by cquiroz** [comment]
Right, that must be it, sorry for the noise

**Comment by kailuowang** [comment]
no worries. If you dont mind I am going to close this one, feel free to reopen if it's still an issue.
