### ISSUE TITLE
SetPartialOrder[A] uses the universal `==` instead of `Eq`

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#1710]
https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/set.scala#L22

This instance should require an implicit `Eq[A]` and use this instance for containment partial order / set equivalence.

**Comment by kailuowang** [comment]
Would it have surprising effects when `Set` itself doesn't use `Eq[A]`?

**Comment by ctongfei** [comment]
@kailuowang OK I get it. For the instances for `scala.collection.{Set/Map}`, use the standard universal `equals`. Thanks!

**Comment by johnynek** [comment]
yeah, I think if you use `Set` and `Map` they have to use universal equality (on keys for map at least), so doing this differently would really be a bug.

**Comment by ctongfei** [comment]
@johnynek You are right. The equality on them must be the universal one. Thanks!
