### ISSUE TITLE
Where is cats.kernel.instances.TupleInstances?

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#1711]
https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/tuple.scala#L4
I couldn't find this class `TupleInstances`. IntelliJ also marks this as unresolved.

**Comment by peterneyens** [comment]
It is generated by sbt in [_project/KernelBoiler.scala_](https://github.com/typelevel/cats/blob/master/project/KernelBoiler.scala#L123).

**Comment by ctongfei** [comment]
@peterneyens Thanks a lot.
