### ISSUE TITLE
Addition to resources for learners on the webpage

### ISSUE THREAD

**Issue by Riptawr** [typelevel/cats#1722]
Hi all,

Underscore recently open-sourced their excellent book, "Advanced Scala with Cats". It is similar to the red book but features Cats explicitly. I propose adding it to the webpage on learning resources.

Here is the link: http://underscore.io/training/courses/advanced-scala/

Keep up the great work! 
LXK

**Comment by kailuowang** [comment]
certainly, PR more than welcome :)

**Comment by denisrosca** [comment]
This was merged in #1726
