### ISSUE TITLE
Add method to perform natural transformation of underlying Monad in Monad Transformers

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#1724]
I've found myself in this position quite often and I think it might be very useful to be able to change the underlying Monad of a Monad Transformer. 
For example in `OptionT`:

    final case class OptionT[F[_], A](value: F[Option[A]]) {
      ...
      def transformF(fn: F ~> G): OptionT[G, A] = OptionT(fn(value))
      ...
    }

We could add this to all Monad Transformers currently in cats, i.e.

- OptionT
- EitherT
- StateT
- WriterT
- Kleisli

The name is debatable, other suggestions one might come up with are: `mapF`, `mapK`, or just `transform`.

Edit: Just realized `Kleisli` already has a method that does exactly this called `transform` so we should probably stick to that.

**Comment by LukaJCB** [comment]
There also seems to be #1644 which adds a `transformF` function that also does the same thing to `EitherT`. I suggest we find a common name for this function (with the precedent of `transform` already available in `Kleisli`)

**Comment by kailuowang** [comment]
This might be calling a higher order Functor, mentioned in #1644

**Comment by kailuowang** [comment]
also related,  @edmundnoble has a `HFunctor` like type class in `cats-mtl`
https://gitter.im/typelevel/cats-dev?at=593b10d86462d8493cf8d3c4

**Comment by edmundnoble** [comment]
This seems to be an exact duplicate of https://github.com/typelevel/cats/issues/1713.
