### ISSUE TITLE
List cats related projects in README. 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1741]
I am thinking about adding two sections of cats related libraries to the readme file, both are list of projects that natively support cats type classes/data structures. 

Section 1, generic libraries to support FP. Here are some examples:

- cats-effects
- cats-mtl
- eff
- Dog
- Alleycats
- Mouse
- Matryoshka (once moved to cats)
- free-style
- monocle  (once moved to cats)
- mainecoon
etc.

Section 2,  libraries with more specific uses, here are some examples: 

- circe
- dooble (once moved to cats)
- monix  
- fs2 (once moved to cats)
- http4s (once moved to cats)
etc. 

The goal is to help users find cats compatible libraries for developing pure FP projects in Scala.  

Each project is listed with a link and brief description, under the permission of the project maintainers.  
If you are a maintainer of projects that support cats, feel free to comment here to either give permssion if it's already in the lists above or suggest one to be listed.

**Comment by rossabaker** [comment]
Permission granted for http4s.  Is on cats as of the 0.17 series.

**Comment by andyscott** [comment]
Please add https://github.com/47deg/iota to the general FP section. Also, I approve/give permission ☺️.

**Comment by milessabin** [comment]
Also kittens :-)

**Comment by pepegar** [comment]
Please add [hammock](https://github.com/pepegar/hammock) to the general FP section as well :)
