### ISSUE TITLE
cartesian builder should support >22 args via shapeless

### ISSUE THREAD

**Issue by fommil** [typelevel/cats#1753]
This kind of thing (imagine there are more than 22 parameters) currently doesn't work, because `CartesianBuilder` is capped at 22 (`v` is a method to validate the input)

```
(v("foo") |@| v("bar")).map { (f, b) => Thing(f, b) }
```

but with the power of shapeless (and kitten's `sequence`), it is possible to handle 22+ parameters

```
scala> import shapeless._
scala> import cats.implicits._
scala> import cats.sequence._
scala> import cats.data.Validated._
scala> val hlist = valid("foo") :: valid(13) :: HNil
scala> hlist.sequence.map(Generic[Thing].from)
```

HOWEVER, this means we are no longer using `Applicative` and cannot do the validations in parallel.

It would be good if

- cartesian's macro swapped to using `HList` after 22 parameters
- it did it in such a way that everything could still occur in parallel

// @SystemFw

**Comment by SystemFw** [comment]
We are still using `Apply` as far as I can see.
`sequenceGeneric[Thing].applyRecord(hlist)` (equivalent to your code), still uses the `Apply` instance for `Validated`. I'm not sure how you would parallelise your code without a `parallelSequence`, `Cartesian` is sequential as well unless the `Apply` instance executes in parallel.

**Comment by fommil** [comment]
apparetly https://github.com/typelevel/cats/pull/1745 deprecates this....
