### ISSUE TITLE
Some tests are really slow

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1757]
- Cokleisli[NonEmptyList, Int, Int].arrow.compose associativity (23 seconds, 144 milliseconds)
- Cokleisli[NonEmptyList, Int, Int].monoidK.semigroupK associative (22 seconds, 496 milliseconds)
- Cokleisli[NonEmptyList, Int, Int].semigroupK.semigroupK associative (26 seconds, 5 milliseconds)
- Traversing with ReaderWriterState is stack-safe (1 minute, 47 seconds)
- StateT[ListWrapper, Int, Int].monadState.apply composition (32 seconds, 992 milliseconds)
- StateT[ListWrapper, Int, Int].monadState.cartesian associativity (31 seconds, 908 milliseconds)
- StateT[ListWrapper, Int, Int].monadState.flatMap associativity (20 seconds, 123 milliseconds)
- StateT[ListWrapper, Int, Int].monad.apply composition (47 seconds, 880 milliseconds)
- StateT[ListWrapper, Int, Int].monad.cartesian associativity (24 seconds, 700 milliseconds)
- StateT[ListWrapper, Int, Int].monad.flatMap associativity (27 seconds, 404 milliseconds)
- StateT[ListWrapper, Int, Int].monadCombine.apply composition (21 seconds, 939 milliseconds)
- StateT[ListWrapper, Int, Int].monadCombine.cartesian associativity (28 seconds, 935 milliseconds)
- StateT[ListWrapper, Int, Int].monadCombine.flatMap associativity (24 seconds, 395 milliseconds)

**Comment by peterneyens** [comment]
For the `StateT[ListWrapper, ...]` tests, maybe we can try limiting the size of the `List`s which is what I think we are doing in [`WriterTTests`](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/WriterTTests.scala#L15-L19).

**Comment by peterneyens** [comment]
Limiting the size range in `StateTTests` cuts the total time for `StateTTests` from around 4 minutes to around 20 seconds.

```scala
  implicit override val generatorDrivenConfig: PropertyCheckConfiguration =
    checkConfiguration.copy(sizeRange = 5)
````
