### ISSUE TITLE
Scalafix rewrite from Scalaz

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#1762]
Once Cats becomes stable, some of us will want to migrate from Scalaz. To ease the process, an automatic migration (e.g. via [scalafix](https://github.com/scalacenter/scalafix)) would be really useful in bigger projects.

**Comment by kailuowang** [comment]
Just like the scalafix for 0.9 to 1.0.0-MF, we can probably start with a template for this scalaz migration so that people can start contributing.

**Comment by gabro** [comment]
It seems the right place where to drop this https://github.com/gabro/scalaz2cats.

⚠️ Big disclaimer: the project above is meant for my needs, and it's very overfitted over a project I've migrated at $JOB.

That said, it may serve as an inspiration/base for more general migrations :-)

**Comment by kubukoz** [comment]
This issue hasn't aged well... at this point, I don't think it's that worth following, so does anyone mind if we close it?

**Comment by kailuowang** [comment]
@kubukoz there isn't much interest in this but I'd like to propose that we add it to the FAQ https://github.com/gabro/scalaz2cats and close this?  What do you think?

**Comment by kubukoz** [comment]
Sure, sounds good.

**Comment by kubukoz** [comment]
https://github.com/gabro/scalaz2cats/pull/11
