### ISSUE TITLE
Guide examples on on "Applicative composes" doesn't compile

### ISSUE THREAD

**Issue by lJoublanc** [typelevel/cats#1768]
The following line in the documentation, under Applicative type class, [the bit about composition](http://typelevel.org/cats/typeclasses/applicative.html#applicatives-compose), doesn't compile:
```
val nested = Applicative[Nested[Future, Option, ?]].map2(Nested(x), Nested(y))(_ + _)
```
Using scala-2.12.1, -Ypartial-unification, and sbt 0.13.5.

Replacing the `?` with an `_` gets you somewhere, but then it complains about 

```
Error:(13, 28) cats.data.Nested[scala.concurrent.Future, Option, _] takes no type parameters, expected: one
  val nested = Applicative[Nested[Future, Option, _]].map2(Nested(x), Nested(y))(_ + _)

```

I apologise if this is trivial, but for somebody just starting out with the library, trying to reproduce the examples in code, it can be very puzzling to try and distinguish between SI-2717 and an error in the code. Would be great if you could update this.

**Comment by kailuowang** [comment]
Okay, so this is probably my bad. All the sample code in the documentation, thanks to tut, has to be compiled before they can be merged to master and constantly checked in each CI build. 
I suspect what happened here is that I published some code that is compiled against master while you are trying to compile it against 0.9.0?

**Comment by lJoublanc** [comment]
Yes, I'm on 0.9.0. The documentation is pretty good, overall, so a big thanks for your efforts!

**Comment by kailuowang** [comment]
Thank you for reporting. Shall I close it for now? Hopefully we'll release 1.0.0-MF soon and get over this.

**Comment by lJoublanc** [comment]
Yes, thanks again.
