### ISSUE TITLE
Support Scala.js 0.6.18 for 1.0.0 release of Cats

### ISSUE THREAD

**Issue by mdedetrich** [typelevel/cats#1770]
It appears that Scala.js 0.6.18 is most likely the latest release in the 0.6.x series, so it would be ideal if Cats for its 1.0.0 release was built with 0.6.18

Furthermore, Scala.js 0.6.18 has vastly improve compiler times due to a regression which was detected in earlier versions of Scala.js

**Comment by peterneyens** [comment]
Upgraded to 0.6.19 in #1771.
