### ISSUE TITLE
Provide an IndexedStateT data type

### ISSUE THREAD

**Issue by iravid** [typelevel/cats#1773]
So this is pretty much straightforward - we want this data type in cats.

The only question is with regards to the existing StateT and RWST: should they be reimplemented on top of the indexed versions? It seems that given bincompat constraints, this needs to be held off to a later version.

Would be happy to provide an implementation after details are fleshed out.

**Comment by edmundnoble** [comment]
Implementing RWST with this would imply making IndexedRWST, which is probably a slightly larger request. Ultimately my reasoning for implementing StateT with IndexedStateT comes down to there being no performance penalty I can see for doing so, as well as reducing conversions.

**Comment by iravid** [comment]
Hmm, why would RWST be different performance-wise?

**Comment by edmundnoble** [comment]
I don't think it would, sorry for the confusion :)

**Comment by iravid** [comment]
Ah, great :-) So what do you think about bincompat and implementing State on top of IndexedState?

**Comment by kailuowang** [comment]
Per our plan, for cats.core there is no strict bincompat constraint yet before 1.0.0RC1, which is scheduled September.

**Comment by iravid** [comment]
Sounds good. So I'll try to get a re-implementation in over the next few weeks.

**Comment by kailuowang** [comment]
TBC, we do want to avoid unnecessary API (source breaking ) change after 1
0.0MF

**Comment by kailuowang** [comment]
And thank u so much for offering the addition.

**Comment by iravid** [comment]
Opening a separate issue for IndexedReaderWriterStateT.
