### ISSUE TITLE
Add transformS() in ReaderWriterStateT

### ISSUE THREAD

**Issue by ronanM** [typelevel/cats#1786]
Add `transformS()` in `ReaderWriterStateT` like `cats.data.StateT.transformS`

`def transformS[R](f: R => S, g: (R, S) => R)(implicit F: Functor[F]): StateT[F, R, A]`.

**Comment by kailuowang** [comment]
related #1775

**Comment by ronanM** [comment]
> related #1775

Does `ReaderWriterStateT` will automatically gain `transformS()` from `IndexedStateT` ?

**Comment by iravid** [comment]
@ronanM see https://github.com/typelevel/cats/pull/1803; added there
