### ISSUE TITLE
Develop an SBT plugin for ease of use with cats

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#1798]
Original idea by @sellout. In theory we could create a plugin that adds the “right” compiler flags (think partial-unification, higherKinds etc. [here's a great list of compile flags](https://tpolecat.github.io/2017/04/25/scalac-flags.html)) as well as explaining common compiler errors using [sbt-clippy](https://github.com/softwaremill/scala-clippy) such as conflicting imports (which seems to be the most common help request on gitter). 
We could also think about adding Wartremover into the mix. Name would have to be bikeshedded, but for now something like `sbt-typelevel` seems like a good idea.

I'm not a big sbt guy, but I'll try to get something going soon. :)

**Comment by kailuowang** [comment]
This is my plan for [sbt-catalyst](https://github.com/typelevel/sbt-catalysts/), which also helps projects manage their dependency on libs in the cats eco system. I also have wip pr for adding a g8 template for starting projects using sbt-catalysts. It will be awesome if you can take a look at that sbt plugin and see what we can add to it. Once the g8 template and the additions you deemed necssseary ready, we can link it to cats' documentation.

**Comment by LukaJCB** [comment]
That sounds really interesting, I'll have a look :)

**Comment by DavidGregory084** [comment]
@LukaJCB I created a little plugin to do the compiler flags part already if that helps https://github.com/DavidGregory084/sbt-tpolecat

**Comment by kailuowang** [comment]
shall we close this? sbt-catalysts is going to play this role.
