### ISSUE TITLE
Move the Cartesian parameter for mapN et al?

### ISSUE THREAD

**Issue by davegurnell** [typelevel/cats#1805]
A proposal for the `mapN` syntax.

The `Cartesian` parameter for the `mapN` syntax and its cohorts is injected in the implicit conversion to `TupleNCartesianOps`:

https://github.com/typelevel/cats/blob/master/project/Boilerplate.scala#L265

This means that, if the compiler can't find a `Cartesian` for your type, it gives the error "the method mapN doesn't exist". I ran into this when updating some code using `mapN` on `Validated` because I didn't have `-Ypartial-unification` enabled.

If the implicit parameter was injected in the parameters to `mapN` instead, the error would change to "can't find a Cartesian for your type". I think is clearer and more indicactive of what's going wrong.

Does this seem like a good tweak or would it break things? Sorry if this ground has been covered already.

**Comment by edmundnoble** [comment]
This is how most of the syntax in cats works; the more that works this way, the better IMO (https://github.com/typelevel/cats/pull/1669)

**Comment by kailuowang** [comment]
looks like the consensus is to make the change. anyone interested in drafting a PR?

**Comment by davegurnell** [comment]
I'll have a go in the next few hours.

**Comment by DavidGregory084** [comment]
I'll have a look at this since it's my fault ;)
