### ISSUE TITLE
NonEmptyVector.last

### ISSUE THREAD

**Issue by durban** [typelevel/cats#1832]
`NonEmptyVector` could have a total `last` method (unlike `Vector`). I think it would be useful.

(`NonEmptyList` could also have this, but I don't know how useful would it be, since it would need to walk the whole list...)

**Comment by johnynek** [comment]
NonEmptyList does have it:

https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/NonEmptyList.scala#L38

Looks like an oversight on NonEmptyVector. Care to send a PR?

Also double check for other missing methods from one or he other of those?
