### ISSUE TITLE
Document implicit naming convention

### ISSUE THREAD

**Issue by aaronlevin** [typelevel/cats#1841]
We should update the contributing guidelines to specify implicit naming convention. I believe the convention is to prefix the name of the implicit with a camel-cased version of the package namespace. See quote from @peterneyens on a ticket I was working on (adding `Traverse` instances in the `cats.free` package):

> It is not really documented outside issue #1061 itself (it should probably be added to [these guidelines](https://typelevel.org/cats/guidelines.html)): the implicit values in Cats are prefixed with the package.
>
> So these implicits would be `catsFreeFoldableForFree` and `catsFreeTraverseForFree`.

**Comment by tbje** [comment]
Hey @aaronlevin, did #1920 fix this issue?

**Comment by kailuowang** [comment]
fixed by #1920 thanks again @tbje
