### ISSUE TITLE
Contravariant functor instance for scala.math.Ordering

### ISSUE THREAD

**Issue by durban** [typelevel/cats#1853]
There doesn't seem to be a `Contravariant` instance for `scala.math.Ordering`.

**Comment by LukaJCB** [comment]
There are some for `cats.kernel.Order` though. You can use `fromOrdering` to get an `Order` from `Ordering` :)

**Comment by durban** [comment]
Sure, but that doesn't really help me if I've got an `Ordering[A]`, and I want to simply `contramap` to get an `Ordering[B]`. (Although for that to work, #1850 also need be fixed.)

**Comment by kailuowang** [comment]
@durban can you elaborate why #1850 is related?

**Comment by johnynek** [comment]
@durban you can call `.on` to go from `Ordering[A]` to `Ordering[B]` but I agree there should be an instance.

https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/Order.scala#L53

**Comment by non** [comment]
I'm opening a PR that addresses this lack (as well as `PartialOrdering`, `Equiv`, and `Duration` which I also noticed were missing).

**Comment by non** [comment]
https://github.com/typelevel/cats/pull/1878

**Comment by durban** [comment]
@kailuowang I was mistaken, it's not.
