### ISSUE TITLE
MonadCombine and MonadFilter still referenced in the docs.

### ISSUE THREAD

**Issue by sellout** [typelevel/cats#1869]
The type class sidebar in the docs still lists MonadCombine and MonadFilter, but they link to 404s now.

Identified by @MansurAshraf on [Gitter](https://gitter.im/typelevel/cats?at=59a3a32e210ac26920cb2921).

**Comment by LukaJCB** [comment]
Fixed by https://github.com/typelevel/cats/pull/1856. Website still needs to be published though :)

**Comment by kailuowang** [comment]
thanks for reporting @sellout and responding @LukaJCB, I will publish the website later today.

**Comment by kailuowang** [comment]
should be fixed by now
