### ISSUE TITLE
Provide Utility Functions

### ISSUE THREAD

**Issue by arjunswaj** [typelevel/cats#1891]
Add utility functions like `sequence`, `map2` etc for Free <-> Stream, List.

```scala
def sequence[S[_], A](fs: Stream[Free[S, A]]): Free[S, Stream[A]] =
  fs.reverse.foldLeft[Free[S, Stream[A]]](Free.pure[S, Stream[A]](Stream()))((b, a) => map2(a, b)(_ #:: _))

def map2[S[_], A, B, C](ra: Free[S, A], rb: Free[S, B])(f: (A, B) => C): Free[S, C] = for {
  a <- ra
  b <- rb
} yield f(a, b)
```

**Comment by LukaJCB** [comment]
`sequence` is implemented on `Traverse` and `Stream` has a `Traverse` instance and `Free` has an `Applicative instance, so you can just do 
```scala
val fs: Stream[Free[S, A]] = ???
val sequenced: Free[S, Stream[A]] = fs.sequence
```

And map2 only requires `Apply`:
```scala
Applicative[Free[S, ?]].map2(ra, rb)(f)
```

**Comment by arjunswaj** [comment]
Thanks! Is there any import that I need to do? I'm using Scala 2.11.7 and Cats-0.9.0. I was not able to get `.sequence` on Stream. I'm using the Scala collection Stream in my DSL. Is it an implicit method?

**Comment by LukaJCB** [comment]
You'll need to activate partial unification, you should be able to upgrade to Scala 2.11.11 and then you just need to import `cats.implicits._`

**Comment by arjunswaj** [comment]
Thank you! :)
