### ISSUE TITLE
many kernel algebraic typeclasses should be `Invariant`

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#1904]
If you have `Invariant[M]` and an isomorphism (or bijection) `A => B, B => A` then you can go between `M[A] <=> M[B]`. This can be very useful when combined with shapeless which can generate iso morphisms between case classes and tuples, etc...

However, Semigroup, Semilattice, Monoid, Group, etc... are left out of that as far as I can see.

It would be nice to have instances for those in `object Invariant` so they could be used without import.

**Comment by kailuowang** [comment]
Shall we schedule this in RC1?

**Comment by johnynek** [comment]
I would like to. I hate when we have obvious instances for our own types that we don't ship.

**Comment by LukaJCB** [comment]
Hey @johnynek, can you elaborate a bit on what you mean by this?  :)
Do you mean instances like `Invariant[Group]` etc.? 
We do already have `InvariantMonoidal` which does extend `Invariant`, so we can already do 
```scala
Monoid[A].imap(aToB)(bToA)
```
I don't think we have these for any of the other kernel classes apart from `Semigroup` and `Monoid` though.

**Comment by johnynek** [comment]
Concretely:

1. we usually put instances for cats owned types into companions. For Monoid we have an import. Should not need that. We should just put that into `Invariant` or `InvariantMonodial` object.
2. we are missing many instances: e.g. all the ones I mentioned above. I'm not sure all are `InvariantMonoidal`. Monoid is, but some of the others may not (pure may or may not work for all cases).

**Comment by LukaJCB** [comment]
I like the idea of having everything in `object Invariant`, but we'd break the API, no? 
We could do something like `object InvariantInstances extends MonoidInstances with SemigroupInstances`, WDYT?

**Comment by johnynek** [comment]
I think these are so rarely used, I don't mind breaking the API to make it consistent current cats practice before 1.0

**Comment by LukaJCB** [comment]
I'll submit a PR soon :)

**Comment by LukaJCB** [comment]
Fixed by #1914 :)
