### ISSUE TITLE
Expected result for Eq[OneAnd[Set, Int]] ?

### ISSUE THREAD

**Issue by ronanM** [typelevel/cats#1909]
I expected `true` has with `Set[Int]`, or maybe I am wrong... ?

```scala
import cats.data.OneAnd
import cats.implicits._

OneAnd[Set, Int](1, Set(2, 3)) === OneAnd[Set, Int](3, Set(1, 2))
> false !!!

Set(1, 2, 3) === Set(3, 1, 2)
> true
```

**Comment by LukaJCB** [comment]
Yeah, you can't get a `NonEmptySet` with `OneAnd`. See https://github.com/typelevel/cats/issues/123

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out now that we have `NonEmptySet` available. The behavior can still perhaps be surprising, but hopefully now people have less of a reason to try to use `OneAnd` with `Set`.
