### ISSUE TITLE
Add traverseN to CartesianBuilder

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#1936]
Similar to `mapN`

```scala
// now
(fa, fb, fc).tupled.traverse{ f(_).tupled }

// after
(fa, fb, fc).traverseN(f)
```

**Comment by kailuowang** [comment]
I probably missed something, what's the difference between this and 
```scala
(fa, fb, fc).mapN(f).sequence
```

**Comment by julien-truffaut** [comment]
it is the same but I believe traverse has the ability to fail early.

**Comment by kailuowang** [comment]
In this example 
```(fa, fb, fc).tupled.traverse{ f(_).tupled }```, as soon as you `tupled`, it's just one element, how to fail "early" with the `traverse` after? 
Would you mind give a concrete example? Just  a `F[_]` in the `fa` and `G[_]` in the `f(_)` would suffice?

**Comment by julien-truffaut** [comment]
If you pick up `F = List` and `G = Option`, you can make `traverse` fail early by returning a `None` as soon as the application of `f` returns a `None`. While with `map + sequence` you have to apply `f` to every single element in the list.

**Comment by kailuowang** [comment]
Ah got it. I got the `tupled` wrong. thanks for bearing with me @julien-truffaut
