### ISSUE TITLE
Class names in `cats.tests` are not consistent.

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1965]
The majority is named `XXXXTests` which causes some conflicts with `cats.laws.discipline.XXXXTests` (discussed in #1960)
Other forms includes

* `XXXXCheck`
* `XXXXTest`
* `XXXXSuite`

We should consolidate them all to a single naming scheme. `XXXXSuite` maybe a good option.

**Comment by AlejandroME** [comment]
I can help with this. Should `XXXSuite` be the naming standard for all the tests? @kailuowang

**Comment by kailuowang** [comment]
@AlejandroME, thanks so much! Yeah I incline to use `XXXXSuite` .

**Comment by AlejandroME** [comment]
Got it! Working on it @kailuowang
