### ISSUE TITLE
Add Apply and Traverse for SortedMap

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#1966]
see #1964 for more discussion.

**Comment by LukaJCB** [comment]
Wouldn't we get conflicting instances because SortedMap is a subtype of Map?

**Comment by LukaJCB** [comment]
So I tried this and it seemed to work just fine. Not sure why I thought it wouldn't work. 

So I think we could get all the instances for SortedMap, that already exist for Map, but require an instance of Order[A] right?

Could potentially be relevant for #1831

**Comment by johnynek** [comment]
Maybe we need to make it higher priority? Or maybe not. Subtyping and implicit resolution confuses me sometimes with what is and is not ambiguous.

**Comment by LukaJCB** [comment]
We should probably also add instances for SortedSet  while we're at it.

**Comment by johnynek** [comment]
+1

**Comment by LukaJCB** [comment]
Actually there can't be any instances for SortedSet, as that'd require an implicit Order [A] instance, when there is no actual A.

**Comment by kailuowang** [comment]
When there are multiple instances for the target type `F`'s inheritance hierarchy, (but not the type class), the instance for the subtype is more "specific" I think.
