### ISSUE TITLE
Make sure code generated by Boilerplate are tested

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1968]
Right now a good portion of which is not. E.g. `SemigroupArityFunctions` and `ApplyArityFunctions`

**Comment by BennyHill** [comment]
I believe this issue replicates #383, with the possible difference that #383 is specifically for auto generating the tests.

Perhaps best to clarify here and close #383 ?

**Comment by ceedubs** [comment]
Closing as a duplicate of #383.
