### ISSUE TITLE
A unified `mapK` 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#1982]
For many `T[F[_], A]` or `T[F[_]]`, we can add a `mapK` that does the following
```scala
class T[F[_], A] {
  def mapK[F[_], G[_]]()(f: F ~> G): T[G, A]`
}
```

This is non-abstracted part of #1815
The following types can have this `mapK` method

- `WriterT`
-  `Kleisli`
-  `OptionT`
-  `EitherT`
-  `IdT`
-  `EitherK`
-  `Tuple2K`
-  `Free`
-  `FreeT`
-  `Func`
-  `Nested`
-  `OneAnd`

@andyscott offered to work on this

**Comment by LukaJCB** [comment]
Fixed by #2000
