### ISSUE TITLE
Kleisli#andThen unavailable for functor Validated[X, ?]

### ISSUE THREAD

**Issue by andyscott** [typelevel/cats#2013]
Composing Kleisli's with `andThen` isn't possible when the functor is `Validated[X, ?]` even though validated has an `andThen` method.

This is because Kleisli's `andThen` is an alias for `flatMap` and requires a `FlatMap` instance but `Validated` doesn't have a `FlatMap` instance (rightly so).

I don't know if it's reasonable, but there could be an `AndThen` type class in the same manner as `FlatMap`. The laws could be the same and for the vast majority of the instances the `andThen` method would just alias to `flatMap`. A default internal `AndThenIsFlatMap` trait could bake this into existing `FlatMap` instances. I don't know if this has any broader benefit outside of fixing the issue described above.

**Comment by johnynek** [comment]
we have the `Parallel` work #1837 which could be used here. So, when you have a `Parallel[F, G]` you could do `.andThen` which lifts the applicative into a monad, flatmaps, then turns it back to the applicative.

**Comment by LukaJCB** [comment]
Just to add to this, `Kleisli` also has a `Parallel` instance if the `F[_]` inside has a `Parallel` instance, so you can use `Either` for any thing you want to do using `andThen` and when actually running anything use `parMapN` or `parTraverse` or something like that! :)
