### ISSUE TITLE
Elect a maintainer of cats-mtl

### ISSUE THREAD

**Issue by andyscott** [typelevel/cats#2018]
I'm creating this here for added visibility.

`cats-mtl` currently needs a new maintainer. Currently the project hasn't been updated for the recent release of cats despite an open PR for the fix.

I'll add that I hope cats-mtl doesn't fall to the wayside as the functionality it provides it quite useful.

**Comment by johnynek** [comment]
I would prefer us not have separate repos personally. Can we merge mtl here as a submodule?

**Comment by mpilquist** [comment]
mtl was originally split out from cats proper b/c we expected its rate of change to be much higher than cats. If mtl is a submodule of cats, what does that imply w.r.t binary compatibility?

**Comment by DavidGregory084** [comment]
@mpilquist as long as the experimental status of cats-mtl is made clear in the cats README I expect that it would be allowed to have a different bincompat story to cats for now?

**Comment by johnynek** [comment]
It appears that expectation may have been incorrect and as a result now we are seeing increased friction.

**Comment by mpilquist** [comment]
@johnynek Can you expand on that? Both why the expectation may have been incorrect and what increased friction we are experiencing?

**Comment by tpolecat** [comment]
If we're prepared to do a full cats release just for `mtl`/`effect` updates and are willing to accept per-module compatibility policies then I'm fine incorporating these things as modules. I would prefer it really because it's simpler and increases visibility. But these things are likely to move much faster than `core` does, at least in the near term.

**Comment by johnynek** [comment]
Just because it was reported that we have not been able to get a PR
