### ISSUE TITLE
EqTests#eqv requires an Eq[A]

### ISSUE THREAD

**Issue by durban** [typelevel/cats#2051]
`cats.kernel.laws.discipline.EqTests#eqv` requires an implicit `Eq[A]`, while it already has one, in the `EqLaws[A]` instance it has. Thus the implicit `Eq[A]` parameter is unnecessary and could be removed.

**Comment by johnynek** [comment]
+1

**Comment by stephen-lazaro** [comment]
I can look at this this weekend if no one has bandwidth before then.
