### ISSUE TITLE
How to stop running

### ISSUE THREAD

**Issue by kostonstyle** [typelevel/cats#2055]
Hi all 

I have the following code, that I have to stop it manually:

```
object KafkaApi {

  private val workers = ExecutionContext.fromExecutor(Executors.newCachedThreadPool())

  def main(args: Array[String]) {

    (for {
      _ <- IO {
        println(Thread.currentThread().getName)
      }
      _ <- IO.shift(workers)
      _ <- IO {
        println(Thread.currentThread().getName)
      }
      _ <- IO {
        println(Thread.currentThread().getName)
      }
      _ <- IO {
        println(Thread.currentThread().getName)
      }
    } yield ()).unsafeRunAsync(_ => ())

    println("Heo")

  }
}

```

How to stop it and to back to the main?  
Thanks

**Comment by ceedubs** [comment]
Hi @kostonstyle. This sounds like a question about [cats-effect](https://github.com/typelevel/cats-effect). I'm not sure that I understand what you are looking to do exactly, but in short, you can't really `shift` back to the main thread. If you want the main thread to wait on the execution of the `IO`, then you might need to use `unsafeRunSync`. Hopefully that helps, but if not I encourage you to raise your question in the cats-effect gitter channel.
