### ISSUE TITLE
Add ArrowChoice

### ISSUE THREAD

**Issue by stephen-lazaro** [typelevel/cats#2067]
Would something like the ArrowChoice typeclass from https://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Arrow.html#t:ArrowChoice be of interest in `cats.arrow`?
Every Kleisli arrow is an instance for monads, and I have an application that is not strictly a Kleisli arrow but a sort of wrapped one at my workplace that I contemplated using this for.
I can work on a PR If so.

**Comment by kailuowang** [comment]
Sounds a good addition to me. And we still have time before the Dec 12 deadline (after which we should still be able to add it but won't have the syntax available from `cats.implicits._ `)

**Comment by stephen-lazaro** [comment]
Cool, I'll try to cook something up. Thanks Kailuo.

**Comment by stephen-lazaro** [comment]
Resolved in #2096
