### ISSUE TITLE
Remove conversion from `Hash` to `Hashing`

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#2120]
`scala.util.hashing.Hashing[A]` presupposes universal equality using `==` -- `a == b` implies `hash(a) == hash(b)`.
`cats.kernel.Hash[A]`'s underlying `eqv` is based upon `cats.kernel.Eq` which is customizable -- `eqv(a, b)` implies `hash(a) == hash(b)`.
One cannot convert a `cats.kernel.Hash[A]` to `scala.util.hashing.Hashing[A]` without compromising the typeclass instance's semantics.
@kailuowang #2116

**Comment by kailuowang** [comment]
@ctongfei thanks for point it out. We had a discussion with @denisrosset in #2116, according the [scala API doc](https://static.javadoc.io/org.scala-lang/scala-library/2.10.0/scala/util/hashing/Hashing.html)

> Note: when using a custom `Hashing`, make sure to use it with the `Equiv` such that if any two objects are equal, then their hash codes must be equal.

So it seems that we should be able to convert `Hash` to `Hashing` and `Eq` to `Eqiv`?

**Comment by ctongfei** [comment]
Thanks @kailuowang for pointing out that. I agree with your justification.
