### ISSUE TITLE
"-MF" is not a special version and so "1.0.0" < "1.0.0-MF"

### ISSUE THREAD

**Issue by fanf** [typelevel/cats#2131]
In maven ordering, a shorthand milestone identifier ("m") must be followed by a number to be considered as such, else the segment is not special. See https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java#L176 (only spec I know of for maven version rules). 

So it means that `cats-core_2.12-1.0.0` is considered to be before `cats-core_2.12-1.0.0-MF`, which is not good at all: nobody will ever be able to use `[1.0.0,1.1)` (or any qualifier meaning '1.0 or above, binary compatible version). 
 
See for example in maven central: 
- https://www.mvnrepository.com/artifact/org.typelevel/cats-core : `1.0.0-MF` is not red
- http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22cats-core_2.12%22 : latest version is `1.0.0-MF`.

Artifacts being published (and can't be unpublished in an open world), that horse left a long time ago, so I'm not sure what is the correct way forward. 
Perhaps the best option is to have a `1.0.1` release quickly, which would assure that the versionning of the whole ecosystem is correct regarding the `1.0` branch, which aims to be stable.

**Comment by tpolecat** [comment]
Ugh, grim. Releasing `1.0.1` seems good to me.

**Comment by paulp** [comment]
As an aside, it also means the MF version was "newer" than the RCs. One can imagine ways that could have lessened the exercise received by the RCs (but I really have no idea.)

**Comment by fanf** [comment]
@paulp : I think it should have been ok, as the version weren't binary compatible, there is very little chance that anybody used anything but the exact version number. A chance that binary compatibility is not a given! (sorry)

**Comment by kailuowang** [comment]
1.0.1 on the way to maven central. Will announce later

**Comment by fanf** [comment]
Now that 1.0.1 is published, that issue can be closed. I'm not sure about cats level process, who should do it?
