### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2139]
- [ ]  In the write test section, link to https://typelevel.org/cats/typeclasses/lawtesting.html
- [ ] add a step of checking binary compatible: `++2.11.12` and then `mimaReportBinaryIssues`
- [ ] in the write code section, copy/consolidate the discussion from the linked issues to [Guidelines.md](https://github.com/typelevel/cats/blob/master/docs/src/main/tut/guidelines.md) and then link to it. 
- [ ] remove the "Publishing the site to github" section, this is done by sbt-microsite now. 
- [ ] The doc suggested to use the Waffle.io to find issues to work on, should replace with finding issue with the low-hanging-fruit or help-wanted tag 
- [ ] in the what goes in cats section also introduce mouse, cats-effect and cats-mtl
Not sure if I captured all the outdated bits. But these should be make it by and large update-to-date.

**Comment by AlejandroME** [comment]
@kailuowang Can I take this?

**Comment by kailuowang** [comment]
of course. @AlejandroME Thanks!

**Comment by Rlucas12** [comment]
Is this done ?

**Comment by AlejandroME** [comment]
@Rlucas12 WIP, pushing the first draft between today and tomorrow.
