### ISSUE TITLE
Missing syntax import for `.unorderedTraverse`

### ISSUE THREAD

**Issue by andyscott** [typelevel/cats#2147]
The import `cats.syntax.traverse._` doesn't provide the `.unorderedTraverse`. This is inconsistent, as the import `cats.syntax.foldable._` does provide the `unorderedFold` syntax.

Unfortunately I think an immediate fix for this would break binary compatibility. `import cats.UnorderedTraverse.ops._` can be used for the time being.

**Comment by kailuowang** [comment]
`cats.syntax.traverse` can extend an extra trait without breaking bin compat. So I think we should be able to fix this one

**Comment by andyscott** [comment]
If that's the case, I'll submit a PR shortly.
