### ISSUE TITLE
IntelliJIDEA's support for simulacrum disabled in cats

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2152]
IntelliJIDEA's support for simulacrum is disabled by this [trick](https://github.com/typelevel/cats/blob/master/build.sbt#L40-L44) to enable compile-time-only dependency. 

See discussion here. 
https://youtrack.jetbrains.com/issue/SCL-13221

IntelliJ is a great tool to navigate the code base, without simulacrum support, it would be less useful in the Cats codebase.
 
3 Options I can see:
1. keep as is. wait for https://youtrack.jetbrains.com/issue/SCL-13221 to fix 
2. document the issue so that user can temporarily comment out the `% CompileTime` when using IntelliJ IDEA with cats. 
3. switch back to use `% Provided` and leave an issue to switch back when jetbrains adds support for it.

**Comment by jgogstad** [comment]
Is this related to other incorrect red squiggles issues with cats and IntelliJ?

"Good code highlighted in red using cats mapN": https://youtrack.jetbrains.com/issue/SCL-12892
"False error (good code red): sequence from cats": https://youtrack.jetbrains.com/issue/SCL-10259
