### ISSUE TITLE
Scaladoc link not working

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#2168]
The "Documentation" ScalaDoc link on the website doesn't seem to be working. The API docs do exist at http://typelevel.github.io/cats/api/cats/index.html though. @larsrh is this something that might have been affected by the changes to the Typelevel site that you made a while back? cc @kailuowang who may also have insight.

**Comment by larsrh** [comment]
Strange. I just went to https://typelevel.org/cats/, clicked on documentation, and arrived at the documentation. What page were you looking at?

**Comment by denis-it** [comment]
+1
Sometimes "Documentation" link is https://typelevel.org/api/cats/index.html.

**Comment by kailuowang** [comment]
Doesn't work when you use typelevel.org/cats without trailing / , fixed by https://github.com/typelevel/cats/commit/8db3501e2026fdfe94a44affbf5acaa64c433f51
But we can't publish website until next release due to yet to release new API additions.
Hopefully we can release soonish

**Comment by ceedubs** [comment]
@kailuowang ah okay thanks for clearing that up.

**Comment by ceedubs** [comment]
This is fixed.
