### ISSUE TITLE
Cross build for Scala.js 0.6.x and 1.x

### ISSUE THREAD

**Issue by ghost** [typelevel/cats#2195]
see https://www.scala-js.org/news/2018/02/01/announcing-scalajs-1.0.0-M3/, esp [the tips on cross-building](https://www.scala-js.org/news/2018/02/01/announcing-scalajs-1.0.0-M3/#cross-building-for-scalajs-06x-and-1x).

Also of interest _may_ be [sbt-dynscalajs](https://github.com/sjrd/sbt-dynscalajs), but read the disclaimers first.

This task may be worth doing in conjunction https://github.com/typelevel/cats/issues/1549 as there are (potentially) some overlaps with the new cross project setup

**Comment by kailuowang** [comment]
maybe we should consider using adding this support to sbt-catalysts and start using it in cats?

**Comment by BennyHill** [comment]
Quick update on this:

This change requires the change to the newer crossproject. Coupled with that,  I recently did a PR for SBT that introduces composite projects - see https://github.com/sbt/sbt/issues/3042 and https://github.com/sbt/sbt/pull/4056

So I'm waiting for sbt 1.2, that hopefully will be out soon

**Comment by randm-ch** [comment]
@BennyHill SBT 1.2.0-M1 [is out](https://github.com/sbt/sbt/releases/tag/v1.2.0-M1) :) Any ETA on this?

**Comment by BennyHill** [comment]
@randm-ch Also required is the new crossproject to use this, but looks like that work is done already - https://github.com/portable-scala/sbt-crossproject/pull/99.

So nothing holding back on moving this forward now... but I'm away on holiday for another week.  


But the tentative release for sbt 1.2 is only 16th July, not far way in any case

**Comment by BennyHill** [comment]
However, in https://github.com/typelevel/cats/issues/2267 @djspiewak notes that sbt-crossbuild is required for 2.13.X, so I'm wondering if it may be better/quicker/easier to split the task up to: 

In Parallel:
- update catalaysts build to use sbt-crossproject, leave everything else as-is (N.B. this requires sbt-catalysts changes)
-  update cats build to use sbt-crossproject, leave everything else as-is

Then:
- update  update catalysts build to use sbt 1.2 and new CI sbt-crossproject, At this point we can see how easy/difficult it is to either migrate cats to sbt-catalysts OR manually update cats build to cross compile with scala-js

My main concern/goal would be to "show" to cats, and derivative projects such as cats-effects, that we can increase the build matrix  AND make it simpler, as I think there is currently some general concern that all this cross-building is a pain

**Comment by BennyHill** [comment]
Status/fyi :

> update cats build to use sbt-crossproject, leave everything else as-is

See pr https://github.com/typelevel/cats/pull/2323

**Comment by randm-ch** [comment]
@kailuowang would you mind taking a look at this issue? Sounds like everything's ready, but the original assignee became a ghost :wink:

**Comment by sorenbug** [comment]
Any update on this? Scala.JS 1.x has some features I require for a project, and I'd like to be using fs2 for it.

**Comment by psttf** [comment]
Can this issue be closed now?

**Comment by djspiewak** [comment]
Most definitely. Thanks for the reminder!
