### ISSUE TITLE
Const should have a CommutativeApply/CommutativeApplicative instance

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2201]
Whenever `C` has a `CommutativeSemigroup/Monoid` instance. We should be able to add these in a backwards compatible way, no?

**Comment by kailuowang** [comment]
Yes. Adding instances is usually binary compatible in cats. I went through all of the instance definitions to make sure they are abstract classes before the 1.0 release.

**Comment by barambani** [comment]
it should be pretty similar to the stuff I've looked into recently. I would try it if that's ok

**Comment by ceedubs** [comment]
Resolved by #2204
