### ISSUE TITLE
Port Alleycats README

### ISSUE THREAD

**Issue by longcao** [typelevel/cats#2202]
I found the [README for Alleycats](https://github.com/non/alleycats/blob/master/README.md) to be pretty useful for understanding why it exists as another module with separated typeclasses. It doesn't look like it was ported in with https://github.com/typelevel/cats/pull/1984 - would it be useful to have some rendition of it again somewhere in this repo?

**Comment by BennyHill** [comment]
ref https://gitter.im/typelevel/cats-dev?at=5a99bffa6f8b4b9946e0c3c6 so another :+1:
