### ISSUE TITLE
Either pattern match Right before Left

### ISSUE THREAD

**Issue by fdietze** [typelevel/cats#2210]
Since `Either` is right-biased, wouldn't it make sense to change the order for pattern matching to match `Right` first? Right should be the common non-error case.

```scala
either match {
	case Right( ... ) =>
    case Left( ... ) =>
}
```

In the code I see it the other way round: https://github.com/typelevel/cats/search?utf8=%E2%9C%93&q=case+Left&type=

Performance wise this should only make a tiny difference. I found a benchmark from 2011: https://stackoverflow.com/questions/7097107/does-the-order-of-alternatives-in-a-scala-match-expression-matter-in-terms-of-pe

**Comment by kubukoz** [comment]
IMO if it doesn't profit performance, then there's no point in matching to `Right` first - and depending on your usecase, you might encounter `Left`s more often - then matching on `Right` first would be the slower solution for the whole thing.
