### ISSUE TITLE
cats.implicits._ doesn't include Show[Duration] instance

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#2216]
I think that fixing this would involve a binary incompatibility for scala < 2.12, so we probably can't fix this until Cats 2.0.

```scala
scala> import cats.Show, cats.implicits._
import cats.Show
import cats.implicits._

scala> Show[scala.concurrent.duration.Duration]
<console>:19: error: could not find implicit value for parameter instance: cats.Show[scala.concurrent.duration.Duration]
       Show[scala.concurrent.duration.Duration]
           ^

scala> import cats.instances.duration._
import cats.instances.duration._

scala> Show[scala.concurrent.duration.Duration]
res1: cats.Show[scala.concurrent.duration.Duration] = cats.Show$$anon$2@2f42b6fc
```

**Comment by peterneyens** [comment]
Not sure, but can we do something for `instances` like we did for `syntax` with [AllSyntaxBinCompat0](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/all.scala#L56-L59) (introduced in #2148)?

**Comment by ceedubs** [comment]
@johnynek in the past I recommended making our instance mix-in traits package-private to ease binary compatibility. However, if I recall correctly, some people didn't want that specifically because they _did_ want to be able to extend the instance mix-in traits. Considering this, we probably shouldn't assume that people aren't subclassing our instance traits.

Binary compatibility becomes much less of an issue for the hierarchy-of-traits approach once we only guarantee backwards compatibility for scala 2.12+ (which it sounds like we may do for Cats 2.0).

I think that we might be able to pull something like what happened in #2148, but I also am not sure whether it's worth the hassle. I haven't seen anyone complain about missing this instance, it's trivial to create if someone wants it, and `Show` is generally not super helpful. I just happened to notice that it was missing when I was looking at a code coverage report.

**Comment by kailuowang** [comment]
should be pretty trivial to add it, just let add the `cats.instance.DurationInstances` to `cats.implicits` and `cats.instances.all`. We can't change `cats.instance.AllInstances` and thus `cats.tests.CatsSuite`, those would have to wait for cats 2.0

**Comment by kubukoz** [comment]
If it's OK, I'd like to contribute this (add `cats.instance.DurationInstances` to `cats.implicits` and `cats.instances.all`) :)

**Comment by LukaJCB** [comment]
I think before we do that, we need to figure out a branching strategy :)

**Comment by kubukoz** [comment]
One PR could do that, and a second one (forking the first one's branch) would move these extensions to `AllInstances` - would that work?
