### ISSUE TITLE
StateT Performance Regression

### ISSUE THREAD

**Issue by fosskers** [typelevel/cats#2220]
Between 1.0.0 and 1.1.0 (and previously between 0.9 and 1.0.0), `StateT` has suffered a performance regression. I discovered this when updating versions for [scalaz-and-cats](https://github.com/fosskers/scalaz-and-cats).

For:
```scala
  type EitherStr[T] = EitherT[Eval, String, T]
  type StEtr[T] = StateT[EitherStr, Int, T]

  def countdownT: StEtr[Unit] = StateT.get[EitherStr, Int].flatMap({ n =>
    if (n <= 0) MonadError[StEtr, String].raiseError("crap")
    else StateT.set[EitherStr, Int](n - 1) *> countdownT
  })

  def runCountDownT: Either[String, (Int, Unit)] = countdownT.run(10000).value.value
```
we see this runtime drop from **8,920,953 ns** to **9,744,808 ns**. This is after a 2x slowdown between 0.9 and 1.0.0 which @iravid said had something to do with `IndexedStateT`. This 9.7 million ns number is around twice as slow as the equivalent ScalaZ, and 5 orders of magnitude slower than Haskell.

**Comment by kailuowang** [comment]
Thanks for reporting this. It's probably introduced in this PR https://github.com/typelevel/cats/pull/2187 which improves the stack safety of StateT. 
A very interesting alternative solution might be @iravid 's [FreeState](https://github.com/iravid/transformer-benchmarks), which seems to be 1 order of magnitude faster.

**Comment by fosskers** [comment]
Can't really get mad about a regression if it's for safety/correctness eh?
