### ISSUE TITLE
Is there a way to treat Tuple as Applicative?

### ISSUE THREAD

**Issue by satansk** [typelevel/cats#2227]
If I have a list of tuples:

```Scala
val xs = (1, 'a') :: (2, 'b') :: Nil
```

I can use `List.unzip` to get a tuple of lists:

```Scala
// (List(1, 2),List(a, b))
xs.unzip
```

But is there any way to do something like this ?

```Scala
// (List(1, 2),List(a, b))
xs.sequence
```

Since the type of `xs` is `List[Tuple2[A, B]]`,  and what I want is `Tuple2[List[A], List[B]]`, it seems like what `Traverse.sequence` does. But to archive it, we have to be able to treat `Tupple` as `Applicative`.

Thanks :)

**Comment by LukaJCB** [comment]
This doesn't really work as of right now, `Applicative` takes a type constructor with a single argument, and `Tuple2` takes two. You can form an `Applicative` for `Tuple2[A, ?]`, but that's not what you're describing in your case.

**Comment by kubukoz** [comment]
@satansk do you think we can close this issue?

**Comment by satansk** [comment]
@kubukoz yes, sorry for my delay, let me close it :)
