### ISSUE TITLE
Add MonadError instance for OptionT where F is a Monad

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2228]
Currently we have `(Monad f) => Monad (OptionT f)` as well as `(MonadError f e) => MonadError (OptionT f) e`, but we could just as well change that first definition to have a `MonadError[OptionT[F, ?], Unit]`. :)

**Comment by LukaJCB** [comment]
I've even got a free implementation to give away:
```scala
private[effect] trait OptionTMonadError[F[_]] extends MonadError[OptionT[F, ?], Unit] {
  implicit def F: Monad[F]

  def pure[A](a: A): OptionT[F, A] = OptionT.pure(a)

  def flatMap[A, B](fa: OptionT[F, A])(f: A => OptionT[F, B]): OptionT[F, B] = fa.flatMap(f)

  override def map[A, B](fa: OptionT[F, A])(f: A => B): OptionT[F, B] = fa.map(f)

  def tailRecM[A, B](a: A)(f: A => OptionT[F, Either[A, B]]): OptionT[F, B] =
    OptionT(F.tailRecM(a)(a0 => F.map(f(a0).value)(
      _.fold(Either.right[A, Option[B]](None))(_.map(b => Some(b): Option[B]))
    )))

  def raiseError[A](e: Unit): OptionT[F, A] = OptionT.none

  def handleErrorWith[A](fa: OptionT[F, A])(f: Unit => OptionT[F, A]): OptionT[F, A] =
    OptionT(F.flatMap(fa.value) {
      case s @ Some(_) => F.pure(s)
      case None => f(()).value
    })
}
```

**Comment by oleg-py** [comment]
Btw, is `MonadError[Option, Unit]` actually useful?

**Comment by LukaJCB** [comment]
As useful as it ever as, I wager ;)

**Comment by abhishek7** [comment]
@LukaJCB I'm new to Cats and wanted to help contribute. While I'm not familiar with the code base yet, I'm happy to give this a try if we think it's appropriate for a newcomer?

**Comment by LukaJCB** [comment]
Sure, go right ahead, I'll guide you through it if you hit any hurdles! :)

**Comment by abhishek7** [comment]
@LukaJCB, appears that this already had a PR merged. I guess we can go ahead and close this open issue? I'll try to pick up another open one.
