### ISSUE TITLE
Add `or` to ApplicativeError

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#2242]
```scala
def or(other: IO[A]): IO[A] = io.attempt.flatMap {
    case Right(a) => IO.pure(a)
    case Left(e)  => other
 }
```

Also, this implies you can make a `SemigroupK` if you have a MonadError. With an example error, you can make a `MonoidK`. Or, if you have a `MonadError[F, Unit]`, such as Option, you have an Alternative, I guess.

**Comment by kailuowang** [comment]
we can add this to [ApplicativeErrorOps](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/applicativeError.scala#L52) in 1.x.

**Comment by johnynek** [comment]
true, handleErrorWith is all that is needed here.

**Comment by johnynek** [comment]
@barambani Please!

**Comment by johnynek** [comment]
@kailuowang do we have a list of changes that we hacked onto AnyVal classes that we would like to undo?

Side question: should we prefer to keep typeclasses minimal, and have most methods on anyval extensions? It seems that we have almost all methods on the typeclass rather than thinking much about what could plausibly be optimized per type. I guess if binary compatibility was not a problem, and it won't be in 2.12, putting on the trait is strictly better. Maybe we just need to get the community to move to 2.12.
