### ISSUE TITLE
Cats testkit based on other testing frameworks?

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2244]
Right now our cats testkit is based on `ScalaTest`, personally I don't really like that testing library all that much, so it'd be great if we could offer an alternative that's just as integrated for law testing. 
I think Monix/minitest would be a good candidate to get this going :) what do you think?

**Comment by tpolecat** [comment]
I'm not a fan of any existing test framework at this point because all of them are side-effecting, but I would definitely prefer something lighter like minitest.

**Comment by kailuowang** [comment]
I am curious what people would need from the cats-testkit if they are using `minitest`. In mainecoon I am using ScalaTest and I don't even need `cats-testkit`.

**Comment by tpolecat** [comment]
The main feature is setting up law-checking, which isn't even remotely obvious. Also providing a combination of deps that work together. This stuff was always a nightmare in scalaz.

**Comment by LukaJCB** [comment]
It also comes with discipline integration so you can do `checkAll` for law tests, which is really the main reason I do it, tbh

**Comment by kailuowang** [comment]
dicispline comes with cats-laws, you don't need cats-testkit. You can do law-checking without cats-testkit.

**Comment by kailuowang** [comment]
maybe we should update the documentation to make this less confusing.

**Comment by tpolecat** [comment]
As far as I can tell there is exactly zero doc for discipline so I don't consider it something we can expect people to use directly. So yeah maybe we could fix that.

**Comment by ChristopherDavenport** [comment]
A better guide for discipline would be extremely useful. As without it being easy to put into place unlawful instances will likely proliferate outside of libraries that have overcome that entry-barrier.

**Comment by kailuowang** [comment]
`Discipline` comes with two tiny parts. 
One is to help define hierarchical laws 
https://github.com/typelevel/discipline/blob/master/shared/src/main/scala/Laws.scala
The other part is two helpers to generate ScalaTest and Spec2 tests using laws - i.e. the `checkAll` thing. 
The `ScalaTest` one is like three lines
```scala
  def checkAll(name: String, ruleSet: Laws#RuleSet): Unit = {
    for ((id, prop) ← ruleSet.all.properties)
      test(name + "." + id) {
        check(prop)
      }
  }
```
I guess what we really need is to provide `checkAll`s for other test frameworks inside `discipline`.

**Comment by kailuowang** [comment]
I am modifying the documentation.

**Comment by BennyHill** [comment]
Catalysts provides all of this, and has done so for a few years. And was based on work done in cats, spire, algebra, shapeless, etc.

Its fine if folk decide on another solution, but we may well be going round in circles here.

**Comment by BennyHill** [comment]
Btw, maybe not obvious, but discipline is well documented in the scaladoc.

**Comment by LukaJCB** [comment]
Picking this up, should we provide `cats-testkit-spec2` and `cats-testkit-minitest` modules that depend on those two testing frameworks instead of ScalaTest? :)
