### ISSUE TITLE
Consider Async.deferFuture

### ISSUE THREAD

**Issue by jmcardon** [typelevel/cats#2250]
Current interop with future is:
```scala
def fromFuture[A](iof: IO[Future[A]]): IO[A] =
    iof.flatMap { f =>
      IO.async { cb =>
        
    }
```

I propose:

```scala
trait Async[A] {
//...
def deferFuture[A](f: => Future) = {
  async {
     f.onComplete(r => cb(r match {
          case Success(a) => Right(a)
          case Failure(e) => Left(e)
        }))(immediate)
      }
  } 
}
```

Reasons:
- This is a common operation for people.
- (Minor reason) `fromFuture` is 3 extra allocations and evals used right: Pure + Suspend (defer) + Bind + Async. This would only be `Async`.
- `fromFuture` allows you to construct non-RT values with `IO.pure` or whatever. While you can go wrong with `deferFuture` at least it is explicitly lazy.

**Comment by kubukoz** [comment]
Of course, it'll have to be a function in the `Async` object though :P

Also, can we use `r.toEither`?

```scala
def deferFuture[F[_] : Async, A](f: => Future[A]): F[A] = {
  Async[F].async { cb =>
    f.onComplete { r =>
      cb(r.toEither)
    }(immediate)
  }
}
```

**Comment by LukaJCB** [comment]
I think this should go to `cats-effect`, no? :)

**Comment by jmcardon** [comment]
@LukaJCB I'm an idiot. Whoops. Wrong repo. lmao

**Comment by kubukoz** [comment]
@jmcardon I didn't notice either 😂 we're all idiots
