### ISSUE TITLE
Syntax extensions for Parallel require Monad[M], but implementation doesn't

### ISSUE THREAD

**Issue by oleg-py** [typelevel/cats#2254]
I discovered today that to use syntax extension for `parTraverse`/`parSequence`, a `Monad[M]` instance is required.

```
final class ParallelTraversableOps[T[_], A](val ta: T[A]) extends AnyVal {

  def parTraverse[M[_]: Monad, F[_], B]
  (f: A => M[B])(implicit T: Traverse[T], P: Parallel[M, F]): M[T[B]] =
    Parallel.parTraverse(ta)(f)

}
```
While `Parallel.parTraverse` is defined as follows (notice lack of `Monad[M]`)
```scala
  def parTraverse[T[_]: Traverse, M[_], F[_], A, B]
  (ta: T[A])(f: A => M[B])(implicit P: Parallel[M, F]): M[T[B]] = {
    val gtb: F[T[B]] = Traverse[T].traverse(ta)(f andThen P.parallel.apply)(P.applicative)
    P.sequential(gtb)
  }
```
Same is true for `parSequence`. Is that an oversight?

**Comment by LukaJCB** [comment]
Yes it is, unfortunately we can't change it until cats 2.0.
There's already a PR at https://github.com/typelevel/cats/pull/2180

**Comment by joroKr21** [comment]
Why can't we change it? Implicits can be changed in a binary compatible way by making the old ones non-implicit and adding the new ones.
