### ISSUE TITLE
`parFlatTraverse` as a syntax extension

### ISSUE THREAD

**Issue by guizmaii** [typelevel/cats#2255]
Hi,

I was wondering if it's imaginable for you to add the `parFlatTraverse` as a syntax extension ?

For now, it only exists in the `Parallel` companion object.

Thanks,
Jules

**Comment by Avasil** [comment]
@guizmaii 
Do you plan on doing PR for that? If not I'm happy to do this :)

**Comment by guizmaii** [comment]
@Avasil I don't have enough time to do this. I still have to finish another PR here. I'm already waiting for your PR 🙂
