### ISSUE TITLE
where is rightmap in bifunctor.scala

### ISSUE THREAD

**Issue by rgkirch** [typelevel/cats#2257]
Why is there a a leftMap in src/main/scala/cats/Bifunctor.scala but there is not rightMap?
Searching rightMap in the github issues shows a commit adding leftMap and rightMap to bifunctor but it is not in the current version and I did not find the commit that removes it.

Thanks.

**Comment by durban** [comment]
It have been removed in #1230. The reasoning seems to be that everything which has a `Bifunctor` also tends to have a `Functor` on the right type param (I don't know if this is actually true). If so, then `rightMap` is simply `map`.

**Comment by rgkirch** [comment]
Ok thanks. Yea, I tested it and map just applies to the right member of a tuple. Thank you.
