### ISSUE TITLE
Define `flatten` for `EitherT`

### ISSUE THREAD

**Issue by gvolpe** [typelevel/cats#2271]
After a [user's question](https://gitter.im/typelevel/cats?at=5b0e644e16f6496124f0636c) on the Gitter channel I realized there's no `flatten` method defined in `EitherT`. If you're guys okay with it, I can work on a small PR to add it :)

**Comment by oleg-py** [comment]
I would appreciate `.leftWiden` too 👍

**Comment by gvolpe** [comment]
@LukaJCB just found out `flatten` syntax does not work for `EitherT[Future, A, EitherT[Future, A, B]]` if there's no `ExecutionContext` available, damn `Future`.

I'll close this issue. @oleg-py if you still want to add `.leftWiden` might be better to raise a separate issue.
