### ISSUE TITLE
Document why monad transformers don't have Applicative instances. 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2272]
see https://github.com/typelevel/cats/pull/2181#issuecomment-370098157
Probably in the FAQ section, maybe also mention in the guideline.

**Comment by kubukoz** [comment]
I could implement this sometime this week if it's OK.

Worth noting (from gitter: https://gitter.im/typelevel/cats?at=5b0ed363361a950a6629f2a4)

> Jakub Kozłowski @kubukoz 18:37
> typelevel/cats#2272 - is this correct? I see a MonadError for EitherT, which implies Applicative
> I'm probably missing something obvious

> LukaJCB @LukaJCB 18:39
> Right, of course they do have an Applicative, just that Applicative[F] doesn’t give them an Applicative :)
