### ISSUE TITLE
Add foldMapK and reduceMapK

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2275]

**Comment by kubukoz** [comment]
`foldMapK` would look something like this, right?

```scala
def foldMapK[G[_], A, B](fga: F[G[A]])(f: A => B)(implicit G: MonoidK[G]): G[B]
```

**Comment by kubukoz** [comment]
hmm, I think I wouldn't be able to implement that without an `Applicative[G]`, which is probably not the point, so I must've got the signature wrong

**Comment by kubukoz** [comment]
`def foldMapK[G[_], A, B](fga: F[A])(f: A => G[B])(implicit G: MonoidK[G]): G[B]` sounds more like it, WDYT?

**Comment by LukaJCB** [comment]
Yes `A => G[B]` is what I had in mind :)

**Comment by kubukoz** [comment]
Cool, I'll work on it then

**Comment by kubukoz** [comment]
I'm wondering how we can test this.

Should there be a new law that says `foldMapK(fa)(f) <-> fa.map(f).foldK`? That'd require a `Functor[F]` in the first place, and there are probably types out there that have a Foldable but not a Functor.

Alternatively, we could have tests for some concrete instance that the equivalence holds, or have a law that reuses what's in the implementation (although I doubt that's the right way to go).

WDYT?

**Comment by LukaJCB** [comment]
I think a better law would be `foldMapK(fa)(f) <-> foldMap(fa)(f)(MonoidK[G].algebra)` :)

**Comment by kubukoz** [comment]
Could be :sweat_smile: that's actually what I meant by having a law that reused the implementation we're going to have - but I guess it would suffice for testing people's implementations if they decide to override

**Comment by kubukoz** [comment]
I'm working on the laws, apparently adding a new type parameter (`G[_]`) breaks tens of other tests, so bear with me

**Comment by LukaJCB** [comment]
You could use `Id` like is done for `foldM` :)

**Comment by kubukoz** [comment]
You're telling me now 😂 

I already did it for `G[_]` and passed Option everywhere (as is the custom that I saw in the use sites), in case it's too much to add I can hardcode `Id`. I'll open a PR now so you can see what it looks like
