### ISSUE TITLE
Meta: 2.x branching strategy

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#2287]
Since there already issues that can't be resolved without breaking binary compatibility, a 2.x branch could be created to allow submitting PRs against it.

This issue can be the home of discussions about how that'll be handled.

**Comment by johnynek** [comment]
Could we add a link to the issues we think need 2.0 to fix and also some notion of how severe each issue is?

**Comment by kailuowang** [comment]
@johnynek [here are some](https://github.com/typelevel/cats/milestone/8) that requires some level of binary breaking. The only main thing is IRT to `Parallel`. But even with that, personally, I don't see the urgency of starting a binary breaking branch out weight the benefit of stability. 

We still don't have a clear roadmap on how long we want to maintain binary compatibility on Scala 2.10, 2.11 and 2.12 respectively. See this issue https://github.com/typelevel/cats/issues/2130.

**Comment by kubukoz** [comment]
Closing, the discussion can be followed on https://github.com/typelevel/cats/issues/2719
