### ISSUE TITLE
Add an update method to NonEmptyMap

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2288]
Something along these lines:

```scala
def update[K, A](nem: NonEmptyMap[K, A], key: K, f: A => A): NonEmptyMap[K, A]
```

Unfortunately `SortedMap` doesn't expose such a method.

**Comment by johnynek** [comment]
Why is this different from mapValues or the Functor map?

**Comment by johnynek** [comment]
Oh, I see. Only update one key. Duh.

**Comment by kubukoz** [comment]
You surely meant `updated`, right? :P

**Comment by kubukoz** [comment]
Nobody said they were working on it, so I guess you're good to go :P

**Comment by kubukoz** [comment]
Btw. wouldn't it be better to have `modify` in the name? `update` reminds me of the standard library's `updated`, which just takes a key and a new value, but this is more like `modifyAt` if you look at how `modify` is named in `Ref`: https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/concurrent/Ref.scala#L115

**Comment by Obarros** [comment]
Yeah, good point @kubukoz. 
When I look at `updated` usually I think of something that will create a new map obtained by updating `this` map with a given key/value pair as well ...
Here we are after Modifying the initial state using `f`, it would make sense to make it part of the name somehow.

**Comment by nasadorian** [comment]
Hi @Obarros @LukaJCB was this issue already addressed in a PR? Happy to help out as it seems like somewhat low hanging fruit.

**Comment by LukaJCB** [comment]
Hi @nasadorian, as far as I know there's been no PR yet

**Comment by nasadorian** [comment]
@LukaJCB https://github.com/typelevel/cats/pull/2592
