### ISSUE TITLE
Ambiguous values for Aplicative[Kleisli[F,A,?]]

### ISSUE THREAD

**Issue by letalvoj** [typelevel/cats#2295]
Hi,

after upgrading cats from `1.0.0-MF` to `1.0.1` i am getting an ambiguous implicit values error.

The following example, which I got from [here](http://codegists.com/snippet/scala/cats-readerscala_ilya-murzinov_scala) (i.e. I am not the only one getting it) demostrates it.
```
import cats.data.Reader
import cats.syntax.applicative._

type MyReader[A] = Reader[String, A]
Applicative[MyReader]
```
yields

```
Error:(19, 16) ambiguous implicit values:
 both method catsDataCommutativeMonadForKleisli in class KleisliInstances of type [F[_], A](implicit F0: cats.CommutativeMonad[F])cats.CommutativeMonad[[γ$7$]cats.data.Kleisli[F,A,γ$7$]]
 and method catsApplicativeForArrow in object Applicative of type [F[_, _], A](implicit F: cats.arrow.Arrow[F])cats.Applicative[[β$0$]F[A,β$0$]]
 match expected type cats.Applicative[ai.blindspot.lueba.detection.CombinedDetector.Tst.MyReader]
    Applicative[MyReader]
```
likely related to the following PR https://github.com/typelevel/cats/pull/2078

**Comment by kailuowang** [comment]
hmm, I couldn't repeat the error on cats 1.1.0 or 1.0.1 . The instance definition inside `Kleisli` should more specific and thus takes higher priority.  You enabled partialUnification right?

**Comment by letalvoj** [comment]
Nope. I mean I even had to google what `-Ypartial-unification` is 😅 

But at the same time I added `circe-core` as a dependency ... That's why I bumbed up the version to match the one required by `circe`. It comes with a paradise plugin. I'll check whether it's caused by one of these.

I thought that it was wierd, that I'd be the first one to experience this.

**Comment by kailuowang** [comment]
try enable `-Ypartial-unification` to see if you still see the error. This setting is going to be enabled by default starting scala 2.13

**Comment by kailuowang** [comment]
no problem. closing.
