### ISSUE TITLE
Missing functions for RWST

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2304]
We're currently missing `listen` from `Writer` and `local` from `Reader`.

Here's an easy implementation:

```scala
def listen[A](fa: ReaderWriterStateT[M, E, L, S, A]): ReaderWriterStateT[M, E, L, S, (A, L)] =
  ReaderWriterStateT((e, s) => fa.run(e, s).map {
    case (l, s, a) => (l, s, (a, l))
  })

def local[A](f: E => E)(fa: ReaderWriterStateT[M, E, L, S, A]): ReaderWriterStateT[M, E, L, S, A] =
  ReaderWriterStateT((e, s) => fa.run(f(e), s))

```

**Comment by kubukoz** [comment]
You're spoiling the fun with these easy implementations!

**Comment by LukaJCB** [comment]
Speaking of `listen`, we should add that one to `Writer` as well.

**Comment by calvinbrown085** [comment]
Hi @LukaJCB I wouldn't mind picking this one up.

**Comment by YuvalItzchakov** [comment]
@calvinbrown085 Did you end up working on this?

**Comment by calvinbrown085** [comment]
@YuvalItzchakov I have not yet, I have not found the time! If someone else would like to pick this up please feel free!

**Comment by satansk** [comment]
@calvinbrown085 so I will take it :)

**Comment by CucumisSativus** [comment]
Hey @satansk are you still working on it? If not would you mind me taking it from you?

**Comment by satansk** [comment]
@CucumisSativus I almost forget about this issue, but I will continue to work on this :)

**Comment by CucumisSativus** [comment]
@satansk so, good luck with it! :)

**Comment by wojciechUrbanski** [comment]
Hey @satansk, are You working on that issue? If not, can I take it?

**Comment by satansk** [comment]
@wojciechUrbanski go ahead, it's yours :)

**Comment by barambani** [comment]
Happy to add it if no one is doing it.

**Comment by barambani** [comment]
This can be closed now. Thanks.
