### ISSUE TITLE
Variance

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#2310]
Do you know why `Validated` is covariant on its two type (like `Either`) but `EitherT` is invariant?

```scala
sealed abstract class Validated[+E, +A]
final case class EitherT[F[_], A, B]
```

**Comment by johnynek** [comment]
Wouldn’t it require `F[+_]`? Which limits us. Note Functor has widen and Bifunctor has leftWiden which you can use like explicit covariance.

**Comment by julien-truffaut** [comment]
@johnynek you're probably right, make sense. I guess it is just annoying that we have to treat `Either` and `EitherT` differently in a for comprehension. It doesn't help that intellij doesn't recognize `leftWiden` (but that's another issue).

**Comment by henricook** [comment]
Has anyone got any clue why IntelliJ doesn't recognise leftWiden?
