### ISSUE TITLE
Apply, Applicative, Monad for contravariant functor?

### ISSUE THREAD

**Issue by davidrpugh** [typelevel/cats#2324]
I have the following trait...

    import cats._
    import cats.implicits._

    trait Preference[-A] {
      self =>
    
      def compare(a1: A, a2: A): Int
    
      final def ordering[A1 <: A]: Ordering[A1] = {
        new Ordering[A1] {
          def compare(a1: A1, a2: A1): Int = {
            self.compare(a1, a2)
          }
        }
      }
    
    }
    
    
    object Preference {
      
      implicit val contravariant: Contravariant[Preference] = {
        new Contravariant[Preference] {
          def contramap[A, B](fa: Preference[A])(f: B => A): Preference[B] = {
            new Preference[B] {
              def compare(b1: B, b2: B): Int = {
                fa.compare(f(b1), f(b2))
              }
            }
          }
        }
      }
    }

I am learning FP and would like to explore definitions of `Apply`, `Applicative`, and possibly even `Monad` instances for this trait but all of these type classes are extensions of `Functor`. Do versions of these type classes exist in Cats for contravariant functors? If these type classes have not yet been implemented, I would be happy to contribute them!

**Comment by diesalbla** [comment]
@drbild The contravariant counterpart of `Applicative` is called a `Divisible`. A Haskell documentation can be seen [here](http://hackage.haskell.org/package/contravariant-1.5/docs/Data-Functor-Contravariant-Divisible.html#g:1)

A _covariant_ functor carries the intuition of being like a function that _produces_ a type of outputs. 
A contravariant functor, instead, carries the intuition of being like a function that **consumes** an input `A`. Thus, if an _applicative_ covariant functor would join two computations `F[A]` and `F[B]` into a tuple-computation `F[(A,B)]`, a _divisible_ contravariant functor would be able to split the input `(A,B)` between a computation that consumes the `A` and one that consumes the `B`.

**Comment by LukaJCB** [comment]
We already have these type classes, they're named `ContravariantSemigroupal` and `ContravariantMonoidal` :)

**Comment by diesalbla** [comment]
It seems this was already done, or suggested, in https://github.com/typelevel/cats/issues/1935

**Comment by davidrpugh** [comment]
@diesalbla Thanks for the link. I also posted this on [SO](https://stackoverflow.com/questions/51306354/apply-applicative-monad-etc-for-contravariant-functors-in-cats).  The answer there suggested that `ContraVariantMonoidal` is cats equivalent of `Divisible`. 

I am still confused though because `ContravariantMonoidal` and `ContravariantSemigroupal` type classes define a `product[A,B](fa: F[A, fb:F[B]): F[(A,B)]` method which does not seem to be splitting "an input `(A,B)` into a computation that consumes the `A` and one that consumes the `B`."

**Comment by LukaJCB** [comment]
`product` is inherited by the invariant version of `Semigroupal`. If you want to "an input (A,B) into a computation that consumes the A and one that consumes the B." You'll need to combine ,`product` with `contramap`. For `Apply` that is `ap` or `map2` or `mapN`, for `ContravariantSemigroupal` that's `contramap2` or `contramapN` :)

**Comment by davidrpugh** [comment]
Right. So I guess I just need to read through the Haskell docs for `Divisible` and look through the code for `ContravariantSemigroupal` and `ContravariantMondoidal` to understand how the pieces fit together.  

In sum, contravariant versions of `Apply` and `Applicative` already exist and there is no contravariant equivalent of `Monad`.

**Comment by diesalbla** [comment]
Here is a discussion about the subject: https://twitter.com/mpilquist/status/431122935081078784

**Comment by LukaJCB** [comment]
Yup Contravariant Monad doesn't really make sense. If you think about a contraFlatMap:
```scala
def contraFlatMap(fa: F[A])(f: F[B] => A): F[B]
```
You realize that implementing something like this is practically impossible for almost all types. 
With that said, I'm going to close this issue now, unless someone has any other concerns :)
