### ISSUE TITLE
List of EitherT sequence does not work

### ISSUE THREAD

**Issue by gbersac** [typelevel/cats#2336]
The following code :

```scala
import cats.data.EitherT
val eitherTList: List[EitherT[Future, MyErrorType, Unit]] = ???
import cats.implicits._
eitherTList.sequence
```

Produce the following error when compiling : 

```
[error] /Users/gbe/projects/up-financeur/sdi/order/abandonedCommandsWorker/src/main/scala/abandonnedCommandsProcessing/AbandonedCommandsProcessing.scala:41:19: could not find implicit value for evidence parameter of type cats.Applicative[G]
[error]       eitherTList.sequence
[error]                   ^
```

Adding `import cats._` and `import cats.data._` does not solve the problem. Unlike what the doc state, it is not enough to have all this import to make cats working. Can you fix this issue please ?

**Comment by LukaJCB** [comment]
Do you have an implicit execution context in scope?

**Comment by gbersac** [comment]
@LukaJCB What yes I do.

**Comment by LukaJCB** [comment]
Partial unification enabled?

**Comment by LukaJCB** [comment]
This compiles fine for me:

```scala
import cats.data.EitherT
import cats.implicits._
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

type MyErrorType = String
val eitherTList: List[EitherT[Future, MyErrorType, Unit]] =
  List.empty

val result: EitherT[Future, MyErrorType, List[Unit]] = 
  eitherTList.sequence
```

And also on [scalafiddle](https://scalafiddle.io/sf/yaJbVC2/0)

**Comment by djspiewak** [comment]
This definitely sounds like you're missing partial unification. Note the first part of [this section](https://github.com/typelevel/cats#getting-started) in the readme.

**Comment by kubukoz** [comment]
@gbersac did you get it to work? Can we close this issue?

**Comment by gbersac** [comment]
@kubukoz I can't add another sbt plugin for my project without asking for permission... I can't implement the solution, but let's close the issue.

**Comment by LukaJCB** [comment]
@gbersac You don't need to add a plugin if you're on scala version 2.12.x or 2.11.9 or later :)
Just add the `-Ypartial-unification` compiler flag.

**Comment by gbersac** [comment]
It's right, my @LukaJCB , it was already set on the project, and I still had the error.

**Comment by LukaJCB** [comment]
What Scala version are you on @gbersac?

**Comment by kubukoz** [comment]
Also note that it's fairly common to make a mistake and do `scalacOptions += ...` instead of `scalacOptions in ThisBuild += ...` if you have a multi-project build.

But yeah, it all depends on the Scala version.

**Comment by djspiewak** [comment]
It's definitely an SBT misconfiguration. If it was a Scala version mismatch then there would have been a different error complaining about the unrecognized option.

@gbersac You can do `show scalacOptions` to see whether or not it has been correctly set. More than likely, you need to do a `in ThisBuild` on your setting.

**Comment by gbersac** [comment]
@LukaJCB `scalaVersion := "2.12.4-bin-typelevel-4"`. De plus, après vérification l'option `"-Ypartial-unification"` est bien activée. Ceci dit, je ne savais pas que l'on utilisait le compilateur de typelevel. Mais ce n'est censé être qu'une extension du compilateur lightben.

**Comment by gbersac** [comment]
@LukaJCB the version of my scala compiler is `scalaVersion := "2.12.4-bin-typelevel-4"`. This is an alternative compiler (I didn't knew we were using an alternative compiler on the project 😱 ). But since the typelevel compiler is just an extension of the lightbend one, that shouldn't be an issue.

@djspiewak thanks, I didn't knew about the `show scalacOptions` commands. On the project I tried to implement the `EitherT.sequence`, the `-Ypartial-unification` was present.
