### ISSUE TITLE
Add `Enum` type class

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#2342]

**Comment by Michaelt293** [comment]
See https://github.com/typelevel/cats/issues/1536#issuecomment-416027544

**Comment by johnynek** [comment]
I have taken a stab at this before with mixed success:

https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/Successible.scala

Some challenges:
1. what if you are countable, but not bounded? e.g. BigInteger
2. what if you are upper bounded but not lower bounded?

If you have something unbounded, you want `def next(a: A): A`, but if you are bounded, you want `def next(a: A): Option[A]`.

As for a law, I think it is something like: `a < next(a)` and there is nothing in between: `forAll { (a, b) => if (a < b) (b == next(a) || next(a) < b) else true`

**Comment by sideeffffect** [comment]
this ticket can be closed
cc @LukaJCB @travisbrown

**Comment by LukaJCB** [comment]
good call, thanks @sideeffffect!
