### ISSUE TITLE
Add NEM[K, V] => NEL[(K, V)] and vice versa, NEL#toNes

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#2346]

**Comment by denisrosca** [comment]
Wouldn't `NEL[(K, V)]` have to change to `NEM[K, NEL[V]]`? Or should the transformation require `V: Semigroup`?

**Comment by kubukoz** [comment]
I think that would resemble `groupBy` or something like that.

What I meant in the issue was equivalents to stdlib's `Map#toList` and `List#toMap` :)

Also, adding `NEL#toNes` to the issue as I've had a few usecases for it recently too.

**Comment by CucumisSativus** [comment]
Guys, I'd like to work on this if its still relevant :)

**Comment by LukaJCB** [comment]
@CucumisSativus Go right ahead :)

**Comment by calvinbrown085** [comment]
@kubukoz @CucumisSativus Can we close this? Looks like the PR has been merged

**Comment by CucumisSativus** [comment]
@calvinbrown085 I split it into 3 PR to make reviews easier. One is merged. The second is awaiting second confirmation https://github.com/typelevel/cats/pull/2541 and my third is waiting for the second to be merged :)

**Comment by calvinbrown085** [comment]
Ah fair enough :)

**Comment by CucumisSativus** [comment]
Okay, issue can be closed. All pull requests are merged

**Comment by kubukoz** [comment]
Closing ;) thanks!
