### ISSUE TITLE
Add combineAllOption to Foldable

### ISSUE THREAD

**Issue by jrduncans** [typelevel/cats#2363]
`combineAllOption` should be added to `Foldable` as a parallel to `combineAll` for `Semigroup` instead of `Monoid`

**Comment by johnynek** [comment]
Seems like a nice PR but will have to be done with careful binary compatibility concerns.

**Comment by LLCampos** [comment]
I think this one can be closed? https://github.com/typelevel/cats/pull/2380 was already merged. :)

**Comment by johnynek** [comment]
yeah, I think so, although, I noticed that PR didn't override toIterable for the common collections (List, Vector, SortedSet, SortedMap could all just return themselves).
