### ISSUE TITLE
Making Eq/Order/Hash contravariant?

### ISSUE THREAD

**Issue by ctongfei** [typelevel/cats#2370]
Since https://github.com/scala/bug/issues/2509 is now fixed by https://github.com/scala/scala/pull/6037, should `Eq`/`Order`/`Hash` be contravariant on its type parameter in a later version of Cats?

**Comment by johnynek** [comment]
This is behind a flag even in 2.13. I think it will be a while before we can leverage this.

**Comment by ctongfei** [comment]
Yeah -- something along Cats 2.0 ?

**Comment by kailuowang** [comment]
Might be even later. 2.0 is likely to be mainly a continuation of 1.x on Scala 2.12, 3.0 is unlikely to drop 2.12 support. So maybe 4.0?
In the meantime, kittens provides auto instance derivation for these type classes, might help you a bit.

**Comment by ctongfei** [comment]
Got it. Let's revisit this for Cats 4.0 :-)
