### ISSUE TITLE
Prepare for 2.13.0-M5

### ISSUE THREAD

**Issue by ghost** [typelevel/cats#2389]

**Comment by BennyHill** [comment]
2.13.0-M5 is now staged at https://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-compiler/2.13.0-M5/ 

Any ideas on the timelines for this yet, please?

**Comment by SethTisue** [comment]
ScalaCheck and ScalaTest have published, but for JVM only at the moment, no Scala.js yet. but that should be enough for someone to at least work on this and make sure everything else is ready

in the Scala 2.13 community build at 
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1511/consoleFull I'm seeing:

```
[cats] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.15/project-builds/cats-aa7183ee3d07eb22bea0ce915cd291c46c2f3147/tests/src/test/scala/cats/tests/RepresentableSuite.scala:63:58: could not find implicit value for parameter iso: cats.laws.discipline.SemigroupalTests.Isomorphisms[[β$5$]String => β$5$]
[cats] [error]     checkAll("String => ?", MonadTests[String => ?].monad[String, String, String])
[cats] [error]                                                          ^
```

**Comment by SethTisue** [comment]
> ScalaCheck and ScalaTest have published, but for JVM only at the moment

they're now both available for JS too

**Comment by SethTisue** [comment]
is there anything any of us can do to help move this along...?

**Comment by SethTisue** [comment]
one place where help is needed is in the typelevel/catalysts repo. see discussion beginning at https://gitter.im/typelevel/general?at=5bd369fabbdc0b2505a4d5d2

**Comment by tpolecat** [comment]
Catalysts is only used for `TypeTagM` in one file, and `Platform.isJVM`/`.isJS` here and there in the tests. Is it worth managing a dependency just for these two things?

**Comment by travisbrown** [comment]
@tpolecat +1 to getting rid of the Catalysts dependency.

**Comment by Alistair-Johnson** [comment]
Looks like this should be closed now?
