### ISSUE TITLE
Update AUTHORS.MD

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2391]
We haven't got the time to update the authors list since 1.1.0 release. We need to go through the 1.2.0 release notes and update the list with new contributors.

**Comment by leusgalvan** [comment]
Can I take this? If I understand correctly I should just go to https://github.com/typelevel/cats/releases/tag/v1.2.0 and add the names to AUTHORS.md keeping it sorted and duplicates-free :smile:

**Comment by LukaJCB** [comment]
Feel free, and thank you! :)
