### ISSUE TITLE
Replace all usage of the list Monoid in the docs with the chain Monoid

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2429]
Using `Chain`s Monoid instead of `List`s can give us an enormous performance boost. We should encourage our users to use it instead of list in many cases, such as, `Validated`, `Ior`, `Writer` or `Const`.

**Comment by jan0sch** [comment]
Do you have a small example? Then I'll try to do this.

**Comment by LukaJCB** [comment]
For example, you could start by using `NonEmptyChain` instead of `NonEmptyList` for the `Ior` docs :) https://typelevel.org/cats/datatypes/ior.html
