### ISSUE TITLE
Add Split documentation

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#243]
At least a ScalaDoc. Possibly a markdown file for the typeclasses section of the website.

**Comment by hardvain** [comment]
Hi @ceedubs , What do you mean atleast typeclass section of the website? A documentation for how typeclass pattern works or something else? I am beginning to learn cats and would love to contribute with some documentation.

**Comment by LLCampos** [comment]
`Split` does not exist anymore, so this one can be closed?
