### ISSUE TITLE
The docs require login

### ISSUE THREAD

**Issue by pferrel** [typelevel/cats#2436]
Why do I have to login to read the docs??? You may think you are being clever by running the example code but why not just show the result so I don't have to give you access to my github info. Remember MS owns them now.

**Comment by tpolecat** [comment]
Where are you seeing this? I can see everything in an anonymous browser session.

**Comment by BennyHill** [comment]
Looks like this is from another site.

https://www.scala-exercises.org/cats/semigroup

**Comment by pferrel** [comment]
Oops, my bad. Sorry for not reading Google more carefully.

**Comment by BennyHill** [comment]
Np...have fun!!
