### ISSUE TITLE
Add `count` method to Foldable 

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2447]
I'm thinking of this one here:

```scala
def count[A](p: A => Boolean): Long
```

We could also provide these specialized for the various collections we have :)

**Comment by johnynek** [comment]
`count(f) = foldMap { if (f(_)) 1 else 0 }`

I think we need commutative foldMap, which we could use here and get probably all of the performance wins of a specialized function.

**Comment by johnynek** [comment]
+1 to use Long, +1 to put it on UnorderedFoldable.

**Comment by johnynek** [comment]
PS: we do have a commutative foldMap for those following along: UnorderedFoldable.unorderedFoldMap.

**Comment by leusgalvan** [comment]
Could I take this?

**Comment by LukaJCB** [comment]
@leusgalvan Sure! Go right ahead :)
