### ISSUE TITLE
use an abstract type member for ApplicativeError's error type

### ISSUE THREAD

**Issue by mberndt123** [typelevel/cats#2468]
Hi,

I stumbled upon an interesting problem recently. As a motivating example, consider `Option`'s toRight method. cats also adds a `toValid` method. Both of these are clearly useful, and they can be easily generalized to arbitrary ApplicativeError instances:
```scala
def orRaise[F[_], A, E](opt: Option[A], e: => E)(implicit F: ApplicativeError[F, E]): F[A] =
  opt.map(F.pure).getOrElse(F.raiseError(e))
```
But this function is quite hard to use because the type parameters need to be specified manually in all but the most trivial cases.

It's probably not possible to infer F, but perhaps the other two type parameters can be inferred? The typical pattern would be something like this:
```scala
class OrRaisePartiallyApplied[F[_]] {
  def apply[A, E](opt: Option[A], e: => E)(implicit F: ApplicativeError[F, E]): F[A] =
    opt.map(F.pure).getOrElse(F.raiseError(e))
}
def orRaise[F[_]] = new OrRaisePartiallyApplied[F]
```
But this interacts badly with subtyping:
```scala
import cats.effect.IO
orRaise[IO](Option(42), new Exception)
// doesn't compile:
// Compiler infers E as Exception,
// but there is only an implicit of type ApplicativeError[IO, Throwable]
```
The only way I could find to fix this problem is to use a type member for the error type: 
```scala
trait ApplicativeFail[F[_]] {
  type Error
  def raiseError[A](e: Error): F[A]
  // … etc
}

object ApplicativeFail {
  type Aux[F[_], E] = ApplicativeFail[F] { type Error = E }
}
```
The function can then be implemented like this:
```scala
class OrRaisePartiallyApplied[F[_]] {
  def apply[A, E, FE](opt: Option[A], e: => E)(implicit F: ApplicativeFail.Aux[F, E], ev: E <:< FE): F[A] =
    opt.map(F.pure).getOrElse(F.raiseError(e))
}
def orRaise[F[_]] = new OrRaisePartiallyApplied[F]
```
So is this a better way to encode the ApplicativeError type class? Thoughts?

**Comment by mberndt123** [comment]
Haha, interesting to see that somebody else already had the idea just a few days ago.

1. The Aux pattern is needed if the error type is relevant. I think that's OK

1. The error type might be ambiguous for something like `EitherT[IO, E, A]`. I personally think that having two `ApplicativeError` instances in the transformer stack is a bit of a code smell, because then you can throw errors on different levels of the stack and it becomes difficult to figure out which errors are being handled and which ones aren't. This is especially true for IO as recovering from an error there will still only give you an IO, so you can't tell from the type which errors have been handled.

So I would still argue that the improved type inference would be worth it in the ApplicativeError case...

**Comment by marcin-rzeznicki** [comment]
Let me point out the issue I raised some time ago #2443 . There are some concerns raised by @johnynek, but maybe this is a solution. WDYT?

**Comment by mberndt123** [comment]
fwiw, I found a simpler way to implement my motivating example that doesn't require this new ApplicativeError encoding: just pass an implicit ApplicativeError[F, _ <: E]. I'm always a bit sceptical about wildcard types, but they seem to be the right thing in this case. My proposal may have other advantages as you suggested, but it's not necessary to implement my motivating example.

**Comment by mberndt123** [comment]
Ugh, and now I realized that [it actually already exists](https://github.com/typelevel/cats/blob/caa54cb221b7b6fb4a28a8f0b6650f744376bfc5/core/src/main/scala/cats/syntax/option.scala#L189). So I'll close this here.
