### ISSUE TITLE
Cats logo

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2486]
The current log of cats is cute but a little bit out of place in the typelevel project family. I don't know its history and our commitment to it. Will us be open to change it, maybe to a more modern design with geometry shapes, more conforming to the typelevel and scala theme? 

@thoefer designed one in #1807, see below: the one in the hexagon on the left.
![cats_friendly_big](https://user-images.githubusercontent.com/202410/44628798-b341b480-a947-11e8-966f-ce1e121d78ad.png)

 Several of us like it. What do you think?

**Comment by kailuowang** [comment]
page @non @ceedubs @tpolecat @adelbertc @rossabaker @djspiewak @johnynek @milessabin @LukaJCB @mpilquist @fthomas and all cats contributors.

**Comment by longcao** [comment]
I like the previous pixelated cat a bit more personally (in my head it's closely associated with the brand, so to speak), but I think this version could be made to work.

Maybe the original red from https://github.com/typelevel/cats/blob/f2850487732a185572b8a1752a24f13b875176d3/docs/src/main/resources/microsite/img/cats-logo.png? Keeping in mind that the original logo has a very slight gradient on it.

**Comment by alexandru** [comment]
Just one more thought for why the color of a "Cats friendly" logo should be less strident ... because it's going to be shown near other logos that may not share a similar color palette. 

See for example [Monix](https://github.com/monix/monix#monix) which is OK near the "Typelevel red", because it's a cooler red, but would probably not be OK near this strident red:

![image](https://user-images.githubusercontent.com/11753/45432423-8c5ae080-b6b2-11e8-935f-ee1345908736.png)

**Comment by rossabaker** [comment]
I like the Cats friendly graphic but I prefer the pixelated cat.  Even after realizing just now that the cat is asymmetrical.

Agree that the abstract cat could make a fine secondary logo.  favicon could be one  ideal context for it.

**Comment by adelbertc** [comment]
I like the original pixelated cats, probably for most things except, like @non mentioned, in maybe like really small sizes or something where due to the pixellation style it won't work out.

**Comment by kailuowang** [comment]
Looks like that we reached a consensus that we'd like to keep the original pixelated cat for logo. If we can create a smaller, i.e. more pixelated, version for smaller images it would be great too. @thoefer what do you think?

**Comment by thoefer** [comment]
@non Do you have your pixelated cat as vector image somewhere?

**Comment by PeterPerhac** [comment]
I must say I **love** the pixelated cat logo. Perfect for cross-stitching 
![cats](https://user-images.githubusercontent.com/1763911/45626322-25a93e80-ba87-11e8-82f0-a512e78394d9.jpg) (but, yeah, it's annoyingly asymmetrical & slightly off-balance on the hexagonal background)

**Comment by alexandru** [comment]
There's beauty in asymmetry 😛

**Comment by kailuowang** [comment]
I think the decision was made to keep the original logo. closing for  now .
