### ISSUE TITLE
eqv alias for ===?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#2513]
Scalatest has its own `===` method, and it can get in the way when trying to use the Cats `===` in a unit test.

I thought that I could get around this by using `eqv` instead of `===`, but since cats-kernel doesn't use simulacrum, the `Eq` syntax is manually written and doesn't include the `eqv` extension. Should we add `eqv` as an alias for `===` on `EqOps`? Since the class is final, I think that this would be binary compatible.

**Comment by binkabir** [comment]
I have added the `eqv` and `neqv`  aliases which simply uses the `Eq` typeclass
