### ISSUE TITLE
Add FiniteDuration instances

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2517]
We currently have instances for `Duration` only, which means that you can use `FiniteDuration` with it, but must upcast it, which can be annoying:

```scala
3.minutes |+| 3.minutes // Fails to compile because `|+|` is not a member of `FiniteDuration`.
```

**Comment by satansk** [comment]
I will do it :)

**Comment by adelbertc** [comment]
I use `FiniteDuration`s all the time, `Duration`s not so much 💯

**Comment by calvinbrown085** [comment]
@satansk If you're still working on this feel free to keep going :) Can we just reuse https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/duration.scala

With `FiniteDuration` instead of `Duration?

Where do these instances go? @codecentric

Thanks!

**Comment by LukaJCB** [comment]
Yes the instances should be exactly the same :) and you should be able to place them analogously to where the duration instances are placed

**Comment by calvinbrown085** [comment]
I opened a PR here, @satansk if you wanted to work on this i'm more than happy to close it!

**Comment by satansk** [comment]
@calvinbrown085 go ahead :)

I'm busy for a release in company, and I was planning to work on this on my 7 days vocation one day later. Since you already have made a PR, just keep on working on it.

**Comment by calvinbrown085** [comment]
@satansk Sounds good! Just making sure I don't trample on anyone :)
