### ISSUE TITLE
Link to the new cats-friendly badge 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2529]
Add to README the links to the newly added "Cats Friendly" badges (see PR below) so that people can start to use. 

https://github.com/typelevel/cats/pull/2524

The urls will be `https://typelevel.org/cats/img/XXXX.svg`

**Comment by calvinbrown085** [comment]
@kailuowang Hi! I'm happy to pick this one up, is there a specific place in the README https://github.com/typelevel/cats#libraries-with-more-specific-uses
maybe at the bottom of this page?

`The full-size Cats logo is available for use for Cats related projects, contents, souvenirs, etc.`

Possibly underneath this? I can create a quick PR to see what it looks like

**Comment by rossabaker** [comment]
I did it for http4s [like this](https://github.com/http4s/http4s/blob/4684dea66213a45964bf7314e35741aad05cdc52/README.md).  I'll bet it can be done better, but there's some prior art.

**Comment by calvinbrown085** [comment]
Oh nice! I'm trying to think of a good way to advertise to other repositories that the badge is available? 

I'm still thinking about that section I mentioned. I might be off in what we are trying to do here though. Happy to discuss!

**Comment by ceedubs** [comment]
Resolved by #2554
