### ISSUE TITLE
Missing Contravariant instance for OptionT

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#2545]
Currently Cats provides a `ContravariantMonoidal` instance for `OptionT` if its `F` has one, but we don't seem to provide a `Contravariant` instance if `F` has a `Contravariant` instance that doesn't form a `ContravariantMonoidal`. This should be possible in the same way that you can currently get a similar instance for `Nested`. See below:

```scala
scala> import cats._, cats.implicits._, cats.data._
import cats._
import cats.implicits._
import cats.data._

scala> Contravariant[Nested[Show, Option, ?]]
res0: cats.Contravariant[[γ$0$]cats.data.Nested[cats.Show,Option,γ$0$]] = cats.data.NestedInstances2$$anon$18@746c9e1c                                                                                     

scala> Contravariant[OptionT[Show, ?]]
<console>:21: error: could not find implicit value for parameter instance: cats.Contravariant[[β$0$]cats.data.OptionT[cats.Show,β$0$]]                                                                     
       Contravariant[OptionT[Show, ?]]
                    ^
```

**Comment by ceedubs** [comment]
I think that the same might be true for `Invariant`.

**Comment by barambani** [comment]
if it's not taken I can have a look

**Comment by barambani** [comment]
I will makes suer Mima is happy 😄 , thanks a lot @ceedubs . Also I see that `Invariant` is missing somewhere else (like WriterT). In case I'll try adding it there as well.
