### ISSUE TITLE
Somewhat annoying to get at rethrow syntax due to invariance

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#2561]
`MonadError` is invariant in `E`, which is problematic in turn because it means that `catsSyntaxMonadErrorRethrow` will not infer on `Either[E, A]` where `E <: Throwable`, which is *vastly* far and away the most common case. For example, if you have an expression that produces `F[Either[RuntimeException, A]]`, you might reasonably expect that `rethrow` would be available syntax on such a value (at least, I did). It won't work though, and it's quite difficult to tease out why this is the case.

We can either make `MonadError` contravariant in `E` (which I believe would cause a cascade of problematic changes, so I don't recommend it), or we can loosen the constraints on `catsSyntaxMonadErrorRethrow`. Something like:

```scala
implicit final def catsSyntaxMonadErrorRethrow[F[_], E2, E1 <: E2, A](fea: F[Either[E1, A]])(implicit F: MonadError[F, E2]): MonadErrorRethrowOps[F, E2, A]
```

Or the latter, which is likely to infer slightly better:

```scala
implicit final def catsSyntaxMonadErrorRethrow[F[_], E1, E2, A](fea: F[Either[E1, A]])(implicit F: MonadError[F, E2], ev: E1 <~< E2): MonadErrorRethrowOps[F, E2, A]
```

**Comment by LukaJCB** [comment]
Closed by #2880
