### ISSUE TITLE
cats.evidence.Is and Scala 2.13

### ISSUE THREAD

**Issue by durban** [typelevel/cats#2569]
As far as I can tell, [`=:=` in Scala 2.13](https://github.com/scala/scala/blob/v2.13.0-M5/src/library/scala/Predef.scala#L662) is very similar (identical?) in functionality to `cats.evidence.Is`. Would it make sense to revisit the decision regarding `Is.unsafeFromPredef`?

- One thing is the `unsafe` prefix. Is it really unsafe? Especially now that in 2.13, it seems possible to write `(A =:= B) => (A Is B)` without any `asInstanceOf`.
- The other (probably more important) is implicitness: *if* they're equivalent, maybe having an `Is` implicitly available when `=:=` is, would not be so bad.

**Comment by johnynek** [comment]
I think unsafe is the wrong prefix there. It is perfectly safe (as the PR to scala 2.13 showed).

Maybe the best thing is to add a new method without unsafe and mark the unsafe as deprecated. The new method can be an implicit from `=:=` possibly at a lower priority to avoid conflicts for the reflexive case.

The same is true for `As`.
