### ISSUE TITLE
Missing `Chain#distinct` and `NonEmptyChain#distinct`

### ISSUE THREAD

**Issue by fmsbeekmans** [typelevel/cats#2575]
When converting some code that was using `NonEmptyList` to `NonEmptyChain` I noticed `distinct` wasn't implemented.

I've started adding `Chain#distinct` and `NonEmptyChain#distinct` [here](https://github.com/fmsbeekmans/cats/tree/chain-distinct).

**Comment by fmsbeekmans** [comment]
Relates to #2539

**Comment by fmsbeekmans** [comment]
#2579

**Comment by ceedubs** [comment]
I believe this was resolved by #2579.
