### ISSUE TITLE
Does a purely functional set based on Eq belong in cats?

### ISSUE THREAD

**Issue by nasadorian** [typelevel/cats#2593]
I noticed that the `distinct` implementations in cats data types are based on `Order` and using Scala's `TreeSet`. But what about a purely functional set based on `Eq`? 

Upsides: 
* Intuitively more performant with constant time lookup and insert vs logarithmic for TreeSet
* Small memory footprint
* Uses Eq
* Could give rise to a `Predicate` data type as a side effect, similar to the one in Haskell docs (http://hackage.haskell.org/package/contravariant-1.5/docs/Data-Functor-Contravariant.html)

Downsides:
* Ironically, could not derive an `Eq` instance for the set itself since it's based on a function
* No way to inspect elements, it is only optimized for checking containment
* No way to check size

I wrote up a basic implementation using just a case class and `Eq`. It should be straightforward to rewrite it in terms of `Invariant` instead. Cheers!

https://gist.github.com/nasadorian/8f10cc1f89225a932238026cf46e57a7

**Comment by kailuowang** [comment]
Absolutely,  probably in the external cats-collections module https://github.com/typelevel/cats-collections

**Comment by nasadorian** [comment]
Ah makes sense @kailuowang. I can close this and reopen there. Definitely looking for some feedback from folks on what typeclasses to use for this. Any insight on reducing GC overhead too, because the add calls are essentially map operations that copy the class over and over.
