### ISSUE TITLE
Typeclass similar to scalaz Alt or haskell Alternative

### ISSUE THREAD

**Issue by kag0** [typelevel/cats#2595]
It would be nice to have a type class that given two values, returns either the first defined value.

like
```scala
trait Alt[A] {
  def orElse(one: A, two: A): A
}
```

with behavior like
```scala 
def optionAlt[A] = new Alt[Option[A]] {
  def orElse(one: Option[A], two: Option[A]) = if(one.isDefined) one else two
}

def listAlt[A] = new Alt[List[A]] {
  def orElse(one: List[A], two: List[A]) = one match {
    case Nil => two
    case nel => nel
  }
}
```

Lots of types already have `orElse` methods defined (including `Option`), and it would be nice to start building on those.

**Comment by DennisVDB** [comment]
Wouldn't that be `SemigroupK`? https://github.com/typelevel/cats/blob/2e781ae32fc35fee49f5b4f8b8cc675db3ed7eee/core/src/main/scala/cats/SemigroupK.scala

In case of an instance for `Option[A]` as we don't know what `A` you could only implement it with the behavior you showed.

**Comment by rossabaker** [comment]
An `orElse` typeclass is proposed in #2536.

**Comment by kag0** [comment]
@DennisVDB `SemigroupK` does exhibit that behavior for `Option`, but it still combines things like `List`. I updated the example to highlight how behavior would be different.

@rossabaker Don't know how I missed that. I'll close this in favor of #2536.
