### ISSUE TITLE
Re-enable unit test that was disabled in pr #2589

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/cats#2601]
In #2589 a unit test was disabled as a temporary workaround for scala 2.13-M5, which should eventually be re-enabled.

**Comment by erikerlandson** [comment]
crossref https://github.com/scala/bug/issues/11242

**Comment by ceedubs** [comment]
Thanks for creating this @erikerlandson!

I don't know why I didn't just create it myself instead of suggesting that it should be created. In my defense it's not yet 7am for me :P
