### ISSUE TITLE
Breaking change: NestedSyntax collides with Optionable in Scalatest causing codebases to no longer compile tests.

### ISSUE THREAD

**Issue by coltfred** [typelevel/cats#2613]
If you upgrade from cats 1.1.0 to 1.2+ and you use `OptionValues` from Scalatest you'll end up with errors like the following.

```
src/test/scala/com/ironcorelabs/admin/CookiesTest.scala:39: type mismatch;
 found   : gottenCookie.type (with underlying type Option[scodec.bits.ByteVector])
 required: ?{def value: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method catsSyntaxNestedId in trait NestedSyntax of type [F[_], G[_], A](value: F[G[A]])cats.syntax.NestedIdOps[F,G,A]
 and method convertOptionToValuable in trait OptionValues of type [T](opt: Option[T])(implicit pos: org.scalactic.source.Position)CookiesTest.this.Valuable[T]
 are possible conversion functions from gottenCookie.type to ?{def value: ?}
      gottenCookie.value shouldBe Password(hexBytes.value)
```

This is caused by the fact that `.value` is syntax added to the `Option` type as well as the NestedSyntax conversion are at the same implicit level. I hadn't upgraded my cats version in a while so I didn't notice this until now, but it's a *huge* PITA. It means people might end up with cats all of a sudden not working for their project.

**Comment by kailuowang** [comment]
related issue https://github.com/typelevel/cats/issues/2514

**Comment by coltfred** [comment]
@kailuowang Should we close these on merge or when the release happens?

**Comment by kailuowang** [comment]
yeah we can close this one.
