### ISSUE TITLE
Fix InvariantMonoidal Laws

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2631]
InvariantMonoidal should have `InvariantSemigroupal` as its parent in its ruleset. 
Furthermore the associativity law should be moved to `InvariantSemigroupalLaws`

**Comment by wojciechUrbanski** [comment]
I'd like to take that one if that's ok

**Comment by sh0hei** [comment]
Fixed by https://github.com/typelevel/cats/pull/2711 ?

**Comment by LukaJCB** [comment]
Indeed :)
