### ISSUE TITLE
Add support for Oracle Flight Recorder

### ISSUE THREAD

**Issue by Alistair-Johnson** [typelevel/cats#2633]
The `bench` project currently uses [jmh](https://github.com/ktoso/sbt-jmh) for benchmarks, but the plugin also supports [Oracle Flight Recorder (OFR)](https://github.com/ktoso/sbt-jmh#using-oracle-flight-recorder).

Whilst looking at OOM's in the core laws, I am reminded that one of the better ways to investigate such issue is by using the OFR.

The suggestion is we add some support for interactive use for this in the build (and not just for bench), such as some nice presets, aliases and the like. The rational is that the easier it is to use, the more likely folk will use it.

**Comment by djspiewak** [comment]
I'm a little confused by this. JMH *itself* supports JFR integration, and you're perfectly free to use it when running the benchmarks in `bench`. I actually do this quite frequently on other projects. What is it you think should be added?
