### ISSUE TITLE
Backwards and Reverse

### ISSUE THREAD

**Issue by dcastro** [typelevel/cats#2638]
I was wondering what the maintainers think about adding something like Haskell's [`Control.Applicative.Backwards`][back] and [`Data.Functor.Reverse`][rev] to cats.
Or maybe something like this already exists in cats and I missed it.

### `Backwards`

`Backwards` is a newtype wrapper around any `f a`.
If that `f` has an instance for `Applicative`, then so does `Backwards f`.

With good ol' applicative composition, this code will print "1" and "2", in that order.
```hs
data Test = Test Int String
  deriving Show

let x = do putStrLn "1"; pure 1 :: IO Int
let y = do putStrLn "2"; pure "2" :: IO String

Test <$> x <*> y
```

But by wrapping the effects in `Backwards`, "2" is printed before "1":

```hs
forwards $ Test <$> Backwards x <*> Backwards y
```

### `Reverse`

`Reverse` is a newtype wrapper around any `f a`.
If that `f` has an instance for `Foldable`, then so does `Reverse f`.
If that `f` has an instance for `Traversable`, then so does `Reverse f`.

Good ol' traversal will apply the effects to each element of a list, going left to right:

```hs
λ> traverse print [1,2,3]
1
2
3
```

But by wrapping the `f a` in `Reverse`, the effects of the traversal are observed in right to left fashion.

```hs
traverse print (Reverse [1,2,3])
3
2
1
```

If this is deemed a good fit for cats, I wouldn't mind giving it a go.

 [back]: https://hackage.haskell.org/package/transformers-0.5.5.0/docs/Control-Applicative-Backwards.html
 [rev]: https://hackage.haskell.org/package/transformers-0.5.5.0/docs/Data-Functor-Reverse.html

**Comment by chuwy** [comment]
Regardless of whether this should belong to cats core or not, I would like to have it in Scala.

**Comment by LukaJCB** [comment]
We have `newts` for these kinds of things. But maybe with #1800 and opaque types on the horizon, it might make sense to rethink the separation and consider moving them into the cats repo. :)

**Comment by dcastro** [comment]
@LukaJCB So, should this go in `newts` for now, and maybe be moved into cats later?
