### ISSUE TITLE
Make ListWrapper part of cats-testkit

### ISSUE THREAD

**Issue by ArturGajowy** [typelevel/cats#2645]
All the reasons for ListWrapper's existence and usefulness in cats tests apply to any laws tests users might want to reuse for their own instances. Would you accept a PR moving the class to cats-testkit's src/main?

**Comment by Alistair-Johnson** [comment]
As I mentioned on gitter, I have found an OOM issue with ListWrapper...but so long as I push the PR fix before a release, then all's fine. Just mentioning in case I forget...

But I concur...good idea :+1:

**Comment by Alistair-Johnson** [comment]
So we _can't_ forget... https://github.com/typelevel/cats/pull/2648
