### ISSUE TITLE
Drop machinist for Dotty

### ISSUE THREAD

**Issue by Alistair-Johnson** [typelevel/cats#2649]
Ref https://gitter.im/typelevel/general?at=5c0072ae464b6c0fd667cdfc

**Comment by ceedubs** [comment]
I assume that we would still want to keep machinist for Scala versions before Dotty. How could we go about doing this? Is there a way to make Machinist a no-op for Dotty and still work the same for previous versions?

**Comment by drdozer** [comment]
I hit this today. The cats syntax macros broke my dotty use of the syntax. I think we can simply replace the macros with inline defs. Unless they are doing something very clever. So what's the magic for building two versions of the macros project, one using machinist, and one with manually plumbed inline defs?

**Comment by rossabaker** [comment]
Fixed by #2925.
