### ISSUE TITLE
Remove fine-grained imports from docs

### ISSUE THREAD

**Issue by tpolecat** [typelevel/cats#2651]
Some of the doc pages use fine-grained imports, which we should discourage as it's very tricky (so tricky in fact that most advanced users don't even try) and is a source of discouraging problems and many questions on the Gitter channel. Can we go through the doc and remove them?

**Comment by calvinbrown085** [comment]
Hi @tpolecat do you have an example here? I'm guessing it's somewhere we can import `._` instead?

**Comment by LukaJCB** [comment]
@calvinbrown085 
In general when there's docs where anything apart from `import cats.implicits._` is used, change it to `cats.implicits._` instead. So e.g. in https://github.com/typelevel/cats/blob/master/docs/src/main/tut/typeclasses/applicative.md

you'll see this:

```scala 
import cats.instances.list._
import cats.syntax.traverse._
```

That should be changed to just 
```scala
import cats.implicits._
```

**Comment by calvinbrown085** [comment]
@LukaJCB Ah, that makes sense! I can try to go through and find some of these to fix

**Comment by ceedubs** [comment]
I think that this can be closed out now. Thanks, @calvinbrown085!
