### ISSUE TITLE
Add mkString_ that just takes separator string 

### ISSUE THREAD

**Issue by matthughes** [typelevel/cats#2663]
Cats provides a Show-compatible version of mkString but it requires all three parameters: prefix, separator, suffix.  The std library also provides a mkString that just takes a separator string; this is what I use 90% of the time. 

Can we add this?  I'd be happy to PR.

**Comment by calvinbrown085** [comment]
Hi @matthughes did you end up working on this?

**Comment by matthughes** [comment]
@calvinbrown085 I have not.  I wanted to see if there was interest before doing the PR as it's pretty simple.  Really just adding a new method that delegates to the form:

```scala
def _mkString(separator: String): String = 
  _mkString("", separator, "")
```

**Comment by kailuowang** [comment]
@calvinbrown085 I think this would be a good addition. And it's rather simple, the code you wrote and a doctest should do.

**Comment by dwijnand** [comment]
Fixed by https://github.com/typelevel/cats/pull/2709
