### ISSUE TITLE
Provide a `combineKEval` method

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2707]
For `Apply` we currently have `map2Eval`, which individual instances can override to get short-circuiting. Would be cool to have the same for `SemigroupK`, as I believe quite a few instances could do some short-circuiting in that way.

**Comment by kailuowang** [comment]
this would be binary breaking right?

**Comment by LukaJCB** [comment]
Yeah, atleast for 2.11 :(

**Comment by LukaJCB** [comment]
Though, maybe it's not such a bad thing, it could fit into other plans such as #2620
