### ISSUE TITLE
Map and SortedMap should have MonoidK instances

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#2714]
Map#++ is associative and should also form a Monoid with Map.empty as the identity :)

**Comment by wojciechUrbanski** [comment]
I would like to take that one :)

**Comment by alexeygorobets** [comment]
Hey @wojciechUrbanski! Do you mind If I take this from you?

**Comment by wojciechUrbanski** [comment]
Hey @alexeygorobets. Sure, go on. Unfortunately i am a little bit occupied right now and cannot continue working on this one.

**Comment by alexeygorobets** [comment]
Thank you @wojciechUrbanski !

hi @kailuowang 
Am I correct that I need to create a separate trait 
`trait AllInstancesBinCompat4 extends SortedMapInstancesBinCompat1 with MapInstancesBinCompat1`
for maintaining binary compatibility?

**Comment by kailuowang** [comment]
@alexeygorobets that's correct. Thanks!

**Comment by rossabaker** [comment]
Fixed by #2744.
