### ISSUE TITLE
Chain.fromSeq vs NonEmptyChain.fromSeq

### ISSUE THREAD

**Issue by dcastro** [typelevel/cats#2718]
There seems to be an inconsistency between these two methods.

`Chain.fromSeq` takes a `scala.collection.Seq`, whereas `NonEmptyChain.fromSeq` takes a `scala.collection.immutable.Seq`.

I assume the correct fix is to change `Chain.fromSeq` to take an immutable sequence, but that sounds like a breaking change...

Cats version: 1.6.0.

**Comment by diesalbla** [comment]
This seems to have been solved, or at least worked around, in #3133 .
