### ISSUE TITLE
CommutativeSemigroup[A] => CommutativeMonoid[Option[A]]

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#2725]
It looks like having a `CommutativeSemigroup[A]` currently doesn't get you `CommutativeMonoid[Option[A]]`. I think that's something that we should be able to provide. Does anyone have a reason not to include this instance?

**Comment by ctongfei** [comment]
Can we get a `Monoid[Option[A]]` from a `Semigroup[A]` in cats now?

**Comment by LukaJCB** [comment]
@ctongfei It's in fact the standard instance :)
See here: https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/option.scala#L9

**Comment by ctongfei** [comment]
@LukaJCB Ahh thanks!

**Comment by kailuowang** [comment]
to fix this we need to move the [current `Monoid` instance](https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/option.scala#L9) to `OptionInstances0`
This change will be binary breaking on scala 2.11 though.  There might be convoluted ways to do it in scala2.11 but it's not obvious to me. If it's not urgent, shall we schedule it to 2.1?
