### ISSUE TITLE
Add FlatMapRequested on Validated to alleycats like scalaz's Validation for convenience

### ISSUE THREAD

**Issue by psilospore** [typelevel/cats#2751]
Although scalaz's Validation and cat's Validated are not monads. Scalaz provides a convenient import for providing flatmap on Validation to use on for comprehensions. 

```
  /** Import this if you wish to use `flatMap` */
  object FlatMap {
    @inline implicit def ValidationFlatMapRequested[E, A](d: Validation[E, A]): ValidationFlatMap[E, A] =
      new ValidationFlatMap(d)
  }
```

In our code base we simply import this right before we want to sequence our Validations. Example

```
def logNumOfPosts() = {
  import scalaz.Validation.FlatMap._
  for {
    user <- fetchUser(userId)
    posts <- fetchPostsByUser(user) //This could potentially go on much longer
  } {
    log.info(s"${user.name} has posted ${posts.size} times")
  }
}
```

Although I could use andThen to sequence I miss out on the nice for-comprehension syntax.

**Comment by psilospore** [comment]
I would be interested in working on this if it gets a 👍

**Comment by chuwy** [comment]
I think if this is going to be implemented it should be in alleycats. I personally prefer `Either` + `Parallel` in most cases to solve this problem.
