### ISSUE TITLE
Should OptionT.mapFilter be implemented in terms of OptionT.subflatMap

### ISSUE THREAD

**Issue by morgen-peschke** [typelevel/cats#2757]
Is there a use case for having different implementations of `OptionT.mapFilter` and `OptionT.subflatMap`?

There's already a test enforcing the invariant that `mapFilter` should be consistent with `subflatMap`. Given this, should `mapFilter` delegate to `subflatMap`? If not, I'd be happy to add the reason to the scaladocs.

Having two implementations doing the same thing is a bit confusing, particularly as `EitherT.mapFilter` does not exist.

**Comment by kailuowang** [comment]
They came from two different contexts. `mapfilter` is a method in the `FunctorFilter` type class while `subflatmap` is more native to the data type. 
I agree that having OptionT.mapFilter be implemented in terms of OptionT.subflatMap would be less confusing.
