### ISSUE TITLE
Upgrade to scalatest 3.1.0

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2761]
Scalatest 3.1.0 is yet to be released. 
We need to upgrade this to avoid potential compatibility issue with scalacheck 1.14 before we can release 2.0

**Comment by erwan** [comment]
Do we have visibility on scalatest roadmap? Scalatest 3.1.0 is still not released, should this ticket still block cats 2.0?

**Comment by kailuowang** [comment]
Due to compatibility with scalacheck on Scala 2.13
, Cats-testkit has to depend on scalatest 3.1.0 . I am on my vacation ATM. I will try find a solution to unblock later this week.

**Comment by nafg** [comment]
Here's the "countdown": https://github.com/scalatest/scalatest/issues/1656

**Comment by julienrf** [comment]
> Cats-testkit has to depend on scalatest 3.1.0

May I ask what is the reason for that?

**Comment by kailuowang** [comment]
@julienrf 
The reason is that Scalacheck .  Scalatest 3.0.x doesn't support Scalacheck 1.14 which is the only Scalacheck version that supports Scala 2.13.
I am on vacation right now. But if anyone has the time to strip out the scalatest dependent part from cats testkit out to a separate module and set it to be not published, and upstate the document teaching people how to integrate with scalatest themselves, I think I can find time to review and help release (or other maintainers can do too).
I will be back Aug 5

**Comment by nafg** [comment]
So then how were cats 2.0-M4 and scalatest 3.0.8 built for scala 2.13?

**Comment by nafg** [comment]
Also, what's stopping an earlier version of scalacheck from being published for scala 2.13?
