### ISSUE TITLE
OptionT[Future]: Execution context

### ISSUE THREAD

**Issue by aaabramov** [typelevel/cats#2769]
Is there any reason to require an `ExecutionContext` for `OptionT.pure[Future](10)`?

I completely understand that `Future` instances could not be provided via`cats.instances.FutureInstances#catsStdInstancesForFuture` without implicit `ExecutionContext`.

But current implementation of `OptionT.pure[Future]#apply` is `Future.successful` which does not require an `ExecutionContext`.

**Comment by kailuowang** [comment]
logically it shouldn't require that EC but practically our code is design to be agnostic of which `F` you pass in when you do `OptionT.pure[F]` and that requires an `Applicative` instance for `F`, in the case of Future that means an `ExecutionContext` is required. 
I am not sure if Cats can/should be changed to accommodate that. You can however write your own helper method that simply does a `def pureFOptionT[A](a: A): OptionT[Future] = OptionT(Option(Future.successful(a)))`
That being said, I am not recommending you to do that or anything with `Future`. Consider using `cats.effect.IO` instead.
Another thing to consider is to adopt final tagless and avoid direct dependency on effect type like `OptionT` altogether.  So most of you code would look like
```scala
class MyComponent[F[_]: MonadError] {
    def return10: F[Int] = 10.pure[F]
}
```

**Comment by LukaJCB** [comment]
There is no specific type class instance which has only `pure`, so I'm not sure this can be done.

**Comment by aaabramov** [comment]
I see, thank you.
Closing this one.
