### ISSUE TITLE
publish for Scala 2.13.0-RC1, please

### ISSUE THREAD

**Issue by SethTisue** [typelevel/cats#2776]

**Comment by SethTisue** [comment]
blocked by simulacrum at the moment, but there's probably other things too (catalysts?)

**Comment by SethTisue** [comment]
note that kind-projector moved from org.spire-math and org.typelevel in their version 0.10.0 release

**Comment by SethTisue** [comment]
simulacrum has now published. not sure what the next blocker is

**Comment by SethTisue** [comment]
I submitted some WIP at https://github.com/typelevel/cats/pull/2783 , not even sure if it's to the right branch, not sure what the plan is around ScalaCheck 1.14.0 being the only ScalaCheck available for 2.13 (for now? not sure if anyone has tried to push for 1.13.x release on 2.13)

**Comment by SethTisue** [comment]
catalysts, I think

**Comment by SethTisue** [comment]
#2791 and #2792 are both merged. is there more work to do before publishing levers can be pulled...?

**Comment by kailuowang** [comment]
@SethTisue I am waiting on a discipline maintainer releasing a milestone with this PR merged in https://github.com/typelevel/discipline/pull/89

**Comment by SethTisue** [comment]
@kailuowang I see, would that be @larsrh ?

**Comment by larsrh** [comment]
0.11.2-M1 is on its way to Maven Central

**Comment by kailuowang** [comment]
Last PR (i hope)  #2806 before 2.0-M1 release on 2.13-RC1

**Comment by djspiewak** [comment]
@kailuowang Are you going to do a cross-build in the 1.x line on 2.13?

**Comment by kailuowang** [comment]
@djspiewak we don't plan to release any non-bug-fix releases in the 1.x line. Cats 2.0 is binary compatible with 1.x on `cats-core` and `cats-free`.  
The only major changes Cats 2.0 introduces is upgrading to Scalatest 3.1.0 and Scalacheck 1.14.0. (There are a couple of minor breaking changes in cats-laws and alleycats, but they are unlikely to impact use site)
These dependency upgrades are intertwined with the update to support Scala 2.13-RC1. For example, Scalacheck 1.13 does not support scala 2.13, and Scalatest 3.0.x does not support Scalacheck 1.14, so if you don't want to upgrade those two, it's not obvious how you can support Scala 2.13 unless you chose to use different scalatest and scalacheck versions for Scala 2.13 and Scala 2.12 (which is what cats has been doing up to this point, with the new API changes in Scalatest 3.10 it's not obvious how to continue to do that. )

**Comment by djspiewak** [comment]
That's all very reasonable. I was mostly thinking about what I wanted to do with shims.

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/typelevel/cats-core_2.13.0-RC1/2.0.0-M1/
