### ISSUE TITLE
unconventional package objects 

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2781]
we have several package objects that are not really package object since there is no corresponding packages and folders. Also their name is not conventional `package.scala` which throws warning in compiler. 
e.g. `kernel/instances/list`, `kernel/instances/tuple` etc. 
We can't make them normal objects now since that will break BC. But we should at least address the compiler warning and move those to `package.scala` and into corresponding folders. 
e.g. 
`kernel/instances/list.scala` -> `kernel/instances/list/package.scala`

**Comment by denisrosca** [comment]
There are a couple instances in there that are not marked as package objects (e.g. `package objects object eq extends EqInstances`). `finiteDuration` doesn't seem to have an object at all. 

Should they be left untouched or would you prefer moving them to package objects for consistency?

**Comment by kailuowang** [comment]
Ieally all these objects should reside in a real package object like this 
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/instances/package.scala
I suspect that moving the non-package objects from their files into the real package object will not break binary compatibility, so, maybe worth a try and run mima on scala 2.11.12. 
We don't need to create an object if it doesn't exist in the file, there should be an existing object in the real package object already.
