### ISSUE TITLE
The scaladoc for `NonEmptyChain` ( `reduceRight` and `reduceLeft To` method) are duplicate

### ISSUE THREAD

**Issue by Obarros** [typelevel/cats#2802]
This is the correct usage. 
https://github.com/typelevel/cats/blob/4b562a85e6c34dadd70d06def24e0f3e8c3f9522/core/src/main/scala/cats/data/NonEmptyChain.scala#L286

This should be using `reduceRightTo` and the result is different if we use `reduceLeftTo` . 
https://github.com/typelevel/cats/blob/4b562a85e6c34dadd70d06def24e0f3e8c3f9522/core/src/main/scala/cats/data/NonEmptyChain.scala#L319

**Comment by LukaJCB** [comment]
Closed by #2802
