### ISSUE TITLE
Can Free of monoidal structures be a Monoid?

### ISSUE THREAD

**Issue by blast-hardcheese** [typelevel/cats#2849]
I see that there is no generic `Monoid` chainer for `Monad`s. I presume this is because `pure` into any arbitrary `Monad` is not guaranteed to work in a useful way, though I can't immediately see why.

That being said, is there a compelling reason why one of these should not work with `Free`, or is it just a case of no previous need for it?

I was able to write the following, which seems to work:
```scala
implicit def freeMonoid[F[_], A](implicit F: Functor[F], M: Monoid[A]): Monoid[Free[F, A]] = new Monoid[Free[F, A]] {
  def empty = Free.pure[F, A](M.empty)
  def combine(x: Free[F,A],y: Free[F,A]) = (x, y).mapN(M.combine)
}
```

Is this bad, or more broadly undesirable, in a way that I'm not currently seeing?

The motivation is that `(_: Option[Free[F, Map[Foo, Bar]]]).orEmpty` would be super convenient, permitting cleaner code in an otherwise dense codebase.

Thanks in advance for your thoughts!

**Comment by tpolecat** [comment]
There is a generic monoid for applicatives that's defined as above but it's not implicit, I assume because it would conflict with things.

```scala
@ Applicative.monoid[Option, Int].combine(Some(1), Some(2)) 
res4: Option[Int] = Some(3)
```

and it will work for your `Free` example.

```scala
@ trait Foo[A] 
defined trait Foo

@ Applicative.monoid[Free[Foo,?], Int] 
res8: Monoid[Free[Foo, Int]] = cats.ApplicativeMonoid@5602e540
```

**Comment by blast-hardcheese** [comment]
Woah, neat.

Any ideas of why that's not implicit?

Alternately, was that something I missed in documentation, or should I have intuited its presence?
