### ISSUE TITLE
Cats Microsite: add Github Links

### ISSUE THREAD

**Issue by diesalbla** [typelevel/cats#2862]
The [`cats` microsite](https://typelevel.org/cats/) has several pages explaining the data types. It would be useful if each of them could add a link to the page in the Github source code where that data structure is defined.

E,g: [Chain doc](https://typelevel.org/cats/datatypes/chain.html) and [Chain code](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Chain.scala)

**Comment by erwan** [comment]
Is it something that should be done manually on each page or is there a way to leverage the `source` header already present in most page?

(What is this header currently used for by the way?)

**Comment by vasiliybondarenko** [comment]
I guess it can be automated using header:
```
---
layout: docs
title:  "Eval"
section: "data"
source: "core/src/main/scala/cats/Eval.scala"
scaladoc: "#cats.Eval"
---
```

**Comment by vasiliybondarenko** [comment]
Can I create PR?

**Comment by reardonj** [comment]
I can take a look at this, though personally I'd rather links to the scaladocs than the source code.

Laika has support to generate API & source links. API links can be configured straight from the `tlSiteApiUrl` setting, which makes me wonder if that step would be more useful to do right in `TypelevelSitePlugin`. I didn't see an obvious analog for source links, but maybe there is a setting elsewhere? Thoughts?

**Comment by armanbilge** [comment]
Thanks for your interest!

> which makes me wonder if that step would be more useful to do right in `TypelevelSitePlugin`

Indeed! We had a PR that was looking into this, I would be very happy to see that effort revived :)

- https://github.com/typelevel/sbt-typelevel/pull/225
