### ISSUE TITLE
publish for Scala 2.13.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [typelevel/cats#2864]
previous go-round was https://github.com/typelevel/cats/issues/2853

[RC2->RC3 delta](https://github.com/scala/scala/pulls?q=is%3Aclosed+milestone%3A2.13.0-RC3) is quite small, so, and I don't want to jinx it but, I expect this will be a routine matter of incrementing numbers and pulling levers

kind-projector is at 0.10.2 now, Scala.js is at 0.6.28/1.0.0-M8, scalatest at 3.0.8-RC5 (and @cheeseng is working on a 3.1.0-SNAPx release)

**Comment by djspiewak** [comment]
Blocked on:

- scalatestplus-scalacheck
- discipline
- machinist
- simulacrum

**Comment by travisbrown** [comment]
The scalatestplus thing and Discipline are out, and I've got (trivial) update PRs for the other two:

* https://github.com/mpilquist/simulacrum/pull/142
* https://github.com/typelevel/machinist/pull/51

**Comment by SethTisue** [comment]
just to check, I think this was auto-closed by GitHub, is the publishing part still being worked on? no artifacts at https://repo1.maven.org/maven2/org/typelevel/cats-core_2.13.0-RC3/ yet
