### ISSUE TITLE
Ambiguous Vector instances

### ISSUE THREAD

**Issue by durban** [typelevel/cats#2891]
The implicits `catsKernelStdPartialOrderForVector` and `catsKernelStdHashForVector` ([here](https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala#L11)) are ambiguous if `A` has both `PartialOrder` and `Hash` instances, and we're looking for an `Eq[Vector[A]]`. (`List` seems to have the same problem.)

**Comment by kailuowang** [comment]
I am not sure if we can fix it for Scala 2.11 without breaking BC. We might have to leave it as is on 2.11 and do a scala version specific fix for 2.12+. Or we simply drop 2.11 which is more likely now than before.

**Comment by travisbrown** [comment]
The fix in #3100 ended up breaking bincompat (MiMa missed it), so we had to revert it for now.

**Comment by UlisesTorrella** [comment]
Hi! I tried to replicate this error in Scala212, Scala213 and Scala3 with the following script:
```
import cats._

type A = String // tried also with Int, List[Int]

// checked that A has a both instances
implicitly(PartialOrder[A])
implicitly(Hash[A])

// replicate implicit ambiguity error
implicitly(Eq[Vector[A]])
implicitly(Eq[List[A]])
``` 
And got successful executions every time. Let me know if there is another situation that breaks, but otherwise the issue could be closed.

**Comment by armanbilge** [comment]
Thanks!
