### ISSUE TITLE
implicitNotFound annotation for Monoid and everything else

### ISSUE THREAD

**Issue by elefthei** [typelevel/cats#2892]
What is the error message when an implicit is not found for a Monoid? I have something like

```
@implicitNotFound(msg = "Cannot find evidence that ${T} is a Monoid")
trait Monoid[T] {
...
}
```

Should I file a PR or has this been addressed before? I can do it for everything not just Monoid.

**Comment by kailuowang** [comment]
I like the idea. I think a more helpful message might be something like "There is no `Monoid` instance in scope for ${T}, for more detail go to https://typelevel.org/cats/typeclasses/monoid "

**Comment by elefthei** [comment]
Does `@typeclass` generate better errors among other things? I am sceptilcal of using both `@implicitNotFound` and `@typeclass` annotations for some classes.

**Comment by kailuowang** [comment]
related https://github.com/typelevel/cats/issues/581

**Comment by larsrh** [comment]
Closed as duplicate.
