### ISSUE TITLE
Style convention for override modifier

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#291]
We should choose a convention for when we use the `override` modifier and be consistent with it.

See [this discussion](https://github.com/non/cats/pull/290#discussion_r28939702).

We can use the comments section of this issue page to discuss what we want our convention to be. Once we've reached a conclusion, someone can create a follow-up PR that updates code to follow the established convention.

**Comment by ceedubs** [comment]
I think I might have just found another benefit of using `override` everywhere it is allowed. [This comment](https://github.com/non/cats/pull/302#discussion_r29667659) made me look into whether we could have Scalastyle enforce that we have return types on public methods. It can, but this would probably require us to add explicit return types in a bunch of places where we are providing an implementation for an abstract method. If we were to add `override` in those places, we could use Scalastyle's `ignoreOverride` flag to not enforce the explicit return type in these cases.

There may be an argument that it's better to just enforce explicit return types for all public methods whether they are implementing an abstract method or not.

**Comment by non** [comment]
Yeah, I pretty much think the type annotations should be on overridden methods too.

**Comment by ceedubs** [comment]
Okay. I'll look into submitting a PR for that.

**Comment by stew** [comment]
personally I'm in favor of putting it everywhere it is allowed, it just enables more compiler verification of types. I don't feel strongly enough to go to the matt with someone on it though

**Comment by sritchie** [comment]
Looks like this is closed by #303, yeah?
