### ISSUE TITLE
Scala 2.13.0 became  partial unification on by default.

### ISSUE THREAD

**Issue by SeanDaru** [typelevel/cats#2948]
Scala 2.13.0 became partial unification on by default.
So, the following option is not necessary for scala 2.13.0, isn't it?
`scalacOptions += "-Ypartial-unification"` 
(from [README.md:Getting Started](https://github.com/typelevel/cats/blob/master/README.md#getting-started) )

----
[Reference]
・[Release Scala 2.13.0 · scala/scala · GitHub](https://github.com/scala/scala/releases/tag/v2.13.0)
 -> Language changes -> Partial unification on by default

> The compiler no longer accepts -Ypartial-unification.

**Comment by kailuowang** [comment]
That's right. A PR to update readme would be great!
