### ISSUE TITLE
Any way to chain `ApplicativeError`?

### ISSUE THREAD

**Issue by morgen-peschke** [typelevel/cats#2951]
When I need to do validation, I usually use either `Validated` or `Either`, depending if I need fail-fast or aggregating semantics, and this works great for most cases.

There are a couple of common operations that I'd really like to be able to use with both, and I'm almost there with `ApplicativeError`. Unfortunately, chaining is a bit of a problem. Basically, I'd like to be able to go from something like this:

```
type Errors
def step1V(in: A): Validated[Errors, B] = ???
def step2V(in: B): Validated[Errors, C] = ???
def step3V(in: C): Validated[Errors, D] = ???

def extractValidated(in: A): Validated[Errors, D] =
  step1V(in).andThen(step2V).andThen(step3V) 

def step1E(in: A): Either[Errors, B] = ???
def step2E(in: B): Either[Errors, C] = ???
def step3E(in: C): Either[Errors, D] = ???

def extractEither(in: A): Either[Errors, B] = 
  step1V(in).flatMap(step2V).flatMap(step3V)


val useInAccumulatingContext = extractValidated(in)
val useInFailFastContext = extractEither(in)
```

To something more like this:
```
type Errors
def step1F[F[_]: ApplicativeError[F, Errors]](in: A): F[B] = ???
def step2F[F[_]: ApplicativeError[F, Errors]](in: B): F[C] = ???
def step3F[F[_]: ApplicativeError[F, Errors]](in: C): F[D] = ???

def extractF[F[_]: ApplicativeError[F, Errors]](in: A): F[B] = 
  step1V(in).???(step2V).???(step3V) 

val useInAccumulatingContext = extractF[Validated[Errors,_]](in)
val useInFailFastContext = extractF[Either[Errors,_]](in)
```

Converting the `stepN` functions is straightforward, what's tripping me up is there doesn't seem to be a way to implement `extractF`, without doing a bunch conversions between `Either` and back. Is there something I'm missing?

**Comment by ybasket** [comment]
Why do you want to use `Validated`/`ApplicativeError` though your computations (`stepN`) are sequential, hence indicating `MonadError`? Let's assume there was some magic way of defining your `extractF`, would you expect any difference in the results (`failingFast` vs `accumulating` - btw I assume you flipped the naming here)? 
Because if you run this concrete example of your code:
```scala
  type Errors = String
  def step1V(in: Byte): Validated[Errors, Short] = (in * 2).toShort.valid
  def step2V(in: Short): Validated[Errors, Int] = "2".invalid
  def step3V(in: Int): Validated[Errors, Long] = "3".invalid

  println(step1V(42) andThen step2V andThen step3V)
```
we see that we get `Invalid("2")` - so no accumulation of errors. And that has to be the case as if `step2V` returns an `Invalid`, there's no value of type `C` (`Int` in my example) to feed to `step3V`.

From what you posted, I believe you'll need an `F` which has a`Monad` instance anyway. Let's assume the steps couldn't raise any errors, how would you chain them without `flatMap`? For sequential validation (and that's how I read your example), you need sequential computation and that's exactly what `Monad` provides. Plus errors, that makes `MonadError` and your `extractF` becomes a simple chain of `flatMap` calls - just as in your example for `Either`. You can still leave the `step` functions with `ApplicativeError` to reuse them in other contexts for parallel validation, but for `extractF`, I don't see a way to use `Validated` in a clean abstract way as its `MonadError` instance is not lawful (see https://typelevel.org/cats/datatypes/validated.html#of-flatmaps-and-eithers). Of course you can still implement it or just define your own type class for `extractF` but I wouldn't suggest to do so…

**Comment by morgen-peschke** [comment]
> (failingFast vs accumulating - btw I assume you flipped the naming here)?

Yes I did, thanks for catching that. It'd been corrected. The names were also not as clear as I'd thought when I originally wrote it, so I've tweaked them slightly.

The behavior in your example is exactly what I'd expect from that code, with the tweaked names in the example it'll hopefully be more clear that what I'm shooting for is the `stepN` functions to be primitives that can be used to build more complicated validations. These validations would in turn be used in contexts which may require fail-fast or accumulating semantics, and I'd love to avoid the extra allocations of converting between `Either` and `Validated` or the boilerplate of duplicating some of the helpers.

Currently I'm working around it by sticking to `Validated` for the entire stack. This works, but the codebase was previously using scalactic's `Or`, and one of the annoyances with working with `Or` is there's no indication if you're in a context where the errors accumulate or fail-fast. 

I'm nearly able to provide this distinction for the primary codepaths, except that a few operations like `collectToValidated` operate in both accumulating and fail-fast contexts and are effectively one or two pre-conditions followed by a set of validations. I'd really love to be able to define them in terms of something like `ApplicativeError`, while avoiding the extra wrapping and unwrapping of converting them to `Either` and back because they're used in what's effectively a tight loop. 

`MonadError` won't work because, as you noted, `Validated` doesn't have a `MonadError` instance. `ApplicativeError` doesn't seem to work because it doesn't define an operation equivalent to `Validated#andThen`. So it seems like I'm stuck in a gap between these abstractions, but I also doubt I'm the first person to run into this, so I figured there might be something I wasn't seeing.

**Comment by ybasket** [comment]
I see, but can't say I see a solution as well…just one thought:

You can abstract over the relation between `Either` and `Validated` using `Parallel`. Not sure whether that helps building exactly what you want, but as an inspiration:

```scala
type Errors = String
  def step1V[G[_]](in: Byte)(implicit G: ApplicativeError[G, Errors]): G[Short] = G.pure((in * 2).toShort)
  def step2V[G[_]](in: Short)(implicit G: ApplicativeError[G, Errors]): G[Int] = G.raiseError(in.toString)
  def step3V[G[_]](in: Int)(implicit G: ApplicativeError[G, Errors]): G[Long] = G.raiseError((in * 2).toString)

  def extractF[F[_] : MonadError[?[_], Errors], G[_] : ApplicativeError[?[_], Errors]](in: Byte)(implicit pa : Parallel[F, G]): F[Long] =
    for {
      r1 <- pa.sequential(step1V[G](42))
      r2 <- step2V[F](r1)
      r3 <- pa.sequential(step3V[G](r2))
    } yield r3

  def ind1[G[_]](implicit G: ApplicativeError[G, Errors]): G[Short] = G.raiseError("Some error 1")
  def ind2[G[_]](implicit G: ApplicativeError[G, Errors]): G[Int] = G.raiseError("Some error 2")

  def extractSequential[F[_] : MonadError[?[_], Errors], G[_] : ApplicativeError[?[_], Errors]](implicit pa : Parallel[F, G]): F[(Short, Int)] =
    for {
      r1 <- pa.sequential(ind1[G])
      r2 <- pa.sequential(ind2[G])
    } yield (r1, r2)

  def extractAccumulating[F[_] : MonadError[?[_], Errors], G[_] : ApplicativeError[?[_], Errors]](implicit pa : Parallel[F, G]): G[(Short, Int)] =
    (ind1[G], ind2[G]).tupled

  println(extractF[Either[Errors, ?], Validated[Errors, ?]](2)) // Left(84)
  println(extractSequential[Either[Errors, ?], Validated[Errors, ?]]) // Left(Some error 1)
  println(extractAccumulating[Either[Errors, ?], Validated[Errors, ?]]) // Invalid(Some error 1Some error 2)
```

Having both types around could be avoided with the `cats-par` library, so you could just require `MonadError` and `Par`:
```scala
import cats.temp.par._

def extractF[F[_] : MonadError[?[_], Errors] : Par](in: Byte): F[Long] =
    for {
      r0 <- (ind1[F], ind2[F]).parTupled
      r1 <- step1V[F](r0._1)
      r2 <- step2V[F](r1)
      r3 <- step3V[F](r2)
    } yield r3 // Left(Some error 1Some error 2)
```

That doesn't allow you to use `Validated` as your `F`, but you can use `Either` and still use accumulating behavior when needed. As behind the scenes it'll do some conversions to and from `Validated`, performance might not be the best, but you avoid some boilerplate.

**Comment by morgen-peschke** [comment]
Thanks @ybasket .
Performance is a decently important concern, so I think I'll stick with using `Validated` throughout. At least I know I'm not missing anything obvious.
