### ISSUE TITLE
Unlawful Hash instances for Function0

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#2952]
I just noticed that `Hash[() => A]` doesn't match `hashCode`, and (possibly worse) it evaluates the function:

```scala
scala> val thunk = () => "abcd"
thunk: () => String = $$Lambda$4719/1999191506@1ef9f59

scala> thunk.hashCode
res0: Int = 32481113

scala> import cats.implicits._
import cats.implicits._

scala> thunk.hash
res1: Int = 2987074

scala> "abcd".hashCode
res2: Int = 2987074
```
We should decide whether / how to handle this and add something like this to `LawTests` in the kernel-laws tests:
```scala
checkAll("Hash[() => Int]", HashTests[() => Int].hash)
```
(I confirmed that it fails now.)

**Comment by kailuowang** [comment]
Any reason why this is closed?

**Comment by travisbrown** [comment]
@kailuowang I'm not sure it's unintended / not the right behavior. Will take a closer look tomorrow.

**Comment by kailuowang** [comment]
thanks! FWIW, this is the PR that added the code. https://github.com/typelevel/cats/pull/1712
