### ISSUE TITLE
Add `fromUniversalEqualsBy` method to `Eq`

### ISSUE THREAD

**Issue by valenterry** [typelevel/cats#2961]
Sometimes I want to derive an `Eq` instance for a value case class, so I do `Eq.instance[CaseClass](_.value == _.value)`.
It would be nice to write that shorter as in e.g. `Eq.fromUniversalEqualsBy[CaseClass, String](_.value)` (similar to `Eq.by`).

**Comment by kailuowang** [comment]
Eq.by should work fine for your use case right? Since cats provides Eq instance for string.

**Comment by valenterry** [comment]
> Eq.by should work fine for your use case right? Since cats provides Eq instance for string.

You are right, I missed the imports. It might still make sense to have that method, but probably not very often. I'll close it.
