### ISSUE TITLE
Add cats-testkit-scalatest microlibrary for V2.0.0

### ISSUE THREAD

**Issue by ronanM** [typelevel/cats#3016]
Add the microlibrary `cats-testkit-scalatest` for testing with scalatest, containing `StrictCatsEquality`.

See this comment: https://github.com/typelevel/cats/pull/2970#issuecomment-521305922

**Comment by ChristopherDavenport** [comment]
I can grab this really quickly if no objections are taken to my template. Example in discipline-specs2 and discipline-scalatest.

**Comment by jhnsmth** [comment]
Maybe it makes sense to combine it with https://github.com/IronCoreLabs/cats-scalatest unfortunately it does not seems well maintained

**Comment by kailuowang** [comment]
We can do that later. Right now we need this for 2.0 release

**Comment by ChristopherDavenport** [comment]
cats-testkit-scalatest 1.0.0-M1 Released! https://github.com/typelevel/cats-testkit-scalatest

**Comment by rajit-iov42** [comment]
The only library I can find for Cats 2 providing `CatsSuite` is `cats-testkit-scalatest`. But this depends on bleeding edge `ScalaTest` libraries that contain significant breaking changes (e.g. `GeneratorDrivenPropertyChecks` no longer works with `Gen` instances from ScalaCheck). Is this the intention? It'd be great to be able to upgrade to Cats 2 without needing to worry about lots of tests breaking and needing to be rewritten.

**Comment by larsrh** [comment]
@rajit-iov42 There's currently an RC-quality version out. IMHO that should be sufficient for tests.
