### ISSUE TITLE
Add `filterNot` to FunctorFilter syntax

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#3022]
Just a general idea. If it sounds good, I'll implement it :)

**Comment by morgen-peschke** [comment]
Seems like something that tends to make life easier, is easy to implement, and doesn't really add much (if any) cognitive complexity to `FilterFunctor`, so I like it (for whatever that's worth ;) )

**Comment by gagandeepkalra** [comment]
Is it okay if I pick this up?

**Comment by kubukoz** [comment]
Sure, I don't think anybody is working on it
