### ISSUE TITLE
add unzip to Functor

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/cats#3023]
what do you think about adding

```scala
trait Functor[F[_]]{
  def unzip[A, B](fab: F[(A, B)]): (F[A], F[B]) = (fab.map(_._1), fab.map(_._2))
}
```

potentially we could have optimised version per type

reference https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List-NonEmpty.html#v:unzip

**Comment by gagandeepkalra** [comment]
Is it okay if I pick this up?

**Comment by stremlenye** [comment]
Wouldn't the implementation @julien-truffaut proposed invoke computation twice for the effect `F[_]`?

**Comment by kubukoz** [comment]
Also concerned about this. This would probably be fine in Foldable, but for effects it'll require evaluating twice or break referential transparency.

**Comment by LukaJCB** [comment]
We could call it `unzipDuplicate` or something to make this clear from the naming. WDYT? :)

**Comment by kubukoz** [comment]
I'd probably like it more with a comment than that name tbh 😆 let's see what others think

**Comment by kailuowang** [comment]
The effect duplication seems pretty obvious in type (2 `F[A]`s out) to me. I agree that if we want to add a note a comment will suffice.

**Comment by joroKr21** [comment]
I don't think there is a way to unzip an effect without running it twice unless we do some memoization, but that's cats-effect territory.

**Comment by kubukoz** [comment]
@joroKr21 even in cats-effect memoization without an additional effect breaks RT.

**Comment by joroKr21** [comment]
Yes you would have to return `F(F[A], F[B])` which defeats the purpose.

**Comment by gagandeepkalra** [comment]
PR merged, closing this now, thanks everyone :)
