### ISSUE TITLE
Hash[SortedSet[A]]'s constraint seems too strong

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3038]
Right now we have the following:

```scala
  implicit def catsKernelStdHashForSortedSet[A: Order: Hash]: Hash[SortedSet[A]] =
    new SortedSetHash[A]
```

I don't think we need `A: Order` here, just `A: Hash` (which implies `A: Eq`).

**Comment by tnielens** [comment]
This was already implemented: 
https://github.com/typelevel/cats/blob/9753b344df3c75e71799ea666d2018ee5f19747f/kernel/src/main/scala/cats/kernel/instances/SortedSetInstances.scala#L11

**Comment by rossabaker** [comment]
Yep.  Thanks for the nudge.
