### ISSUE TITLE
Hash[Map[K, V]] has unnecessary constraint

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3039]
Similar to #3038. Now we have:

```scala
  implicit def catsKernelStdHashForMap[K: Hash, V: Hash]: Hash[Map[K, V]] =
    new MapHash[K, V]
```
But the `K: Hash` isn't used in the implementation.

**Comment by vasiliybondarenko** [comment]
I'll create PR if nobody minds.

**Comment by travisbrown** [comment]
@vasiliybondarenko Sounds good to me, although the problem is that I don't think it's possible to fix it without breaking bincompat, which means the PR will be have to be parked for a long time.

**Comment by kailuowang** [comment]
as soon as https://github.com/typelevel/cats/pull/3051 gets merged we can fix this right without breaking BC: deprecate the current one and remove the `implicit` keyword and add a new one without the constraint.

**Comment by travisbrown** [comment]
@kailuowang Oh, I guess that's right—the erasure will be different so the names won't collide.

**Comment by ctongfei** [comment]
I'm the author of that function.

`Hash[V]` is actually used in the implementation: to hash a map, we need to have the hash code for each `(K, V)` pair, which, in turn, requires an implicit `Hash[V]`.

See the implementation here: https://github.com/typelevel/cats/blob/master/kernel/src/main/scala/cats/kernel/instances/MapInstances.scala#L33

**Comment by vasiliybondarenko** [comment]
@ctongfei that's right. But we still don't need `Hash[K]`,  as key uses Scala's `hashCode`

**Comment by ctongfei** [comment]
@vasiliybondarenko That is right. Scala's `Map` uses universal hash code, so `Hash[K]` is not needed.
