### ISSUE TITLE
Move Parallel instances into instance packages for the type constructors they characterize

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3059]
It seems pretty reasonable to expect the following to work:

```scala
import cats.instances.either._, cats.instances.string._, cats.syntax.parallel._

val e: Either[String, Int] = Left("e")

(e, e).parTupled
```
But it doesn't, because the `Parallel` instance for `Either` is in `cats.instances.parallel`, not `cats.instances.either`

After #3033, the only instances in the `parallel` instance package are for `Either`, `Stream`, and the `NonEmptyParallel` instances for `List` and `Vector`. I think all of these should be moved the instance packages for those types—`cats.instances.either`, `cats.instances.stream`.

This change would break source compatibility, but could be done in a binary-compatible way in 2.1 (by making all of the contents of `cats.instance.parallel` non-implicit and deprecated).

**Comment by barambani** [comment]
If the work on this hasn't started yet I'd like to give a hand.

**Comment by travisbrown** [comment]
@barambani I've not done anything on it, so that sounds good to me! I think it's a pretty reasonable change that could happen in 2.1, but we'll want to make sure there's consensus about that.

**Comment by barambani** [comment]
Makes sense, I will wait for another while then, to give time to the discussion. Thanks 👍
