### ISSUE TITLE
Law testing documentation improvement

### ISSUE THREAD

**Issue by miklos-martin** [typelevel/cats#3068]
Hi,

First of all, thank you all for your amazing work on cats.

I have recently upgraded to 2.0 and I had a semi-hard time figuring out how to make my tests compile again. Previously I have been using `CatsSuite` from `cats-testkit`. If I understand correctly, my tests broke because of 9ef3af09493d01bd8f73fd58c624b9b1733497b.

I had some trouble following the [Laws Testing](https://typelevel.org/cats/typeclasses/lawtesting.html) docs and I think it would be nice to mention there what additional dependencies one will need if they are using scalatest, or specs2 (I'm using scalatest and I needed to add a snapshot version of it to have `org.scalatest.funsuite.AnyFunSuite` and a milestone release of`discipline-scalatest` in addition to `cats-laws` to have `org.typelevel.discipline.scalatest.Discipline`).

I could send a PR if you like, what do you think?

**Comment by kailuowang** [comment]
Sorry about the inconveniences, it's an oversight on our part, I did update the doc to point to the new way to use Catsuite, but we didn't publish the website, which I will do shortly. In the meantime, I think it's a good idea to mention dependency needed if you are not using Catsuite: a milestone release of discipline-scalatest in addition to cats-laws. A PR will be great!

**Comment by miklos-martin** [comment]
Fixed in #3072, thanks!
