### ISSUE TITLE
NonEmptyReducible doesn't have a companion object

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3069]
This is clearly a bug:
```scala
scala> import cats._, cats.data._, cats.implicits._
import cats._
import cats.data._
import cats.implicits._

scala> NonEmptyReducible[NonEmptyList, List]
<console>:21: error: not found: value NonEmptyReducible
       NonEmptyReducible[NonEmptyList, List]
       ^
```
It's also the case that while the instances for `NonEmptyList`, etc. implement `NonEmptyReducible`, that isn't reflected in their static type. For example:
```scala
scala> implicitly[NonEmptyReducible[NonEmptyList, List]]
<console>:21: error: could not find implicit value for parameter e: cats.NonEmptyReducible[cats.data.NonEmptyList,List]
       implicitly[NonEmptyReducible[NonEmptyList, List]]
                 ^

scala> Monad[NonEmptyList].isInstanceOf[NonEmptyReducible[NonEmptyList, List]]
<console>:21: warning: non-variable type argument cats.data.NonEmptyList in type cats.NonEmptyReducible[cats.data.NonEmptyList,List] is unchecked since it is eliminated by erasure
       Monad[NonEmptyList].isInstanceOf[NonEmptyReducible[NonEmptyList, List]]
                                       ^
res2: Boolean = true
```
I can't think of a good reason for this, and would consider it also a bug, but maybe I'm missing something.

**Comment by LukaJCB** [comment]
Maybe I'm missing something, but I always thought of `NonEmptyReducible` as a helper to define a `Reducible from `Foldable`, nothing more. 
What is its use as a type class, should it really be used that way?

**Comment by travisbrown** [comment]
Hmm, I was going on the analogy of `NonEmptyTraverse`, but yeah, I guess it doesn't actually carry additional static guarantees in this case. I can take a shot at making the documentation clearer. Thanks, @LukaJCB.

**Comment by joroKr21** [comment]
Yes `Reducible` is the non-empty `Foldable`. We don't have a nice name for the corresponding `NonEmptyTraverse`.
