### ISSUE TITLE
Consider an `Empty[+A]` type class

### ISSUE THREAD

**Issue by non** [typelevel/cats#307]
On Gitter @paulp brings up the possibility of a type class to represent emptiness. Here are some code snippets he posted:

``` scala
trait Empty[+A] { def emptyValue: A }

object Empty {
  def apply[A](x: A): Empty[A]                        = new Empty[A] { def emptyValue = x }
  def unapply[A](x: A)(implicit z: Empty[A]): Boolean = x == z.emptyValue
}

trait EmptyInstances {
  implicit val emptyAttrs: Empty[Attrs]                = Empty(Attrs.empty)
  implicit val emptyOption: Empty[Option[Nothing]]     = Empty(None)
  implicit val emptyjPath: Empty[jPath]                = Empty(jPath(""))
  implicit val emptySfsPath: Empty[SfsPath]            = Empty(SfsPath(""))
  implicit val emptyUid: Empty[Uid]                    = Empty(Uid(-1))
  implicit val emptyName: Empty[Name]                  = Empty(Name(""))
  implicit val emptyNames: Empty[Names]                = Empty(Names(Vector()))
  implicit val emptySize: Empty[Size.UnitsOf[Nothing]] = Empty(Size.empty)
  implicit val emptyBytes: Empty[Bytes]                = Empty(Bytes(Array.emptyByteArray))
  implicit val emptyJavaFileKey: Empty[JavaFileKey]    = Empty(JavaFileKey(empty, new Object))

  val emptyNothing: Empty[Nothing] = new Empty[Nothing] { def emptyValue = abort("Empty[Nothing]") }
}

implicit class HasEmptyOps[A: Empty](x: A) {
    def isEmpty: Boolean                     = x == empty[A]
    def toOption: Option[A]                  = if (isEmpty) None else Some(x)
    def | (alt: => A): A                     = if (isEmpty) alt else x
    def map[B: Empty](f: A => B): B          = if (isEmpty) empty[B] else f(x)
    def filter(p: Pred[A]): A                = if (!isEmpty && p(x)) x else empty[A]
    def fold[B](none: => B)(some: A => B): B = if (isEmpty) none else some(x)
  }
```

My sense is that like Scalaz's earlier `Zero[A]` type class, many folks intuitively feel like something like this should exist.

Some possible problems I can foresee:
- Can we write laws about `Empty[A]` in isolation? If not, what laws can we write relative to other type classes?
- Should it act on types like `A` or types like `F[_]`? The example here uses variance to support `Option[_]` via `Option[Nothing]` but there are many cases where that won't work.
- How does `Empty[A]` relate to `Monoid[A]` if at all? `MonoidK[F[_]]`? `MonadFilter[F[_]]`?
- What instances should we provide? Are there instances we should forbid?
- If there is a distinction between `Monoid[A].empty` and `Empty[A].empty` will that be confusing?

One argument against including this in Cats is that a capability like _emptiness_ might make more sense in some kind of collections framework, or some context that was a bit more concrete.

Anyway, what do you all think?

**Comment by rossabaker** [comment]
I wouldn't add `Empty` solely for this, but the [discussion of coflatMap and emptiness](https://gitter.im/non/cats?at=54e28036355bbcc86103e3ec) comes to mind.

**Comment by paulp** [comment]
Yes, in that discussion we hear talk of ```def partialExtract(fa: F[A]): Option[A]```, but this is fully covered by ```def extract(fa: F[A]): A``` in combination with ```Empty[F]``` (that's ```* -> *```, not sure how the kind-polymorphism situation platys out) and avoids hardcoding Option into the interface.

**Comment by mdedetrich** [comment]
I may be missing something here, but what is the use case of `Empty` vs `Option`, is it just an `Option` that happens to be a `semigroup` or is there something more?

**Comment by ceedubs** [comment]
@mdedetrich From the description, it looks to me like `Empty` and `Option` are two different concepts. For example, we could have an `Empty[List[A]]` that says that `Nil` is the empty `List`. Or we could have an `Empty[String]` that says `""` is the empty `String`. I could also imagine a `getOrElseEmpty` method attached to `Option[A]` that is implemented as `getOrElse(Empty[A].emptyValue)`.

My main concern with this proposal is that (as far as I can tell) "empty" isn't well-defined by itself. With `Monoid` there's a clear definition of `empty` (when used in `combine`, it's a noop). I'm not saying we should absolutely trash this idea. But if we go forward with it, I'd like to see a definition of what it means to be empty so that one can reason about code that uses this typeclass for generic input types.

**Comment by paulp** [comment]
> I could also imagine a getOrElseEmpty method attached to Option[A] that is implemented as getOrElse(Empty[A].emptyValue).

Right, no need to imagine.

```scala
final class OptionOps[A](val x: Option[A]) extends AnyVal {
  def | (alt: => A): A                             = x getOrElse alt
  def ||(alt: => A): Option[A]                     = x orElse Some(alt)
  def |?[A1 >: A](alt: => A1): A1                  = x getOrElse alt
  def ||?[A1 >: A](alt: => Option[A1]): Option[A1] = x orElse alt

  def zfold[B: Empty](f: A => B): B    = x.fold[B](emptyValue)(f)
  def orEmpty(implicit z: Empty[A]): A = x getOrElse emptyValue[A]
  def or(alt: => A): A                 = x getOrElse alt
  def orFail(msg: String): A           = x getOrElse abort(msg)
  def toDirect: Direct[A]              = Direct fromScala x.toVector
}
```

**Comment by noelwelsh** [comment]
After skimming this issue I think there are at least two notions of an empty element: identities and absorbing elements. 

Identities have laws as defined for a monoid:
- there is a binary operation `*: (A, A) => A`
- there is an element `1` s.t. `a * 1 == 1 * a == a`

Absorbing elements are defined as:
- there is a binary operation `*: (A, A) => A`
- there is an element `0` s.t. `a * 0 == 0 * a == 0`

The final notion comes in things like `Option` where `None` is like an absorbing element under `map` and `flatMap` but there are two difference:
- we have a higher kinded type
- the binary operation has a different type

The closest analogue I know of here is an annihilator in linear algebra.

**Comment by BennyHill** [comment]
ref https://gitter.im/typelevel/cats-dev?at=5a99bffa6f8b4b9946e0c3c6 

Could this now be closed?

**Comment by johnynek** [comment]
I think so. I don't see any laws this follows and I think we try to avoid lawless typeclasses.

**Comment by paulp** [comment]
@johnynek I think the reasoning was more that [it has since been added](https://github.com/typelevel/cats/blob/master/alleycats-core/src/main/scala/alleycats/Empty.scala). Which is not to say it is lawful, but your response implies it never came to be.

**Comment by johnynek** [comment]
Sorry @paulp I didn't know it was added to alley-cats.

Indeed alley-cats is our collection of less-than-lawful typeclasses and instances, and it was merged into cats as a submodule to ease publishing and adoption.
