### ISSUE TITLE
Document relationship between Or and Validation

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#31]
We've [removed documentation on `Or`](https://github.com/non/cats/pull/26) that had been copied from Scalaz since we don't have a `Validation` type yet, but once we do we should reinstate this note.

**Comment by non** [comment]
Since we have a `Validated` type now, we can proceed on this issue.

**Comment by adelbertc** [comment]
Would folks consider https://github.com/non/cats/blob/e8ebbabe6aa469de58c38abc616d789e31c04a76/docs/src/main/tut/validated.md#of-flatmaps-and-xors to be sufficient?

**Comment by non** [comment]
My vote would be yes. I'd prefer to keep issues relatively small in scope -- if there are specific things that are still lacking we should open a new issue for those.

**Comment by ceedubs** [comment]
@adelbertc I think the (wonderful) `Validated` doc does a good job of distinguishing it from `Xor`. I think the one small missing piece is that the `Xor` docs should give a shoutout to `Validated` and say that that's probably want you want if you want error-accumulation.

**Comment by peterneyens** [comment]
@ceedubs There currently is a reference from the [`Xor` docs](http://typelevel.org/cats/tut/xor.html) to `Validated`. I suppose this issue can be closed ?

**Comment by ceedubs** [comment]
@peterneyens I agree. Thanks for pointing that out.
