### ISSUE TITLE
Enable Binary compatibility tests for scala 2.13

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#3109]
This includes `binCompatTest` as well as mima tests

**Comment by BluePat** [comment]
Is help still wanted?  If it is, I would like to start working on it.
I am a Scala developer, not so experienced with cats. But hey, love the project, one needs to start somewhere.

**Comment by kailuowang** [comment]
Yeah, this is mainly a sbt task, thanks a lot!

**Comment by BluePat** [comment]
In that case, I'm on it.

**Comment by travisbrown** [comment]
Sorry, @BluePat, but I've gone ahead and done this in a PR I'll be opening in a few minutes, since I was afraid we might have let breaking changes slip through on 2.13 (and I was right 😦).

**Comment by BluePat** [comment]
My fault entirely, was to busy to do it ASAP. Thanks for letting me know.
