### ISSUE TITLE
Add sum: (F[A], F[B]) => F[A Either B]

### ISSUE THREAD

**Issue by Krever** [typelevel/cats#3112]
Hey, I have

```
type X[T] = Kleisli[OptionT[F, *], Foo, T]
```
and would like to go from `(X[A], X[B])` to `X[Either[A, B]]`. 

So similar to what `<+>` does (e.g. in http4s) but on two different types joined by `Either`. Right now I `map` and use `<+>` afterwards.

Signature proposed by @LukaJCB :

```
def sum[F[_]: SemigroupK, Functor, A, B](fa: F[A], fb: F[B]): F[A Either B]
```

**Comment by pk044** [comment]
i'd be happy to give it a try :)
