### ISSUE TITLE
Add foldA, reduceMapA and reduceA

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#3141]

**Comment by Twizty** [comment]
Hi, I'd like to implement it.

**Comment by LukaJCB** [comment]
Hi @Twizty, go right ahead! You can have a look at https://github.com/typelevel/cats/pull/3130 for inspiration and do feel free to ask any questions you might have here or on the gitter channel :)

**Comment by Twizty** [comment]
@LukaJCB all these 3 methods should have the same signature as their monadic versions, but instead of `Monad[G]` they should have `Applicative[G]`?

**Comment by LukaJCB** [comment]
Pretty much, yeah :)

**Comment by travisbrown** [comment]
Done in #3150 and some follow-ups.
