### ISSUE TITLE
EitherT.fromMonadError

### ISSUE THREAD

**Issue by tg44** [typelevel/cats#3177]
I think #1644 is related.

Basicly something like:
```
import cats.implicits._
import cats.data.EitherT
import cats.MonadError

def fromMonadError[F[_], A, B](me: F[B])(implicit ev: MonadError[F, A]) = {
  EitherT(me.map(Either.right[A, B]).recover{case ex => Either.left[A, B](ex)})
}
```

Or if we have this functionality already maybe it would worth a mention in the EitherT/MonadError documentation.

If others think this is useful, I try to PR it :)

**Comment by djspiewak** [comment]
I think this is neat, though I believe it could be more simply implemented with `attempt`. Something like this:

```scala
def fromMonadError[F[_], E, A](fa: F[A])(implicit F: MonadError[F, E]): EitherT[F, E, A] =
  EitherT(F.attempt(fa))
```

It's kind of like a mechanism for lifting into a redundant signal channel. I do stuff like this semi-frequently; I'm curious if others do as well.

**Comment by joroKr21** [comment]
It comes up surprisingly often for me as well.

**Comment by fthomas** [comment]
It seems this already exists and is called [`attemptT`](https://github.com/typelevel/cats/blob/00ff6fe7107b895d5bb22875803cb8baa0fd0873/core/src/main/scala/cats/ApplicativeError.scala#L74-L78).

**Comment by tg44** [comment]
Nice! So can we add this to the EitherT docs?
