### ISSUE TITLE
More binary compatibility breakage

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3202]
Compile this with 2.0.0:

```scala
object Test {
  val instances = new cats.instances.AllInstancesBinCompat6 {}
  def main(args: Array[String]): Unit = println(
    instances.catsKernelStdHashForSortedSet(
      cats.kernel.instances.int.catsKernelStdOrderForInt,
      cats.kernel.instances.int.catsKernelStdOrderForInt
    )
  )
}
```

Then run it with 2.1.0-RC1 or RC2, and you get this:

```scala
Exception in thread "main" java.lang.NoSuchMethodError: cats.instances.SortedSetInstancesBinCompat1.catsKernelStdHashForSortedSet$(Lcats/instances/SortedSetInstancesBinCompat1;Lcats/kernel/Order;Lcats/kernel/Hash;)Lcats/kernel/Hash;
        at Test$$anon$1.catsKernelStdHashForSortedSet(Test.scala:2)
        at Test$.main(Test.scala:6)
        at Test.main(Test.scala)
        ...
```

This is the same basic issue as #3163 but my original MiMa fix didn't catch it. Working on a PR now.

**Comment by dwijnand** [comment]
> but my original MiMa fix didn't catch it

Could you share what other changes were needed?  I don't see anything more recent in https://github.com/travisbrown/mima/commits/topic/cats-3162-check.

**Comment by travisbrown** [comment]
@dwijnand The version in that branch is what caught these—I'd been through a few iterations of filtering out synthetics, etc. before then and I must not have tried the final version on Cats, just on my test cases.
