### ISSUE TITLE
Fix Scala.js Future tests

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3247]
Right now the Scala.js `FutureTests` use the `runNow` execution context, which was deprecated in Scala.js 0.6 and removed in 1.0. In #3246 I replace `runNow` with an equivalent implementation, since I want to unblock 1.0 compatibility, but this isn't a real solution (see e.g. [this issue](https://github.com/scala-js/scala-js/issues/2102) for discussion).

**Comment by larsrh** [comment]
Seems like this is not an issue any more.
