### ISSUE TITLE
Use imports for instances and syntax in tests

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3262]
Over the weekend I hit a [Dotty bug](https://github.com/lampepfl/dotty/issues/8033) while trying to run the Cats tests on Dotty, and while the workaround is pretty trivial, it highlighted the fact that our tests aren't really exercising normal usage, since the instances and syntax come from traits that are mixed into `CatsSuite` (rather than imported from the usual objects).

This feels like overengineering. It lets us avoid one import in each of our test files, but at the expense of testing instances in a way that doesn't represent what our users are actually doing.

**Comment by rossabaker** [comment]
I think I'm responsible for this in the early days, and I agree with you now.

**Comment by travisbrown** [comment]
Done in #3304.
