### ISSUE TITLE
how do i read documents offline?

### ISSUE THREAD

**Issue by mrParabol** [typelevel/cats#3286]
how do i read documents offline?help me, please.

**Comment by LukaJCB** [comment]
What do you mean by documents? The cats documentation?

**Comment by mrParabol** [comment]
yes, please cats's documention.

**Comment by vincenzobaz** [comment]
You can build the website with the documentation by running `sbt docs/makeMicrosite` inside the repository folder.
If you refer to the API documentation defined in scaladoc, you can run `sbt unidoc` inside the repository folder.
These procedures are described [here](https://typelevel.org/cats/contributing.html).
