### ISSUE TITLE
Add `Either.unit`

### ISSUE THREAD

**Issue by sirthias** [typelevel/cats#3343]
Working with `flatmap` stacks on `Either` I frequently find myself creating `Right(())` instances in cases where only the error channel is relevant.
For these it'd be great if `EitherObjectOps` came with this member:

```scala
val unit: Either[Nothing, Unit] = Right(())
```

which would help with reducing unnecessary allocations in application code.

As a consequence `EitherObjectOps` would have to be turned into an `object` (right now it's a value class) but I currently don't see any issue with that.

**Comment by joroKr21** [comment]
You can cache the `Right(())` somewhere and just delegate to it:
```scala
def unit: Either[Nothing, Unit] = cachedRightUnit
```

**Comment by sirthias** [comment]
Yes, that's what I'm currently doing.
However, IMHO `Either.unit` would the perfect "place" for such a cache.

**Comment by joroKr21** [comment]
It's too late for `Either.unit` in the std lib.

**Comment by sirthias** [comment]
Yes, that's why I'm proposing to add it to the `EitherObjectOps` in `cats.core`.

**Comment by rossabaker** [comment]
I've added a `RightUnit` to several projects, so I agree this would be nice.

Unless I misunderstand the approach, changing EitherObjectOps to an object would break binary compatibility.  We could add a def to a private, cached value.

It would also make sense to use it in the Applicative instance.

**Comment by sirthias** [comment]
> Unless I misunderstand the approach, changing EitherObjectOps to an object would break binary compatibility. We could add a def to a private, cached value.

Yes, right. As always I didn't think of breaking binary compat.
The delegate to a private cached value works even better then.

**Comment by rossabaker** [comment]
I wanted to prove to myself that the applicative part was right, and by that point, I had a working PR. :laughing:

I think your idea of changing it to an object would be viable in Cats 3.0.  The implicit would still need to wrap the `Either` companion, but the ops class doesn't need the reference and could therefore be an object if not for the bincompat concern.

**Comment by sirthias** [comment]
Yes, that was my thinking as well. 👍
