### ISSUE TITLE
Alternatives to #head for `NonEmpty*` classes

### ISSUE THREAD

**Issue by morgen-peschke** [typelevel/cats#3369]
One of the things which is comes up from time to time in code reviews is that it's not obvious if `foo.head` is a safe call to `NonEmptyList#head` or an unsafe call to `List#head`.

If it's something which would be helpful generally, I'd be happy to put together a PR adding a `safeHead` alias to the `NonEmpty*` classes to help cut down on the confusion.

**Comment by rossabaker** [comment]
I find that aliases tend to add more confusion than they resolve.  

What about using a linter?  I think warrmover's TraversableOps would catch this.

**Comment by morgen-peschke** [comment]
Unfortunately the linter we use (scalastyle) doesn't include this rule, and the one I'm familiar with that does (scapegoat) required too much TLC to keep working.

Did you mean [Wartremover](https://www.wartremover.org/) ?

**Comment by joroKr21** [comment]
That's a general problem with reviewing statically typed code. Ideally you should make use of types also when you review code. But the current tooling is not optimised for this. For example how do you know that a `.get` is called on a `ThreadLocal` and not on `Option`?

**Comment by rossabaker** [comment]
Yes, wartremover.  And yes, this is where a linter that runs after the typer is invaluable.  I've seen scalafix floated as a solution to this, but haven't found a standard set of rules that's easy to extend.

I'm still hesitant to add long term API for a short term deficit in tooling. I'd much rather we attack the latter problem.

**Comment by morgen-peschke** [comment]
Fair enough
