### ISSUE TITLE
WriterTInstances: insufficient prioritization?

### ISSUE THREAD

**Issue by chwthewke** [typelevel/cats#3385]
The following snippet:

```scala
  import cats.instances.int._

  Functor[Writer[Int, *]]
```

fails to compile with 

    [E]      ambiguous implicit values:
    [E]       both method catsDataCommutativeMonadForWriterT in class WriterTInstances of type [F[_], L](implicit F: cats.CommutativeMonad[F], implicit L: cats.kernel.CommutativeMonoid[L])cats.CommutativeMonad[[?$3$]cats.data.WriterT[F,L,?$3$]]
    [E]       and method catsDataTraverseForWriterTId in class WriterTInstances of type [L](implicit F: cats.Traverse[cats.Id])cats.Traverse[[?$5$]cats.data.WriterT[[A]A,L,?$5$]]
    [E]       match expected type cats.Functor[[?$0$]cats.data.WriterT[[A]A,Int,?$0$]]
    [E]      L9:   Functor[Writer[Int, *]]

It's a silly type, but one that I actually wanted to use for real (in tests).

It seems the two aforementioned methods might need to be be in different "levels" of the WriterTInstances "tower"? To be honest, I'm quite a bit handwavy on how these work _exactly_, also I have not a single clue on the bincompat implications, so I'm not really able to suggest a fix in a more precise fashion.

Thank you for your consideration

**Comment by djspiewak** [comment]
I agree this is a real issue. They should be factored across two traits.

**Comment by barambani** [comment]
I'll look into this
