### ISSUE TITLE
`EitherT.pure` does not call `F.pure` on the 'Right' value

### ISSUE THREAD

**Issue by aherrmann13** [typelevel/cats#3398]
`EitherT.pure` (and `EitherT.rightT`) does not have the same behavior as `EitherT.leftT`

`EitherT.rightT`calls `EitherT.pure`, which calls `right(F.pure(b))`, which results in `EitherT(F.map(F.pure(b))(Right(_)))`

`EitherT.leftT` calls `EitherT(F.pure(Left(a)))`

when using `IO` the execution of converting `F[B] => F[Either[A, B]]` is delayed until IO is run on `EitherT.pure` and `EitherT.rightT` and it is not delayed on `EitherT.leftT`

Is there a reason for having `pure` as an alias for `rightT`, and evaluating `F.pure(a)` and then converting it to a `Right` value with `map` instead of using `EitherT(F.pure(Right(b)))`?

**Comment by joroKr21** [comment]
I think we should use the more performant version 👍
