### ISSUE TITLE
Macro Error in FunctionK.lift

### ISSUE THREAD

**Issue by channingwalton** [typelevel/cats#3400]
Hi,
I was wrapping doobie's liftIO in FunctionK:

```scala
val lifter: FunctionK[IO, ConnectionIO] = FunctionK.lift(Async[ConnectionIO].liftIO)
```

and got

```scala
Error:(24, 80) Unexpected tree {
  <synthetic> val eta$0$1: cats.effect.Async[doobie.free.connection.ConnectionIO] = cats.effect.Async.apply[doobie.free.connection.ConnectionIO](free.this.connection.AsyncConnectionIO);
  ((ioa: cats.effect.IO[Nothing]) => eta$0$1.liftIO[Nothing](ioa))
} when lifting to FunctionK
  val lifter: FunctionK[IO, ConnectionIO] = FunctionK.lift(Async[ConnectionIO].liftIO)
```

This fixed it:

```scala
val acio = Async[ConnectionIO]
val lifter: FunctionK[IO, ConnectionIO] = FunctionK.lift(acio.liftIO)
```

@milessabin suggested the macro might have been confused about whether it was supposed to be looking at the Async.apply or the liftIO.

**Comment by kailuowang** [comment]
There have been some attempts to replace that macro with non macro solutions, but they fell short on being fully backward compatible. 
But I think cats remains committed to remove all macro usages in the code base to ease transition to Scala 3. 
In short, this issue is probably low priority.

**Comment by joroKr21** [comment]
I think it's confused by the eta-expansion.

**Comment by channingwalton** [comment]
Awesome, thank you.
