### ISSUE TITLE
Missing TupleK Semigroupal

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#3410]
I don't see an implementation (although there is ContravariantMonoidal, which is more constrained).

I'll plan to send a PR, but if anyone sees a reason why this can't exist, please feel free to let me know.

**Comment by johnynek** [comment]
this seems to work just fine, and I think is lawful:
```scala
  implicit def semigroupalTuple2K[F[_]: Semigroupal, G[_]: Semigroupal]: Semigroupal[Tuple2K[F, G, *]] =
    new Semigroupal[Tuple2K[F, G, *]] {
      def product[A, B](left: Tuple2K[F, G, A], right: Tuple2K[F, G, B]): Tuple2K[F, G, (A, B)] =
        Tuple2K(
          Semigroupal[F].product(left.first, right.first),
          Semigroupal[G].product(left.second, right.second))
    }

```

**Comment by rmehri01** [comment]
Hi, I can try to add this. Just one thing, why are there so many Tuple2KInstances (the abstract classes)? I'm guessing there's some structure to them?

**Comment by rmehri01** [comment]
Hi, I can try adding this.
