### ISSUE TITLE
Add a fproductLeft function to Functor

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#3414]
Currently we have `def fproduct[A, B](fa: F[A])(f: A => B): F[(A, B)]` on `Functor`, it'd be nice to also have one that tuples on the other side, i.e.
`def fproductLeft[A, B](fa: F[A])(f: A => B): F[(B, A)]`

**Comment by pk044** [comment]
i could take this one :)

**Comment by LukaJCB** [comment]
@pk044 go for it! :)
