### ISSUE TITLE
Describe example questions at top of nomenclature page.

### ISSUE THREAD

**Issue by arosien** [typelevel/cats#3460]
[Comment from reader](https://gitter.im/typelevel/general?at=5ede73972c49c45f5ace5711):

> Should these three questions be on the nomenclature page? They look like they’re supposed to be on FAQ. There is no answer and they just kind of float there:
>
> What is the difference between unit and void?
> To discard the first value and keep only the first effect, is it <* or *>?
> How do I make a computation F[A] fail by checking a condition on the value?

https://typelevel.org/cats/nomenclature.html

This page could preface those questions the paragraph that currently follows them:

> This is a catalogue of the major functions, type classes, and data types in Cats. It serves as a bird’s-eye view of each class capabilities. It is also intended as a go-to reference for Cats users, who may not recall the answer to questions like **these:**
>
> <insert questions here>

☝️ suggested copy

**Comment by rmehri01** [comment]
Hi, I'd like to help with this! Just to clarify, do you mean these questions should be moved to FAQ or just moved below the paragraph you suggested?

**Comment by arosien** [comment]
I meant the latter, move the questions below the suggested paragraph. (And make the questions a regular font size, not the giant size it is now)

**Comment by arosien** [comment]
And thanks for your help!

**Comment by rmehri01** [comment]
Ah okay, no problem :)
