### ISSUE TITLE
Consider fine-granularity of typeclass instances

### ISSUE THREAD

**Issue by japgolly** [typelevel/cats#349]
This is just a suggestion. First, some background: Scala.JS compiles to JS using two alternate methods of generation: fast and full. One of the tools employed by full optimisation to produce small output is whole program optimisation. Only code that your entry point(s) transitively touch are included; the rest is discarded.

What this means for Cats specifically, is that when one uses a typeclass instance, everything accessible by said instance is included. Consider this snippet:

``` scala
trait StreamInstances {
  implicit val streamInstance: Traverse[Stream] with MonadCombine[Stream]
with CoflatMap[Stream] =
```

If one's app only needs `Traverse[Stream]`, by this definition `MonadCombine`, `CoflatMap` and their combined transitive dependency graphs are now included in the output JS despite the lack of use. If Cats' typeclasses are split like below, then the resulting JS size can be reduced, in some cases quite significantly.

``` scala
trait StreamInstances {
  implicit val streamTraverse: Traverse[Stream] = …
  implicit val streamMonadCombine: MonadCombine[Stream] = …
  implicit val streamCoflatMap: CoflatMap[Stream] = …
```

(I had the same experience with Scalaz already in ScalaCss; users whinged and whined for days. Output size isn't something I'm (we're) used to normally considering but it does come with the territory in JS-land.)

/cc @InTheNow

**Comment by InTheNow** [comment]
@japgolly Thanks for raising this issue and the /cc. For others, it's based on [this gitter chat] (https://gitter.im/japgolly/scalajs-react?at=557d4fee7d5adaae3b4efe39) that is the gitter for his scala.js interface to [facebook's react framework](https://facebook.github.io/react/)

What I think is really of interest to Cats is a real test case for cat's modularity in scala.js on a popular library. But as @japgolly has already stated, he does not have the bandwidth for direct help, in the same way that @milessabin said he was happy to add support to shapeless for scalajs _providing_ someone else took ownership of the sjs parts.

As @japgolly was one of those that did that, and [maintained the fork previously](https://github.com/japgolly/shapeless), I wonder if cats could benefit from a similar approach: fork [scalajs-react](https://github.com/japgolly/scalajs-react), port it to cats and show that the modularity works? And @japgolly can focus on his other stuff.

(might need to wait for https://github.com/japgolly/scalajs-react/issues/145 but that's OK as we/I have not got cats fully onto scala.js yet )

**Comment by japgolly** [comment]
Oh I don't mean this in relation to `IO` - that's separate *(and I ended up decided in japgolly/scalajs-react#145 we're going be self-sufficient there - maybe even entirely decoupled from Scalaz (and Cats) with those being ext modules)*.

I meant this just as a general point when using Cats with any Scala.JS lib. It was actually https://github.com/japgolly/scalacss/issues/17 I was thinking of. :smile:

**Comment by InTheNow** [comment]
Wow - so that's two use cases then :+1:

**Comment by non** [comment]
@japgolly That's a great observation. I'll look into splitting up the instances where it makes sense.

**Comment by InTheNow** [comment]
:+1:  for this to be added to release 0.1.0 (will also be useful for banana-rdf, btw)

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. I think that it raises some good points, but there are lots of competing factors such as implicit ambiguities, and at this point Cats can't make significant changes in this regard due to compatibility constraints.
