### ISSUE TITLE
Future instances not in implicit scope

### ISSUE THREAD

**Issue by mrdziuban** [typelevel/cats#3536]
Importing `cats.instances.future._` is still required to summon typeclass instances for `scala.concurrent.Future`, e.g.

```scala
import cats.Applicative
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global

Applicative[Future]
// Could not find an instance of Applicative for scala.concurrent.Future

import cats.instances.future._

Applicative[Future]
// cats.Applicative[concurrent.Future] = cats.instances.FutureInstances$$anon$1@479111ba
```

This was the only `cats.instances` import I needed to keep around when upgrading a large codebase that strictly uses a la carte imports from v2.1.1 to v2.2.0-RC2.

**Comment by LukaJCB** [comment]
Thanks for bringing this up! Will have a look soon

**Comment by travisbrown** [comment]
I believe there was some discussion about this somewhere, and that excluding them was a design decision, but I don't remember the details, and I'm not committed to either including or excluding them from implicit scope.

**Comment by barambani** [comment]
This https://github.com/typelevel/cats/issues/2334 may or may not be what @travisbrown is referring to, but I'm adding it here for reference as that discussion is still open and marked for milestone 3.0

**Comment by barambani** [comment]
Referencing relevant discussion here https://github.com/typelevel/cats/pull/3566#issuecomment-674367117
