### ISSUE TITLE
Scalafix rule to help migration to 2.2.0

### ISSUE THREAD

**Issue by cb372** [typelevel/cats#3563]
I'm really looking forward to upgrading to 2.2.0 and deleting all my `cats.instances.*` imports!

Is it worth providing an official scalafix rule to help people do this?

It could be just a simple grep to delete all `import cats.instances.*` lines, or it could be a bit smarter and also delete `import cats.implicits._` lines that are only being used to import instances, not syntax.

**Comment by cb372** [comment]
Started work on a rule here: https://github.com/cb372/cats/tree/scalafix-rules-2.2.0

Now I just need to draw the rest of the owl...

**Comment by joroKr21** [comment]
There was an issue with `Future`'s instances through.

**Comment by cb372** [comment]
Yes, I saw the discussion about that. I think it should be pretty simple to make the rule do special handling for `Future` instances.

**Comment by fthomas** [comment]
It would be great to add this migration rule to [Scala Steward](https://github.com/scala-steward-org/scala-steward/blob/master/docs/scalafix-migrations.md) so that it can be used for the PRs that update Cats to 2.2.0.

**Comment by cb372** [comment]
Sure! If my PR gets merged, I'll make a PR to add it to Scala Steward.
