### ISSUE TITLE
Override *> / <* in Monad

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#3584]
At present, they delegate down to `ap` and `pure` and `Function1`, which in turn delegates down to `flatMap`. It would be a nice efficiency win to override these to correspond directly to `flatMap`, similar to `>>`

**Comment by SimY4** [comment]
Can I take a stab at this one?

**Comment by LukaJCB** [comment]
Go for it!

**Comment by SimY4** [comment]
I experimented a bit with this and it seems that cats 2.1.1 is already working like you suggested.

`Apply` methods `productL` and `productR` already overridden in `FlatMap` so whenever you use `Apply` syntax for `Monad` or `FlatMap` type class, you get `flatMap` semantics there.

Or maybe I misunderstood the problem.

**Comment by Wosin** [comment]
I think the idea here is to overwrite the `*>` and `<*` inside `Monad` to directly call `flatMap`, but correct me if I'm wrong @djspiewak

**Comment by SimY4** [comment]
@Wosin @djspiewak that's what already happening. `<*` and `*>` are just syntax extensions for Apply.productL and Apply.productR which has overrides in `FlatMap` type class. I believe Monad can't make them more effective that implementation provided in FlatMap.

**Comment by JosephMoniz** [comment]
Ah yeah, `productR` and `productL` already are overridden on `FlatMap` here:
https://github.com/typelevel/cats/blob/76edb1094331e610e4913ad3c0e393e066bbf373/core/src/main/scala/cats/FlatMap.scala#L100-L104

The question is, do these overrides get picked up and used when a `FlatMap` instance is in scope?

**Comment by SimY4** [comment]
@JosephMoniz yes, if `FlatMap` is in scope.

**Comment by djspiewak** [comment]
Ah interesting! I'm not sure why I was seeing the non-overridden variants in my testing, but they are clearly there. I'm going to close this because Monad can't do any better than what's already in FlatMap.
