### ISSUE TITLE
Add `.sum` method on Foldables using `scala.Numeric`

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#3643]
It would be good to have to enable summing NonEmptyLists like standard collections, similarly with other structures.

**Comment by kubukoz** [comment]
cc @hmemcpy

**Comment by hmemcpy** [comment]
Thanks! Yeah, I migrated some code from `List` to `NonEmptyList` and had to scratch my head for a second about `.sum` being an extension for `SemigroupK`. Replaced with `.reduce` and carried on, but it would be good to have `.sum` on a NEL that works as `List.sum`

**Comment by kubukoz** [comment]
Oh no, I didn't realise it was SemigroupK syntax... we'll need to find another name to avoid conflict, then.

**Comment by kubukoz** [comment]
I would suggest `addAll`.

And now that I think about it, we should have `product` too, but that's definitely overloaded as well from Semigroupal. So I'm thinking `addAll` / `multiplyAll` or `sumAll` / `productAll`.

**Comment by Lealea9** [comment]
Lange hab ich mich mit den Codes rumgeschlagen, jetzt beschäftige ich mich lieber mit Eigentumswohnungen. Zum Beispiel die von [www.vandenberg-berlin.de/eigentumswohnungen/](url).

**Comment by LukaJCB** [comment]
Deleted a comment that was spam

**Comment by johnynek** [comment]
I would really rather we not use scala.Numeric. I think we should instead be using Ring from algebra, which we have talked about merging into this repo as a separate subproject.

**Comment by GrigoriiBerezin** [comment]
Maybe we can use Semigroup in case the algebra is not merged into this repo yet?
