### ISSUE TITLE
Add `grouped` to NonEmptyCollection

### ISSUE THREAD

**Issue by bbstilson** [typelevel/cats#3650]
I chatted with @johnynek on Gitter about adding this. For example, in Scala one can call `grouped` on any `Iterable`:

```scala
@ val xs = List(1,2,3,4) 
xs: List[Int] = List(1, 2, 3, 4)

@ xs.grouped(2).toList 
res1: List[List[Int]] = List(List(1, 2), List(3, 4))
```

My current plan is for grouped to return an `Iterable[NE[A]]`, but I'm also open to returning the same collection type, e.g.,`NE[NE[A]]`. As for handling invalid grouped size, I am open to ideas. I'm not a fan of throwing exceptions. One option is to make the name obvious, something like `unsafeGrouped`. Another is to return some error handler like `Either`, e.g., `Either[Iterator[NE[A]]]`.

A (likely bad) option would be to use a Refined type like:

```scala
def grouped[A](size: Int Refined Positive): Iterator[NE[A]]
```

This is a bad option as bringing in another library is likely not desirable.

**Comment by kubukoz** [comment]
I think we'll be fine with a runtime check on `size`, we do that on `Monoid.combineN`, AFAIK. Users will be able to use a refined type on their own, plus `refined.auto._` for convenient auto-unwrapping.
