### ISSUE TITLE
Unapply syntax for nested/specific types

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#367]
There are certain `Ops` classes that have special constraints of the type that they wrap. In many cases they require a nested type, but there are also other types of requirements.

Currently these types don't have `*SyntaxU` conversions to make them compatible with `Unapply`-aided implicit lookup.

Here are the `Ops` classes that I see currently falling into this category:
`FlattenOps`, `IfMOps`, `NestedFoldableOps`, `NestedMonadCombineOps`, `NestedReducibleOps`, `NestedTraverseOps`.

As an example, the `flatMapSyntaxU` method exists to wrap an `FA` in a `FlatMapOps` object. However, there is no corresponding `flattenSyntaxU` method to convert to a `FlattenOps` object.

I don't know how this fits into potential future Simulacrum usage.

**Comment by eed3si9n** [comment]
[day9]: http://eed3si9n.com/herding-cats/monadic-functions.html

Does `F[A, ?]` fit into this? From [herding cats day 9][day9]:

```scala
scala> import cats._, cats.std.all._, cats.syntax.flatMap._
import cats._
import cats.std.all._
import cats.syntax.flatMap._

scala> import cats.data.Xor
import cats.data.Xor

scala> val xorOfXor = Xor.right[String, Xor[String, Int]](Xor.right[String, Int](1))
xorOfXor: cats.data.Xor[String,cats.data.Xor[String,Int]] = Right(Right(1))

scala> xorOfXor.flatten
<console>:23: error: value flatten is not a member of cats.data.Xor[String,cats.data.Xor[String,Int]]
              xorOfXor.flatten
                       ^
```

**Comment by ceedubs** [comment]
@eed3si9n that actually corresponds exactly to the example I gave: a lack of `flattenSyntaxU`. We have syntax on some `F[A, ?]` cases, but not on this nested one: `F[A, F[A, ?]]`. I don't think that last part is actually valid kind-projector syntax for what I mean, but hopefully you know what I mean

**Comment by ceedubs** [comment]
Currently our `flattenSyntax` requires an `F[F[A]]` which doesn't get picked up for type constructors with two type parameters without Unapply help. It looks like scalaz approaches this a little different by using `F[A]` and separate evidence that `A <~< F[B]`.

**Comment by ceedubs** [comment]
Resolved by `-Ypartial-unification`!
