### ISSUE TITLE
addLeft/addRight convenience methods for Iors?

### ISSUE THREAD

**Issue by keirlawson** [typelevel/cats#3689]
Whilst contributing to a cats-based codebase that makes extensive use of Iors (https://github.com/gemini-hlsw/gsp-graphql/pull/96) I found myself needing a "addLeft" function, which given an Ior would either `combine` the new value with the existing LHS or in the case where it was a `Right`, turn it in to a `Both` with the new value on the left, ie

```scala
  def addLeft[A: Semigroup, B](ior: Ior[A,B], a: A): Ior[A, B] = ior match {
    case Ior.Right(r) => Both(a, r)
    case Both(l, r) => Both(l combine a, r)
    case Ior.Left(l) => Ior.left(l combine a)
  }
```

Would this be something that would make sense to include within Cats itself?

**Comment by LukaJCB** [comment]
Sounds like a good addition to me :)
