### ISSUE TITLE
Sponsor logos are broken in README (and on website)

### ISSUE THREAD

**Issue by larsrh** [typelevel/cats#3690]
![Screenshot_2020-11-22 Cats Home](https://user-images.githubusercontent.com/923079/99906303-96d38480-2cd6-11eb-8a89-613c4b020e21.png)

**Comment by arosien** [comment]
https://github.com/typelevel/cats/tree/gh-pages/img doesn't contain the `sponsors` subdirectory, so I suspect they weren't copied during the build of the site. However, the source for sbt-microsites hints that [the image directory _should_ be copied recursively](https://github.com/47degrees/sbt-microsites/blob/6fd0ac6bde9187d3aee56e3e45e8b4064960d612/src/main/scala/microsites/util/MicrositeHelper.scala#L114), so I'm confused.

**Comment by arosien** [comment]
FYI the images are ok on in the README, but are still broken on the website, which as noted above, is probably something to do with the site packaging.

**Comment by rossabaker** [comment]
I'm very sorry for the delay.  This is the first I've seen this, and I am allergic to Jekyll, but I'm digging in now.

The site hasn't been published since April.  I'm going to try to build it locally, and if that works, manually republish.

**Comment by rossabaker** [comment]
Well, it's not copying them locally, either.

**Comment by rossabaker** [comment]
I took the image directory produced by #3956 and manually synchronized that directory on the gh-pages branch.  It's loading for me now.

If anything else got overlooked, please let us know.

**Comment by arosien** [comment]
Thanks @rossabaker!!!!!! I do worry, however, that the next update will run into the same problem. Any tips that could be documented?

**Comment by arosien** [comment]
FYI there are non-sponsor broken images with the URL https://placehold.it/15/f03c15/000000?text=+. New issue?

**Comment by rossabaker** [comment]
For the individuals?  I'm not seeing anything with that URL in the source.  New issue would be good.

I think the linked PR will make sure that this fix doesn't get reverted, provided that there is no release before the merge.  If it doesn't attract a review soon, I'll merge by fiat before it gets forgotten.
