### ISSUE TITLE
Potential trait encoding binary compatibility issues

### ISSUE THREAD

**Issue by larsrh** [typelevel/cats#3719]
Since #3596, MiMa recognizes more potential binary compatibility issues. The cause for those is documented in that PR.

Eventually we should try to fix these problems, possibly in Cats 2.4.0.

```
exclude[NewMixinForwarderProblem]("cats.kernel.Band#mcI#sp.combineN"),
exclude[NewMixinForwarderProblem]("cats.kernel.Band#mcD#sp.combineN"),
exclude[NewMixinForwarderProblem]("cats.kernel.Band#mcJ#sp.combineN"),
exclude[NewMixinForwarderProblem]("cats.kernel.Band.combineN"),
exclude[NewMixinForwarderProblem]("cats.kernel.Band#mcF#sp.combineN"),
exclude[NewMixinForwarderProblem]("cats.data.Tuple2KApply.product"),
exclude[NewMixinForwarderProblem]("cats.InvariantInstances0.catsApplicativeForArrow")
```

**Comment by armanbilge** [comment]
With modern cats/mima only `exclude[NewMixinForwarderProblem]("cats.kernel.Band.combineN")` is still relevant. Unfortunately I don't think it's possible to fix bincompat here without breaking override semantics, see https://github.com/typelevel/cats/pull/4204#issuecomment-1120151360.
