### ISSUE TITLE
EitherT scaladoc

### ISSUE THREAD

**Issue by majk-p** [typelevel/cats#3741]
Current description of `EitherT.rethrowT` says:  
> Inverse of `MonadError#attemptT`

When you look at `attempT` it's:
> Similar to [[attempt]], but wraps the result in a [[cats.data.EitherT]] for convenience.

And then `attempt`'s scaladoc actually explains the behavior. This introduces unnecessary difficulty of learning Cats to newcomers. 

I'd like to extend `EitherT.rethrowT`'s scaladoc with something like:
```
  /**
   * Inverse of `MonadError#attemptT`
   * Given MonadError[F, E :> A] transforms Either[F, A, B] to F[B]
   * If the value was B, F[B] is successful
   * If the value was A, F[B] is failed with E
```

WDYT? If it's okay, I'll prepare a PR.

**Comment by LukaJCB** [comment]
I think that would make a very reasonable addition, thank you @majk-p :)

**Comment by majk-p** [comment]
@LukaJCB great, the PR is ready :wink:
