### ISSUE TITLE
Functor: rename the `as` operator.

### ISSUE THREAD

**Issue by diesalbla** [typelevel/cats#3755]
Scala 3 has redefined `as` as a keyword for pattern-matching, _as_ an alternative to the `@` operator.
https://github.com/lampepfl/dotty/issues/9829

The `Functor[F]` typeclass defines a method also called `as`, that we need to rename.

```Scala
def as[A](ff: F[_], c: A): F[A] = map(ff)(_ => c)
```

Here are some possible names, to open some suggestions:

- Haskell-inspiration: `$>` operator. https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Functor.html#v:-36--62-
- `fill`: in a (_not even wrong_) view of `Functors` as a form of containers, this operator is just refilling the container with a constant value. 
- `asConst`
- `toConst`

**Comment by mpilquist** [comment]
`as` is a soft keyword in Scala 3 and hence we don't need to deprecate it on Functor.

**Comment by diesalbla** [comment]
> as is a soft keyword in Scala 3 and hence we don't need to deprecate it on Functor.

Provided that we may keep using `as` for this purpose, without 

1. Do we want to keep a possible confusion with the Scala language? No keyword is 
2. Is the `as` word the best name we can give this method? Normally, saying "take string as key" means that the string is the key; but this operator is about _modifying_ the contents or returns of the `F` to replace it with a constant value...

**Comment by mpilquist** [comment]
I'm definitely in favor of keeping `as` as-is. :)

That's why I clarified this on the PR that introduced the soft keyword: https://github.com/lampepfl/dotty/issues/9829#issuecomment-695786657

I suspect there might be other conflicts with other new soft keywords as well, but haven't gone through them exhaustively.

**Comment by djspiewak** [comment]
I think that we would probably choose a different name here for Cats 3, which is intended to be Scala 3-only, but we can just embrace the soft keyword for Cats 2.x

**Comment by mpilquist** [comment]
We can debate during Cats 3 development, but I'd object to changing `as` even then. The cost of changing such a commonly used name isn't worth the added clarity of new name.

**Comment by rossabaker** [comment]
I also am unsure that it is even still a soft keyword as of M3: https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html#drop-as-in-patterns
