### ISSUE TITLE
Provide BoundedEnumerable[Byte] instance

### ISSUE THREAD

**Issue by ashleymercer** [typelevel/cats#3756]
Following on from https://github.com/typelevel/cats-collections/issues/315 it seems that there is no `BoundedEnumerable[Byte]` instance but I think it should be easy to provide (following the same pattern as `Int`, `Long` and so on).

I'm happy to try to put together a PR for this, although might need some guidance on binary compatibility if it's an issue, since the obvious fix would be to make:

```scala
implicit val catsKernelStdOrderForByte: Order[Byte] with Hash[Byte] with LowerBounded[Byte] with UpperBounded[Byte]
```

into

```scala
implicit val catsKernelStdOrderForByte: Order[Byte] with Hash[Byte] with BoundedEnumerable[Byte]
```

**Comment by rossabaker** [comment]
I think that will be binary compatible.  Trying it and running `mimaReportBinaryIssues` is the way to be sure.

If it doesn't work, a strategy I've used before is to make the old value explicit and deprecated, and create the new implicit that you want.   But I don't anticipate that being necessary here.

**Comment by ashleymercer** [comment]
@rossabaker `mimaReportBinaryIssues` came back clean so we should be good to go - thanks :)
