### ISSUE TITLE
NonEmptyChain.toList?

### ISSUE THREAD

**Issue by ean5533** [typelevel/cats#3763]
When working with non-cats APIs I often find myself converting `NonEmptyChain`s into `List`s via `nec.toChain.toList`. I'm mildly surprised that this doesn't already exist in NEC:

```
final def toList: List[A] = toChain.toList
```

Is there a good reason not to add it?

**Comment by Slakah** [comment]
It's worth mentioning that due to all the `NonEmpty*` stuff having a `NonEmptyReducible` typeclass, a `toList` syntax will be available with an import.

In ammonite:

```scala
@ import $ivy.`org.typelevel::cats-core:2.3.1`
import $ivy.$

@ import cats.data._
import cats.data._

@ import cats.syntax.all._
import cats.syntax.all._

@ NonEmptyChain.one(1).toList
res3: List[Int] = List(1)

@ NonEmptySeq.one(1).toList
res4: List[Int] = List(1)
```

**Comment by ean5533** [comment]
Yup, that works, thanks.
