### ISSUE TITLE
Spark friendliness

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#377]
I think that playing nice with Spark would/will be a big win for Cats.

I believe our [serializable tests](https://github.com/non/cats/blob/master/laws/src/main/scala/cats/laws/discipline/SerializableTests.scala) are ensuring that our typeclass instances can be serialized and used in Spark. However, I just wanted to make sure that someone had actually tried using Cats with Spark before we advertised that it's Spark-friendly.

If it is Spark-friendly, we should advertise this fact in a prominently visible section of the docs.

@adelbertc I know that you had some interest in this. Have you tried it out at all?

**Comment by non** [comment]
So one thing we definitely need to do is cross-build for 2.10. I am submitting a PR to add that.

**Comment by adelbertc** [comment]
We could maybe start a Spark sub-project in this repo (or perhaps another one?) with a simple Spark application (or several) that uses Cats that we may able to test against some Spark cluster?

**Comment by non** [comment]
I just created a project that provides a few instances for Spark, and more importantly tests using some of our instances inside a Spark job: https://github.com/non/big-electric-cat.

**Comment by non** [comment]
IMO we shouldn't include anything spark-specific in Cats itself, but I'm happy to collaborate with folks in that (hastily thrown together) repo.

**Comment by tpolecat** [comment]
I approve of the project name.

**Comment by ceedubs** [comment]
@adelbertc @non would you say that cats qualifies as Spark-friendly at this point? I'm wondering if we can close out this issue, but I have no experience with Spark.

**Comment by non** [comment]
Yes -- I think Cats is doing everything it needs to, and there is an integration project (https://github.com/adelbertc/frameless) that is getting some love.
