### ISSUE TITLE
Google Plus Logo Broken Link

### ISSUE THREAD

**Issue by benkio** [typelevel/cats#3830]
![image](https://user-images.githubusercontent.com/4698396/111054165-26f23100-8462-11eb-8760-d578b77fe695.png)

**Comment by djspiewak** [comment]
Should probably just remove it since G+ no longer exists.

**Comment by chaitanyawaikar** [comment]
I looked into the code and I can nowhere find any references for `google plus`, or even `twitter` or `Watchers`. 
The library `sbt-microsites` seems to be performing some kind of magic as I was not able to even locate any images for the given icons :(

**Comment by chaitanyawaikar** [comment]
I cannot find any references of `Google Plus` or even `Twitter` or `Watchers` in the code. Moreover, I tried to find the `.svg` for the files present in the header, but could not find them. I believe there is some high level abstraction provided by the `mdoc` library and without knowing it, it is difficult to make progress here. Any help will be highly appreciated. Thanks

**Comment by rossabaker** [comment]
It was in [sbt-microsites](https://github.com/47degrees/sbt-microsites/commit/37b5f97cace0a79ccd54b70d6da6722ecace4ea0#diff-3f1cb76fd03a6d69fa37b46b5ad1b2400e6961ef769d45700b368f0dc2f4a831).  I think we just need to republish the site on a version >= 1.3.2.

**Comment by chaitanyawaikar** [comment]
@rossabaker Does this require any code changes ? I can see that the `sbt-microsites` version is already `1.3.3`

**Comment by rossabaker** [comment]
I don't think so.  I think republishing the site would be enough.

**Comment by tnielens** [comment]
How can that be done?  #3645 notes that the site updates haven't been published since November 2019.

**Comment by larsrh** [comment]
I've just redeployed the website.
