### ISSUE TITLE
Update 'Jump Start Guide' page to modern cats

### ISSUE THREAD

**Issue by Daenyth** [typelevel/cats#3849]
https://typelevel.org/cats/jump_start_guide.html

The page is written for cats 1.0.1 and contains advice about using a-la-carte syntax imports (generally considered a bad practice), and has sections on instance importing (obsolete).

We should update the recommendations to use modern style and streamline the page.

**Comment by chaitanyawaikar** [comment]
I can pick this up.

**Comment by Daenyth** [comment]
Thanks!

**Comment by chaitanyawaikar** [comment]
Created this PR https://github.com/typelevel/cats/pull/3851

**Comment by haaami01** [comment]
Tank You

**Comment by ExpandingShapes** [comment]
I think the issue can be closed now
