### ISSUE TITLE
some tuple syntax doesn't work in Scala 3

### ISSUE THREAD

**Issue by tpolecat** [typelevel/cats#3874]
I don't know how general this is, but functor syntax for tuples don't work in Scala 3 (tested with 3.0.0-RC3). The instance is there but the syntax doesn't work.

```
scala> import cats.syntax.all._

scala> cats.Functor[(String,*)].map(("abc", 1))(_ + 1)                                                                                                                                              
val res0: (String, Int) = (abc,2)

scala> ("abc", 1).map(_ + 1)
1 |("abc", 1).map(_ + 1)
  |               ^
  |     Missing parameter type
  |
  |     I could not infer the type of the parameter _$1 of expanded function:
  |     _$1 => _$1 + 1.

scala>
```

**Comment by smarter** [comment]
It's because the map defined on Tuple takes priority, and that map is polymorphic: https://github.com/lampepfl/dotty/blob/3d8b6a1df0b316b7c2d8be72085478dc6606d4ec/library/src/scala/Tuple.scala#L54

**Comment by tpolecat** [comment]
Ok I guess the solution is to use `fmap`.

**Comment by smarter** [comment]
It's very awkward but you can also do something equivalent with the polymorphic map:
```scala
    type MapInt[T] = T match {
      case Int => Int
      case Any => T
    }
    
    ("abc", 1).map[MapInt]([t] => (x: t) => (x match {
      case x: Int => x + 1
      case x: Any => x
    }): MapInt[t])
```
The match type is needed to map subtypes of `Int` like `1` to `Int` and the `: MapInt[t]` ascription is needed for inference to figure out what's going on (but it shouldn't need to really).
