### ISSUE TITLE
The cats friendly badges disappeared

### ISSUE THREAD

**Issue by froth** [typelevel/cats#3882]
https://typelevel.org/cats/img/cats-badge.svg returns 404, did the url change or is it gone for good?

**Comment by kubukoz** [comment]
Noticed this today, the file is indeed gone on the `gh-pages` branch...

**Comment by kubukoz** [comment]
https://github.com/typelevel/cats/pull/3863 could be related too

**Comment by joroKr21** [comment]
Hmm why do you think #3863 is related 🤔

**Comment by kubukoz** [comment]
I think it _could_ 😅 like maybe the syntax change resulted in different handling of operator precedence? Probably not though, could be a red herring.

**Comment by rossabaker** [comment]
This was also fixed by what I did in #3690, and a more persistent fix is proposed in #3956.
