### ISSUE TITLE
Deprecate and remove `ifA`

### ISSUE THREAD

**Issue by chuwy** [typelevel/cats#3889]
I recently ran into a very dangerous bug thinking `ifM` and `ifA` have the same semantics. It can be repdocued with:

```scala
def test[F[_]: Sync] =
  Ref.of[F, Map[Boolean, Unit]](Map.empty).flatMap { ref =>
    Sync[F].pure(true).ifA(
      ref.update { c => c ++ Map(true -> ())},
      ref.update { c => c ++ Map(false -> ())}
    ) *> ref.get
  }

@ test[IO].unsafeRunSync()
res6: Map[Boolean, Unit] = Map(true -> (), false -> ())
```

I'd argue that we never ever ever want to use this just with `IO`. But it's not much better (at first glance) with other data types:

```scala
@ true.some.ifA(true.some, false.some)
res0: Option[Boolean] = Some(true)

@ true.some.ifA(true.some, none)
res1: Option[Boolean] = None

@ true.some.ifA(none, false.some)
res2: Option[Boolean] = None
```

I do understand now that this is an intended behavior of executing all three effects and we simply cannot do what I wanted to do with `Applicative` (we can though with [selective functors](https://github.com/typelevel/cats/issues/2745), https://github.com/kowainik/validation-selective), but I still think the potential risk overweight the usefulness -also  just grepp'ed few popular projects (doobie, http4s, fs2) and nobody uses it it seems.

Assuming the [decision has been made](https://gitter.im/typelevel/cats?at=609d5020c6359264b1af58eb) I can create a PR deprecating it.

**Comment by benhutchison** [comment]
4 years later, went to use `ifA` and noticed it was deprecated... curious.. git blame.. followed the thread... 

It is quite a surprising behavior, and I'm glad there was a warning. `ifM` is what I intended. Thanks @chuwy
