### ISSUE TITLE
MonadError missing a raiseWhen method

### ISSUE THREAD

**Issue by qwbarch** [typelevel/cats#3912]
Is there a reason for [IO#raiseWhen](https://github.com/typelevel/cats-effect/blob/b54a38483376c0a5050593c0174aa5b3b5680ed9/core/shared/src/main/scala/cats/effect/IO.scala#L1128) being omitted from ``MonadError``?  
MonadError has [ensure](https://github.com/typelevel/cats/blob/303f2a648df72939ad3c3bbc17ebc6960598680f/core/src/main/scala/cats/MonadError.scala#L13), but if ``[A]`` is ``Unit``, this is more verbose compared to ``raiseWhen``.

For example using ``raiseWhen``:
```scala
IO.raiseWhen(condition)(expression)
```
Versus using ``ensure``:
```scala
MonadThrow[F].unit.ensure(exception)(_ => condition)
```

If adding this method to ``MonadError`` is a welcome change, I'd like to make a PR for it!

**Comment by ivan-klass** [comment]
I believe this is resolved by https://github.com/typelevel/cats/pull/3950 so should be closed
