### ISSUE TITLE
cats friendly batch 's link is dead

### ISSUE THREAD

**Issue by keyno63** [typelevel/cats#3927]
An image url of the batch is specified "https://typelevel.org/cats/img/cats-badge-tiny.png" by [this](https://github.com/typelevel/cats/blob/d8045b1cac84944cf770fd2ddb1ccceabf141924/docs/src/main/mdoc/typelevelEcosystem.md).
```
Below are quick html and markdown snippets to use the badge in your own project.

<a href="https://typelevel.org/cats/"><img src="https://typelevel.org/cats/img/cats-badge-tiny.png" alt="Cats friendly" /></a>
```

but, the link is dead (return 404).

where is a new link ?

**Comment by erikerlandson** [comment]
upvote

**Comment by froth** [comment]
Possible dublicate of https://github.com/typelevel/cats/issues/3882

**Comment by keyno63** [comment]
@froth 
thank you.
I missed to find it.
