### ISSUE TITLE
`Eq[NonEmptySet[A]]` requires `Order[A]`, but only needs `Eq[A]`

### ISSUE THREAD

**Issue by domaspoliakas** [typelevel/cats#3957]
Hello folks 👋 

[`NonEmptySetEq[A]`](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/data/NonEmptySet.scala#L426) has an `Eq[A]` member, but the implict construction of `NonEmptySetEq[A]` [here](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/data/NonEmptySet.scala#L413) declares an `implicit A: Order[A]` parameter, meaning that you can't have a `Eq[NonEmptySet[A]]` unless `A` has an instance of `Order`, despite the fact that an `Eq` should suffice.

I'd be more than happy to get this fixed, but I don't know how to approach it with regards to binary compatibility.

**Comment by joroKr21** [comment]
Hey - the binary-compatible approach is to make the old instance `private[data]` and not implicit and just add a new instance with the relaxed constraints. In this case you can even simply forward the old one to the new because `Order[A] <:< Eq[A]`.
