### ISSUE TITLE
Doc building is failing

### ISSUE THREAD

**Issue by LLCampos** [typelevel/cats#3969]
Locally, following what is described on [CONTRIBUTING.md](https://github.com/typelevel/cats/blob/main/CONTRIBUTING.md#generating-the-site) I run `sbt docs/makeMicrosite`, but it fails with:

```
error: state.md:236:1: Expected compile errors but program compiled successfully without errors
val nextLong: State[Future[AsyncSeed], Future[Long]] = State { seedF => 
^
error: state.md:310:1: Expected compile errors but program compiled successfully without errors
val invalid = for {
^
error: state.md:329:1: Expected compile errors but program compiled successfully without errors
valid.run(Open)
^^^^^^^^^^^^^^^
info: Compiled in 26s (3 errors, 12 warnings)
```

**Comment by rossabaker** [comment]
I just hit this.  It works under `++2.12.14`.  We need to get that fixed in the contributing guide.

**Comment by armanbilge** [comment]
The site now builds with the default Scala in sbt. https://github.com/typelevel/cats/pull/4160
