### ISSUE TITLE
Restore Open Collective sponsors to site

### ISSUE THREAD

**Issue by rossabaker** [typelevel/cats#3974]
I tried with #3972 and made it worse, because I used a non-CORS endpoint after hacking CORS locally.  The conversation continued on that issue, but it is very important we find and publish a solution.  This is to hold us accountable for doing so quickly, or to revert #3972 and manually add a couple more sponsors if there is no quick solution.

@armanbilge has PR'ed a fix upstream, and also has a backup plan.

**Comment by armanbilge** [comment]
I'll invoke the backup plan first thing tomorrow unless upstream moves fast tonight.

**Comment by armanbilge** [comment]
FYI some movement on my upstream PR with the promise that "Maybe not today, but it could be landed sometime this week."

Therefore, backup plan it is.

**Comment by rossabaker** [comment]
@djspiewak is the only admin right now, so I think he'd need to provide the key.

This means we're going to have to keep it as part of the build process, doesn't it?  And if we do that, periodically refresh the site?  I guess we could have a scheduled GitHub workflow just to fetch this JSON, and then our fetch could fetch that.

**Comment by armanbilge** [comment]
> This means we're going to have to keep it as part of the build process, doesn't it?

Well, until I bug them enough to get my CORS fix live 😛 

Alternatives:
1. We can host a tiny proxy (e.g., a free cloudflare worker) that adds CORS to the request and point to that. Actually, I tried this first but ran into problems without the API key.
2. With an API key, we _may_ be able to use the GraphQL API directly in the site. Not sure, I'm confused about whether the key should be kept private, and if so, how it's even possible to use GraphQL in the frontend. I'll research this again.
3. Use your idea to extract the sponsors from the transactions API which does have CORS enabled. I'm sorry I was stubborn and tried to find "better" ways, but more and more that might be the best fix.
