### ISSUE TITLE
Introducing `.flatMapN(f)` as a shorthand for `.mapN(f).flatten`

### ISSUE THREAD

**Issue by domaspoliakas** [typelevel/cats#4003]
Hello 👋 this follows from my question on discord and is basically the title. 

I find myself doing `.mapN(f).flatten` very frequently and I think it'd be nice to have a `.flatMapN` for this scenario. 

I am told this was rejected in the past, but I could not find a past issue for this and so I was hoping I could reopen a discussion.

Thanks!

**Comment by joroKr21** [comment]
I've thought about this too. The only potential issue I see is the cost in terms of increased Jar size (because that would add not 1 but 22 extra methods). However I'm not sure that's really a concern because #3871 didn't generate much interest.

**Comment by domaspoliakas** [comment]
Given that there were no nays yet, I shall get started on making this. Is that alright?
