### ISSUE TITLE
Missing @implicitNotFound for ApplicativeError and MonadError

### ISSUE THREAD

**Issue by satorg** [typelevel/cats#4059]
Check it out:
```
scala> import cats.syntax.all._

scala> none[Int].raiseTo[Option]
-- Error:
1 |none[Int].raiseTo[Option]
  |                         ^
  |                      Could not find an instance of Applicative for Option

```
But in fact, `Applicative[Option]` *DOES* exist in the scope.

The error message for the above should look like: "Could not find an instance of ApplicativeError[Option, Int]" instead.
The reason why it is incorrect is that `ApplicativeError` does not have `@implicitNotFound` annotation applied and compiler picks one up from its parent.

**Comment by armanbilge** [comment]
These errors frequently trip me up, and not just in Cats proper. E.g. if something in the CE hierarchy is missing then it says you are missing `Monad` (and not `Concurrent` or `Async`).

**Comment by djspiewak** [comment]
Scala 3 inherits these definitions while Scala 2 does not. This has generated… no small amount of confusion. :-) Basically the consequence of this is the fact that in any typeclass hierarchy which has one `@implicitNotFound` needs to have them on *all* classes.

**Comment by satorg** [comment]
Seems that Scala 2 also uses the inherited annotation (notice the sentence in parentheses):
```
could not find implicit value for parameter F: cats.ApplicativeError[Option,Int] (Could not find an instance of Applicative for Option)
```
But the overall error message is a way easier to decipher.

**Comment by joroKr21** [comment]
Why does `Applicative` need an `@implicitNotFound` with such a generic message? How is it different than the default?

**Comment by joroKr21** [comment]
And is that an argument against inheritance of `@implicitNotFound` messages 🤔

**Comment by armanbilge** [comment]
Yes, I agree, I'm pretty sure we don't need these `@implicitNotFound` if the messages are so generic.

I experimented in a scastie (2.13) and it seems the default is to use the FQCN?
https://scastie.scala-lang.org/TUftkqyJSyyOg0XkkcntRw
```scala
trait Applicative[F[_]]
trait Foo[A]
implicitly[Applicative[Foo]]
// could not find implicit value for parameter e: Playground.Applicative[Playground.Foo]
```

**Comment by armanbilge** [comment]
Lol, apparently this inheritance issue was known at the time! https://github.com/typelevel/cats/issues/581#issuecomment-150054140
> (The bad part here is that I think this would require annotating every type class with some kind of message. Either that, or wiring it up to Simulacrum somehow.)

**Comment by joroKr21** [comment]
Hmm so it's coming from simulacrum 🤔 , but the message never included the suggestion to import `cats.implicits` which is now obsolete anyway. 😄

**Comment by djspiewak** [comment]
Let's just remove the annotations. I don't think they're carrying any weight.
