### ISSUE TITLE
cats 2.7.0 broke binary compatibility for Scala 3 (because mima wasn't run)

### ISSUE THREAD

**Issue by smarter** [typelevel/cats#4062]
As discovered by @xuwei-k, see https://gist.github.com/xuwei-k/afe78856f95124c6ca5323beb7b32b5c from https://github.com/argonaut-io/argonaut/pull/476

Seems like mima isn't setup for scala 3:
```scala
> ++3.0.2 coreJVM/mimaReportBinaryIssues
[info] Setting Scala version to 3.0.2 on 32 projects.
[info] Excluded 14 projects, run ++ 3.0.2 -v for more details.
[info] Reapplying settings...
[info] set current project to cats (in build file:/home/smarter/opt/cats/)
[error] stack trace is suppressed; run last coreJVM / mimaPreviousClassfiles for the full output
[error] (coreJVM / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: Error downloading org.typelevel:cats-core_3:2.1.0
```
(it needs to use cats-core_3:2.6.1 since that's the only previously published version for Scala 3).

Note that this is absolutely not a bug in Scala 3: we intentionally use a different type erasure algorithm for intersection/compound types, because the Scala 2 algorithm was not commutative but also because it was dependent on compiler implementation details so we couldn't fully reproduce it even if we tried, cf https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Erasure.scala, https://github.com/lampepfl/dotty/issues/5139.

**Comment by smarter** [comment]
Broken in https://github.com/typelevel/cats/pull/3906 /cc @joroKr21

**Comment by smarter** [comment]
It should be possible to introduce an implicit with a different type without breaking BC by doing something like:
```scala
   @deprecated("retained for binary compatibility")
   private[cats] def catsInstancesForId: Distributive[Id] with Comonad[Id] = cats.catsInstancesForId
   implicit def catsInstancesForId2
     : Distributive[Id] with Bimonad[Id] with CommutativeMonad[Id] with NonEmptyTraverse[Id] =
    cats.catsInstancesForId
```

**Comment by armanbilge** [comment]
Might not want to make it `private` right away to avoid breaking source compatibility.

**Comment by djspiewak** [comment]
We generally don't consider implicits to be part of source compatibility, so IMO this is something we can (and should) do in 2.7.1

**Comment by joroKr21** [comment]
`Distributive[Id] with Comonad[Id]` erases to `Comonad`? 🤔

**Comment by joroKr21** [comment]
I guess we were unlucky that `Bimonad` is lexicografically before `Comonad`. Do type aliases matter? 🤔 
Not the tricky issue is that to restore bincompat with older versions we have to break bincompat with 2.7.0.
I guess it's fine because it affects only Scala 3 but still it's pretty bad.

**Comment by smarter** [comment]
Type erasure in Scala 3 is commutative: the erasure of A & B when A and B are unrelated traits is based on their lexicographic ordering

> Do type aliases matter?

Not in Scala 3 where erasure of intersections is computed from the erasure of each erased operand of the intersection.
In Scala 2 it does matter in some contrived situations unfortunately as witnessed by https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Erasure.scala, e.g. in https://github.com/lampepfl/dotty/blob/f6b6e5068cc630d8fa5c3f3e72b4335c9149a216/sbt-test/scala2-compat/erasure/scala2Lib/Api.scala#L145-L149 the presence of a type alias changes erasure (the test checks that the first letter of the method name corresponds to its erased type), even worse, two identical type aliases can end up aftecting type erasure differently: https://github.com/lampepfl/dotty/blob/f6b6e5068cc630d8fa5c3f3e72b4335c9149a216/sbt-test/scala2-compat/erasure/scala2Lib/Api.scala#L125-L132 (think how much fun I had making Scala 3 support calling these methods correctly!)

(As an aside, the Scala 3 intersection type erasure algorithm is still not as good as I wish it was: it turned out to not be associative due to an oversight, I have an alternative proposal in http://guillaume.martres.me/pathless-scala.pdf but that'll have to wait for Scala 4 :grimacing: )

**Comment by armanbilge** [comment]
Seems `Id` is only the tip of the iceberg?
```
[error] Cats Free: Failed binary compatibility check against org.typelevel:cats-free_3:2.6.1! Found 6 potential problems (filtered 33)
[error]  * static method unsafeApply(java.lang.Object,scala.collection.immutable.List)cats.free.ContravariantCoyoneda in class cats.free.ContravariantCoyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.ContravariantCoyoneda.unsafeApply")
[error]  * abstract method ks()scala.collection.immutable.List in class cats.free.ContravariantCoyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.ContravariantCoyoneda.ks")
[error]  * method unsafeApply(java.lang.Object,scala.collection.immutable.List)cats.free.ContravariantCoyoneda in object cats.free.ContravariantCoyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.ContravariantCoyoneda.unsafeApply")
[error]  * static method unsafeApply(java.lang.Object,scala.collection.immutable.List)cats.free.Coyoneda in class cats.free.Coyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.Coyoneda.unsafeApply")
[error]  * abstract method ks()scala.collection.immutable.List in class cats.free.Coyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.Coyoneda.ks")
[error]  * method unsafeApply(java.lang.Object,scala.collection.immutable.List)cats.free.Coyoneda in object cats.free.Coyoneda does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.free.Coyoneda.unsafeApply")
```

**Comment by smarter** [comment]
Those seem to be `private[cats]` methods? Maybe mima knows to ignore them when reading Scala 2 pickling information but doesn't know how to interpret Scala 3 signatures in tasty /cc @dwijnand

**Comment by armanbilge** [comment]
Alternative, does Scala 3 treat `private[cats]` differently from Scala 2?

**Comment by smarter** [comment]
Not as far as I know, it all becomes public methods.

**Comment by armanbilge** [comment]
Yes it's very strange. That was my PR https://github.com/typelevel/cats/pull/3987 btw, and I had to add some filters but not for those. In any case should be safe to filter them on Scala 3.

**Comment by dwijnand** [comment]
> Maybe mima knows to ignore them when reading Scala 2 pickling information but doesn't know how to interpret Scala 3 signatures in tasty /cc @dwijnand

That's correct.  I parse Scala annotations from Scala 2's pickle and Scala 3's tasty, but only parse the package private information from Scala 2's pickle.  Not for any true reason, it's work just waiting for a motivating case to arise.

But I must be blind this morning because I can't for the life of me see those unsafeApply and ks methods in the sources...

**Comment by smarter** [comment]
Thanks for the confirmation. These methods were removed in https://github.com/typelevel/cats/pull/3987

**Comment by armanbilge** [comment]
Interesting, thanks for chiming in, is this a (relatively) new feature? I feel like I've had to add filters for package privates in the recent past, but maybe I'm confused :)

**Comment by joroKr21** [comment]
Maybe a similar feature is needed for sealed traits 🤔

**Comment by armanbilge** [comment]
> Yeah. I've added so many filters for tweaking private[sbt] methods and classes... I should have stopped and done it a long time ago.

I think this is a really important change, far more than the nuisance factor. It always seemed dangerous to me that:
1. an initially public method could be made package private
2. someone innocently assuming that the method was always package private, would then change it and filter the MiMa warning
But, now that MiMa natively understands package private, those filters wouldn't be necessary in ordinary use, thus disabling the footgun. So I think it would be excellent if Scala 3 can get this feature as well.

**Comment by joroKr21** [comment]
So I guess in this case checking both against old and new versions with MiMa makes sense.

**Comment by armanbilge** [comment]
> So I guess in this case checking both against old and new versions with MiMa makes sense.

WDYM by this?

**Comment by joroKr21** [comment]
I mean checking against cats 1.0, 1.1, 1.2, etc. instead of just the latest version - i.e. transitivity doesn't apply without caveats

**Comment by armanbilge** [comment]
I'm not sure we are talking about the same thing. But I could be confused.

In theory, I don't think checking against old versions is necessary at all. Since binary-compatible changes can only add to the public binary API, there should never be a situation where M.N has something that that M.(N+1) doesn't. So checking against M.(N+1) should be sufficient.

OTOH, I'm talking about adding MiMa filters. When you do that, you are effectively telling MiMa "I am taking full responsibility the bincompat of this code." So if in M.(N+100) you do add a filter for a method that you _thought_ was always package private, but was actually public in M.N and everyone forgot, it doesn't matter if you check M.(N+100) against M.N because you just told MiMa that you know best.

Ideally, the only time we should have to add filters is when we are in fact breaking public APIs (in the Scala not Java sense). Which should be exceedingly rare.

**Comment by joroKr21** [comment]
> OTOH, I'm talking about adding MiMa filters. When you do that, you are effectively telling MiMa "I am taking full responsibility the bincompat of this code." So if in M.(N+100) you do add a filter for a method that you thought was always package private, but was actually public in M.N and everyone forgot, it doesn't matter if you check M.(N+100) against M.N because you just told MiMa that you know best.

Yes but if MiMa knows about sealed traits and package private methods it should let you do those changes without adding a filter. And then it matters whether you check with the older version or not.

**Comment by armanbilge** [comment]
Ahhh. Yes, you are absolutely right :)

> transitivity doesn't apply without caveats

Now I get this 😆

**Comment by satorg** [comment]
Sorry, I'm not completely catching this... The possibility to make some obsolete methods package private is one of vital features that allow us to add new features while maintaining the binary compatibility with older versions. So I'm wondering – will such a possibility still be preserved?

**Comment by joroKr21** [comment]
> So I'm wondering – will such a possibility still be preserved?

Yes but it shouldn't come at cost of being able to change library internals. So we just have to be careful.

**Comment by armanbilge** [comment]
Personally, I'm hoping sometime in the next few weeks, pressure is mounting to release on Scala 3 + Native. There are snapshots available for anyone in a pinch.

https://github.com/typelevel/cats/milestone/41
