### ISSUE TITLE
Additional syntax for EitherT/OptionT

### ISSUE THREAD

**Issue by matwojcik** [typelevel/cats#4068]
In our team we use additional syntax for EitherT/OptionT, we thought about adding it directly to cats, and would like to know your opinion before finding a place for it with some PR.

```scala
trait EitherTSyntax {

  implicit final class FEitherToEitherT[F[_], E, A](private val fea: F[Either[E, A]]) {
    def toEitherT: EitherT[F, E, A] = EitherT(fea)
  }

  implicit final class FToEitherT[F[_], A](private val fa: F[A]) {
    def liftToEitherT[E](implicit F: Functor[F]): EitherT[F, E, A] = EitherT.right[E](fa)
  }

  implicit final class FOptionToEitherT[F[_], A](private val foa: F[Option[A]]) {
    def toEitherT[E](ifNone: => E)(implicit F: Functor[F]): EitherT[F, E, A] = EitherT.fromOptionF(foa, ifNone)
  }
}

trait OptionTSyntax {

  implicit final class FOptionToOptionT[F[_], A](private val foa: F[Option[A]]) {
    def toOptionT: OptionT[F, A] = OptionT(foa)
  }

  implicit final class FAToOptionT[F[_], A](private val fa: F[A]) {
    def liftToOptionT(implicit F: Functor[F]): OptionT[F, A] = OptionT.liftF(fa)
  }
}

```

Additional syntax makes business logic less _soiled_ with monad transformers, so instead of writing `OptionT(doSomething)` you can write `doSomething.toOptionT`, having business behaviour more clear for a reader.

Please let me know if such syntax additions would be acceptable, then I'll make a PR.

**Comment by rossabaker** [comment]
Similar (not precisely the same) was [recently added to mouse](https://github.com/typelevel/mouse/commit/0068e6d14c950a2a4f9ef407a4575ce1c64144d1)

**Comment by matwojcik** [comment]
@rossabaker interesting, do you think that mouse would be a better fit then?

**Comment by rossabaker** [comment]
I think so.  I don't understand the rules for what syntax goes in Cats vs. Mouse, but this does look much more like what's in Mouse already.

**Comment by matwojcik** [comment]
I can see in mouse docs:

> Mouse includes enrichments for:
> 
> Any
> Boolean
> Double
> **F[A] for any F, A
> F[Either[A, B]]
> F[Option[A]]**

so according to this I indeed think that would be the right place.

**Comment by satorg** [comment]
This issue pops up from time to time and there was even a discussion about it in Discord (sorry, cannot remember a link).

Eventually, there was some sort of conclusion: if someone prefers a chaining-like syntax for building `OptionT`/`EitherT` instances, then it can be achieved with existing means.

1. Using `scala.util.chaining` syntax:
    ```
    scala> import scala.util.chaining._
    scala> import cats.data.EitherT
    
    scala> val fa = List(Right(123), Left("hello"), Right(456), Left("world"))
    val fa: List[scala.util.Either[String,Int]] = List(Right(123), Left(hello), Right(456), Left(world))
    
    scala> fa.pipe(EitherT(_))
    val res1: cats.data.EitherT[List,String,Int] = EitherT(List(Right(123), Left(hello), Right(456), Left(world)))
    ```

2. Pure "Cats" but more obscure way:
    ```
    scala> import cats.syntax.all._
    scala> import cats.Id
    scala> import cats.data.EitherT
    
    scala> val fa = List(Right(123), Left("hello"), Right(456), Left("world"))
    val fa: List[scala.util.Either[String,Int]] = List(Right(123), Left(hello), Right(456), Left(world))

    scala> fa.pure[Id].fmap(EitherT(_))
    val res1: cats.Id[cats.data.EitherT[List,String,Int]] = EitherT(List(Right(123), Left(hello), Right(456), Left(world)))
    ```

    Note: `fmap` is used instead of just `map` because `List` has its own `map` and the compiler tries to pick the latter up first.

**Comment by matwojcik** [comment]
IMHO it's nowhere near the ease of use and readability of `mouse` equivalent.

**Comment by matwojcik** [comment]
Closing as this was moved to mouse: https://github.com/typelevel/mouse/pull/276
