### ISSUE TITLE
Consider using the Imp project

### ISSUE THREAD

**Issue by non** [typelevel/cats#408]
Recently I created (and published) a project called [Imp](https://github.com/non/imp).

Basically, it provides `imp`, an improved version of `implicitly`, and `summon`, an improved way to define `apply` methods for type class companions.

I'd like to start using this (tiny) library in Cats. It would allow us to commit more fully to using the context bound syntax, and provide more efficient apply methods on type class companions.

**Comment by rossabaker** [comment]
```
// if you want to use the imp.summon macro you'll need this too:
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value % "provided"
```

To be clear, is "using this macro" defining a method with summon, or calling a method defined by summon?  Seems good for internal cats use, but I'd hesitate to mandate a provided library downstream.

**Comment by non** [comment]
Yeah, I think for starters I was just suggesting using `imp[...]`.

In the long run we may be interested to try to the other macro, but for now I agree we should not create the dependency.

(We could also move the macro implementation into Cats and provide `summon` that way if that was more appealing.)

**Comment by ceedubs** [comment]
For one reason or another I'm always a bit hesitant to introduce macros to solve a problem, but this does look pretty nice.

Is requiring the provided `scala-reflect` dependency ever expected to be a problem in practice? I know that many libraries (such as Shapeless) do this, and I had assumed that it was a dependency that will just always be there for any library compiled with Scala. I suppose maybe this could be a problem if something wanted to call from Java? Is that something we have ever thought about supporting? I'm probably totally misunderstanding how this works.

**Comment by non** [comment]
So here is my understanding:

1. If Cats uses `imp` internally we will need `scala-reflect` to build Cats, but Cats won't pass that dependency along to projects using Cats.

2. If Cats uses `summon` to define `apply` methods then I think downstream projects **will** need to depend on `scala-reflect` as well.

I haven't had any major complaints from folks that Spire depends on `scala-reflect`, so in some ways I didn't consider it a big deal. I guess you're right that it wouldn't be possible to call `apply` from Java, but since Java also doesn't support implicits the problem is moot IMO.

It sounds like folks are in favor of trying out `imp` and deferring the rest for now.

**Comment by ceedubs** [comment]
@non that explanation makes sense and lines up with what I would have suspected.

Personally I'd be in favor of trying out them both, but if people have any objections, I'm open to them.

**Comment by mdedetrich** [comment]
Just putting it out there, I have had issues with libraries providing `scala-reflect` downstream, mainly as historic issues that Scala has had with reflection (`scala-reflect` breaks on the minor, not major, for versions)

For this reason, I am more leaning towards 1 (`Cats` using `imp` internally only)
