### ISSUE TITLE
SortedSet, SortedMap, NonEmptySet, and NonEmptyMap Unexpected Behaviors

### ISSUE THREAD

**Issue by isomarcte** [typelevel/cats#4103]
During the implementation of https://github.com/typelevel/cats/pull/4092 I noticed several unexpected properties of the SortedSet, SortedMap, NonEmptySet, and NonEmptyMap and the related code.

I'm not exactly sure what, if anything, should be done so I wanted to open up this issue to talk through the various topics.

# Background #

## Related Typeclass Instances ##

The topics relate to the following currently implemented typeclass instances. `NonEmptySet` and `NonEmptyMap` are mostly involved here just because they are implemented in terms of `SortedSet` and `SortedMap`, so I'll primarily focus on the `SortedSet` and `SortedMap`.

* `Order[SortedSet[A]]`
* `Eq[SortedMap[K, V]]`
* `CommutativeMonoid[SortedMap[K, V]]`

Of note, cats does not have an implementation currently of `Order[SortedMap[K, V]]`. One is proposed here, https://github.com/typelevel/cats/pull/4092.

## Interaction With Order/Ordering ##

All of these topics relate in some way or another to the fact that it is generally assumed that `cats.kernel.Order` will be coherent (only one instance exists for a given type `A`), `scala.math.Ordering` is not necessarily expected to be coherent. In fact, the Scaladocs for it suggest that one would use `Ordering` idiomatically for non-coherent alternative orderings, using `scala.math.Ordered` subtypes for the canonical ordering of a given type.

# Monoid for SortedSet Not Lawful #

This is the big issue. Specifically, if the given `SortedSet` is not using the same `Ordering` as `Monoid[SortedSet[A]].empty`, then the identity property doesn't hold.

```scala
scala> val reverseOrdering: Ordering[Int] = Ordering[Int].reverse
val reverseOrdering: Ordering[Int] = $anonfun$1@2c6a4b4d

scala> val x = SortedSet(1, 2)(reverseOrdering)
val x: scala.collection.immutable.SortedSet[Int] = TreeSet(2, 1)

scala> Eq[SortedSet[Int]].eqv(Monoid.empty[SortedSet[Int]] |+| x, x)
val res0: Boolean = false
```

This is because the `Eq` instance for `SortedSet` relies on iteration order. When we combine `Monoid.empty` with a `SortedSet` which is using a valid, but different, order then the result will not compare equal to the original value.

# Surprising `Eq` Behavior #

Currently cats provides an `Eq[SortedSet[A]]` instance which is implemented using the underlying iterator. This leads to a surprising disagreement about equality for `Eq.eqv` and `.equals`.

```scala
scala> val x = SortedSet(1, 2) // Using the canonical implicit Ordering[Int]
val x: scala.collection.immutable.SortedSet[Int] = TreeSet(1, 2)

scala> val y = SortedSet.from(x)(reverseOrdering)
val y: scala.collection.immutable.SortedSet[Int] = TreeSet(2, 1)

scala> Eq[SortedSet[Int]].eqv(x, y)
val res0: Boolean = false

scala> x == y
val res1: Boolean = true
```

They are effectively ordered like `List[A]`.

For `SortedMap[K, V]` however, the implementation of `Eq` _is_ in agreement with `.equals`. This is because it doesn't rely on iteration order, but checks if the sizes agree, and if so, then traverses one of the two maps to see if all the same keys and values are in the other map.

```scala
scala> val x = SortedMap(0 -> 0, 1 -> 1)
val x: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(0 -> 0, 1 -> 1)

scala> val y = SortedMap.from(x)(reverseOrdering)
val y: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(1 -> 1, 0 -> 0)

scala> Eq[SortedMap[Int, Int]].eqv(x, y)
val res0: Boolean = true

scala> x == y
val res1: Boolean = true
```

Of secondary note here, there _is currently not_ and instance of `Eq[SortedSet[A]]` for `A` types which do _not_ have a `Order[A]` but do have an `Eq[A]`, however there currently _is_ an instance of `Eq[SortedMap[K, V]]` for `K` types which have an `Eq[K]`, but _not_ an `Order[K]`. We can however get an instance of `Eq[NonEmptySet[A]]` for `A` types which only have `Eq[A]`, _not_ `Order[A]`, but the `Eq[A]` instance being used [is based on the Ordering in the underlying SortedSet](https://github.com/typelevel/cats/blob/v2.7.0/core/src/main/scala/cats/data/NonEmptySet.scala#L39). This is _probably_ fine, but is definitely strange.

# CommutativeMonoid/Order #

Cats has a `CommutativeMonoid` instance for `SortedMap[K, V]`, the laws for which stat that `x |+| y == y |+| x`. Because our `Eq` for `SortedMap` relies on size and key/value comparison, as opposed to `SortedSet`, this works out correctly.

```scala
scala> val x = SortedMap(0 -> 0, 1 -> 1)
val x: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(0 -> 0, 1 -> 1)

scala> val y = SortedMap(2 -> 2, 3 -> 3)(reverseOrdering)
val y: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(3 -> 3, 2 -> 2)

scala> CommutativeMonoid[SortedMap[Int, Int]].combine(x, y)
val res1: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(3 -> 3, 2 -> 2, 1 -> 1, 0 -> 0)

scala> CommutativeMonoid[SortedMap[Int, Int]].combine(y, x)
val res2: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(0 -> 0, 1 -> 1, 2 -> 2, 3 -> 3)

scala> res1 == res2
val res3: Boolean = true

scala> Eq[SortedMap[Int, Int]].eqv(res1, res2)
val res4: Boolean = true
```

However, if we were to implement an `Order` instance for `SortedMap` then a problem arises. We must be very careful to _not_ implement it in the same manner as we did for `SortedSet`, otherwise our `CommutativeMonoid` instance would yield `false` for `x |+| y == y |+| x` because the order of the resulting map would depend on the `Ordering` in the left most `SortedSet` in the `|+|` operation. It also then follows that given our current implementation of `Order` for `SortedSet` prevents us from writing an otherwise valid `CommutativeMonoid` for `SortedSet`.

# Options For What To Do #

The only safe thing I can see to do for `SortedSet` is to reorder the sets based on the canonical `Order` instance for `A` when performing the `Order.compare` operation unless the `_.ordering` value for both sets `a1.ordering eq a2.ordering == true` holds. Clearly, this is non-ideal as we gain several traversals over the sets to the complexity.

In general, I think we should make the instances and behaviors of `SortedSet` and `SortedMap` consistent with each other. Further, right now for `SortedSet` we imply that orderings for a given `A` may differ and that does matter for `Order[SortedSet[A]]`, but we take the opposite stance with `SortedMap` (in terms of `Eq`). This creates surprising behaviors and prevents consistent implementation between the two. My opinion is that we should say for any given `SortedSet` or `SortedMap`, if they contain the same elements then they should yield `0` for `compare`.

Taking this a step further, I think we might want to consider requiring that if, `a.equals(b) == true`, then `Eq[A].eqv(a, b) == true` by adding it to the laws. I suspect this is what _most_ users expect the behavior to be, and while it's not technically unlawful to deviate here, I'm not sure anything good comes from that.

We also might consider creating newtypes for `SortedSet` and `SortedMap` which enforce that they are ordered using the `Order[A]` instance. Maybe call them `OrderedSet` and `OrderedMap`. This would allow for the trivial addition of `Order[OrderedMap[K, V]]` and `CommutativeMonoid[OrderedSet[A]]` as well as remove us from having to reconstruct the underlying sets.

**Comment by johnynek** [comment]
BTW @non and I explored a way to make this sound in the past but kind of abandoned it. You can imagine something like this:

```scala
sealed abstract trait OrderingModule[K] {
  implicit val ordering: Ordering[K]
  type Map[V] = SortedMap[K, V]
  type Set = SortedSet[K]

  def emptyMap[V]: Map[V]
  def emptySet: Set

  implicit def mapMonoid[V]: Monoid[Map[V]] = ...

  // etc...
}

object OrderingModule {
  def apply[K](implicit ordK: Ordering[K]): OrderingModule[K] =
    new OrderingModule[K] {
      override val ordering = ordK
    }
}

val om = OrderingModule[String]
import om.{setMonoid, mapMonoid, ... }
val stringSet: om.Set = Monoid[om.Set].empty
...
```

So, basically, you use the path dependent type to prove that two elements have the same ordering. This pattern can be extended to other values that depend on typeclasses (heaps, or things that require serialization, etc...)

**Comment by isomarcte** [comment]
Per discussion on #4105 and #4092, it has been decided that cats will assume that given any `SortedSet` or `SortedMap`, and thus also `NonEmptyMap` and `NonEmptySet`, cats will assume that the `Ordering`, and thus the `Order`, shared between all instances is consistent with all other instances in scope. If this assumption is invalid, then it is known and expected that the behavior of cats classes in these cases will be unlawful.
