### ISSUE TITLE
release scala-native for Scala 3

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/cats#4117]
- [ ] https://github.com/typelevel/scalacheck/pull/868

**Comment by i10416** [comment]
I found some dependencies start supporting Scala 3 x Scala native. Will next release include Scala 3 native support? Is there still any blocker?

**Comment by armanbilge** [comment]
That is my intention! We are currently waiting for munit.

**Comment by armanbilge** [comment]
Munit has released a milestone with Scala 3 + Native, so that should be sufficient. Now we just need a snapshot of https://github.com/typelevel/discipline-munit/pull/165 and I think we should have everything.

**Comment by i10416** [comment]
Great! I find you everywhere these days :) Thank you for maintaining a lot of libraries important for Scala eco system.

**Comment by armanbilge** [comment]
We are now unblocked via https://github.com/typelevel/discipline-munit/releases/tag/v2.0.0-M1

**Comment by rossabaker** [comment]
This is only a test and docs dependency, right?  Non-milestone releases that depend on milestones are bad, but I think one would be okay.

**Comment by armanbilge** [comment]
Yup, just test, not even docs. We don't ship anything dependent on munit.

**Comment by armanbilge** [comment]
We now have a snapshot available! Will try to do 2.8.0 release next week :)
https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/alleycats-core_native0.4_3/2.8-e070e7e-SNAPSHOT/
