### ISSUE TITLE
Provide documentation for or to non/algebra typeclasses

### ISSUE THREAD

**Issue by philwills** [typelevel/cats#413]
A number of core typeclasses that one would expect from a project like cats are in fact provided by the algebra project. This isn't obvious for someone new to the project and there's nothing listing or even linking through to the algebra readme.

Given the style of documentation for cats is quite distinct from that in the algebra project, my inclination would to be explicitly document these typeclasses in the cats docs, but at least a link and explanation would help a lot for those unfamiliar with the project.

**Comment by adelbertc** [comment]
I'm in favor of having type classes from algebra have documentation on the Cats side - considering things like `Semigroup` and `Monoid` show up in other Cats data types (e.g. `Validated`), people will probably expect to have documentation on those type classes on the Cats website as well.

**Comment by ms-ati** [comment]
+1

**Comment by ceedubs** [comment]
These have been moved into cats, so I'm going to close this out.
