### ISSUE TITLE
Chain in Cats built for Scala 2.12 can keep a mutable collection

### ISSUE THREAD

**Issue by satorg** [typelevel/cats#4162]
Example (see in [Scastie](https://scastie.scala-lang.org/UX7lT1miTyys5qU1XCDJnA)):
```scala
import cats.data.Chain

// Should contain lease 2 elements initially to enforce Chain.Wrap
val buff = scala.collection.mutable.ListBuffer(1, 2) 
val chain = Chain.fromSeq(buff)

// Add more elements to the source buff
buff += 3
buff += 4

println(chain)
// Chain(1, 2, 3, 4)
```

This is because `Chain.fromSeq` takes a default `Seq` (defined in `Predef`) which in Scala 2.12 is just `scala.collection.Seq` which in turn can be both `..mutable.Seq` and `..immutable.Seq`.

This snippet does not compile in Scala 2.13 and above.

**Comment by armanbilge** [comment]
Woops. We can fix this bin-compatibly by explicitly importing `immutable.Seq` and then adding a deprecated method using the non-qualified `Seq` on 2.12 only.

**Comment by satorg** [comment]
I would suggest that the deprecated method could be fixed as well. It could check whether the seq passed is mutable and if it is so then copy all its elements into an immutable seq. It would be work slower for mutables (which are not supposed to be used there anyway), but would make `Chain` safer.
