### ISSUE TITLE
Newtype/tagged types/value classes for different type class instances?

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#425]
A couple I've found useful are `First` and `Max`. Another is [`Parallel`](https://github.com/scalaz/scalaz/commit/fb9720166487c772a84fdfe89acd0f4a9bfbabb6) which I can see being quite useful.

Thoughts on this and how to approach it?

**Comment by milessabin** [comment]
What type classes does this apply to? Descendents of semigroup?

**Comment by adelbertc** [comment]
`First` would be an alternative `Semigroup` for all `A` I think. `Max` would be a `Semigroup` for things with `Order`, and a `Monoid` for types like `Int` (similarly for `Min`). `Parallel` would be for the `Applicative` instance for `Future` (or a `Task`-y thing if we were to have to one).

**Comment by non** [comment]
So, I'm sitting with @ceedubs and here is what we think should be done:

1. We should have a separate project to provide a good type tags implementation.
2. There should be a project that provides useful tags for Cats (either in a Cats subproject, or in a Tags subproject, or elsewhere).
3. Cats should accommodate use of type tags.
4. Cats should not require type tags (i.e. should still allow users to manage their imports/implicits manually)

I don't think any of these are a blocker for 1.0 but they would be nice to have.

**Comment by adelbertc** [comment]
For #2 I would vote to have it as a cats subproject. Reason is I've often found myself wanting something like the `First` and `Max` monoid and would expect it to be in the "official" project somewhere. I would like to see this before we hit 1.0.

Another thing that came up when discussed on the Gitter channel a week or so ago was the variety of approaches for such a tags project. There were issues with subtyping in Scalaz (I think this is the ticket: https://github.com/scalaz/scalaz/issues/838 /cc @ceedubs ) though it was mentioned that behavior is desired for a project like [refined](http://github.com/fthomas/refined).

**Comment by non** [comment]
I still want to do this, but I'm moving it out from the 1.0 milestones. I think it is a nice-to-have but not essential.

(If anyone disagrees, feel free to move it back and we can talk about it here.)

**Comment by torgeirsh** [comment]
I'd say it depends on the criteria for 1.0. Without tagged types, cats is less of a drop-in replacement for scalaz, but I don't know if that that level of easy adoption is a goal for 1.0.

**Comment by benhutchison** [comment]
Just learned about https://github.com/julien-truffaut/newts in this space

**Comment by SystemFw** [comment]
This issue should probably be closed since we have #1800
