### ISSUE TITLE
Use laws to explain why there is no e.g. `Monad[Validated]`

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats#4251]
H/t @toniogela, seems we could improve the `Parallel` docs https://typelevel.org/cats/typeclasses/parallel.html

**Comment by TonioGela** [comment]
The [Validated doc](https://typelevel.org/cats/datatypes/validated.html#of-flatmaps-and-eithers) talks precisely about the example in the title, demonstrating that implementing `Monad` the `ap` function will get overridden and the new implementation is a short-circuiting one. What's your idea for the `Parallel` doc exactly?

**Comment by armanbilge** [comment]
Thanks for that pointer! I think it would be great if the documentation could specifically reference a law that relates `flatMap` to `ap`. It's the law that specifies the correct behavior, the override default implementation is merely a convenience.

However, at this moment I am struggling to find said law, or appreciate why it doesn't need to exist 🤔 
https://github.com/typelevel/cats/blob/fe9afb59b576cc778d5c68eaf442fd12b7c4a661/laws/src/main/scala/cats/laws/MonadLaws.scala#L31

**Comment by TonioGela** [comment]
> I believe this is the law:
> 
> https://github.com/typelevel/cats/blob/fe9afb59b576cc778d5c68eaf442fd12b7c4a661/laws/src/main/scala/cats/laws/FlatMapLaws.scala#L51

Thanks @johnynek! I'll try it and I'll submit an idea asap.

**Comment by TonioGela** [comment]
I opened a PR for this. BTW @johnynek I showed that overriding `ap` in a `Validated[Monad]` instance would not satisfy this law:

```scala
def flatMapConsistentApply[A, B](fa: F[A], fab: F[A => B]): IsEq[F[B]] =
  fab.ap(fa) <-> fab.flatMap(f => fa.map(f))
```

but since `mproduct` [is defined in `FlatMap`](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/FlatMap.scala) it had no point demonstrating its faultiness. Am I right?
