### ISSUE TITLE
Should Id[A] have Parallel?

### ISSUE THREAD

**Issue by SimY4** [typelevel/cats#4268]
Every time you have a method constrained by `Monad` `Applicative` or even `Traverse` you can easily slap `Id` into it and it would work just fine for testing. 

But if `Parallel` is involved then it's no longer the case.

Question: Is it possible to have `Parallel[Id] { type F = Id }`? And if it's is not lawful, can we have it in alleycats?

**Comment by armanbilge** [comment]
Yes, and indeed we do :)
https://github.com/typelevel/cats/blob/15b4d33a7ca871c7e05378cf29935d139e46f8a8/core/src/main/scala/cats/package.scala#L154

**Comment by SimY4** [comment]
Awesome!
