### ISSUE TITLE
Add traverseCollect to TraverseFilter typeclass

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/cats#4276]
Analogous to the `collect` method on `FunctorFilter` we can define a `traverseCollect` method derived from `traverseFilter` using a `PartialFunction` like this:

```scala
 def traverseCollect[F[_]: TraverseFilter, G[_]: Applicative, A, B](fa: F[A], f: PartialFunction[A, G[B]]): G[F[B]] =
    fa.traverseFilter(a => f.lift(a).sequence)
```

**Comment by olivierschultz** [comment]
Hi, I can work on this issue if nobody minds.

**Comment by emilhotkowski** [comment]
Can I help with this? I'm looking for my first contribution to Cats.

**Comment by armanbilge** [comment]
@emilhotkowski indeed, that would be great!
