### ISSUE TITLE
remove Hash law that it equals `.hashCode`

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#4284]
This precludes `Hash[A]` for many types (any type that may be an opaque type, e.g. in scala 2 type members that have some semantic meaning beyond their values, or in scala 3 opaque type).

see discussion in:
https://github.com/typelevel/cats/issues/4147

also need to fix hashDistinct or any other callsites that may be using Hash this way:
https://github.com/typelevel/cats/issues/4147#issuecomment-1218314475

**Comment by armanbilge** [comment]
I think in one of the discussions it's mentioned that some of our own instances aren't passing this law anyway ... so I'd be in favor of it going away.

> also need to fix hashDistinct or any other callsites that may be using Hash this way

This is what makes it not nice, particularly for downstream projects.

**Comment by johnynek** [comment]
I'd be surprised if there were more than 1 or two people using this law. I say we should break it unless we can find evidence I'm wrong.

The case in our repo can be fixed without breaking anyone.

**Comment by armanbilge** [comment]
lol
https://github.com/typelevel/cats/blob/f47123e338cf79304240b070528074e5611d1bd5/free/src/test/scala-2.13%2B/cats/free/FreeStructuralSuite.scala#L49-L50
