### ISSUE TITLE
Provide documentation for data types

### ISSUE THREAD

**Issue by ochrons** [typelevel/cats#430]
Many existing Cats data types are not mentioned at all on the http://non.github.io/cats//datatypes.html page. Of those that are mentioned, only FreeMonads and State have reasonable documentation.

**Comment by adelbertc** [comment]
Leaving a checklist here that can be edited as people leave comments on which ones they're taking up to avoid duplicate work:

- [ ] Const
- [ ] OneAnd
- [ ] Xor/XorT
- [ ] Ior
- [ ] Validated
- [ ] Kleisli: https://github.com/non/cats/pull/440

**Comment by ceedubs** [comment]
All of the data types in https://github.com/typelevel/cats/issues/430#issuecomment-129741788 now have docs. I'm going to close this out and we can open new tickets for anything that we find is missing.
