### ISSUE TITLE
Traverse[F[_].sequence is slow

### ISSUE THREAD

**Issue by kamiKAZIK** [typelevel/cats#4357]
```
val start2 = System.currentTimeMillis()
val result2 = Seq(Try(1), Try(2), Try(3)).sequence
val end2 = System.currentTimeMillis()
println("TEST = " + (end2 - start2) + " -- " + result2)
```

This takes arround 100 - 130 ms
```
TEST = 130 -- Success(Vector(1, 2, 3))
```

```
org.typelevel:cats-core_2.13:2.8.0:jar
```

```
ed@____:~$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
```

And scala version is 2.13.10

I am not sure what kind of operations it does behind the scenes, but 100+ ms for transforming a sequence of simple tries seems like it's a bit too much. Maybe someone could provide some insight about this problem? is this expected?

**Comment by armanbilge** [comment]
If you are running it on a "cold" virtual machine it indeed may be very slow. The JVM needs time to warm up and for JIT optimizations to be applied. Before benchmarking something you should run it several thousand times.

**Comment by kamiKAZIK** [comment]
Oh... I haven't considered that! After trying it to run at least several dozens of times. The execution time wend down to 0.02ms - 0.04ms. Thanks @armanbilge for the hint. I will close this issue.
