### ISSUE TITLE
[docs] Error in Rendering Document from .md to .html

### ISSUE THREAD

**Issue by ShapelessCat** [typelevel/cats#4366]
Please check the **first** unordered list in https://typelevel.org/cats/typeclasses/alternative.html. The Markdown of this unordered list is like:
 * Right Absorption: Applying a contextual function `F[A => B]` to `empty [A]` should be `empty [B]`.
   * `ff ap F.empty[A] = F.empty[B]`.
 * Left Distributivity:  Mapping over a combined element must be the combinations of the mapped elements.
   * `(fa <+> fb) map f = ((fa map f) <+> (fb map f))` where `fa: F[A]` and `fb: F[B]` and `f: A => B`.
 * Right Distributivity: Applying the combination of two functions must be the combination of their applications.
   * `(ff <+> fg) ap fa = (ff ap fa) <+> (fg ap fa)` where `ff: F[A => B]`, `fg: F[A => B]`, and `fa: F[A]`.

**The above Markdown in document is rendered as this HTML code snippet:**

```html
<ul>
  <li>Right Absorption: Applying a contextual function <code>F[A =&gt; B]</code> to <code>empty [A]</code> should be <code>empty [B]</code>.</li>
</ul>
<ul>
  <li><code>ff ap F.empty[A] = F.empty[B]</code>.</li>
  <li>Left Distributivity:  Mapping over a combined element must be the combinations of the mapped elements.</li>
</ul>
<ul>
  <li><code>(fa &lt;+&gt; fb) map f = ((fa map f) &lt;+&gt; (fb map f))</code> where <code>fa: F[A]</code> and <code>fb: F[B]</code> and <code>f: A =&gt; B</code>.</li>
  <li>Right Distributivity: Applying the combination of two functions must be the combination of their applications.</li>
</ul>
<ul>
  <li><code>(ff &lt;+&gt; fg) ap fa = (ff ap fa) &lt;+&gt; (fg ap fa)</code> where <code>ff: F[A =&gt; B]</code>, <code>fg: F[A =&gt; B]</code>, and <code>fa: F[A]</code>.</li>
</ul>
```

The view of this HTML is wrong, and it looks like:

 * Right Absorption: Applying a contextual function `F[A => B]` to `empty [A]` should be `empty [B]`.
 * `ff ap F.empty[A] = F.empty[B]`.
 * Left Distributivity:  Mapping over a combined element must be the combinations of the mapped elements.
 * `(fa <+> fb) map f = ((fa map f) <+> (fb map f))` where `fa: F[A]` and `fb: F[B]` and `f: A => B`.
 * Right Distributivity: Applying the combination of two functions must be the combination of their applications.
 * `(ff <+> fg) ap fa = (ff ap fa) <+> (fg ap fa)` where `ff: F[A => B]`, `fg: F[A => B]`, and `fa: F[A]`.

**Comment by armanbilge** [comment]
Thanks. Usually that means it needs some extra newlines between bullets I think. A PR would be great, you can't preview the site locally with `sbt tlSitePreview`.

https://github.com/typelevel/cats/blob/b036fb47196d1a788db09eb2bc262071fa3cb928/docs/typeclasses/alternative.md?plain=1#L23-L28

**Comment by ShapelessCat** [comment]
> Thanks. Usually that means it needs some extra newlines between bullets I think. A PR would be great, you can preview the site locally with `sbt tlSitePreview`.
> 
> https://github.com/typelevel/cats/blob/b036fb47196d1a788db09eb2bc262071fa3cb928/docs/typeclasses/alternative.md?plain=1#L23-L28

I can try to fix.
