### ISSUE TITLE
Scala 3 Ambiguous Implicits in UnorderedFoldable

### ISSUE THREAD

**Issue by bpholt** [typelevel/cats#4370]
Using cats 2.9.0 and Scala 3.2.1, this code results in a migration warning (or an [error in Scastie](https://scastie.scala-lang.org/qxoyTXlZThKQs2qy7osUTg))

```scala
import cats.syntax.all._

val list: List[(String, String)] = List.empty

list
  .nested
  .map(_.length)
  .value
```

I saw this locally:
> Migration Warning:
> Ambiguous implicits method `catsTraverseForSeq` in object `UnorderedFoldable` and method `catsTraverseForList` in object `UnorderedFoldable` seem to be used to implement a local failure in order to negate an implicit search. According to the new implicit resolution rules this is no longer possible; the search will fail with a global ambiguity error instead.
> 
> Consider using the scala.util.NotGiven class to implement similar functionality.

and see this error in Scastie (which is actually Scala 3.2.0, and isn't cross-building with sbt-typelevel, like I was locally)

> Found:    `cats.data.Nested[F, G, A]`
> Required: `?{ map: ? }`
>
> where:    `A` is a type variable with constraint `>: String`
>           `F` is a type variable with constraint `>: List` and `<: [_] =>> Any`
>           `G` is a type variable with constraint `>: [T2] =>> (String, T2)` and `<: [_] =>> Any`
> 
> Note that implicit conversions cannot be applied because they are ambiguous;
> both method `catsTraverseForList` in object `UnorderedFoldable` and method `catsTraverseForSeq` in object `UnorderedFoldable` match type `cats.Traverse[F]`

**Comment by armanbilge** [comment]
If anyone wants to give it a try: I wonder if we can fix this by de-prioritizing the `Seq` instances in implicit search:
https://github.com/typelevel/cats/blob/f2c78d9bbae80e11891956ef07b4050c5cb56f20/core/src/main/scala/cats/UnorderedFoldable.scala#L127-L129

**Comment by UlisesTorrella** [comment]
Hi, if no one is working on it yet I can give it a try

**Comment by armanbilge** [comment]
@UlisesTorrella yes please, thank you!

**Comment by UlisesTorrella** [comment]
I've implemented the de-prioritization of the seq instances in UnorderedFoldable like this:
`trait LowPriorityImplicits {
  implicit def catsTraverseForSeq: Traverse[Seq] = cats.instances.seq.catsStdInstancesForSeq
}

object UnorderedFoldable
    extends ScalaVersionSpecificTraverseInstances
    with cats.instances.NTupleUnorderedFoldableInstances with LowPriorityImplicits{ ...
`
And though it *solves this issue*, it rises plenty warnings of the type `the type test for cats.*.*[A] cannot be checked at runtime`
I'll be checking other alternatives later, unless it's ok like this (I'm new to the repo)

**Comment by armanbilge** [comment]
@UlisesTorrella nice work! Would you mind putting up a PR for further discussion, and to give CI a crack at it? Thanks!
