### ISSUE TITLE
Remove Obsolete `Either` Documentation

### ISSUE THREAD

**Issue by reardonj** [typelevel/cats#4392]
The Cats documentation website includes a page on [Either](http://typelevel.org/cats/datatypes/either.html), that IMO is no longer relevant.

Cats no longer supports Scala 2.11, so the unbiased/biased discussion is no longer relevant, and the remaining syntax enrichment for Either is already discussed in the Jumpstart guide. 

The rest is a discussion on typed error handling, but that is not directly Cats related. The specific example also may lead new users down the wrong path, since on the Typelevel stack, I'd expect the application to be implemented on `F[_]` or `IO`, but then we're talking about EitherT, or eschewing typed error handling entirely.

**Comment by armanbilge** [comment]
> IMO is no longer relevant.

I agree. I think we should remove it, and maybe relocate the material if someone wants it. I could see it transplanting into a back-dated "blog post" on typelevel.org—since what's there is not bad/wrong so much as it is dated.
