### ISSUE TITLE
readme points to broken link

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats#4395]
this link:

[https://typelevel.org/cats](https://github.com/typelevel/cats/blob/main)

appears on the readme, but it is (currently?) broken for me.

**Comment by armanbilge** [comment]
It's because the `href=""` is blank ...
https://github.com/typelevel/cats/blob/ccd576f0fb82af1747fe31fed28b833ff13cac03/README.md?plain=1#L39

**Comment by johnynek** [comment]
well, that would do it...
