### ISSUE TITLE
Seq instance `.foldRight` has performance implications

### ISSUE THREAD

**Issue by rudolmi** [typelevel/cats#4439]
I was profiling an application that relies heavily on traversal of conditions and contents it then needs to return. Such traversals include using `.findM` `.forallM` or `.existsM`, all defined in `Foldable`. I stumbled on the fact that these traversals are in case of performance reduced to `List.length` (see img - selected part of icicle graph )
<p align="center">
<img src="https://github.com/typelevel/cats/assets/11032933/e62c1db0-968b-4ffc-b31b-47a50f429f1f">
</p>

When I then looked at the implementation of `foldRight` in `seq.scala`:
```scala
def foldRight[A, B](fa: Seq[A], lb: Eval[B])(f: (A, Eval[B]) => Eval[B]): Eval[B] = {
  def loop(i: Int): Eval[B] =
    if (i < fa.length) f(fa(i), Eval.defer(loop(i + 1))) else lb
  Eval.defer(loop(0))
}
```
The `fa.length` is indeed called in each iteration of the loop function, going through approx. $\dfrac{3n^2}{2}$ elements for seqence of length `n`.

When I tried computing the length only once the `foldRight` function consistently achieved trice as many operations per time unit which is no surprise as the only iterations through the sequence would be the ones getting the i-th element, giving us estimate of only $\dfrac{1}{2}n^2$ for sequence of length `n`.

The proposed solution is then 
```scala
def foldRight[A, B](fa: Seq[A], lb: Eval[B])(f: (A, Eval[B]) => Eval[B]): Eval[B] = {
  val length = Eval.later(fa.length)
  def loop(i: Int): Eval[B] = if (i < length.value) f(fa(i), Eval.defer(loop(i + 1))) else lb
  Eval.defer(loop(0))
}
```

I used `.value` on the length `Eval` for simplicity but it can be just as well `flatMap`ped, keeping the laziness I believe.

I believe this is a low hanging fruit that should help speed up some things (at least in our app).

Let me know what you think!

**Comment by armanbilge** [comment]
Good catch, that seems reasonable to me!

> I used `.value` on the length `Eval` for simplicity but it can be just as well `flatMap`ped

I'm wondering if we can do something like this:

```scala
  Eval.defer {
    val length = fa.length
    def loop(i: Int): Eval[B] = if (i < length.value) f(fa(i), Eval.defer(loop(i + 1))) else lb
    loop(0)
  }
  ```

**Comment by johnynek** [comment]
this is a good catch, but there is no reason to `Eval.later(fa.length)` imo. I would either just do `val length = fa.length` or `lazy val length = fa.length`.

Let's consider two cases:

1. fa.length == 0, in which case it is very fast, in in that case we neve call `f`.
2. fa.length > 0, in which case we have to call f at least once and evaluate `fa.length`

So I think eagerly evaluating it is fine. That said, I guess it is possible you would never evaluate the result, in which case we could avoid evaluating `fa.length` if we use a lazy val.

Finally... there is a deeper issue here...

`fa(i)` is `O(N)` for many `Seq`. We really shouldn't use that. That said... why aren't we just calling this:
https://github.com/typelevel/cats/blob/bf3547357b1641b73b72efbcfe3674be806be3db/core/src/main/scala/cats/Foldable.scala#L952

**Comment by rudolmi** [comment]
>  I would either just do `val length = fa.length`
this defies laziness which is desired IMO

> or `lazy val length = fa.length`
`lazy val` synchronizes whole class as opposed to `Eval` which should synchronize only itself iirc

> why aren't we just calling `iterateRight`
That would be great!  I'm all for it.

**Comment by johnynek** [comment]
@rudolmi do you want to send a PR changing Seq to use iterateRight?

**Comment by rudolmi** [comment]
So when could this be a part of release? I'm asking because I'm excited about my first contribution and also expecting a business impact so it's good to have some estimate in hand. Is there an appetite for a patch version maybe?

**Comment by danicheg** [comment]
If snapshots work for you, you can already use `2.10-7499220-SNAPSHOT`.
