### ISSUE TITLE
`Apply` syntax is allocating

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats#4475]
I recently decompiled `fa *> fb` in https://github.com/http4s/http4s/pull/7154#discussion_r1257504907 and realized that using `Apply` syntax causes allocations 😬 

The problem seems to be here where we create a new instance of an `Apply.Ops` instead of creating an instance of an `AnyVal` class.

https://github.com/typelevel/cats/blob/fa32a6bf68cef64889fe00a5ab324bcfae0249d2/core/src/main/scala/cats/syntax/apply.scala#L26-L27

**Comment by armanbilge** [comment]
There's at least a few more like this 😕 

https://github.com/typelevel/cats/blob/fa32a6bf68cef64889fe00a5ab324bcfae0249d2/core/src/main/scala/cats/syntax/semigroupal.scala#L26-L27

https://github.com/typelevel/cats/blob/fa32a6bf68cef64889fe00a5ab324bcfae0249d2/core/src/main/scala/cats/syntax/contravariantSemigroupal.scala#L28-L31

https://github.com/typelevel/cats/blob/fa32a6bf68cef64889fe00a5ab324bcfae0249d2/core/src/main/scala/cats/syntax/contravariantMonoidal.scala#L28-L31

**Comment by mox692** [comment]
I'll look into this one.
