### ISSUE TITLE
Option size method implicitly selected from UnorderedFoldable

### ISSUE THREAD

**Issue by mcanlas** [typelevel/cats#4533]
Is this behavior expected?

```scala
//import cats.syntax.all._

object Main extends App:
  println(Option(123).size.getClass)
```

The `size` method on `Option` returns `Int` normally. But the `Ops`-style method from the import returns `Long`. Including the import automatically selects the `Ops` method. Is this expected?

Happens in both Scala `3.3.1` and `2.13.10`

See also #4370

**Comment by armanbilge** [comment]
> Is this expected?

Yes, I think so. I believe explicitly imported implicit conversions take precedence over implicit conversions that would normally be in scope automatically.

I think to fix it `def size: Int` would have to be explicitly added to `Option` in the Scala stdlib (I'm a little surprised its not already there).

**Comment by mcanlas** [comment]
Ahh, I did not realize `Option.size` in the STL was implicit via an `option to iterable` conversion. Now it makes sense
