### ISSUE TITLE
Support Scala Native 0.5

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats#4587]
Depends on https://github.com/typelevel/discipline-munit/issues/286.

**Comment by ekrich** [comment]
Looks like everything is ready so I requested a release - https://github.com/typelevel/discipline-munit/issues/294

**Comment by ekrich** [comment]
Release made it to central - https://repo1.maven.org/maven2/org/typelevel/discipline-munit_native0.5_3/

**Comment by satorg** [comment]
Just for cross-reference: this can be resolved by #4585 (awaiting a review)
