### ISSUE TITLE
tailRec instances aren't visible by default

### ISSUE THREAD

**Issue by kubukoz** [typelevel/cats#4652]
As far as I know, `import cats.syntax.all.*` is now the recommended mega-import. However, it doesn't bring the instances for `scala.util.control.TailCalls.TailRec` - those still require `import cats.instances.tailRec.*`.

These instances should probably be included in the companion objects of the typeclasses themselves so that they're auto-discoverable like most other instances.

**Comment by aluscent** [comment]
@kubukoz I'm interested in helping on this issue.
As I assumed from your explanation, we need to add implicit instances of the TailRecInstances into `Defer` and `StackSafeMonad`, right? Please give me more details and help me understand the problem.

**Comment by kubukoz** [comment]
I just checked and `Defer[TailRec]` already is in the companion of `Defer`: `implicit def catsDeferForTailRec: Defer[TailRec]`.

`StackSafeMonad` isn't a typeclass per se, I'm actually not sure why it appears in the type annotation (should be just `Monad` IMO)...

but there's a `Monad[TailRec]` in the companion object of `Invariant` too: `implicit def catsMonadForTailRec: Monad[TailRec]` - so I don't see why I opened this issue in the first place...

This works fine on 2.12, 2.13 and 3.x:

```scala
//> using dep org.typelevel::cats-core:2.12.0
import scala.util.control.TailCalls.TailRec
import cats.Monad
import cats.Defer

object Demo extends App {

  println(Monad[TailRec])
  println(Defer[TailRec])

}
```

**Comment by kubukoz** [comment]
Maybe there's a combination of compiler flags that causes the instances not to be picked up, but so far this seems like a non-issue.

**Comment by aluscent** [comment]
@kubukoz Thank you for checking!
As you discussed this is not an issue anymore. Do you think this thread should be closed?

**Comment by kubukoz** [comment]
yeah, I don't think I can reproduce it now.
