### ISSUE TITLE
Make Alleycats a submodule of Cats?

### ISSUE THREAD

**Issue by non** [typelevel/cats#472]
The original rationale for keeping Cats and Alleycats in separate repos was to accentuate the differences between the projects' strictness, PR guidelines, etc.
- Cats' type classes' behavior are underpinned by laws, Alleycats' may not be.
- Cats' instances are (generally) lawful, Alleycats' may not be.
- The criteria for including new or novel structures is more relaxed in Alleycats
- Useful-but-dangerous code is more welcome in Alleycats

However, @InTheNow brings up the possibility of moving Alleycats to a submodule of Cats, and there are a few reasons this could be a good idea:
- The libraries already require lock-step releases, this would make that harder to mess up.
- Reduce the barrier of moving code into Alleycats from Cats
- It would help reading code which is split across the two projects (e.g. related to JS futures)
- Alleycats could take advantage of the documentation machinery/links we are using in Cats

What do you all think? I'm leaning toward keeping the repos separate, but I'm open to being convinced.

**Comment by milessabin** [comment]
+1 from me to making alleycats a submodule of cats.

In the work I'm doing on Kittens I'm constantly switching between the two and having them together would make my life easier both from a readability PoV and the lockstep release PoV.

I'd also like to hope that we can come up sufficient inferred laws (via derivation) for at least some alleycats type classes that we could consider moving them into cats.

**Comment by dwijnand** [comment]
I think it's a good idea.

Both sides of the argument are good, but the 'against' arguments are more project related than repo-related. I'd say with keep the name 'alleycats' to keep accentuating the differences and detail what you've done above in places (README, docs..).

**Comment by InTheNow** [comment]
:+1: for alleycats under cats

For the tests for `FutureInstances` in `alleycats` I have currently copied the test from Cats. An alternative would be to publish the tests - and that, to me, is going even further in the wrong direction.

**Comment by adelbertc** [comment]
Unsure myself - I guess my concern is users may bring in `alleycats` easily seeing it's a proper module of Cats and then freely and happily use the law-breaking instances. I know bringing in `cats` (without a module suffix) brings in everything, is it possible to exclude `alleycats` from this and force people who want it to bring it in explicitly?

Also if we do bring it in, perhaps not `cats-alleycats`.. maybe `cats-lawbreaker`.. OK maybe not that, but something along those lines :-)

**Comment by non** [comment]
@adelbertc I think the plan would be to keep the Alleycats code in a separate scala module. So all the imports, etc would remain different. The only difference here is which repo the code lives in, it would still be published under `alleycats`, imported from `alleycats._`, etc.

**Comment by InTheNow** [comment]
@adelbertc I understand your concerns. 

I was originally going to suggest that `alleycats` not be part of the cats POM, but rather had to be explicitly specified in the client `build.sbt`. In further thought though, I think this is overkill, as just because `alleycats` is in the cats POM , you still have to explicitly import the alleycats modules in scala files (as @non said ^^). So, my personal vote would be "cats" brings in the lot, "alleycats" is _not_ changed to "cats-alleycats" and "build.sbt" authors can choose to bring in the lot or individual libraries.

Also, having used it a little bit, every time I type "alleycat" I do get that "yeah, dodgy" feeling - so the name does it's job for me

**Comment by ceedubs** [comment]
I wouldn't say I'm strongly opposed to this, but it leaves a feeling of being a slight publishing/infrastructure convenience at the cost of bloat. My main concern is this: if we add a binary-incompatible change to alley-cats and want that to be published, does this mean we need to publish a new version of cats? So far we don't have per-module versioning. I know cats is in active development now, but I'm hoping that at some point it can become pretty stable so it's not a nightmare to have as a dependency in a common library. This is especially important as more libraries like [circe](https://github.com/travisbrown/circe/issues/29), [monocle](https://github.com/julien-truffaut/Monocle/issues/235), and [http4s](https://github.com/http4s/http4s/issues/390) are considering whether they want cats to be a dependency. Considering this fact, I whether wonder this is really a publishing convenience at all.

**Comment by non** [comment]
@ceedubs: It's a good question.

So far, the policy is that new releases of Cats require new releases of Alleycats, and that the versions are kept in sync where possible. However, I agree that changes in Alleycats should not force changes in Cats. So I probably overstated the "lock-step releases" part.

We're in a weird state due to being pre-1.0, but in general, I see patch releases in Cats as strictly bug fixes, so in general Cats `a.b.x` and Alleycats `a.b.y` should always be compatible, for any `x` and `y`.

**Comment by InTheNow** [comment]
Is this worth adding to the https://github.com/typelevel/cats/milestones/cats-1.0.0 milestone?

**Comment by milessabin** [comment]
Bumped by #1059.

**Comment by ceedubs** [comment]
My main concerns here are those that I stated in https://github.com/typelevel/cats/issues/472#issuecomment-134554879 and that I'd be hesitant to have this included in the cats root project. The readme says to add `libraryDependencies += "org.typelevel" %% "cats" % "<version>"`, and I'd hate for people to pick up potentially troublesome instances/types/etc without explicitly opting into them (hopefully after a bit of research into why they are potentially troublesome).

**Comment by InTheNow** [comment]
@ceedubs But as per https://github.com/typelevel/cats/issues/472#issuecomment-133703261 , to actually use them, you have to explicit import them, eg  : 

```scala
import alleycats.Empty._
```
So the "warning" is quite explicit in the code, far better than in a build file

**Comment by InTheNow** [comment]
OTOH.....I would rather have them in the cats repo than not in, even if that meant they are not in cats root.

Somewhere, I also think also by @ceedubs, there was also the concern that the root project just pulled in everything, even if people did not want everything - ie cats root should never be used for production, but just as a quick "get started". Given that we should highlight this fact regardless, it would also perhaps be OK to include alleycats as well?

**Comment by ceedubs** [comment]
@InTheNow that's a fair point. Sorry I had forgotten about that and didn't notice it when I was skimming this issue again :)

**Comment by benhutchison** [comment]
Coming late to the party.. Im a +1 to this proposal.

I expect that alleycats will become a standard tool in my kit, so having it more integrated with cats releases would suit well. Also Im already observing some [close coupling](https://gitter.im/non/alleycats?at=57622c14b8ad3d5d7ee09da2) between alleycats and cats code  that suggests they should live close by.

**Comment by kailuowang** [comment]
@non if I understand correctly, in this [comment](https://github.com/typelevel/cats/issues/472#issuecomment-134559496) you are suggesting that we can have binary incompatible changes in Alleycats between patch release? I think as long as we communicate that well I am a +1 on this. I've been keeping alleycats in sync with cats in the last couple of releases, it's a bit annoying but not that big a deal.

**Comment by edmundnoble** [comment]
I am certainly a +1 on this. As long as we exclude alleycats from cats' imports, I don't see an issue here.

**Comment by milessabin** [comment]
Also :+1: ... it would be good to have a decision on this before 1.0.

**Comment by BennyHill** [comment]
Well that's 4 :+1: .

Maybe someone should just do a PR on this to move this forward? If nothing appears by the weekend, I'll try and push something for review with the understanding that acceptance is not guaranteed.

**Comment by BennyHill** [comment]
update: Had to fly back home last weekend, hence did not have the time I thought I would. This coming weekend is free, however.

**Comment by kailuowang** [comment]
Remove from project 1.0.0-MF as it's consolidated into #1682.

**Comment by dwijnand** [comment]
Done in #1984.
