### ISSUE TITLE
Dedupe readme and docs site

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#479]
Currently documentation that serves as an introduction to cats exists in both the [readme](https://github.com/non/cats#cats) and on the [cats site](http://non.github.io/cats/). @SethTisue has [pointed out](https://github.com/non/cats/pull/450#issuecomment-131660458) that it's an issue that getting started guides exist in two places.

We definitely don't want these to provide inconsistent information. The easiest way to ensure that is to trim them down to a single location.

My vote would be to have everything on the documentation site with a very light readme that links to the docs.

**Comment by fthomas** [comment]
Since #1915 the README.md is also the index.html of the docs site, so I think this can be closed.
