### ISSUE TITLE
Laws are missing in the published API docs

### ISSUE THREAD

**Issue by fthomas** [typelevel/cats#510]
All `*Laws` are missing in http://non.github.io/cats/api/#package. They should be included in the API docs because the laws are an important part of our type classes.

**Comment by sritchie** [comment]
Happy to fix this, but it looks like Github Pages isn't currently built. Should I try to get that working first?

**Comment by kailuowang** [comment]
@sritchie thanks! the repo is moved so the link original given isn't correct. It should be  http://typelevel.org/cats/api/#package

**Comment by bba615523** [comment]
bba615523@gmail.com
