### ISSUE TITLE
Fix law-checking to print better error messages

### ISSUE THREAD

**Issue by non** [typelevel/cats#514]
I'm not sure how to do this, but in Cats right now when a property fails you see the generated input (good) but then just a gigantic stack trace.

When we set this up in Algebra, the `?==` operator was designed to use ScalaCheck's labels so that you could "see" the values being compared when there was a failure. I'm not sure why that isn't working here.

Anyway, this isn't critically-important, but since many folks will be discovering law-checking through Cats, it would be good to have a better experience here.

**Comment by ceedubs** [comment]
I made an override to our `List` instance's `map` method to always return `Nil`, and I see a helpful label of the two values being compared just after the generated input:

```
[info] - List[Int] with Option.traverse.traverse identity *** FAILED *** (13 milliseconds)
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (Discipline.scala:14)
[info]     Falsified after 4 successful property evaluations.
[info]     Location: (Discipline.scala:14)
[info]     Occurred when passed generated values (
[info]       arg0 = List(-1847342633, -1931831606, 558565564, 0),
[info]       arg1 = <function1>
[info]     )
[info]     Label of failing property:
[info]       (List(-1135542905, -1135542905, -1135542905, -1135542905) ?== List()) failed
```

Note the `Label of failing property:` section at the end.

@non was this not showing up for you somewhere?

**Comment by ceedubs** [comment]
I think that this was improved by #2052. I'm going to go ahead and close this out. @non feel free to reopen if you think that there are still improvements that could be made here.
