### ISSUE TITLE
Consider publishing Cats test helpers

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#529]
@InTheNow has raised some good suggestions (https://github.com/non/cats/pull/522#discussion_r39263357 and https://github.com/non/cats/pull/522#discussion_r39263505) for items in Cats tests that may be useful in other project that depend on Cats. Currently we are publishing laws but not some of our helpers like `CatsSuite`, (currently pending) `CatsEquality`, etc. We may not want to publish `CatsSuite` in its entirety, since then it becomes harder to change, but there may be useful elements worth extracting.

We should consider publishing such items.

**Comment by InTheNow** [comment]
As an advanced possible route forward, you may want to look at [scala-bricks](https://github.com/InTheNow/scala-bricks), and in particular [scala-bricks test](https://github.com/InTheNow/scala-bricks/tree/master/tests/src/main/scala/bricks/tests)

**Comment by rossabaker** [comment]
`CatsSuite` could be very useful, but also favors ScalaTest.  One question to consider is what useful test kit might be produced that plays well with all the major test frameworks.

**Comment by adelbertc** [comment]
[discipline](https://github.com/typelevel/discipline) does a similar thing.. ish

**Comment by ceedubs** [comment]
Resolved by #1758

**Comment by BennyHill** [comment]
from ^^

> One question to consider is what useful test kit might be produced that plays well with all the major test frameworks.

https://github.com/typelevel/catalysts/ :wink:  see also https://gitter.im/typelevel/cats-dev?at=5ab7bb09e3d0b1ff2c66cb35

 But yes. this particular issue should be closed
