### ISSUE TITLE
Move Eval constructors to companion object?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#534]
Currently the `Eval` constructors (`Now`, `Later`, `Always`) are at the top-level of the `cats` package. That is, you would import `cats.Now`.

I would expect these to be defined within the `Eval` companion object, such that one would import `cata.Eval.Now`.

Arguments that come to mind for having them in the companion object:
- This would follow a convention that is used by many other Cats types such as `Xor`, `Ior`, `Streaming`, etc.
- Better namespacing. If we wanted another `Now` class, such as `Task.Now`, in the future, we wouldn't have to worry about name collisions.

Arguments that come to mind for the current approach:
- `Now`, `Later`, and `Always` may be used often enough in code that it is a bit more convenient to be able to grab them with `import cats._`.
- ScalaDoc makes it very hard to find types that are defined within an object. If you are looking for a class named `Right`, you have to know to search for `Xor` and then look at either its companion object or click on "Known Subclasses".

**Comment by non** [comment]
I agree that this seems to be a bit non-standard compared to the other types in `cats.data`.

In practice I almost never want to type `Eval.Now`, since you would tend to be using it in situations like these:

```scala
// compare this
ns.foldRight(Eval.Now(false)) { (n, b) => if (n != 0) Eval.Now(true) else b }

// to this
ns.foldRight(Now(false)) { (n, b) => if (n != 0) Now(true) else b }

// of course we wish were were writing
ns.foldRight(false) { (n, b) => if (n != 0) true else b }
```

So yeah, I personally enjoy it being pulled in with `import cats._` but the inconsistency is not great either (although you could argue that the convention might be limited to things in `cats.data`).

Anyway, I am happy to go whichever way folks think is best.

**Comment by ceedubs** [comment]
@non would you consider it much of a burden if for your example you needed something like `import cats._, Eval._` or `import cats._, Eval.Now` or `import cats._, Eval.now` at the top of the file to support this?

**Comment by milessabin** [comment]
Can you spell out a little more why you think this case is analogous with `Xor`, `Ior` etc.?

**Comment by ceedubs** [comment]
@milessabin the constructors for `Xor`, `Ior`, `Streaming`, etc are defined within the companion object (see [`Xor` constructors](https://github.com/non/cats/blob/master/core/src/main/scala/cats/data/Xor.scala#L142-L143) for example). So i would use `Xor.Right(a)` to wrap `a` in an `Xor`.

Does that answer your question, or were you asking why I think there should be consistency between `Eval` and `Xor` constructor placement?

**Comment by milessabin** [comment]
The latter.

I started writing a comment arguing that `Eval` was relevantly less like an ADT than `Xor` and `Ior` are, but in the process persuaded myself that it wasn't, or at least that it wasn't clear cut.

I will say that I think it seems more likely that `Always` and `Later` will appear in a method signatures than `Xor.Left` or `Xor.Right`, which suggests that for `Eval` it makes more sense to treat constructors as first class. OTOH, I'm in favour of treating constructors as first class _anyway_, so I can't really use that as an argument for distinguishing between the two ;-)

**Comment by ceedubs** [comment]
At this point it would needlessly break compatibility to change this, so I'm going to close this out.
