### ISSUE TITLE
Rename/create cats.effect.*

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#540]
Package would contain effect data types such as `Xor(T)`, `Writer(T)`, `Kleisli`, etc.

`data` would then contain stuff like `Streaming`, `Prod`, etc.

A trickier thing is what goes in `effect`:
- Does `Xor` count as an effect? If so, then so does `Validated`
- What about `Const`?
- Should we move the `mtl`-y things like `MonadError` and stuff in there?

**Comment by non** [comment]
Well, I would imagine things like `Streaming`, `OneAnd`, and other similar types would stay in `cats.data` right?

**Comment by adelbertc** [comment]
Right right, I assumed incorrectly everything in `data` was an "effect" - edited.

**Comment by philwills** [comment]
As someone still fairly low down the learning curve of FP, I still don't find effect an intuitive term, especially for something like Xor.

**Comment by tpolecat** [comment]
`Streaming` and `OneAnd` still have the "more than one value" effect, so I wonder if it's just too vague a term to be useful. Might just confuse people.

**Comment by arosien** [comment]
Perhaps the transformer versions of the typical monadic effects (XorT, ReaderT, WriterT) go in effect, whereas the non-transformer versions are "just" data. That is, effects are always layered on something.

**Comment by ceedubs** [comment]
Along the lines of what @tpolecat said, I'm not sure data/effect is the most meaningful distinction. List is definitely a data structure, but when I'm explaining `Functor` to people I'll often say that List's `map` has the "effect" of applying `f` to multiple elements.

Two thoughts:
1) Do people dislike that `Xor` etc are currently in the `data` package?
2) What about "structure" as a generic term that captures these classes?
3) There is always the possibility of putting structures into the top-level `cats` package where the core typeclasses are. I'm not necessarily saying we should do that, but it's a possibility.

**Comment by ceedubs** [comment]
Looks like I had an off-by-one error on my "Two thoughts".

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. We have settled on a convention. It may not be perfect, but to change it now would probably cause more of a headache than it would be worth. @adelbertc let me know if you have any lingering concerns here.
