### ISSUE TITLE
Create Auto macros a la Spire

### ISSUE THREAD

**Issue by non** [typelevel/cats#544]
In Spire we have some macros that will build type class instances by wiring up the "normal" method names.

https://github.com/non/spire/blob/master/core/shared/src/main/scala/spire/macros/Auto.scala

For example:

``` scala
package spire.examples

import spire.implicits._

case class Semi(n: Int) { lhs =>
  def plus(rhs: Semi): Semi = Semi(lhs.n + rhs.n)
  def times(rhs: Semi): Semi = Semi(lhs.n + rhs.n)
  def compare(rhs: Semi): Int = lhs.n compare rhs.n
}

object Semi {
  val semiHasSemiring: Semiring[Semi] = Auto.scala.semiring[Semi]
  val semiHasOrder: Order[Semi] = Auto.scala.order[Semi]
}
```

(The `.scala` part is there because we also support Java classes. I don't think Cats would need to do this -- we could just use `Auto` probably.)

This would be really nice for data types which know about Cats -- in those cases, they can just use the "normal" names and get wired up automatically. For example, you could imagine something like:

``` scala
implicit val NelHasBimonad: Bimonad[Nel] =
  Auto.bimonad[Nel](pure = ..., extract = ...)
```

This reduces boilerplate and helps make it easy for us to define methods both on the data type and also on a type class instance.

What do you all think?

**Comment by larsrh** [comment]
New macros are definitely out of scope now.
