### ISSUE TITLE
Add syntax for MonadError, MonadReader, and MonadState

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#561]
Currently these type classes don't have syntax support.

**Comment by stew** [comment]
what would syntax support allow you to do that you can't do now?

**Comment by adelbertc** [comment]
i've found myself wanting `MonadError#handleError`

**Comment by stew** [comment]
ah yes, that one makes sense. I'm not sure what makes sense for Reader. i guess with state we can expose put and and modify but read doesn't make sense, right?

**Comment by adelbertc** [comment]
Agreed

**Comment by davegurnell** [comment]
I'm in need of `raiseError`. I'll knock up a PR for `ApplicativeError` covering:

- `raiseError`
- `handleErrorWith`
- `handleError`
- `attempt`
- `attemptT`
- `recover`
- `recoverWith`

**Comment by edmundnoble** [comment]
We have syntax for `MonadReader` and `MonadState` in cats-mtl; every transformer class has *all* of the syntax that makes sense for it.
