### ISSUE TITLE
Should Unapply live in another project?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#574]
As I was watching @non's [Principles for Modular, Functional, Approachable Libraries](https://www.youtube.com/watch?v=iKyIKozv8a8) talk, his claim that we have many libraries reinventing their own versions of the same concept (such as tagged types) resonated with me. It occurred to me that our [`Unapply`](https://github.com/non/cats/blob/master/core/src/main/scala/cats/Unapply.scala) is not specific to Cats at all. Should this be extracted into a separate standalone project? Is this something that would live in [typeclassic](https://github.com/typelevel/typeclassic)?

**Comment by non** [comment]
I think this is a good idea. I'd like to make it easy for other projects which need `Unapply` to be able to interoperate without depending on `cats-core`. I could certainly imagine including something like that in Typeclassic (I think @milessabin had mentioned something like this too).

**Comment by mpilquist** [comment]
:+1: from me. The generated syntax traits could benefit from `Unapply` living in typeclassic.

**Comment by stew** [comment]
:+1:

**Comment by milessabin** [comment]
I agree that this could be split out from Cats to a separate library. I'm not 100% convinced that it should be typeclassic though ... that's supposed to be focussed on supporting type class idioms in Scala, and `Unapply` strikes me as orthogonal to that.

**Comment by ceedubs** [comment]
@milessabin it may be convenient for typeclassic to use `Unapply` to help reduce `Unapply` boilerplate for type class syntax that often comes up. However, I think `Unapply` can also stand on its own. So perhaps it would make more sense to have `Unapply` be in its own micro library and typeclassic could depend on that if desired?

**Comment by milessabin** [comment]
@ceedubs :+1:

**Comment by milessabin** [comment]
(sorry, hit the wrong button)

**Comment by ceedubs** [comment]
I'm quite happy to close this out in favor of the SI-2712 fix. There's #1073 to track the details of that transition for Cats.
