### ISSUE TITLE
Should we rename Coyoneda?

### ISSUE THREAD

**Issue by stew** [typelevel/cats#576]
@ceedubs introduced a Coyoneda into a project here at $work and got some snide comments about "what language is this?". it got us talking about whether or not we should consider renaming Coyoneda to FreeFunctor, which might be a little less "scary" to people less familiar with these concepts.

Cody quickly remarked that he would then want to also rename Free to FreeMonad for consistency.

how do people feel about this one?

**Comment by non** [comment]
I definitely support renaming `Free` to `FreeMonad`. There are many *free* constructions and I don't think it necessarily makes sense to privilege monads here.

**Comment by hakuch** [comment]
I just wanted to comment that the difference between specific monads (like `FreeMonad`) and type-classes like `MonadError` is a little confusing without prior knowledge.

**Comment by tpolecat** [comment]
Can we rename `List` to `FreeMonoid`?

**Comment by stew** [comment]
@tpolecat and alias `String` to `FreeMonoidOverChars` ?

**Comment by fthomas** [comment]
And `NonEmptyList` to `FreeSemigroup`. But seriously, I too support `Free` -> `FreeMonad`

**Comment by non** [comment]
Do you all think using aliases makes sense here?

I'm not sure I support forcing people to stop using the `Coyoneda` name. For one thing, if someone is working with `Yoneda` that is also a *free functor*. For another thing, the relationship between `Yoneda` and `Coyoneda` (and the *Yoneda Lemma*) might be useful to highlight.

In some ways, providing a type alias (and a companion object alias as a `val`) might allow folks in this kind of situation to use a less esoteric name. But maybe that doesn't really help things?

**Comment by tpolecat** [comment]
I vote for leaving things as-is (i.e., `Yoneda/Coyoneda` and `Free/Cofree`).

**Comment by travisbrown** [comment]
Using standard, easily searchable names seems a lot more beginner-friendly to me than using something non-standard and less precise. I also think type aliases for things like this just add to the confusion.

I would vote for renaming `Free` to `FreeMonad`, though.

**Comment by rossabaker** [comment]
:+1: to everything @travisbrown just said.  I think the alias would be more confusing than either name.

**Comment by refried** [comment]
If there were an alias, which one would be the "standard" name? (appearing in error messages)

I think my $work would understand FreeFoo more readily.  When I was learning, the "Free" monad and Coyoneda were pretty meaningless; even after I kind of got Coyoneda thanks to @puffnfresh's post about Set, it wasn't until hearing about the free monoid in one of @runarorama talks that all three really clicked for me, and I think for coworkers as well when I retold it.

But I mainly came to say I'm jealous of @stew and @ceedubs now that I know they both work someplace with multiple cats contributors.

**Comment by runarorama** [comment]
Just to comment on @hakuch's concern about confusion with type classes... it's not entirely unwarranted to think of the free monad as a type class. It's not one specific monad, but a whole class of monads, namely the monads that admit a homomorphism to any other monad.

Also, @refried, you should come work with us.

**Comment by refried** [comment]
@runarorama Tell me how ;-)

**Comment by runarorama** [comment]
@refried Send's an email to my github handle at gmail.

**Comment by ceedubs** [comment]
I think that now that we are past a 1.0 release it would be a hassle and _more_ confusing to make any of these name changes now. I'm going to go ahead and close this out.
