### ISSUE TITLE
Missing Contravariant instances

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#579]
There are a number of types that we are either missing `Contravariant` instances or are not being tested by the `ContravariantTests` introduced in #578.

I think the following fit into this category: `Kleisli`, `Const`, `Show`, `Equal`, `Order`, `StateT`. There could very possibly be more.

We should add these instances and tests.

https://github.com/non/cats/pull/578/files#diff-5a256f6c87581d09dae79f590a0a91e4R23 should serve as a good example of testing a type's `Contravariant` instance.

**Comment by philwills** [comment]
Partially addressed by #626

**Comment by peterneyens** [comment]
I think #1211 added the last missing `Contravariant` instance, so I am closing this issue. 
We can still reopen this if someone finds a missing instance.
