### ISSUE TITLE
Better error message for missing implicits

### ISSUE THREAD

**Issue by non** [typelevel/cats#581]
Lots of newcomers forget to import implicit instances (e.g. `cats.implicits._`) which causes lots of pain.

It might be nice if when `Functor[X]` is not found, the the message indicates that you may have failed to import it (and can even mention `cats.std.all._` or `cats.implicits._`).

What do you all think?

**Comment by non** [comment]
(The bad part here is that I think this would require annotating every type class with some kind of message. Either that, or wiring it up to Simulacrum somehow.)

**Comment by milessabin** [comment]
Big +1 for wiring up in Simulacrum.

**Comment by erwan** [comment]
I just did a PR in Simulacrum (with help from @larsrh) : https://github.com/typelevel/simulacrum/pull/144
