### ISSUE TITLE
Cross reference `Xor` and `Validated` in documentation

### ISSUE THREAD

**Issue by metasim** [typelevel/cats#603]
Per [gitter conversation](https://gitter.im/non/cats?at=563cbd5a3264958d1dc5d70b), it would be helpful for new users to understand the nuanced difference between the use cases supported by `Xor` and `Validated` (vis a vis accumulation of errors).

**Comment by ceedubs** [comment]
I believe this was resolved a while back. Feel free to reopen if there is more that you would like to see happen.
