### ISSUE TITLE
Add binary compatibility plugin

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#608]
Note: this can wait until just before the 1.0 release.

We should add the [mima plugin](https://github.com/typesafehub/migration-manager/wiki/Sbt-plugin) for detecting binary compatibility issues. This will ensure that patches patches (such as 1.0.1) are compatible with previous versions (such as 1.0.0) that other dependencies in a project may be built against.

**Comment by InTheNow** [comment]
See also Add Mima support - https://github.com/InTheNow/sbt-catalysts/issues/8

**Comment by kailuowang** [comment]
we just need to enable it for all modules post 1.0.0

**Comment by kailuowang** [comment]
done
