### ISSUE TITLE
Add more WriterT instances

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#620]
`WriterT` currently has `Monad` and `Eq` instances, but there are many more that it could have. Some examples that I think can be added are:
- [x] Functor (#628)
- [x] Apply (#628)
- [x] Applicative (#628)
- [x] FlatMap (#628)
- [x] MonadFilter (#696)
- [x] Alternative (#696)
- [x] MonadCombine (#696)
- [x] ApplicativeError (#689)
- [x] MonadError (#689)
- [x] Show (#928)
- [ ] Foldable
- [ ] Traverse
- [x] Bifunctor (#673)
- [x] CoflatMap (#1049)
- [ ] Comonad
- [x] Semigroup (#1014)
- [x] Monoid (#1014)
- [x] SemigroupK (#696)
- [x] MonoidK (#696)

**Comment by ceedubs** [comment]
I'll work on this.

**Comment by akilegaspi** [comment]
Is this still in progress? I'm thinking of contributing for this enhancement.

**Comment by kailuowang** [comment]
that'll be awesome. I updated the checklist, three instances still missing.

**Comment by akilegaspi** [comment]
Just a quick question.

Is the resolving type for the `WriterT[F, L,  A]` after passing through `extract` is `F[(L, A)]`

**Comment by barambani** [comment]
I would look into this one if that's ok.

**Comment by akilegaspi** [comment]
I think this should be closed since @barambani already finished it and it has been merged to master
