### ISSUE TITLE
Misleading error for type class instances related to Future

### ISSUE THREAD

**Issue by lambdista** [typelevel/cats#670]
When using `Future`-related type classes you get a misleading error: _could not find implicit value for parameter instance..._. It's as if it cannot find an instance of the given type class for `Future` in scope when it actually cannot just find an `ExecutionContext`. Example, with a REPL session, for `Functor`:

``` scala
scala> import scala.concurrent.Future
import scala.concurrent.Future

scala> import cats.Functor
import cats.Functor

scala> import cats.std.future._
import cats.std.future._

scala> Functor[Future].map(Future.successful(42))(_ + 1)
<console>:16: error: could not find implicit value for parameter instance: cats.Functor[scala.concurrent.Future]
       Functor[Future].map(Future.successful(42))(_ + 1)
              ^
```

but after importing the default `ExecutionContext` it works:

``` scala
scala> import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.ExecutionContext.Implicits.global

scala> Functor[Future].map(Future.successful(42))(_ + 1)
res1: scala.concurrent.Future[Int] = scala.concurrent.impl.Promise$DefaultPromise@6335ab80
```

**Comment by ceedubs** [comment]
For reference, [here](https://gitter.im/non/cats?at=564a3a658b242470793e3053) is a Gitter conversation that happened about this.

**Comment by armanbilge** [comment]
`Future` instances are deprecated now via https://github.com/typelevel/cats/pull/4230.
