### ISSUE TITLE
OptionT implements MonadCombine, but doesn't meet the laws

### ISSUE THREAD

**Issue by mikejcurry** [typelevel/cats#693]
Whilst looking at `OptionT` today and adding some tests in #692, I noticed that the `OptionT` has a `MonadCombine` instance, plus implementations for empty and combine. 

The tests exercise `MonadCombineTests.monad` instead of `MonadCombineTests.monadCombine`, which means that the implementations of `empty` and `combine` are not tested against the laws (or anything).

I briefly looked at increasing the test to `monadCombine`, but the current implementation of `OptionT` does not pass the laws, at least not for `OptionT[List, Int]`.

I noticed that #687 proposes to remove, at least temporarily, the `MonadCombine` for `XorT` - if a similar approach is warranted here I can take a look. By similiar in this instance, I mean that it might make sense to reduce the implementation to `Monad` until the laws pass.

**Comment by ceedubs** [comment]
Good catch! Thank you for bringing this to attention.

I think that the right approach would probably be to:
1. Remove this instance
2. Make sure we have an issue for separating the weak and strong laws suggested by those comments in the `XorT` code
3. Create new issues for adding back in the `XorT` and `OptionT` instances once the laws work has been finished.

How does that sound?

**Comment by mikejcurry** [comment]
That sounds sensible. I can put together a PR(after #692 - as both PRs will touch OptionTTests) and create issues for tracking.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out since it was resolved with #698 and #695 tracks the follow-up.
