### ISSUE TITLE
Move Cats to typelevel / org.typelevel?

### ISSUE THREAD

**Issue by non** [typelevel/cats#723]
Hi folks,

Now that the project has gotten pretty big I feel like it may be time to move from my personal account.

I think Typelevel is a good fit (we already use its code of conduct) and many of us are involved there. It would also allow many other people to be involved in the release process (currently I think I am the only one who can publish releases, which is not ideal).

This change would involve changing the organization from *org.spire-math* to *org.typelevel* and moving the repo from *non* to *typelevel*.

I think I've discussed this in Gitter informally and everyone agreed. Are there any concerns?

**Comment by milessabin** [comment]
+1

**Comment by julien-truffaut** [comment]
:+1:

**Comment by fthomas** [comment]
:+1:

**Comment by philwills** [comment]
:+1:

**Comment by tpolecat** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1:

**Comment by mandubian** [comment]
:+1:

**Comment by travisbrown** [comment]
:+1:

**Comment by mpilquist** [comment]
:+1:

**Comment by ceedubs** [comment]
I'm not sure if it's necessary at this point, but throw another :+1: onto the list :)

I would like to understand more about what Typelevel is, and it sounds like that's going to be discussed quite a bit between now and the Typelevel summit, which I very much look forward to.

**Comment by adelbertc** [comment]
So looks like this is done, should we start publishing under `org.typelevel` now instead of `org.spire-math`? Also do we want to move the repo to typelevel?

**Comment by adelbertc** [comment]
This is done
