### ISSUE TITLE
Add cata to syntax.option

### ISSUE THREAD

**Issue by TimPigden** [typelevel/cats#749]
I want to move codebase over to cats from scalaz. But I've made a lot of use of the cata extension to option
It would be great if this could be implemented in cats too.

**Comment by ceedubs** [comment]
For some more background, here's an example of where `cata` has better inference than `Option.fold`:

```
scala> val x: Option[Int] = Some(3)
x: Option[Int] = Some(3)

scala> x.fold(Nil)(_ :: Nil)
<console>:9: error: type mismatch;
 found   : List[Int]
 required: scala.collection.immutable.Nil.type
              x.fold(Nil)(_ :: Nil)
                            ^

scala> final implicit class OptionOps[A](fa: Option[A]) { def cata[B](ifNone: => B, ifSome: A => B): B = fa.fold(ifNone)(ifSome) }
defined class OptionOps

scala> x.cata(Nil, _ :: Nil)
res1: List[Int] = List(3)
```

**Comment by ceedubs** [comment]
There is some relevant Gitter conversation [here](https://gitter.im/non/cats?at=566eba84187e75ea0e488bf2). My initial stance is that the inference from `cata` can be be handy, and I'd be happy to see this in Cats. But I also will admit that this probably isn't critical core functionality that one needs to do functional programming in Scala, so I'm also okay with the decision being that this should live somewhere else.

For what it's worth, there is a precedent of adding handy Option-related syntax in #483.

**Comment by mikejcurry** [comment]
Worth noting that `OptionT` defines `cata` as a single parameter list variant of `fold`, with a comment noting the type inference implications.

Whilst `OptionT` is a full data type, so different from `Option`, it is worth considering the consistency perspective here.

**Comment by benhutchison** [comment]
+1 to adding `cata` or similar

**Comment by ceedubs** [comment]
The official recommendation is now to use [mouse](https://github.com/benhutchison/mouse) for syntax enrichments to std library types that aren't really closely related to cats. I'm going to go ahead and close this out.
