### ISSUE TITLE
Proposed Contribution: The Emm Monad

### ISSUE THREAD

**Issue by djspiewak** [typelevel/cats#766]
I threw some scattered thoughts up on twitter on this topic today, but code speaks louder than words: https://gist.github.com/djspiewak/da1189c49887b04d1dc7  Currently implemented in terms of scalaz typeclasses, but it's easy to see how it could be swapped to cats.  Quick example:

``` scala
type C = List |: Option |: CCNil
// > defined type alias C
val e = Option(42).liftM[C]
// > e: Emm[C,Int] = Emm(List(Some(42)))

e map (2 *)
// > warning: there was one feature warning; re-run with -feature for details
// > res2: Emm[C,Int] = Emm(List(Some(84)))

for {
  x <- Option(42).liftM[C]     // can't use Some without ascribing Option
  y <- List(12, 22).liftM[C]
} yield x + y
// > res3: Emm[C,Int] = Emm(List(Some(54), Some(64)))


import scalaz.effect.IO
// > import scalaz.effect.IO

// note how the IO action is the outermost effect
type CIO = IO |: List |: CCNil
// > defined type alias CIO

val e = for {
  v <- List(1, 2, 3, 4).liftM[CIO]
  _ <- (IO { println(v) }).liftM[CIO]
} yield ()
// > e: Emm[CIO,Unit] = Emm(scalaz.effect.IOFunctions$$anon$6@6f8b1902)

e.run.unsafePerformIO()
// > 1
// > 2
// > 3
// > 4
// > res4: |:[List,CCNil]#Point[Unit] = List((), (), (), ())
```

Basically, this is a replacement for monad transformers designed to be clean and simple and friendly to scalac's type inference quirks.  It differs from Oleg's `Eff` in that I make no attempt to solve some of the fundamental _limitations_ of monad transformers (Oleg has some excellent examples [here](http://okmij.org/ftp/Haskell/extensible/)), but in avoiding this rats nest, `Emm` acquires some significant advantages.

Most notably, `Emm` is completely compatible with any pre-existing monad.  In fact, it's actually _more_ compatible and well-integrated than monad transformers are, since you don't need to define a special `Hoist` or "T" encoding of your monad.  Everything is defined in terms of `Functor`, `Applicative`, `Traverse` and `Bind`.  Constraints are minimally imposed, which means that stacks such as `Emm[IO |: Option |: CCNil, A]` are sensible and allowed, but `Emm[Option |: IO |: CCNil, A]` is nonsense and disallowed statically.

Anyway, the implementation is very friendly to type inference, requires type lambdas only in the event of stack slots like `Either` or `State`, and because most of the machinery is done via implicits, it would actually be possible to customize the error messages to a significant degree.  The goal is basically to take all of the things about monad transformers that are legitimately confusing, annoying and downright dumb… and fix them.

Would there be interest in contributing this to cats?  Where would you want me to put it?  Some of the organization is non-trivial, as there's a bit of global-namespace syntax and a noticeable amount of (scoped) implicit machinery, _a la_ shapeless.  What is the idiomatic way to integrate such functionality?  Any thoughts on organization and constraints?  Bugs?  Syntax objections?

Without getting too far ahead of ourselves, this functionality does have the potential to completely replace all monad transformer mechanisms (it's weaker than `Eff`, but equal in power to the current "T encoding").  If we want to all jump on the crazy train, we could rip out the existing transformer functionality once this lands, though given that this code is literally five hours old, such a step might be a _bit_ premature.  ^_^

**Comment by milessabin** [comment]
Is there any need to introduce a concrete coproduct type for this? One of the goals of shapeless 3.0 is to remove (or at least make unnecessary) both `HList` and `Coproduct` and rework them in terms of a [more general abstraction](https://github.com/milessabin/shapeless/blob/wip/smc/core/src/main/scala/shapeless/smc.scala#L25) which can be realized in terms of nested pairs and `Unit` or nested eithers and `Nothing` or anything else structurally equivalent. So why not use nested `Either` here as well?

Otherwise, a bit :+1: ...

**Comment by milessabin** [comment]
BTW, what's the etymology of "Emm"?

**Comment by julienrf** [comment]
@djspiewak Interesting, I didn’t digest the gist yet but I have one question: your `Emm` monad only has `map`, `flatMap` and `flatMapM` ; how could you define a method like [`OptionT#getOrElse`](https://github.com/non/cats/blob/88babeeca3e926e885bc35ed6e9e82b254b693be/core/src/main/scala/cats/data/OptionT.scala#L48-L49)? (Or what could be the equivalent, with your solution)

**Comment by djspiewak** [comment]
> Is there any need to introduce a concrete coproduct type for this? One of the goals of shapeless 3.0 is to remove (or at least make unnecessary) both HList and Coproduct and rework them in terms of a more general abstraction which can be realized in terms of nested pairs and Unit or nested eithers and Nothing, or anything else structurally equivalent. So why not use nested Either here as well?

Partially for syntactic reasons (it needs to be *very* easy to write the effect stack, since users need to be somewhat explicit), partially because I was being lazy and not generalizing, but mostly because of type inference.  The coproduct in my implementation (`CoPConst`) is a coproduct (or rather, an hlist; uniqueness is irrelevant) of type constructors of arity 1.  I was very leery of making that structure too fancy simply because of SI-2712.  The nice thing about how this came together is the coproduct effectively acts as a guide for type inference in all subsequent terms, avoiding the need to be explicit except in the coproduct type declaration.  I suspect I would lose that property in some cases if I tried to generalize the underlying structure.

> BTW, what's the etymology of "Emm"?

Well, Oleg already took "Eff".  Eff is a brilliant name, because it is both short for "effect" and a pun on the english pronunciation of the letter "F", a common variable name for polymorphic type constructors (e.g. `F[_]`).  I wanted to make it clear that my monad was *not* `Eff`, but still accomplished many of the same goals.  I couldn't be as cool with the punning, but I liked the idea of phonetically spelling out a common variable name.  We often use `M[_]` for polymorphic monad types, so… "emm".  :-)

> Interesting, I didn’t digest the gist yet but I have one question: your Emm monad only has map, flatMap and flatMapM ; how could you define a method like e.g. OptionT#fold? (Or what could be the equivalent, with your solution)

It's an interesting question.  The best way I can think of to handle functions like `EitherT#fold` or `OptionT#getOrElse` is something like this:

```scala
val e: Emm[IO |: Option |: CCNil, String] = ...

e.flip[Option] map { _ getOrElse "default" }     // => Emm[IO |: CCNil, String]
```

To be clear, the `flip` function would traverse the specified type constructor to the base of the stack and then lift it out of the hierarchy.  So, in this case, `flip` would have the following type:

```scala
e.flip[Option]      // => Emm[IO |: CCNil, Option[String]]
```

You would probably want an `unflip` to reverse this process.  And honestly, you would probably want a couple of different functions that give you more control over the stack order post-construction.  But this is the general thought about how the transformer-specific functions could be handled.

**Comment by djspiewak** [comment]
@julienrf After some experimentation, a pair of functions, `expand`/`collapse`, appears to work the best in terms of type inference.  An example:

```scala
type E = Task |: Option |: CCNil
val opt: Option[Int] = None

// this type infers better than a single function
val e = opt.liftM[E].expand map { _ orElse Some(24) } collapse

e.run.run must beSome(24)
```

I tried implementing the `base` idea, since it's more syntactically lightweight, but unfortunately the order of type parameters forces an explicit annotation of the lambda value parameter, which is annoying.  The `expand`/`collapse` functions though seem to infer quite nicely.

Basically, `expand` takes the inner-most effect off the stack and pushes it into the value slot, making it manipulable using standard functions (e.g. `map`).  The `collapse` function is simply the inverse operation: inferring the outer-most type constructor from the value slot and making it the inner-most effect on the stack.  Note that this is basically guaranteed to run into higher-order unification problems if you try it with any non-trivial type constructors (or a value slot which is itself a nested type constructor), so don't go crazy and expect it to work.  :-)

In other news, I tossed everything into a github repo for now, since working on a gist (and, local to my machine, a single raw file) is awkward.  https://github.com/djspiewak/emm

**Comment by djspiewak** [comment]
@larsrh I was reminded by a few people today of some old work that @tixxit did – I think he called it `TraverseT` – which derived monad transformer instances using `Traverse`.  There was some sort of problem with this approach, I *believe* with `ListT` and `OptionT`, where the behavior was inconsistent with expectations or something like that.  No one (including me) can remember what the problem was, and it appears that the discussion where the issue was identified happened offline and was never transcribed onto the interwebs (gasp!), because Google can't find it either.

Do you remember what the problem was?  It's entirely possible that `Emm` would suffer from the same issue, due to the similar fundamental derivation.

**Comment by ceedubs** [comment]
@djspiewak I took a look at `Emm`, and it's really neat!

There's a constant struggle to figure out what belongs in Cats and what should live as its own separate project. Do you have thoughts on whether bringing something like this into Cats could be more beneficial than having it live as a separate project?

At the moment there seem to be several different approaches to effects being actively worked on in the Scala community, and I kind of like that they are each being developed in parallel instead of one becoming the default and work on the others halting. I guess I'd be inclined to continue down that path unless/until there is some stabilization and a consensus that a certain approach (or approaches) should live in a core FP library directly. I'm curious what your thoughts are.

**Comment by djspiewak** [comment]
@ceedubs I can see both sides of it.  On the one hand, having something like this in the core library makes it clear that people don't need to use monad transformers to get effect composition.  It gives them a better option without having to seek out another library that they may or may not know exists.  On the other hand, `Emm` can evolve rapidly outside of cats, which is a nice perk.  It also gives us the opportunity to use things like shims to support not just cats but also scalaz, whereas I don't think that would make any sense if it were part of cats (even as a submodule).

**Comment by adelbertc** [comment]
A related question is @etorreborre also has [`eff-cats`](https://github.com/etorreborre/eff-cats) (and is [proposing](https://github.com/typelevel/general/issues/8) it as a Typelevel project) with a similar but separate idea of composing effects. While I don't see anything wrong with say, having `Emm` in `cats` and having `eff-cats`, it may be a bit confusing? I can see value in having a separate `emm-cats` (along with `eff-cats`) .. perhaps we should also do `transformer-cats` or something.

**Comment by etorreborre** [comment]
I think transformers and effects libraries should be left as separate projects involving different trade-offs like type-inference, flexibility of the stack, of the interpreters, performance, support for all types of monads, compilation error messages... It is probably too early to name a definitive "winner" in terms of how to deal with effects (if such a thing exists).

**Comment by adelbertc** [comment]
Agreed, though it seems transformers seem to be the de facto. That said I would like to discuss (even if we end up not doing it) the idea of having a cats-transformer and pulling XorT and friends in there

**Comment by wedens** [comment]
I think it should be closed as Emm is proved to be unlawful and not recommended to use.

**Comment by djspiewak** [comment]
Oh I completely forgot about this. Very much it should be closed.
