### ISSUE TITLE
Code in documentation does not compile

### ISSUE THREAD

**Issue by PhilAndrew** [typelevel/cats#773]
In https://non.github.io/cats//tut/const.html

implicit def constApplicative[Z]: Applicative[Const[Z, ?]] =

Where it has the ?, does not compile.

**Comment by non** [comment]
@PhilAndrew In order for examples using `?` to compile you'll need to use [Kind Projector](https://github.com/non/kind-projector).

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out, because I think we now have a message about kind-projector on all of the code examples that use it. Please feel free to reopen if we've missed any or if you think there's another way we could make this clearer.
