### ISSUE TITLE
Names of operations of for semigroups, monoids, groups

### ISSUE THREAD

**Issue by rklaehn** [typelevel/cats#776]
There was a long discussion about the name of the Monoid methods in https://github.com/non/algebra/issues/131

The conclusion from both spire and algebra was that while everybody was OK with `combine`, `empty` is not a good name for the neutral element in an algebraic context. `neutral` was suggested and found acceptable by @denisrosset and @johnynek from the algebra side as well as @mpilquist and @ceedubs from cats.

I would propose renaming the neutral element to `neutral` and related methods (e.g. `isEmpty`) to `isNeutral`. Other possible names would be `id` (like it was called in spire) and `identity`, but I am not sure if we should start the whole discussion again. @non what do you think?

**Comment by ceedubs** [comment]
I guess that we dropped the ball on resolving the discussion on this one. @rklaehn I think that you bring up good points. But at this point it would be rather disruptive to change these names, for marginal benefit. I'm going to go ahead and close this out.
