### ISSUE TITLE
Move Free/State to data package?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#785]
Currently there are separate (but small) packages for `free` and `state`. This is because up until #760 they were in their own separate modules. Now that they are within `core`, should we drop the `free`/`state` from their package name and move them to the `data` package to be more consistent with other types like `WriterT`?

I'm not sure `data` is a particularly meaningful package name for some of these types, but that's probably a tangential issue (if it's an "issue" at all).

**Comment by dwijnand** [comment]
:+1: from me, for either `cats.data` or `cats`.

**Comment by travisbrown** [comment]
:+1:, and I'm fine with having them all directly under `cats.data`.

**Comment by ceedubs** [comment]
Update: Since #990 was merged, this no longer applies to `free`.

**Comment by ceedubs** [comment]
Oops I just realized that `State` has already been moved to the `data` package. Looks like it's time to close this out.
