### ISSUE TITLE
Bitraverse type class

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#800]

**Comment by ceedubs** [comment]
This would extend `Bifoldable`, which it seems like people have agreed on adding in #94 but that nobody has gotten around to yet.

**Comment by ceedubs** [comment]
oh and :+1: :)

**Comment by adelbertc** [comment]
Does anyone have a use case for this?

**Comment by travisbrown** [comment]
I've used both `bisequence` and `bitraverse` fairly often, for things like a more generic `zip`:

```scala
scala> import scalaz._, Scalaz._
import scalaz._
import Scalaz._

scala> (some('a'), some(1)).bisequenceU
res0: Option[(Char, Int)] = Some((a,1))
```

…or printing / logging both sides of an option, etc.

**Comment by adelbertc** [comment]
working on this
