### ISSUE TITLE
cats/scalaz migration guide

### ISSUE THREAD

**Issue by stew** [typelevel/cats#82]
we should have one in the gh-pages

**Comment by ceedubs** [comment]
I'm marking this as "on hold" until things stabilize. I'd hate to see someone put a lot of effort into making this and then having everything change out from underneath the migration guide.

**Comment by ceedubs** [comment]
Oops accidentally hit "Close and comment" instead of "Comment"

**Comment by stew** [comment]
makes sense

**Comment by rabbitonweb** [comment]
Maybe it's worth starting to work on migration guide, step by step, things getting more stable I guess?
