### ISSUE TITLE
Table of Contents in docs

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#846]
@raulraja [has mentioned](https://github.com/typelevel/cats/pull/832#discussion_r51351700) that it might be nice to puts tables of contents in the documentation, especially for longer docs. I agree that this might be helpful.

We could manually create them, or we could look into something fancy like a Jekyll plugin that automatically generates them.

**Comment by adelbertc** [comment]
I think we have this now in the new microsites, got a sidebar on the left.
