### ISSUE TITLE
Update docs to 0.4.0

### ISSUE THREAD

**Issue by ochrons** [typelevel/cats#854]
The current documentation (at http://typelevel.org/cats/) is still referring to `"org.spire-math" %% "cats" % "0.2.0"`. Also some parts of the doc are not correct anymore, due to changes in 0.4.0 (for example http://typelevel.org/cats//tut/apply.html)

**Comment by ceedubs** [comment]
@ochrons this has been resolved now that the updated site has been pushed, right?

**Comment by ochrons** [comment]
Yup, all good! Sorry for the false alarm :)
