### ISSUE TITLE
Update sources links in the docs, or remove them entirely

### ISSUE THREAD

**Issue by vpavkin** [typelevel/cats#860]
As noted [here](https://github.com/typelevel/cats/pull/859#discussion-diff-51724965), all pages should be updated.

There's another problem with those links: they are not shown anywhere. Template markup has `useful links` section, but it's hidden by [this css line](https://github.com/typelevel/cats/commit/02ea3d924c3edc0861c15d68b7d0b0a18d2e69b1#diff-2009f4ad11b19b6bd3d7fb196170fcd1R102).

So the question is: Do we need those links in the first place?

**Comment by vpavkin** [comment]
How about show useful links section with updated styles? E.g. like this:

![ul_0](https://cloud.githubusercontent.com/assets/410508/12807878/e129d04e-cb23-11e5-8402-66d120ee681e.png)

Should look ok on mobiles too:

![ul_1](https://cloud.githubusercontent.com/assets/410508/12807890/ef724960-cb23-11e5-9098-346994ff13d4.png)

If it's ok, I'll make a pr :)

**Comment by adelbertc** [comment]
:+1:
