### ISSUE TITLE
Move transformers to a separate module

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#869]
With a bunch of work around composing effects like [Eff](https://github.com/etorreborre/eff-cats) and [Emm](https://github.com/djspiewak/emm) I'm wondering if we should split out the transformers into a project or sub-module? Monad transformers are the more tried and true way of stacking effects, with Eff and Emm being relatively new, but I'm wondering how it'll look moving forward.

I took a preliminary look at our transformers and it seems they tend to not be very closely baked into the non-transformer bits of the codebase. Stuff like `XorT`, `Kleisli`, `WriterT`, `StateT`, and also the MTL-y type classes we have.

Pinging @stew as well since he has some ideas and thoughts around Cats modularization.

**Comment by mpilquist** [comment]
:-1: at least for `XorT`, `Kleisli`, and `StateT`. Too common to not be in core, and I don't think Eff and Emm supplant these at this point. If nothing else, the latter are much harder to understand.

**Comment by ceedubs** [comment]
I think that I could be convinced either way on this.

However one thing that bothers me a bit (@non and I discussed this a little while ago): as with `free`, it seems like a fairly arbitrary way to define a module. It seems unlikely that I either want all the transformers or none of them (or similarly all of the free structures or none of them). Most likely there are a couple that are more common for people to want and they won't have any use for the others. Unfortunately the way that dependencies work in scala is just not really conducive to lots of tiny modules, so there probably isn't a lot we can do here. That's not really an argument against doing this - just a somewhat related thought.

**Comment by diesalbla** [comment]
@mpilquist: It is true that monad transformers seem a more prominent technique for implementing new monadic instances by compositions. One reason is that there is a longer record track on them, both in [research literature](http://dblp.uni-trier.de/search?q=monad%20transformers) and [Haskell implementations](https://github.com/ekmett/mtl). Nevertheless, a major reason to separate monad transformers is not that they may be uncommon, but that they are one _alternative_ technique for _implementating_ monads, and IMHO a good design should separate alternative implementation from necessary specifications. 

As an intermediary step for this issue, ¿would it be convenient to move the existing monad transformers, with their syntax companions, to a separate package `cats.mtl`?

**Comment by ceedubs** [comment]
@adelbertc what do you think -- should we keep this open for consideration in future versions of Cats, or do you feel comfortable with the convention that we have settled on?

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out as a stale issue. Cats seems to be pretty stable in having a few core monad transformers, and Cats-MTL provides further support.
