### ISSUE TITLE
OptionIdOps.some inconsistent

### ISSUE THREAD

**Issue by aebrett** [typelevel/cats#871]
While obviously `null` shouldn't be used, if it were to creep in then `x.some` violates the principle of least surprise. Given this code:

```scala
val s: String = null
val o = s.some
```

I might expect `o` to be `Some(...)`, but it ends up as `None`.

**Comment by ceedubs** [comment]
Thanks for pointing this out, @aebrett. I agree with you.

**Comment by vpavkin** [comment]
@ceedubs I'll take it :)

**Comment by vpavkin** [comment]
Perfectly fits here:
![image](https://cloud.githubusercontent.com/assets/410508/12951145/eee71964-d021-11e5-9b20-fc232991e574.png)
