### ISSUE TITLE
Rethinking cats.data.Prod

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#874]
For product composition of type classes we are using `cats.data.Prod` which is defined like

```scala
sealed trait Prod[F[_], G[_], A]
```

which fixes `F` and `G` to be unary type constructors. This works fine when defining product composition for type classes abstracting over unary type constructors like `Functor` and `Apply`. But for type classes like `Bifunctor` and `Bifoldable` which abstract over binary type constructors, they also have product composition but they can't use `cats.data.Prod`. We can just have the `compose` on those type classes return the tuple directly `Lambda[(A, B) => (F[A, B], G[A, B])]`, but that would be inconsistent with our use of `Prod` in the other type classes.

I looked in the [Essence of the Iterator Pattern](https://www.cs.ox.ac.uk/jeremy.gibbons/publications/iterator.pdf) paper which I believe inspired `cats.data.Prod` and dont' see them using it with the `Bifoldable`-y stuff.

/cc @eed3si9n since he added `Prod`

**Comment by adelbertc** [comment]
Another argument for using the tuple directly and putting it on the type class `e.g. Apply#product` would be the `compose` and `product` composition combinators would be in the same place instead of `compose` being on the type class and `product` being on `Prod`.

**Comment by eed3si9n** [comment]
I preferred defining  `Prod[F[_], G[_], A]` since it's more restrictive than `(A, B)`. Prod specifically stores `(F[A], G[A])` whereas a `Tuple2` can store whatever.
Another motivation was to define typeclass instances for `Functor` and `Applicative` unambiguously. `Tuple2` as a datatype can overload all sorts of semantics like a pair and coproduct/HList, where they have their own definition of what `map` means in there. `G[F[A]]` on the other hand, is pretty clear what it means.

**Comment by adelbertc** [comment]
You can still get an `(A, B)` if you have `F = G = Id` where `type Id[A] = A`. But good point about the `Tuple2` overloads.. should we then have a `BiProd[F[_, _], G[_, _], A, B]` for the `Bi-` type classes?

**Comment by eed3si9n** [comment]
> should we then have a `BiProd[F[_, _], G[_, _], A, B]` for the `Bi-` type classes?

To me that makes sense.

**Comment by adelbertc** [comment]
I'll take on adding `BiProd`, will use as example for my talk at http://typelevel.org/event/2016-03-summit-philadelphia/

**Comment by adelbertc** [comment]
Closing in favor of https://github.com/typelevel/cats/issues/968
