### ISSUE TITLE
Improve performance of the native scala Future Monad

### ISSUE THREAD

**Issue by oseval** [typelevel/cats#881]
In real-world code fragments like the following often arise:
`if (flag) Future.successful(default) else callAsyncMethod`
or:
`(x: Option[Future[Int]]).getOrElse(Future.successful(None))`

A big part of Promise objects are completed right after creation and can be handled immediately.

Native scala `Future`s create one `Task` for each `map` and two `Task`s for each `flatMap` regardless if the `Future` is completed or not. Hence, dropping unnecessary Tasks can improve performance substantially.

I opened a small PR doing that, but I need help for understanding which tests and where I must write. There should be performance tests as well, for sure.

https://github.com/oseval/cats/pull/1

**Comment by ceedubs** [comment]
@oseval thanks for this. Sorry for the lack of response. To me this sort of things seems like something that may be better to submit as a PR to the scala standard library itself - have you considered that? I think that the people who have contributed `Future` there would probably be more familiar with the implications/benefits of this sort of change.

**Comment by oseval** [comment]
Ok, there is no big problem.
