### ISSUE TITLE
Confusing behavior of Monoid[Xor[A, B]]#combine

### ISSUE THREAD

**Issue by notxcain** [typelevel/cats#888]
Don’t you feel that it’s strange that `Monoid[Xor[A, B]]` requires `A: Semigroup`?
I expected `combine` to be implemented like this
```
def combine(x: A Xor B, y: A Xor B): A Xor B =
  x.flatMap { xb =>
    y.map { yb => Monoid[B].combine(xb, yb) }
  }
```
In current implementation it also tries to combine `Left`s

**Comment by benhutchison** [comment]
It seems that two lefts combine, and two right combine, but a left and a right combined is a left. I think that is consistent with Scalaz, eg [https://gist.github.com/travisbrown/3732844]. It's an interpretation where a failure of a part fails the combined group. 

But I can definitely imagine cases where you'd want to opposite, to discard failures. Like a lot of types, there are several monoids for Xor and one gets blessed as the default. But IMO its a mistake to think of it as *the* monoid for Xor.

```
Welcome to the Ammonite Repl 0.5.2
(Scala 2.11.7 Java 1.8.0_51)
@ load.ivy("org.typelevel" %% "cats" % "0.4.1")
@ import cats._
import cats._
@ import cats.data._
import cats.data._
@ import cats.syntax.all._
import cats.syntax.all._
@ val left1 = Xor.left[String, Int]("fail1")
left1: Xor[String, Int] = Left(fail1)
@ val right = Xor.right[String, Int](7)
right: Xor[String, Int] = Right(7)
@ import cats.std.all._
import cats.std.all._
@ left1 |+| left1
res7: Xor[String, Int] = Left(fail1fail1)
@ left1 |+| right
res8: Xor[String, Int] = Left(fail1)
@ right |+| right
res9: Xor[String, Int] = Right(14)
```

**Comment by ceedubs** [comment]
@notxcain sorry I missed this issue when you first opened it, but I was thinking the same thing the other day. I would expect the errors to combine for `Validated` but not for `Xor`.

There was a [conversation](https://gitter.im/typelevel/cats?at=572b8d2d12cceadb7b1afe25) about this on Gitter yesterday.
