### ISSUE TITLE
Applicative doesn't have default implementation for map and product

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#904]

**Comment by julienrf** [comment]
I thought that was the intended design. Maybe we should provide a trait that one can mix in an implementation of `Applicative` and provides `map` and `product`, implemented in terms of `ap` and `pure`?

**Comment by adelbertc** [comment]
Was it? What was the motivation for that? I know `Cartesian` intentionally doesn't extend `Functor` to make it more general, but I'd imagine `Applicative` should implement both.

**Comment by DavidGregory084** [comment]
@non has mentioned on a few occasions that he would like to move to a model whereby no default implementations are provided in typeclass traits, but I don't know if there has been a consensus about that?
