### ISSUE TITLE
document imports

### ISSUE THREAD

**Issue by stew** [typelevel/cats#912]
We need a document which states exactly what needs to be import when, so that newcomers know exactly what imports do what, and what the basic set is they can use to get going.

**Comment by longcao** [comment]
For posterity: @non mentioned in the round table discussion at the Typelevel Summit unconference that it should be the standard to publish only:

```scala
import cats.implicits._
```

as the fully-capable gateway to using `cats`, and that more specific imports can be used but with the caveat of being a) not exhaustively documented and b) for more advanced usage. IMO, part of this would include rewriting current `tut` documentation to use only `import cats.implicits._`, and publishing that this is the recommended pathway.

(hope I remembered correctly!)

**Comment by lvicentesanchez** [comment]
+1 for using `import cats.implicits._` in the documentation, but I would love to have an advanced usage section with an extended version of what @noelmarkham has started [here](https://gist.github.com/noelmarkham/5815e3b1be81cf74c536).

**Comment by longcao** [comment]
@lvicentesanchez :+1: that's pretty nice! I think that cheat sheet might be good to have in the documentation, perhaps as a sub-bullet to `core` in "Project Structure" (http://typelevel.org/cats/)

**Comment by noelmarkham** [comment]
I've started a PR at https://github.com/typelevel/cats/pull/936

**Comment by ceedubs** [comment]
There has been an imports guide for a while. One thing that it doesn't include is a guide on piecemeal imports, so I've created #1668 to track that.
