### ISSUE TITLE
Monoid and Order for Vector

### ISSUE THREAD

**Issue by davegurnell** [typelevel/cats#919]
`Vector` doesn't have a `Monoid`, which would allow it to be used as a log in a `Writer`. It also doesn't have an `Order`. The two type classes are brought in from algebra and defined side-by-side for `List`:

https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/std/list.scala#L68-L69

This is potentially related to https://github.com/non/algebra/pull/50, which would add the relevant type classes to algebra.

**Comment by ceedubs** [comment]
@davegurnell sorry for the long delay, but I think this was fixed in #1001 and should be in the most recent release. I'm going to go ahead and close this out. Please feel free to reopen it if I've missed anything.

**Comment by davegurnell** [comment]
No worries. Awesome news that it was fixed - thanks for the update!
