### ISSUE TITLE
Add `Read` typeclass

### ISSUE THREAD

**Issue by pathikrit** [typelevel/cats#932]
Opposite of `Show`:

```
trait Read[T] {
  def read(f: String): T
}
```

See also: http://eed3si9n.com/herding-cats/Read.html

**Comment by julienrf** [comment]
I’m not sure such a class would be very useful, because the input type is fixed to `String`. Also, the returned value should make it possible to handle failures.

**Comment by pathikrit** [comment]
Don't have any other reason besides a) [Haskell has it](https://www.haskell.org/tutorial/stdclasses.html) and b) it makes sense to have "an opposite of `Show`" c) I [need it](https://github.com/pathikrit/better-files/commit/b6e772c3372ecf7bbf7bac59780c0fea967d6684) :-)

**Comment by milessabin** [comment]
It also means that we can have a law for `Show`, jointly with `Read`.

**Comment by adelbertc** [comment]
If we move forward with this I would prefer it return `Option[T]`. That being said, while we can define laws for `Read` and `Show` in terms of each other..

1. By themselves they have no laws
2. I am not sure `forAll((s: String) => read(show(s)) === Some(s))` is a useful law, especially given instances for `Show` show things like `OneAnd(...)`, which is not the parsing behavior I would expect. In general it seems parsing should be done by a parser (e.g. [atto](https://github.com/tpolecat/atto))

**Comment by ceedubs** [comment]
I think I tend to agree with @julienrf and @adelbertc on this: I'm not yet convinced it would be a good addition to Cats. I do, in theory, like the way that it would relate to `Show`, but I don't think that it is something that people should actually use "in the real world".

To be honest I'm not that convinced that `Show` should live in Cats, but I see little harm in it being there. It's a simple type class that can be useful for teaching the type class "pattern" via log messages. However, `Read` would encourage being used for deserialization, which would make the exact string format produced by `Show` instances start to really matter. I don't think we'd ever make Cats support deserialization all that well. I think that parsing and deserialization are complex enough that they deserve libraries of their own, and great ones like atto, parboiled, jawn, circe, etc already fulfill this role.

**Comment by ceedubs** [comment]
One more comment: while I think Haskell is a fantastic language, I think that Cats should avoid the "because this is what Haskell does" philosophy, which I think @milessabin agrees with me on, even if we don't necessarily agree on whether Cats should gain `Read` :)

**Comment by milessabin** [comment]
I do agree that we shouldn't do what Haskell does, just because that's what Haskell does. However, I would like to try and establish the principle that type classes can be lawful jointly and shouldn't be required to be lawful singly. Given that we don't want to remove `Show` and we do advocate for lawfulness I think `Read` would be a useful addition.

**Comment by milessabin** [comment]
I agree with @adelbertc that the result type should be `Option[T]`.

**Comment by milessabin** [comment]
I'd also be happy to see both `Show` and `Read` generalized to things other than `String`.

**Comment by julien-truffaut** [comment]
As far I know `Show` is intended to log / print something e.g. in repl but it is not a "serious" serialisation. So I would rather avoid to have a `Read` typeclass, one can always define a pair of typeclass for a given format e.g. Json or ByteString.

**Comment by pathikrit** [comment]
I agree on both counts that `Show` and `Read` should be generalized to things other than `String` and `Read.read` should return `Option[T]`. A better name might be `Serialize` and `Deserialize` (or `Encode` and `Decode` from https://github.com/scodec/scodec):

```scala
trait Encode[F, T] {
   def encode(f: F): T
}

trait Decode[F, T] {
   def decode(f: F): Option[T]
}

trait Codec[A, B] extends Encode[A, B] with Decode[B, A]
```
Although they don't violate any laws like the other felines in https://github.com/non/alleycats, it might be a better place for these:

```scala
trait Show[A] extends Encode[A, String]
trait Read[A] extends Decode[String, A]
```

**Comment by pathikrit** [comment]
I agree on both counts that `Show` and `Read` should be generalized to things other than `String` and `Read.read` should return `Option[T]`. Borrowing from https://github.com/scodec/scodec a better name might be `Encode` and `Decode`:

```scala
trait Encode[F, T] {
   def encode(f: F): T
}

trait Decode[F, T] {
   def decode(f: F): Option[T]
}

type Codec[A, B] = Encode[A, B] with Decode[B, A]
```
Although they don't violate any laws like the other felines in https://github.com/non/alleycats, it might be a better place for commonly used versions:

```scala
type Show[A] = Encode[A, String]
type Read[A] = Decode[String, A]

type Serialize[A] = Encode[A, Seq[Byte]]
type Deserialize[A] = Decode[Seq[Byte], A]
```

**Comment by alexknvl** [comment]
```scala
type Codec[A, B] = Encode[A, B] with Decode[B, A]
// is the same as
type Codec[A, B] = (A => B, B => Option[A])
```
And that looks a lot like a [prism](http://www.slideshare.net/JulienTruffaut/beyond-scala-lens). And prisms (and all other optics) have laws, form categories, splits, etc. As far as I understand, `Read[A]` and `Show[A]` could be collapsed into a lawful type class:

```scala
final case class Prism[A, B](encode: A => B, decode: Kleisli[Option, B, A])
// It could be trait Prism[A, B] {...}
// Laws:
// decode(encode(x)) = Some(x)
// decode(x).map(encode) = Some(x) or None
//
// It is also a category, a split (almost an arrow), 
// an invariant functor in both type parameters, 
// maybe even a cartesian in both arguments (assuming that SemigroupK[Option] is defined) (?).

object Prism {
  def id[A]: Codec[A, A] = Prism(identity, Kleisli(Some.apply))

  implicit val instance = new Category[Prism] with Split[Prism] {
    override def id[A]: Prism[A, A] = Prism.id[A]
    override def compose[A, B, C](f: Prism[B, C], g: Prism[A, B]): Prism[A, C] =
      Prism(
        encode=f.encode compose g.encode,
        decode=f.decode andThen g.decode)
    override def split[A, B, C, D](f: Prism[A, B], g: Prism[C, D]): Prism[(A, C), (B, D)] =
      Prism[(A, C), (B, D)](
        encode=(a: A, c: C) => (f.encode(a), g.encode(c)),
        decode=Split[Kleisli[Option, ?, ?]].split(f.decode, g.decode))
  }

  implicit def leftInvariant[X]: Invariant[Prism[?, X]] = ???
  implicit def rightInvariant[X]: Invariant[Prism[X, ?]] = ???
}

def println[A](x: A)(implicit codec: Prism[A, String]): IO[Unit] = ???
```

I personally don't see much of a point in having `Show[A]` considering that there is a `_.toString` method on every class and `Show[A]` is intended for debugging purposes. I think that both `Show[A]` and `Read[A]` (if implemented) will be abused.

**Comment by rabbitonweb** [comment]
Just quick thought: If you are going to implement Read typeclass, please don't call it Decode :) It might be just confusing for anyone coming from ScalaZ, Haskell etc.

**Comment by OlivierBlanvillain** [comment]
I think cats should adopt the same position than the one with `Task` and recommend other libraries instead of adding a `Read` typeclass.

**Comment by pathikrit** [comment]
@OlivierBlanvillain : What other libraries would you recommend for `Read` typeclass?

**Comment by adelbertc** [comment]
@pathikrit `Read` is generally used as a quick way to do some parsing from a `String` into a type, so I think you should be looking at proper parsing libraries as an alternative. These come to mind:

* [atto](https://github.com/tpolecat/atto)
* [fastparse](https://github.com/lihaoyi/fastparse)
* [parboiled2](https://github.com/sirthias/parboiled2)

**Comment by johnynek** [comment]
Yeah, I’m -1 on Read.

**Comment by tpolecat** [comment]
I'm also 👎 . As a practical matter it's not useful because it doesn't compose unless you build it out into a parser combinator library (of which there are already many to choose from). And as an dual to `Show` it's also not very useful because `Show` itself is not very useful; it's no more than a properly parametric `toString` and is similarly useful only for debugging. I think the key insight is that the string representation isn't uniquely determined by the type, so what we're talking about is not a typeclass. A better representation would be something like a printing/parsing pair joined as a `Prism` or similar, as normal data.

**Comment by ceedubs** [comment]
While there are various points of view on this, it seems that the majority of Cats maintainers don't think that `Read` belongs in Cats. For real-world use-cases you probably want more than an `Option` as a result, as you probably want to know a reason that a `String` failed to be parsed. I'd recommend a parsing library such as @adelbertc recommended [here](https://github.com/typelevel/cats/issues/932#issuecomment-336753779).

This issue has been hanging around for quite some time. In an effort to clean up some of the stale backlog, I'm going to go ahead and close this out.
