### ISSUE TITLE
Bifoldable

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#94]
`Bifoldable` is a type class (currently not in cats) for a type that has two separate `Foldable`s. For example, `Or` has a `Foldable` instance (via its `Traverse` instance) that folds over the `RightOr` case, but `Or` could equally fold over the `LeftOr` case.

One of my favorite methods from scalaz is [`MonadPlus.separate`](https://github.com/scalaz/scalaz/blob/aab1891bb193432bab21a5e6c5055346ec0d55d1/core/src/main/scala/scalaz/MonadPlus.scala#L24). This can do things like take a `List[A Or B]` and turn it into a `(List[A], List[B])`. Or similarly, take a `List[(A, B)]` and turn it into a `(List[A], List[B])`. In Cats, I believe we could implement the same sort of method on `MonadFilter` if we were to bring in a `Bifoldable` type class.

What do people think? Is this something that would belong in `core`?

**Comment by tpolecat** [comment]
Yep, I would like to see `Bifoldable`.

**Comment by mpilquist** [comment]
It's worth mentioning that `Foldable` and `Bifoldable` are lawless. We admitted `Foldable` anyway due to its usefulness for adhoc polymorphism. `Bifoldable` occurs much less frequently in practice, so we might want to carefully consider its inclusion.

**Comment by adelbertc** [comment]
`Foldable` kind of has laws: https://github.com/scalaz/scalaz/blob/series/7.2.x/scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazProperties.scala#L369

**Comment by mpilquist** [comment]
Those only require that `foldMap`, `foldLeft`, and `foldRight` are mutually consistent. They only exist in Scalaz because `Foldable` can be implemented in terms of `foldMap` *or* `foldRight`. If you pick one as the abstract method and just derive the other, the law simplifies to a unit test of the derived method.

**Comment by non** [comment]
Is there consensus here?

So far it seems like @ceedubs and @tpolecat would like to see this and @mpilquist is skeptical?

**Comment by coltfred** [comment]
I personally use Bifoldable from Scalaz on a regular basis and would like to have it. 

Plus it gives rise to wildly useful things like `separate` on MonadPlus. 

:+1:

**Comment by adelbertc** [comment]
Re: Laws some quick Googling turned up

https://github.com/scalaprops/scalaprops/blob/master/scalazlaws/src/main/scala/scalaprops/scalazlaws/bifoldable.scala /cc @xuwei-k 

and 

https://github.com/ekmett/bifunctors/blob/master/tests/BifunctorSpec.hs#L169

**Comment by mpilquist** [comment]
Re-reading this just now, I'm not skeptical of adding `Bifoldable`. :+1:
