### ISSUE TITLE
Cannot find implicit Functor for Kleisli of ValidatedNel

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#943]
The `Functor` for a `ValidatedNel` is found just find. But for some reason trying to find the `Functor` for a `Kleisli` where the effect type is `ValidatedNel` doesn't work. I haven't yet tried to debug what's going wrong here.

```scala
> coreJVM/console
[info] Compiling 4 Scala sources to /Users/v751429/code/cats/core/.jvm/target/scala-2.11/classes...
[info] Compiling 8 Scala sources to /Users/v751429/code/cats/core/.jvm/target/scala-2.11/classes...
[info] Starting scala interpreter...
[info] 
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions for evaluation. Or try :help.

scala> import cats._, data._, implicits._
import cats._
import data._
import implicits._

scala> Functor[ValidatedNel[String, ?]]
res0: cats.Functor[[β]cats.data.Validated[cats.data.OneAnd[[+A]List[A],String],β]] = cats.data.ValidatedInstances$$anon$1@688a8f50

scala> Functor[Kleisli[ValidatedNel[String, ?], Int, ?]]
<console>:21: error: could not find implicit value for parameter instance: cats.Functor[[γ]cats.data.Kleisli[[β]cats.data.Validated[cats.data.OneAnd[[+A]List[A],String],β],Int,γ]]
       Functor[Kleisli[ValidatedNel[String, ?], Int, ?]]
```

**Comment by travisbrown** [comment]
This looks kind of like [an issue I opened years ago](https://issues.scala-lang.org/browse/SI-6895) that was eventually closed as a duplicate of SI-2712.

**Comment by ceedubs** [comment]
It appears that this isn't an issue in projects that use the [SI-2712 fix plugin](https://github.com/milessabin/si2712fix-plugin). I'm inclined to say that we should encourage people who are running into this sort of thing to use that plugin as opposed to pursuing too cumbersome of a workaround for this within cats.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out in favor of #1073.
