### ISSUE TITLE
Eval should have a corresponding type-class

### ISSUE THREAD

**Issue by alexandru** [typelevel/cats#944]
Thinking of our prior discussions, on making `Eval` asynchronous for making it equivalent to a `Task`, I think that what was missing is that `Eval` is too specific and we need type-classes to represent it.
- [Evaluable](https://github.com/monixio/monix/blob/master/monix-types/shared/src/main/scala/monix/types/Evaluable.scala) ([laws](https://github.com/monixio/monix/blob/master/monix-types-laws/shared/src/main/scala/monix/laws/EvaluableLaws.scala))
- [Nonstrict](https://github.com/monixio/monix/blob/master/monix-types/shared/src/main/scala/monix/types/Nonstrict.scala) ([laws](https://github.com/monixio/monix/blob/master/monix-types-laws/shared/src/main/scala/monix/laws/NonstrictLaws.scala)) (for representing synchronous non-strict evaluation)

What's cool is that both Monix's [Task](https://github.com/monixio/monix/blob/master/monix-async/shared/src/main/scala/monix/async/Task.scala#L726) and [Observable](https://github.com/monixio/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/Observable.scala#L412) are instances of `Evaluable`, but not instances of `Nonstrict` because that would imply synchronous execution and tasks and observables are asynchronous. `Eval` on the other hand [is an instance](https://github.com/monixio/monix/blob/master/monix-types/shared/src/main/scala/monix/types/instances/eval.scala#L23) of `Nonstrict`.

Why this is important is for the Cats dependency model. If within the dependency chain `cats-core` is at the bottom, that would bring problems for people using Scalaz or for people not wanting a 2.5 MB JAR dependency just for `cats-core` (excluding Algebra, which I assume is also not too light). So one way of doing it is to have a `cats-core` project be at the top of the hierarchy, such that it is optional, with a sub-project integrating with the various Cats type-classes. And then you can have a project that integrates with Scalaz. That would be the advantage of having type-classes, as open interfaces, right?

Except that `Eval` is a data-structure and if you want to do non-strict evaluation and have something that replaces by-name parameters, one has no choice but to depend on `cats-core` and `Eval`.

**Comment by ceedubs** [comment]
@alexandru is this now satisfied by type classes in cats-effect?

**Comment by alexandru** [comment]
The ideas I had in this issue are old and my attempt obsolete.

Also at this moment `Eval` can't be described by the type classes in cats-effect, the issue being that for now we needed `MonadError`, see discussion at: https://github.com/typelevel/cats-effect/issues/67 - but on the other hand we are able to work with `EitherT[Eval, Throwable, ?]`.

So that said I'm not interested in pursuing this any further. 
We can close the issue.

**Comment by ceedubs** [comment]
👍 thanks, @alexandru
