### ISSUE TITLE
s/ListWrapper/OptionWrapper

### ISSUE THREAD

**Issue by adelbertc** [typelevel/cats#957]
Lots of Lists flying around makes build times slow and sometimes time out.

**Comment by ceedubs** [comment]
I've thought about this in the past. One downside is that we only have some type class instances (`Semigroup`, `Monoid`) for `Option[A]` if we have a `Semigroup[A]` instance, which isn't the case with `List[A]`. You can create an alternative version of `Semigroup[A]` that uses `orElse` and doesn't require `Semigroup[A]`. I think that I advocated for this in an issue way back but ultimately we decided not to go with it. I guess we could have `OptionWrapper` do that, but I could see the difference between the two getting confusing.

**Comment by ceedubs** [comment]
@adelbertc since our builds haven't been timing out for a long time now, I'm going to go ahead and close this out. See also the experiment in #1143.
