### ISSUE TITLE
Kleisli.apply isn't what it seems like it should be

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#969]
In [this gitter discussion](https://gitter.im/typelevel/cats?at=5702da0fe4a8384a1bbec87f) we realized that `Kleisli.apply` should probably be renamed `Kleisli.ap`.

We probably also want to create a new `apply` method that looks like `def apply(a: A): F[B] = run(a)`.

**Comment by adelbertc** [comment]
fixed by #970
