### ISSUE TITLE
Remove scoverage dependency from POMs

### ISSUE THREAD

**Issue by mpilquist** [typelevel/cats#980]
The cats-core 0.4.1 POM has the following entries:

```
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-runtime_2.11</artifactId>
            <version>1.1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-plugin_2.11</artifactId>
            <version>1.1.0</version>
            <scope>provided</scope>
        </dependency>
```

These should be removed, via pomPostProcess perhaps.

**Comment by rossabaker** [comment]
* Related upstream discussion: https://github.com/scoverage/sbt-scoverage/issues/153
* Related upstream PR: https://github.com/scoverage/sbt-scoverage/pull/166

**Comment by alexandru** [comment]
See the commit of this guy: https://github.com/rozza/mongo-spark/commit/21eab2096ca8f453648ce92a14dcfa88b06fe591
