### ISSUE TITLE
Add withFilter to OptionT

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#981]
`-Xfuture` on 2.11 doesn't allow `filter` methods to be used in `for`-comprehensions, which means e.g. this won't compile with `-Xfuture` on:

```scala
import cats.Eval, cats.data.OptionT

for { x <- OptionT(Eval.now(Option(1))) if x > 0 } yield x
```

It [sounds like](https://gitter.im/typelevel/cats?at=570fba504c2125fc3f0260fa) there's no reason not to add a `withFilter` method to `OptionT`.

**Comment by xuwei-k** [comment]
FYI: There is `MonadPlusOps#withFilter` in scalaz.
- https://github.com/scalaz/scalaz/blob/v7.2.2/core/src/main/scala/scalaz/syntax/MonadPlusSyntax.scala#L12

**Comment by adelbertc** [comment]
I like the idea of putting it on `MonadFilter`, but when defining a `MonadFilter` instance for `OptionT`:

```
 47 [info] - OptionT[List, Int].monadFilter.monadFilter right empty *** FAILED *** (14 milliseconds)
 48 [info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
 49 [info]    (Discipline.scala:14)
 50 [info]     Falsified after 0 successful property evaluations.
 51 [info]     Location: (Discipline.scala:14)
 52 [info]     Occurred when passed generated values (
 53 [info]       arg0 = OptionT(List())
 54 [info]     )
 55 [info]     Label of failing property:
 56 [info]       (OptionT(List()) ?== OptionT(List(None))) failed
```

Related: https://github.com/typelevel/cats/pull/698

**Comment by ceedubs** [comment]
I'd vote for adding `withFilter` to `OptionT` now and worrying about the `MonadFilter` component later as a resolution to #694 (which I'm guessing we won't get around to for a while).

**Comment by ceedubs** [comment]
Added in #1028.
